src/app/components/popover-audit/popover-audit.component.ts, src/app/components/popover-audit/popover-audit.html
Tooltip en posición "left" para que se vea el último editor del turno.
=> Fecha y Hora de la última actualización del turno

src/app/components/paciente/paciente-search.component.ts
Cambio getPermission to check para poder usar el '*' desde el gestor de permisos
=> Cambio getPermission to check para poder usar el '*' desde el gestor de permisos

src/app/components/inicio/inicio.component.ts
=> Fix punto inicio

src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
Fix error javascript al momento de reasignar un turno
>  "Cannot read property 'horaInicio' of undefined"
=> fix bug "cannot read horaInicio of undefined" cuando reasigna turno

src/app/app.component.ts, src/app/components/login/login.component.ts
=> fix: se arma el menu hamburguesa luego de realizar el login

src/app/app.component.ts, src/app/components/login/login.component.ts
Lo dicho, se agrega un chequeo de logged in para evitar que la api tire un palo en checkpermissions
=> enhancement en el appcomponent (armado del menu hamburguesa)

src/app/components/paciente/paciente-search.component.ts, src/app/components/turnos/dashboard/paciente-search-turnos.component.ts, src/app/components/turnos/dashboard/paciente-search-turnos.html
- Cuando se escanea un paciente que ya existía pero tenía error QR no devolvía el paciente para poder seleccionarlo.
=> fix de escaneeo similar

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
-  Verifica que el paciente tenga dni antes de intentar una busqueda de numero de carpeta
=> Fix búsqueda numero carpeta

src/app/components/paciente/paciente-search.html
=> Controles paciente temporal en resultados pacienteSearch

src/app/components/paciente/paciente-create-update.component.ts, src/app/components/paciente/paciente-search.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dashboard/paciente-search-turnos.component.ts, src/app/components/turnos/dashboard/puntoInicio-turnos.component.ts, src/app/services/paciente.service.ts
- Linteos varios.
- Duplicaba pacientes Temporales en el Pto. de inicio de agendas.
=> Fix temporales

src/app/components/paciente/paciente-create-update.component.ts, src/app/components/paciente/paciente-create-update.html, src/app/components/turnos/dashboard/activar-app.component.ts, src/app/components/turnos/dashboard/activar-app.html, src/app/services/appMobile.service.ts
Activar app mobile desde mpi y desde punto de inicio de citas
=> Activarappmobile

src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts
-  filtramos candidatas por organizacion
=> Agregamos chequeo de organizacion para las agendas candidatas

src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.html, src/app/components/turnos/gestor-agendas/turnos.html
- Agregamos nueva funcionalidad que permite borrar agendas en estado de planificacion
- Chequeo de permisos para borrar agenda
=> Feature borrar agenda

src/app/components/paciente/paciente-create-update.component.ts
- Fix al cancelar debería ocultar la activación mobile.
=> fix cancelar

src/app/components/turnos/dashboard/activar-app.component.ts
=> cartelito de envio

src/app/components/turnos/gestor-agendas/turnos.html, src/app/components/turnos/gestor-agendas/turnos.scss
Por las dudas bajá esta rama @kroce y probá cómo se ve, el cambio se nota en los badges (audit, reasignado/no reasignado, asistió/no asistió...). Gracias por la atención.
=> Mejoras en badges de turnos

src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts
Se apresta la consulta a tener un formato de fecha que la API pueda comprender y validar usando el paquete moment.js :1st_place_medal:
=> Se agrega .toDate() a fechaDesde y fechaHasta en query de agendas

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
Fix en agregar registros desde la huds
=> Evoluciones

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/services/term/snomed.service.ts
Agregar check en la validación para diagnósticos cie10-c2
=> Mostrar check para diagnosticos de primera vez que mapeen a cie10

src/app/modules/rup/components/ejecucion/huds-tabs/tabs/tabs.component.ts, src/app/modules/rup/components/ejecucion/huds-tabs/tabs/tabs.scss, src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/hudsBusqueda.scss, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Fijar la consulta actual dentro de los tabs cuando voy agregando elemento de la HUDS y hago scroll.
=> Fix tab scroll

src/app/components/usuario/usuarioCreate.component.ts, src/app/components/usuario/usuarioCreate.html, src/app/components/usuario/usuarioUpdate.component.ts, src/app/components/usuario/usuarioUpdate.html
- actualizamos el crear usuario
:fearful:
=> fixes en creacion de usuario

src/app/components/paciente/paciente-create-update.component.ts
- Fix de ocultar el btn luego de validar el form
=> Fix btn save

src/app/components/turnos/dashboard/turnos-paciente.html
Se agrega control para los turnos que no tienen asignado un profesional.
(Este fix se debe mergear al release domuyo)
=> Lista de turnos por paciente

src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
=> Rup datos tabs completos

src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts
- Corrección al reasignar agendas en el mismo dia
- Es necesario mergear el PR de la api para que funcione correctamente
- hay que mergear también a domuyo
=> Enhancement reasignación

src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.print.scss, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts, src/app/components/turnos/gestor-agendas/turnos.component.ts
-  Corrección turnos restantes en agendas con más de un bloque
- Fix  error que daba al cancelar edición de agenda luego de asignar un bloque vacío
- Modificaciones propuestas  a impresión de listado de turnos
- Modificación: al suspender una agenda, el envío de sms por defecto muestra los checkboxes sin seleccionar
=> Fix dar turno

src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
=> Mejoras en impresión de listado turnos

src/app/components/turnos/dashboard/turnos-paciente.component.ts, src/app/components/turnos/dashboard/turnos-paciente.html
- No se muestran los turnos viejos en punto inicio
- Cambios en liberar turno.
=> Cambios punto inicio

src/app/app.module.ts, src/app/components/paciente/paciente-create-update.component.ts, src/app/components/turnos/configuracion/mapa-espacio-fisico/filtros-mapa-espacio-fisico.html, src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts, src/app/components/turnos/dashboard/activar-app.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts, src/app/modules/rup/components/ejecucion/resumen.component.ts
- Array estatico de componentes rup.
- seteamos como publicas las propiedades privadas de algunos components porque da error aot true
- Variables que no estaban definidas y se usaban en el html de algunas paginas.
=> fix for aot true

src/app/components/turnos/dashboard/paciente-search-turnos.component.ts, src/app/components/turnos/dashboard/turnos-paciente.component.ts, src/app/components/turnos/dashboard/turnos-paciente.html
- Corregimos bug en puntoInicio
=> fix bugsito punto inicio - >turnos paciente-> nuevo paciente - >cancelar

src/app/components/turnos/dashboard/puntoInicio-turnos.component.ts
=> fix punto inicio palo

src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/components/turnos/gestor-agendas/gestor-agendas.html
- Fix espaciosFisicos que no filtra por efecto en el gestor de agendas.
- Fix para undefined si no esta el servicio muestra la descripción del edificio. Si está toda la info muestra todo.
=> fix espacio fisico en creacion de agenda

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
- Corregir bugs en Punto de inicio para agendas con bloques
- Agregar profesional que ejecuto la prestación en el listado de pacientes del Punto de inicio
=> Corregir bugs en punto de inicio para agendas con bloques

src/app/app.module.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/elementos/filtradoGlomerular.component.ts, src/app/modules/rup/components/elementos/filtradoGlomerular.html, src/app/modules/rup/components/elementos/riesgoCardiovascular.component.ts, src/app/modules/rup/components/elementos/riesgoCardiovascular.html
- Fix en mas frecuentes.
- Átomo de RCVA 
- Átomo de filtrado glomerular
=> atomos nuevos y fixes

src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
- Luego de pasarlo por QA se debería mergear a domuyo
=> agregamos fecha nacimiento a la impresión de lista de turnos

src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
- Pantalla reasignación de turnos incorpora un plex-bool para activar/desactivar envío de sms
- Se agrega la funcionalidad de envío SMS 
- Fix filtros gestor de agendas
=> Slider sms reasignacion

src/app/components/paciente/paciente-create-update.component.ts, src/app/components/turnos/dashboard/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts, src/app/components/turnos/gestor-agendas/gestor-agendas.html
* Agrega un campo requerido en la solicitud de turno para solucionar error en la carga de una nueva solicitud de turno.
* Quita undefined del filtro espacio físico en el gestor de agendas
=> Linteo y modificaciones en solicitudes de turno

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/elementos/autocitado.component.ts, src/app/modules/rup/components/elementos/autocitado.html
- Revisar componente de autocitación 
- Mostrar botón de asignar turnos solo si hay agendas con turnos para profesional disponibles
=> Revision autocitados

src/app/modules/rup/components/elementos/frecuenciaCardiaca.component.ts, src/app/modules/rup/components/elementos/frecuenciaCardiaca.html, src/app/modules/rup/components/elementos/frecuenciaRespiratoria.component.ts, src/app/modules/rup/components/elementos/frecuenciaRespiratoria.html, src/app/modules/rup/components/elementos/saturacionOxigeno.component.ts, src/app/modules/rup/components/elementos/saturacionOxigeno.html, src/app/modules/rup/components/elementos/talla.html, src/app/modules/rup/components/elementos/temperatura.component.ts, src/app/modules/rup/components/elementos/tensionDiastolica.component.ts, src/app/modules/rup/components/elementos/tensionDiastolica.html, src/app/modules/rup/components/elementos/tensionSistolica.component.ts, src/app/modules/rup/components/elementos/tensionSistolica.html
Corregir alertas en átomos de signos vitales
=> Revisión alertas

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts
- Fix en Huds para la visualización de los tabs en ejecución y la vista de la huds. 
- Fix en la posición del icono de la Huds para conceptos de nombre muy largo.
- Fix en elementoRup evolución por default para la vista huds.
=> Se arreglan algunos bugs para la vista de los tabs en ejecucion

src/app/app.module.ts, src/app/app.routing.ts, src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts, src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.html, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
- Se agrega componente para la vista de la huds con el buscador de mpi.
- Se agrega boton en punto de inicio
- Se modifica el componente vistaHuds para que pueda recibir por parámetro el paciente.
=> componente para la vista de la huds con un buscador de pacientes

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- Implementamos condiciones para permitir la revisión de agendas.
=> revisión de agendas

src/app/components/turnos/dashboard/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts, src/app/modules/rup/components/ejecucion/huds-tabs/tabs/tabs.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
- Agregar en el punto de inicio permisos por profesional para prestaciones en ejecución
=> Permisos pi

src/app/modules/rup/components/ejecucion/huds-tabs/tabs/tabs.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts, src/app/modules/rup/components/ejecucion/vistaHuds.html
Fix en la vista de la Huds con cerrar los tabs..
=> fix en los tabs en vista huds

src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Fix en el ojo de la huds (Mínimos cambios).
=> fix en el ojo de la HUDS

src/app/modules/rup/components/ejecucion/vistaHuds.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/interfaces/snomed-concept.interface.ts, src/app/modules/rup/services/prestaciones.service.ts
Agregar badge por referentSet en el componente evolución default
=> Agregar badge por referentSet en el componente evolucion default

src/app/components/snomed/snomed-buscar.component.html, src/app/components/snomed/snomed-buscar.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- Corregir error al intentar evolucionar un elemento de la huds. 
- Agregar los mas frecuentes de la consulta
=> Fix evolucionar un elemento de la huds

src/app/components/snomed/snomed-buscar.component.html, src/app/components/snomed/snomed-buscar.component.ts
- Búsqueda Guiada mergeada con Develop.
- Se ocultan los filtros.
- Se agregan en los desplegables los registros de los filtros.
=> New búsqueda guiada

src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html, src/app/components/turnos/gestor-agendas/turnos.component.ts, src/app/components/turnos/gestor-agendas/turnos.html
- Fix suspensión de agenda  (o turno) con **turnos dobles**
=> Fixes suspender

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/autocitado.component.ts, src/app/modules/rup/components/elementos/autocitado.html
- Agregar al nombre del registro de autocitación el nombre de la prestación seleccionada.
- Arreglar mensajes de asignación de turnos en la validación
=> Nombre autocitados

src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- Filtramos espacios físicos por organización cuando editamos agendas publicadas
=> Edicion de agenda

src/app/components/snomed/snomed-buscar.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
=> linteo en punto de inicio

src/app/components/snomed/snomed-buscar.component.html, src/app/components/snomed/snomed-buscar.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- Fixes varios
- Agrego botón de mas frecuentes
=> agrego boton de mas frecuentes

src/app/components/snomed/snomed-buscar.component.html, src/app/modules/rup/components/ejecucion/huds-tabs/tabs/tabs.component.ts
- Fix en tabs
- El boton de busqueda guiada se muestra solo cuando tenemos resultados
- Se agrega el badge con el semanticTag en los resultados de la búsqueda guiada
=> Bugsitos rup

src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
- Cambiar la visualización de los hallazgos en la vista HUDS (evoluciones)
=> Rup detalles vista huds

src/app/components/turnos/dar-turnos/calendario-dia.class.ts, src/app/components/turnos/dar-turnos/calendario.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Fix para que se visualicen agendas con múltiples bloques que no tienen turnos programados en el dar turnos a partir de solicitud
=> Bug multiples bloques

src/app/components/turnos/dar-turnos/calendario-dia.class.ts, src/app/components/turnos/dar-turnos/calendario.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/dashboard/puntoInicio-turnos.component.ts
Se corrige filtro en dar turno desde solicitud con autocitación
=> Fix filtros solicitudes

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/interfaces/prestacion.registro.interface.ts
Corregir error al colapsar un registro transformado.
=> Rup fix colapse transformado

src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss, src/app/modules/rup/components/elementos/registrarMedicamentoDefault.component.ts, src/app/modules/rup/components/elementos/registrarMedicamentoDefault.html
**IMPORTANTE**
Se debe insertar (o actualizar) este elementoRUP:
```
db.getCollection("elementosRUP").insert({
"activo": true,
"componente": "RegistrarMedicamentoDefaultComponent",
"tipo": "atomo",
"defaultFor": [
"producto"
],
"esSolicitud": false,
"style": {
"columns": 6.0,
"cssClass": null
},
"conceptos": [],
"requeridos": [],
"frecuentes": []
})
```
=> Se agregan todos los campos al formulario default de medicamentos

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/turnos.html
=> fixes en carga de agendas en calendario turnos

src/app/components/snomed/snomed-buscar.component.ts, src/app/modules/rup/components/core/rup.scss, src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/buscador.scss, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/variables.scss
- Agregar semanticTag regimen/Tratamiento al buscador. 
- Corregir bug planes
=> Rup agregar tag regimen

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.html
=> arreglos en el buscador

src/app/modules/rup/components/core/rup.scss, src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.scss, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.scss, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/components/variables.scss
Ordenamiento de registros en pantalla de Validación
=> Se agrega ordenamiento por fecha y mejoras en ordenamiento por tipo, etc

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.scss
=> Se agregan reglas CSS para impresión de registros RUP

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- Se ven los mas frecuentes de las prestaciones y no solo los del profesional
- Se muestran los más frecuentes de un concepto cuando le hacemos click en la ejecución
=> Frecuentes prestacion

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html
=> Rup linteo huds

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.scss, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts
- Función para que el botón borrar no se muestre en las prestaciones que son requeridas por la consulta. Por ejemplo el informe en la consulta de colonoscopia.
- Fix en los resultados cuando hacemos una nueva búsqueda. 
- Fix con el NaN en los Hallazgos. 
- fixsito en los estilos, se agrega adjuntos..
=> Eliminar consulta

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/services/prestaciones.service.ts
Ocultar fecha Inicio y estado para los hallazgos: Pone por defecto estado activo y la fecha actual como fecha de inicio.
Filtrar hallazgos no activos del listado de hallazgos de la huds.
=> Rup evolucion hallazgos

src/app/components/turnos/dar-turnos/calendario-dia.class.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
Agrega filtros a la visualización de las prestaciones, de acuerdo a los permisos en el módulo de Citas
=> Permisos gestor

src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Poder asignar una situación como diagnostico principal
=> Poder asignar una situación como diagnostico principal

src/app/modules/rup/components/core/rup.scss, src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/buscador.scss, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/seguimientoDelPeso.component.ts, src/app/modules/rup/components/variables.scss
Refacorización de código y simplificación del buscador / Cambios de algunas variables y estilos SASS / Cambio de estilo de átomo de seguimiento
Agregado los sugeridos por cada prestación que agrego y hago clic en ejecución
Agregado estilo en validacion para elemento de registro
=> Nuevo buscador

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
-  Solucionamos errores en revisión de agendas con sobreturnos :call_me_hand:
=> Fixes citas

src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.html
- Fix en color de planes en la pantalla de validación
- Fix en colapsar las prestaciones al vincular y en la de vincular desde el buscador directamente
- Fix en color de planes en la pantalla de validación
- Se agrega nuevamente el tachito para eliminar con drag and drop un registro de la consulta en ejecución
=> Fix ejecucion rup

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/services/frecuentesProfesional.service.ts
Nuevos filtros para consultar los frecuentes de un profesional también por efector y tipo de prestación
=> Cambios frecuentes profesional

src/app/components/paciente/paciente-search.component.ts
Verifica el valor devuelto de los pacientes similiares que tengan campo de scan seteado.
=> agregar verificación al valor devuelto de pacientes similares

src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts, src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
- Fix en el select de profesionales  en solicitudPrestacionDefault.component.ts
=> fix select de profesionales en los planes

src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- fix en agregar paciente fuera de agenda, si no existe el paciente muestra un alerta.
=> fix en crear prestacion fuera de agenda

src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
- correcciones en la verificación de conflictos al clonar agenda.
=> Fix conflictos clonar

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/modules/rup/components/elementos/seguimientoDelPeso.component.ts
Linteo de codigo en dar turnos
=> linteo de codigo

src/app/modules/rup/components/core/rup.scss, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/variables.scss
=> Fixes varios, que básicamente arreglan algunos mocos con colores

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/vistaHuds.html, src/app/modules/rup/components/elementos/autocitado.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/components/elementos/observaciones.html, src/app/modules/rup/components/elementos/registrarMedicamentoDefault.html, src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html, src/app/modules/rup/services/prestaciones.service.ts
Corrección de bug al mostrar evoluciones de trastornos en una prestación validada.
llevamos la visualizacion de la evoluciones de un trastorno/hallazgo dentro del componente de evolucionarHallazgos para unificar formatos y fechas de evoluciones.
=> Rup evolucion trastornos

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/components/elementos/observaciones.html, src/app/modules/rup/services/elementosRUP.service.ts
Si hay un solo diagnostico se marca como diagnostico princial.
Se muestra si un concepto pertenece a uno de los grupos de la búsqueda guiada.
=> RUP: Ajustes

src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
- Fix condición de verificarConflictos para clonar agendas
=> cambio cndicion verificar conflictos

src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
- Fixes en verificación de conflictos
=> Fix bugs clonar

src/app/app.module.ts, src/app/app.routing.ts, src/app/components/organizacion/cama-create-update.component.ts, src/app/components/organizacion/cama-create-update.html, src/app/components/organizacion/camas.component.ts, src/app/components/organizacion/camas.html, src/app/components/organizacion/organizacion-create-update.component.ts, src/app/components/organizacion/organizacion-create-update.html, src/app/components/organizacion/organizacion.component.ts, src/app/components/organizacion/organizacion.html, src/app/interfaces/ICama.ts, src/app/interfaces/ICamaEstado.ts, src/app/services/organizacion.service.ts
- Abm de camas
- se agregan servicios
=> Abm mapa cama

src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
- **jotfix** :fire:  listar turnos -> nroCarpeta efector
=> fix nroCarpeta paciente para impresion turnos

src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.print.scss
=> release 2.4.0

src/app/app.module.ts, src/app/services/ocupacion/ocupacion.service.ts
- Se agrega ocupacion.service.ts para traer todas las ocupaciones.
=> se agrega el servicio para traer todas las ocupaciones

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- Cambio en condición btn revisión de agenda
- Cambio en condición para cerrar codificación
=> Hot fix revisión

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html, src/app/components/turnos/gestor-agendas/turnos.html
- Se agregó la posibilidad de agregar una nota en el momento de dar el sobreturno
- Fix en manejo de las carpetas del paciente en el sobreturno
=> Hot fix sobreturnos

src/app/app.module.ts, src/app/components/turnos/dashboard/arancelamiento-form.component.ts, src/app/components/turnos/dashboard/arancelamiento-form.html, src/app/components/turnos/dashboard/arancelamiento-form.scss, src/app/components/turnos/dashboard/puntoInicio-turnos.component.ts, src/app/components/turnos/dashboard/puntoInicio-turnos.html, src/app/components/turnos/dashboard/turnos-paciente.component.ts, src/app/components/turnos/dashboard/turnos-paciente.html, src/app/services/fuentesAutenticas/servicioSisa.service.ts
- se agrega un componente que imprime datos de arancelamiento para que el paciente firme.
=> Arancelamiento form

src/app/components/mapa-de-camas/cama/cama.component.html, src/app/components/mapa-de-camas/cama/cama.component.ts, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.scss, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/pipes/iconoCama.pipe.ts, src/app/services/camas.service.ts
- Cambio de nombre: los servicios por unidadOrganizativa.
- Cambio en los estados de mapa de camas, quedan todos los estados funcionando
=> Mapa camas

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- se **ocultan** los botones de guardar, guardar y clonar agenda y dar turno para evitar efecto happy trigger :gun:
=> Ocultar botones

src/app/components/mapa-de-camas/cama/cama.component.html, src/app/components/mapa-de-camas/cama/cama.component.ts
- Se agrega el campo fecha en las cards de los estados de una cama.
- Se agrega una selección cuando se desbloquea una cama, para poder elegir el estado que tendrá (desocupada o disponible).
- Por defecto el campo fecha tiene la fecha y hora actual.
=> Cards camas

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html
- En la pantalla de dar turno, el filtro de prestaciones también actúa filtrando los bloques de la agenda seleccionada. :date:
=> Filtro de prestaciones

src/app/app.module.ts, src/app/components/turnos/dashboard/arancelamiento-form.component.ts, src/app/services/arancelamiento.service.ts
-  botón de arancelamiento desde punto inicio
=> Arancelamiento

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/interfaces/turnos/ITurno.ts
- modificamos interfaz turno para incluir alias de paciente
=> Alias paciente

changelog-rup-otoemision-acustica.md, src/app/app.module.ts, src/app/components/turnos/dashboard/arancelamiento-form.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/elementos/SelectPorRefset.component.ts, src/app/modules/rup/components/elementos/SelectPorRefset.html, src/app/modules/rup/components/elementos/otoemisionAcusticaDeOidoDerecho.component.ts, src/app/modules/rup/components/elementos/otoemisionAcusticaDeOidoIzquierdo.component.ts, src/app/modules/rup/components/elementos/otoemisionOidoDerecho.html, src/app/modules/rup/components/elementos/otoemisionOidoIzquierdo.html, src/app/modules/rup/services/elementosRUP.service.ts, src/app/modules/rup/services/prestaciones.service.ts
**Sólo para RUP: para hacer funcionar esta prestación, seguir las instrucciones del changelog:**
https://github.com/andes/app/blob/RUP-otoemision-acustica/changelog-rup-otoemision-acustica.md
=> Rup screening otoemisión acústica

src/app/app.module.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/dashboard/arancelamiento-form.component.ts, src/app/interfaces/IObraSocial.ts, src/app/interfaces/turnos/ITurno.ts, src/app/services/obraSocial.service.ts
Se agregó la información de obra social del paciente y la posibilidad de establecer un motivo de consulta en dar turno
=> Dar turno os

src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html, src/app/components/turnos/gestor-agendas/turnos.html
- cambios en la pantalla de dar sobreturno
=> Pantalla sobreturno

src/app/app.module.ts, src/app/app.routing.ts, src/app/components/mapa-de-camas/cama/cama-create-update.component.ts, src/app/components/mapa-de-camas/cama/cama-create-update.html, src/app/components/mapa-de-camas/cama/cama.component.html, src/app/components/mapa-de-camas/cama/cama.component.ts, src/app/components/mapa-de-camas/cama/camaEstado.component.ts, src/app/components/mapa-de-camas/cama/camaEstado.html, src/app/components/mapa-de-camas/cama/camasListado.html, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.scss, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/components/paciente/paciente-detalle-actualizar.html, src/app/interfaces/ICama.ts, src/app/interfaces/ICamaEstado.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/ejecucion/internacion/ocuparCama.component.ts, src/app/modules/rup/components/ejecucion/internacion/ocuparCama.html, src/app/modules/rup/components/elementos/ingresoInternacion.component.ts, src/app/modules/rup/components/elementos/ingresoInternacion.html, src/app/modules/rup/services/prestaciones.service.ts
- Se cambia el esquema de las camas para agregar la unidad organizativa, especialidades, genero y censable como datos dinámicos cuyos cambios se almacenen como cambios de estados y se mantenga en el histórico de la cama.
- Agregar la ocupación de cama en el ingreso de internación.
- Desocupar cama
- Ocupar una cama disponible con una internación ya iniciada. (pase de cama)
=> Completar ingreso internacion

src/app/app.module.ts, src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.html, src/app/modules/rup/components/elementos/egresoInternacion.component.ts, src/app/modules/rup/components/elementos/egresoInternacion.html, src/app/services/procedimientosQuirurgicos.service.ts
- Creo el elemento rup para la molécula de egreso
- Lo agrego a la ejecución de internacion con los métodos para ejecutar un concepto snomed
=> Molecula egreso

src/app/app.module.ts, src/app/components/mapa-de-camas/cama/cama-create-update.component.ts, src/app/components/mapa-de-camas/cama/cama.component.html, src/app/components/mapa-de-camas/cama/camasListado.html, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.scss, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.html, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/elementos/pasesCama.component.ts, src/app/modules/rup/components/elementos/pasesCama.html, src/app/modules/rup/services/prestaciones.service.ts
- Mostrar en la ejecución de la internación el listado con los cambios de cama
=> Agregar listados de cambios de cama para una internacion

src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-carpetas.print.scss, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
- ahora es posible imprimir más de una agenda desde listado de turnos
=> Plan de contingencia

.angular-cli.json, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts, src/environments/environment.test.ts
- Nuevo environment para test
- fix imports de environments
=> Fix imports variables entorno

src/app/components/inicio/inicio.html
Sacar botón Acosta2 (de acceso a la internación) de la pantalla principal.
=> Botón internación

package-lock.json, package.json, src/app/app.routing.ts, src/app/components/mapa-de-camas/cama/camaEstado.component.ts, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/components/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts
Poder cargar el ingreso de un paciente a internación sin asociarlo a una cama.
=> Ingreso sin cama

src/app/components/paciente/paciente-create-update.component.ts, src/app/components/paciente/paciente-detalle.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/services/obraSocial.service.ts
- Se invoca al servicio de ANSES para verificar cuil de paciente.
- Se invoca al PATCH para insertar el N° de CUIL en la BD a demanda.
- Linteos varios
=> Cuil demand

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/internacion/ocuparCama.component.ts, src/app/modules/rup/components/elementos/ingresoInternacion.html
Fix para compilar para producción
=> Corregir fix para compilar para produccion

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Fix bug en el toast que mostraba "mensaje enviado a paciente UNDEFINED"
=> Fix sms producción

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
Resuelve error en reasignacion de turnos y en rup
=> se agrega _id  en el tipoPrestacion del turno

src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
fix sobre turnos que no guardaba tipo prestacion
=> Fix sobreturno

src/app/components/organizacion/organizacion-create-update.component.ts, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.html, src/app/modules/rup/components/elementos/egresoInternacion.component.ts, src/app/modules/rup/components/elementos/egresoInternacion.html
- Molécula de egreso.
- Guardado de internacion.
- Validar una prestación.
- Romper la validación y guarda un clon.
=> Egreso guardado

src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/dashboard/turnos-paciente.component.ts, src/app/components/turnos/dashboard/turnos-paciente.html
- Mostramos el historial de turnos del paciente en el punto de inicio. Accediendo a las operaciones de turnos, y luego al tab "historial"
- En las "estadísticas de paciente" del punto de inicio mostramos el nro de carpeta del paciente
=> Historial punto inicio

Dockerfile
Saco las dependencia globales de la imagen de Docker.
=> Dockerfile Modificaciones

src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- Se visualizan los sobreturnos en el panel derecho p/ agendas suspendidas.
- se agrega soporte para enviar sms a sobreturnos suspendidos.
Observación: evaluar este cambio con los PO.
=> fix Bug 43 - Agenda suspendida/sobreturnos

src/app/app.component.ts, src/app/components/turnos/dashboard/paciente-search-turnos.component.ts, src/app/components/turnos/dashboard/paciente-search-turnos.html, src/app/components/turnos/dashboard/puntoInicio-turnos.component.ts, src/app/components/turnos/dashboard/puntoInicio-turnos.html, src/app/components/turnos/dashboard/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts, src/app/components/turnos/dashboard/solicitud-turno-ventanilla/solicitud-turno-ventanilla.html, src/app/components/usuario/arbolPermisos.component.ts
- agregamos controles de permisos para dar turno, solicitudes y solicitudes/autocitación en punto de inicio
=> control permisos pto inicio

src/app/components/prestamosHC/historial/historial-hc.component.html, src/app/components/prestamosHC/prestamos/listar-prestamos.component.html, src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts, src/app/services/prestamosHC/prestamos-hc.service.ts
funcionalidad para que se presten masivamente, en la sección de solicitud de carpetas.
=> se agrega multiselect de solicitudes de carpetas para prestar masivamente

src/app/components/prestamosHC/historial/historial-hc.component.html, src/app/components/prestamosHC/historial/historial-hc.component.ts, src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
para limpiar los commits locales, creo esta rama para resolver el marge
=> fix al deseleccionar en seleccion multiple de prestamos y solicitudes

src/app/app.module.ts, src/app/modules/rup/components/elementos/circunferenciaCintura.component.ts, src/app/modules/rup/components/elementos/circunferenciaCintura.html
Nuevo atomo para circunferencia de cintura
Agregar "elementoRup" a la base de datos.
{
"_id" : ObjectId("5acf93518651e106baf2add4"),
"componente" : "CircunferenciaCinturaComponent",
"style" : {
"columnas" : 6.0,
},
{
"fsn" : "circunferencia de la cintura (entidad observable)",
"semanticTag" : "entidad observable",
"refsetIds" : [ 
"900000000000497000"
],
"conceptId" : "276361009",
"term" : "circunferencia de la cintura"
}
],
"frecuentes" : []
}
=> RUP circunferencia de cintura

src/app/components/turnos/dashboard/estadisticas-agendas.component.ts, src/app/components/turnos/dashboard/estadisticas-agendas.html, src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
Fix en log de pacientes. Se muestra cantidad de turnos auditados x el usuario loggeado. Se corrigen valores en estadisticas de punto de inicio
=> Fix log pacientes

package-lock.json, src/app/app.module.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/elementos/odontologiaDefault.component.ts, src/app/modules/rup/components/elementos/odontologiaDefault.html
Atomo para registrar procedimientos, trastornos, hallazgos, etc de odonto y poder asociarlos a una pieza dental y/o a una cara dental.
Elemento RUP que se debe cargar en la base:
```
{
"_id" : ObjectId("5ace582e563f39df936ced27"),
"componente" : "OdontologiaDefaultComponent",
"style" : {
"columns" : 12.0,
},
{
"fsn" : "tratamiento de conducto completo (procedimiento)",
"semanticTag" : "procedimiento",
"refsetIds" : [ 
"721145008", 
"900000000000497000"
],
"conceptId" : "54258006",
"term" : "tratamiento de conducto completo"
}, 
{
"fsn" : "inserción de restauración con amalgama en el diente (procedimiento)",
"semanticTag" : "procedimiento",
"refsetIds" : [ 
"721145008", 
"900000000000497000"
], …
```
=> Atomo default odonto

package-lock.json, src/app/components/prestamosHC/prestamos/listar-prestamos.component.html, src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
* sort de carpetas en la sección de **prestamos** (al igual que en solicitudes)
* sort de carpetas en la sección de **solicitudes** se mejora, porque no se tenia en cuenta los num de carpetas con letras
=> se agrega sort en prestamos de carpetas

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/gestor-agendas/operaciones-turnos/carpeta-paciente.component.ts
- Creación de Nro de carpeta en punto de inicio.
- Avisos de carpeta repetida cuando se intenta modificarla en punto de inicio, desde el gestor o al momento de dar el turno
=> Numeros de carpeta de pacientes

src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/components/turnos/gestor-agendas/gestor-agendas.html
- Sacamos el botón dar turnos del gestor de agendas :crying_cat_face:
=> (BugZilla) Bug 60 - Botón dar turnos - gestor

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/services/prestaciones.service.ts
Parche para la autocitación desde rup: búsqueda de agendas para tipos… de prestaciones con sinónimos
=> Parche para la autocitacion

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- fix revisión no mostraba el diagnóstico principal cie10
=> Hotfix revision

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- hotfix revisión no mostraba diagnóstico principal por condición errónea
=> modifico revision

src/app/components/turnos/autocitar/autocitar.component.ts, src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
Mostrar todas las agendas disponibles y publicadas sin limitar al mes corriente. Fix de estados en los trastornos
=> Corregir listado de agendas para autocitaciones

src/app/app.component.ts
Modificamos el tiempo en que se llama al servicio de RED CLOUD
=> red cloud checker every minute

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html
=> Fix numero carpeta

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
quitamos restricción fecha inicio en planificar agenda
=> mejora planificación agendas

src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/carpeta-paciente.component.ts
Gestor agendas, actualizo la función de modificar carpeta
=> fix carpetas gestor

src/app/app.module.ts, src/app/modules/rup/components/elementos/percentiloPerimetroCefalico.component.ts, src/app/modules/rup/components/elementos/percentiloPerimetroCefalico.html, src/app/modules/rup/components/elementos/perimetroCefalico.component.ts, src/app/modules/rup/components/elementos/perimetroCefalico.html
El conceptId de perímetro cefálico es: 363812007.
El conceptId de percentilo de perímetro cefálico es: 248397001
Son registros agregados a elementosRUP
=> percentilo perimetro cefalico y perimetro cefalico

src/app/components/usuario/arbolPermisos.component.ts, src/app/components/usuario/arbolPermisos.html, src/app/services/tipoPrestacion.service.ts
Agregamos un parche para que se vean correctamente las prestaciones en el listado de permisos.
=> Corregir la visualización de listado de prestaciones en los permisos

src/app/components/turnos/dar-turnos/dar-turnos.html
- Botón no asigna turno disponible desde que se ingresa a la pantalla dar-turno.
=> Botón no se asigna turno

package-lock.json, src/app/app.module.ts, src/app/components/paciente/paciente-create-update.component.ts, src/app/components/paciente/paciente-create-update.html, src/app/components/paciente/paciente-detalle.html, src/app/components/paciente/paciente-detalle.scss, src/app/components/paciente/paciente-detalle.ts, src/app/services/fuentesAutenticas/servicioRenaper.service.ts
- Si el paciente está validado agrega la foto y si no tiene cuil también lo agrega.
- Si el paciente es temporal, agrega la información y valida.
Obs: también entra para el prox. test. (Ojo que la API no tiene las URL definitivas de producción)
=> Renaper foto

src/app/modules/rup/components/core/rup.scss, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/elementos/lactancia.html, src/app/modules/rup/components/elementos/percentiloPerimetroCefalico.component.ts, src/app/modules/rup/components/elementos/percentiloPeso.component.ts, src/app/modules/rup/components/elementos/percentiloTalla.component.ts, src/app/modules/rup/components/variables.scss
Permite tener percentilos en 0 pero muestra una alerta en tal caso.
Arreglos en lactancia
=> Lactancia y percentilos

src/app/components/paciente/paciente-create-update.html, src/app/components/paciente/paciente-detalle.html, src/app/components/paciente/paciente-detalle.ts
=> nueva funcion "deshacer validación por renaper"

src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.html, src/app/components/prestamosHC/solicitudes/imprimir-solicitudes.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-carpetas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-carpetas.html
- Fix en listados de nros de carpeta.
=> fixes nros carpeta

src/app/components/prestamosHC/solicitudes/prestar-hc.component.ts
Se agrega control para los préstamos automáticos
=> fix prestamos automáticos

.angular-cli.json, package-lock.json, package.json, src/app/app.component.html, src/app/app.component.ts, src/app/components/login/login.component.ts, src/app/components/login/login.html, src/app/modules/estadisticas/components/home.html, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/environments/environment.demo.ts, src/environments/environment.prod.ts, src/environments/environment.ts
- Plex Ribbon
- Pruebas de Plex Layout en algunas vistas.
- Environment de producción, demo y testing. 
- Versión de la aplicación en el environment.
=> Actualización de Plex

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
=> Corregir la validacion para los datos obligatorios de Screening neonatal

src/app/components/reportes/consultaDiagnostico.html, src/app/components/reportes/encabezadoReportes.html, src/app/components/reportes/reporteC2.component.ts
- Se modifica nombre de botón a Generar Reporte
- Se muestra lista de pacientes en todos los items
=> Cambio en Reporte C2

src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/services/camas.service.ts
Se agrega funcionalidad para que el mapa de cama se pueda ver por fecha y hora.  [OP#118](https://openproject.hospitalneuquen.org.ar/projects/rup/work_packages/118/activity)
=> Internación: Ver el estado del mapa de cama en una fecha determinada.

src/app/components/usuario/arbolPermisos.component.ts, src/app/components/usuario/usuarioUpdate.component.ts
* Se resuelven los incidentes relacionados con el almacenamiento y visualización de las prestaciones en diferentes operaciones
=> Mostrar prestaciones guardadas en permisos

src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/ejecucionInternacion.html
Agrego un badge en la epicrisis de ejecución internacion, para avisar que tiene una epicrisis en ejecución
=> Internación: Visualización de la epicrisis

package-lock.json, package.json, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
=> Fix Mensaje de texto -  reasignar un turno

src/app/components/inicio/inicio.html, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts, src/app/components/prestamosHC/solicitudes/prestar-hc.component.html
mostrar numero de carpeta al prestarla
se cambia nombre del componente historia clínica por PRESTAMOS DE CARPETAS
=> fix para v330

package-lock.json, package.json, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/components/elementos/informe.html, src/app/modules/rup/components/elementos/observaciones.html
Se cambian los textarea por rich-text en los siguientes componentes:
- Evolución
- Informes
- Observaciones
=> Se cambia textarea/plex-text por rich-text

src/app/components/turnos/dashboard/arancelamiento-form.component.ts, src/app/components/turnos/dashboard/arancelamiento-form.html
- Resueltos los temas del issue #568
- Quitamos pantalla de "vista previa" de la impresión, ahora se abre directamente el diálogo de impresión del browser.
=> fix arancelamiento

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
Ahora se visualiza la fecha de inicio estimada a la altura del titulo del problema
se saca el estado de cada evolucion
=> Issue 581 fecha estimada

src/app/modules/rup/components/laboratorios/laboratorios.component.ts
- Fix del borrado de la extensión PDF
=> fix extension

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html
Se busca la obra social del paciente
se guarda la obra social en la solicitud de la prestacion
=> #205 Agregar obra social a la prestacion internacion

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html
Si el usuario logueado es profesional, se asigna al select de profesional por defecto
=> #205 Internacion - se agrega profesional en el ingreso de internacion

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html
Se agrega organización en el inicio de la internación si el origen de hospitalización es _traslado_ o _consultorio externo_
=> #205 Internacion - se agrega organizacion en inicio internacion

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/carpeta-paciente/carpeta-paciente.html, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/gestor-agendas/turnos.component.ts, src/app/components/turnos/gestor-agendas/turnos.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
* **Va con el PR 371 en API ---> https://github.com/andes/api/pull/371** 
* fix issue #599 
* fix issue #638 
* fix issue #637 
*fix issue #635
=> Carpeta paciente en sobreturnos

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html
se deja comentado los datos del paciente y de la cama cuando se inicia internacion
=> se reacomodan los datos de ingresio en internacion

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/services/prestaciones.service.ts
=> fixeo el issue 571 del buscador de rup.

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html
=> huds: Visualización de planes  

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- Bug fix #665 
- Mostramos en Nro de carpeta correcto para los pacientes listados en revisión de agendas.
=> Nro. Carpeta paciente en revisión de agenda - Corrección

.github/pull_request_template.md
Agregamos template para los nuevos pull request, con una guía para el titulo y la descripción de los mismos.
=> Agregamos template para los pull request

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/carpeta-paciente/carpeta-paciente.html
* Link a la user storie de open project, referencia al issue (#1111) o breve descripcion del requerimiento
issue #663 
1. Nuevo permiso y validaciones para editar carpetas desde pto de inicio
*  **PR homónimo en la API**
=> CITAS - Punto de inicio - Mejoras en edición de nro de carpeta

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html, src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
* Reporte de error al intentar imprimir formulario de arancelamiento
1. Corrección patch de motivo de consulta 
2. Actualización de la llamada a la ventana de impresión de form. arancelamiento
=> Actualización formulario arancelamiento

src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
* **issue *#660***
* Se corrige un error en el código que refrescaba el historial de turnos del paciente luego de interactuar con los botones de dar/quitar asistencia.
=> Punto de inicio - Bug en cambio de asistencia

src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.html
1. Agregamos emitter perdido en merge
=> agregamos lineas perdidas en el merge

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
=> Issue#644: 'Colapsar registros'

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/vistaHuds.html
=> issue 647: Se modifica label "motivo principal de consulta" 

src/app/app.component.ts, src/app/app.routing.ts, src/app/components/inicio/inicio.html
=> se modifica ruta del puntoInicio de turnos

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Planificar Agenda:
- Se corrige el form para que el botón guardar no desaparezca luego de un input inválido en la cantidad de turnos.
=> fixed de botones "guardar" y "clonar" que no volvian a aparecer.

src/app/components/turnos/gestor-agendas/gestor-agendas.html
* Issue #682 
1. fix condición para mostrar badge turnos suspendidos
=> Badge turnos suspendidos Issue#682

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dashboard/turnos-paciente.html
* Error al intentar dar turnos dobles, en el componente dar-turnos
1. BugFix en turnos dobles.
2. :turtle:
=> Turnos dobles

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Mostrar el numero de carpeta del paciente en el punto de inicio de rup para pacientes en agendas
1. Filtramos los nro de carpetas que se visualizan en el punto de inicio de RUP por efector
=> RUP - Filtramos los números de capeta por efector en el punto de inicio

src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
#695 
1. Mejora en la búsqueda de profesionales en filtros del gestor de agenda y en planificación de agenda
=> Búsqueda de profesionales en filtro gestor de agendas

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
* Issue: Agenda Auditada #577
1. Se unificaron los métodos que cerraban la asistencia y la codificación en uno solo para evitar que las llamadas asincrónicas a éstos generaran inconsistencias.
=> CITAS - Se corrigen inconsistencias en cambios de estado (de agenda) en la Revisión

src/app/modules/rup/components/elementos/consultaDeNinoSanoE2Y3A.html, src/app/modules/rup/components/elementos/consultaDeNinoSanoE3Y6A.html, src/app/modules/rup/components/elementos/consultaDeNinoSanoM2A.html
Visualizar el texto que e cargaba como observación por defecto para los procedimientos de niño sano de x días/meses/años
1. Mostramos en el html de los componentes para niño sano de x días/meses/años el registro.valor para ver los registros históricos.
=> RUP - Niño sano: visualizar el texto que se venia cargando por defecto antes de nueva implementación

src/app/modules/rup/components/elementos/consultaDeNinoSanoE2Y3A.component.ts, src/app/modules/rup/components/elementos/consultaDeNinoSanoE3Y6A.component.ts, src/app/modules/rup/components/elementos/consultaDeNinoSanoM2A.component.ts, src/app/modules/rup/components/elementos/indiceDeMasaCorporal.component.ts, src/app/modules/rup/components/elementos/percentiloDeMasaCorporal.html, src/app/modules/rup/components/elementos/percentiloDeTensionArterial.html, src/app/modules/rup/components/elementos/percentiloPerimetroCefalico.html, src/app/modules/rup/components/elementos/percentiloPeso.html, src/app/modules/rup/components/elementos/percentiloTalla.html, src/app/modules/rup/components/elementos/perimetroCefalico.html
Evolucionar el procedimiento consulta de niño sano a los x dias/mese/años se estaban tomando por rango de edades y no por el mismo concepto.
1. Corregimos la búsqueda en la huds del paciente para que busque por concepto a ejecutar y no por el conjunto de un mismo elementoRUP 
2. Corregimos que se ocultaban por defecto los átomos de peso y talla para el IMC
3. Sacamos los requerid de los input de los átomos de percentilos.
=> RUP - Se corrige la búsqueda de la última consulta para niño sano

src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
ISSUE: fix #720 
1. Se redujeron los márgenes
=> CITAS - Corrección de márgenes en UI Dar Turnos

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
* fix #733
1. Se visualizan las modificaciones realizadas a la carpeta del paciente en el dar-turno desde el punto inicio
=> Citas > Punto Inicio > carpetas paciente

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html
* Ver las relaciones entre registros en RUP en forma de árbol.
1. Se corrigen errores a la hora de visualizar  las relaciones.
=> RUP: Visualización de relaciones

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* fix #713 - Al picar sobre un profesional dentro de la lista "búsquedas recientes", no se activan los filtros y aparece un error en consola.
* Búsquedas recientes mal ordenadas, las últimas quedan al final de la lista
1. Corregimos el orden de inserción/borrado de nuevos elementos para las búsquedas recientes
2. Corregimos el error que aparecía al elegir un profesional en la lista de búsquedas recientes
=> CITAS > Búsquedas recientes en dar turnos

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
* Luego de crear una nueva carpeta, si la editamos se guarda duplicada. :fire: :fire: :fire: :fire: 
1. Limpio código no utilizado en estadisticas-paciente
2. Fix del bug reportado
=> Punto inicio > Carpetas - Error carpetas duplicadas

src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/components/elementos/informe.html, src/app/modules/rup/components/elementos/observaciones.html
Se redujo la altura de los elementos rup observaciones, informes y evolucion
#645
=> RUP - Reducción campo richText issue#645

src/app/modules/rup/components/core/rup.html, src/app/modules/rup/components/elementos/indiceDeMasaCorporal.component.ts, src/app/modules/rup/components/elementos/indiceDeMasaCorporal.html, src/app/modules/rup/components/elementos/peso.html, src/app/modules/rup/components/elementos/talla.html, src/app/modules/rup/components/elementos/tensionSistolica.html
HUDS: Se mejora la visualización en columnas según sus relaciones. 
* https://pm.andes.gob.ar/projects/rup/work_packages/191/activity?query_id=22
* Parte de los requerimientos no tenían user story (alineamiento de los items) y otra parte tenía que ver con datos desactualizados en el servidor de DEMO
1. Los valores antropométricos se visualizan en la columna de la izquierda, mientras que los percentilos se alinean a la derecha.
2. Se actualizaron los datos en el servidor de DEMO para que se muestren registros faltantes.
Se ejecutaron las siguientes _queries_:
1.
```
db.getCollection("elementosRUP").insert({
"activo": true,
"componente": "ObservacionesComponent",
"tipo": "atomo",
"esSolicitud": false,
"style": {
"columns": 12,
"cssClass": null
},
"conceptos": [],
"requeridos": [], …
```
=> HUDS niño sano issues

src/app/components/usuario/usuarioCreate.component.ts, src/app/components/usuario/usuarioCreate.html
Se oculta el boton guardar si el nuevo usuario por agregar no esta seteado, esto evita que se guarden usuarios con datos en nulo
=> Fix crear usuario

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/services/documentos.service.ts
Funciona en conjunto con rama de la API con mismo nombre
=> Se implementa versión nueva de descarga de informes

src/app/components/turnos/dar-turnos/calendario.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
* Grisar días que no corresponden al mes seleccionado, para evitar confusiones, ya que en ellos no se ve si existen agendas disponibles.
1. Agregamos controles para evitar mostrar en el calendario de dar turnos los días que no corresponden al mes seleccionado.
=> Dar turnos > Calendario

src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.html
* https://pm.andes.gob.ar/projects/citas/work_packages/302/activity
1. Se visualizan en el historial del paciente los turnos que le fueron otorgados y posteriormente liberados.
2. Quitamos el botón LIBERAR de los SOBRETURNOS que aparecen en el listado de turnos del paciente
3.
=> Log liberar turno

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
1. HOTFIX select profesionales en planificar agenda. No carga el plex select desde el ngmodel. Pasamos los datos por el event del getdata
=> CITAS > planificar agenda > Precarga select profesionales

src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.html
Issue #759 
1. Se repara el issue #759
=> Internacion - Issue #759

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Issue #723 
1- En el gestor de agendas -> Crear nueva agenda: Se limita la creación de bloques VACIOS a uno. Es decir que antes de poder agregar un nuevo bloque vacío debe configurarse al menos el horario inicio y fin del bloque anterior.
2- Se reasignan los índices de cada bloque luego de eliminar alguno.
=> CITAS -> Dar Turnos -> Bloques desordenados

src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts
Resuelvo el issue #758  y issue #749
=> Internacion - Issue758 y issue #749

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* Cuando se asigna turno desde las solicitudes de un paciente (en punto de inicio turnos), el sms muestra el tipo de prestación como UNDEFINED
1. Se obtiene del input el tipo de prestación solicitada.
=> Citas - Punto Inicio - Dar turno desde solicitud - Fix tipo prestación SMS

src/app/components/organizacion/organizacion-sectores.component.ts, src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.html, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.html, src/app/modules/rup/components/elementos/ingresoInternacion.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama-create-update.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts
Solucionar la visualización de la obra social en el formulario de ingreso de una internación. Cambiar labels de genero y servicios. Agregar la validación al egreso
1. Solucionamos la consulta de la obra social del paciente en el ingreso.
2. Cambiamos labels genero y servicio en la carga de la cama
3. Agregamos la validación en el form de egreso
4. Corregimos la eliminación de un sector en el mapa de sectores de la organización
- [] Si
- [] Si
=> Consultar obra social paciente en ingreso internacion

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
* Hotfix de mapeos (Agendas no nominalizadas)
1. En ejecución y validación se corrije llamada a método prestacionPacienteAusente()
=> Hot fix no nominalizada

src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/vistaCDA.component.ts, src/app/modules/rup/components/ejecucion/vistaCDA.html
* La visualización del Histórico sólo mostraba (en caso de SIPS) un código CIE10 a pesar de contener información sobre la evolución del paciente. Se habilitó esta visualización desde el html quitando el filtro del "title" que en estos casos no viene en el xml.
1. Se habilito en el html el control para poder visualizar la evolución en caso que se haya cargado.
2. Se le agrega el campo evolución en negrita para una mejor legibilidad.
- [] Si
- [] No
- [] Si
=> habilitamos el texto de la evolución

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html
Poder editar el formulario de ingreso para la internación
1. Cambiamos la llamada al patch para actualizar los registros (ingreso y egreso) del formulario de hospitalización 
2. Agregamos los datos que no se veían del formulario al momento de actualizar (traslados, obra social)
=> RUP - Internación: Edición form hospitalización

src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.html, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/services/internacion.service.ts
Calcular días de estada para el formulario de egreso
1. Se agrega el campo días de estada formulario de egreso 
2. Se agrega emit al validar la internación para actualizar el mapa de cama
=> Actualizar egreso

src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Agregamos un control para el acceso al paciente en el componentes que  se cargan dinamicamente
1. Agregamos un control de que este cargado el paciente para cargar los componentes dinámicos en la validación
2. Agregamos un control en la validación para el acceso a los registros vinculados
3.
=> RUP - Control del paciente en la validación de una prestación

src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts
* https://pm.andes.gob.ar/work_packages/530
Operación inline: dividir fecha y hora en dos campos porque el ancho no da
Operación inline: los botones deben ser plex-button
Desbloquear: quitar textos innecesarios. Usar plex-radio:
=> Internación-Mejoras para internación #530

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama-create-update.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama-create-update.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html
https://pm.andes.gob.ar/projects/rup/work_packages/530/activity
Filtros: ocultar por el momento la columna “Estados” y expandir Sector y Unidad organizativa. 
Filtros: sacar el “requerido” de los buscadores así no se ve como arriba
Ocultar el botón para cerrar el sidebar. Por lo pronto que el sidebar quede siempre abierto
- [] Si
- [x ] No
- [ x] No
=> Internacion- Mejoras para internación

src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.scss
* Se modifica visualización de camitas en el mapa de camas.
1. Se eliminan botones inferiores y se llevan a la botonera superior.
2. Correcciones en estilo del back de las camas.
=> Se actualizan estilos y botones de camitas (front y back)

src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama-create-update.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.scss, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/interfaces/ICamaEstado.ts, src/app/modules/rup/services/camas.service.ts, src/app/modules/rup/services/internacion.service.ts, src/app/modules/rup/services/prestaciones.service.ts
* Simplificar el workflow de internación
1. Agregamos una configuración en el servicio de internación para indicar por efector si requiere workflow completo o no. Esto es que incluya el estado a preparar y la lista de espera.
2. Modificamos la operación de desocupar cama para indicar si se realiza un movimiento de cama o se egresa al paciente.
=> Cambio workflow

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts
1. Se utiliza el servicio notificarRuta para setear label y ruta de botones para la navegación desde punto de inicio y mapa de camas
=> Internacion - Botones navegacion internacion

src/app/app.module.ts, src/app/app.routing.ts, src/app/components/inicio/inicio.component.ts, src/app/components/inicio/inicio.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts, src/app/modules/rup/components/internacion/puntoInicio-internacion.html, src/app/modules/rup/components/internacion/puntoInicio-internacion.scss, src/app/pipes/html2text.pipe.ts
1. Se cambian los estilos para que el sideber de epicrisis se pueda visualizar en pantallas mas chicas
=> Internacion - cambio de estilos para distintos dispositvos

src/app/app.module.ts, src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.component.ts, src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.html
* https://pm.andes.gob.ar/projects/rup/work_packages/458/activity
1. Se agrega componente que corresponde a la prestación de enfermería. 
2. Se agregan los elementos RUP que corresponden a esta prestación.
Insertar los siguientes registros en la colección elementosRUP
// Procedimiento de Enfermería
{
"_id" : ObjectId("5b895b28bd7c1f8e59c2ad1d"),
"componente" : "ProcedimientoDeEnfermeriaComponent",
"motivoConsultaOpcional" : false,
"style" : {
"columns" : 12,
},
{
"fsn" : "procedimiento de enfermería (procedimiento)",
"semanticTag" : "procedimiento",
"conceptId" : "9632001",
"term" : "procedimiento de enfermería"
}
],
"defaultFor" : []
}
// Consulta de …
=> RUP - Prestación de enfermería

src/app/modules/rup/components/ejecucion/internacion/ListaEsperaInternacion.html, src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.html, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.html, src/app/modules/rup/components/internacion/censo/censoMensual.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/services/camas.service.ts, src/app/modules/rup/services/internacion.service.ts
https://pm.andes.gob.ar/projects/rup/work_packages/530/activity
Convertir los botones en tabs (Internación ( Sólo si está la cama ocupada), Cama, Historial de la cama)
Tab Internación: Ordenar mejor los datos de ingreso (similar formulario). Ocultar labels de campos que estén vacíos. Donde se muestren los datos del paciente, mostrar un botón de acceso a la HUDS. Cuando se edite ingreso/egreso, ocultar todo el resto de los elementos y dejar sólo se formulario. Al volver/guardar volver a mostrar todo
Tab cama: mostrar más data. Por ejemplo, si está bloqueada que muestre la razón de bloqueo. En general: servicio, OU, nombre, qué tiene (oxígeno), etc.
Tab Historial de cama: que muestre una tablita con todo lo que paso en esta cama en los últimos 30 días en forma descendente. También se puede …
=> RUP-Issue internacion

src/app/components/carpeta-paciente/carpeta-paciente.html, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts
* Ingreso de paciente a Internación
1. Se agregaron datos del paciente.
2. Se reorganizó la UI con fieldset con las siguientes secciones: Datos de Paciente, Datos de la internación, Datos estadísticos.
3. Se permite cambiar de paciente
=> Ui ingreso

src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.html
* resize de campos minutos en prestación de enfermería
=> resize de campos minutos

package-lock.json, package.json, src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.html, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/services/internacion.service.ts
* Ordenar los datos de egreso de la internación
1. Ordenamos los campos en el formulario de egreso
2. Visualización de los eventos obstetricos según diagnostico cie10
3. Cambiamos radios por plex-radio
=> RUP - Mejoras en el form de egreso

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
1. Se acortan la cantidad de caracteres en el sms de confirmación de turno
=> CITAS - Se formatea y se achican los caracteres del sms de confirmacion de turno

src/app/components/popover-audit/popover-audit.component.ts
* Se agrega control para turnos emitidos desde appMobile en tooltip de auditoría (componente turnos)
=> CITAS - Control en tooltip auditoría de turnos.

src/app/modules/rup/components/ejecucion/internacion/egresoInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.html, src/app/modules/rup/components/ejecucion/internacion/resumenInternacion.html, src/app/modules/rup/components/internacion/censo/censoDiario.component.ts, src/app/modules/rup/components/internacion/censo/censoDiario.html, src/app/modules/rup/components/internacion/censo/censoMensual.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama-create-update.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.scss, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.html, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.scss, src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts, src/app/modules/rup/services/internacion.service.ts
* Simplificar UI del mapa de camas (sin terminar)
* Resolver bug al desocupar la cama teniendo el card seleccionado
=> RUP - Visualización del sidebar al seleccionar y desocupar una cama. Simplificación UI (parte I)

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
* Filtrar en las prestaciones fuera de agenda solo las prestaciones en ejecución y validadas
1. Se agrega filtro en el listado de fuera de agenda para prestaciones en ejecución y validadas
2. 
3.
=> RUP - Filtro sobre prestaciones fuera agenda

src/app/app.component.ts, src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts, src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.html, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts, src/app/modules/rup/components/ejecucion/vistaHuds.html
* Agregar acceso a la HUDS de un paciente desde el menú principal con un permiso especial
1. Se agrega al menu hamburguesa el acceso a la HUDS del paciente.
2. Se agrega control para que el acceso lo realice o bien un profesional o el que tenga el permiso especial
3.
=> RUP - Acceso a la HUDS desde el menu principal

src/app/components/paciente/paciente-detalle.ts, src/app/services/paciente.service.ts
1. Se modifica el regex del PR #802 para que chequee despues de espacios en blanco
2. Check de nombre y apellido de ws renaper contra regex modificado
=> MPI -> Se chequea nombre y apellido traido por renaper

src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
* ISSUE: https://github.com/andes/app/issues/886
**Requiere aprobación de PR en la API**
=> TOP - fix #886 

package-lock.json, package.json, src/app/components/paciente/paciente-detalle.ts
* fix #903
1. Mejora en el workflow de validación del paciente, en el caso mencionado en el issue.
=> mejora en el workflow de la validación

src/app/modules/rup/services/prestaciones.service.ts
=> TOP - Se corrige error de prestación en generación de solicitudes desde RUP

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
* Resuelve el issue #825 
1. Ocultar la cara y el diente en la revisión cuando el diagnostico es de Snomed.
=> CITAS - Revisión de agenda de Odontología

src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
=> CITAS - Bug en agendas dinámicas con múltiples prestaciones

package-lock.json
* Se cambia la versión de plex a 3.6.2
=> Actualización de versión 3.6.2

package-lock.json, package.json, src/app/components/paciente/paciente-detalle.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/services/fuentesAutenticas/servicioSisa.service.ts
Soluciona incidente issue #787 y https://github.com/andes/app/issues/906
1. Se chequea que el usuario no intente validar un paciente con campo de sexo 'otro'. En dicho caso se muestra un toast.
2. Soluciona incidentes en los intentos de validación para el caso que la validación con Renaper traiga caracteres inválidos. Fix (https://github.com/andes/app/issues/906)
=> Agrega controles en la validación de pacientes

src/app/components/top/solicitudes/nuevaSolicitud.component.ts
* Quita restricciones en permisos TOP por tipo de prestación (temporalmente)
=> hotfix permisos TOP

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
* Quita el confirm al volver al punto de inicio desde la validación
1. 
2. 
3.
=> RUP - Quita el confirm al volver al punto de inicio desde la validación

src/app/components/prestamosHC/historial/historial-hc.component.html, src/app/components/prestamosHC/historial/historial-hc.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts, src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.html, src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.ts
1. Antes de generar prestamo manual, busca carpetaEfectores en el Paciente
2. Si no encuentra carpetaEfectores en Paciente sigue con la busqueda en la coleccion carpetaPaciente
3. Si existe carpeta en carpetaPaciente, se guarda en las carpetaEfectores en Paciente
=> PRESTAMOS HC - refactorizacion en la busqueda de carpetasPacientes

src/app/components/turnos/autocitar/dinamica.component.ts
* Resuelve Issue #948
1. Controla si hay una sola prestación en la agenda y la selecciona por defecto
2. 
3.
=> RUP - Corrige bug de cargar un paciente en una agenda dinamica

src/app/components/auditoria/prestacionPaciente/editar-auditoria-prestacionPaciente.component.ts, src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/llaves/tipoPrestacion/editar-llaves-tipoPrestacion.component.ts, src/app/components/organizacion/organizacion-create-update.component.ts, src/app/components/organizacion/organizacion-sectores.component.ts, src/app/components/organizacion/sectores-item/sectores-item.component.ts, src/app/components/paciente/paciente-create-update.component.ts, src/app/components/paciente/paciente-search.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts, src/app/components/top/solicitudes/nuevaSolicitud.component.ts, src/app/components/turnos/configuracion/espacio-fisico/panel-espacio.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts, src/app/components/turnos/gestor-agendas/turnos.component.ts, src/app/components/turnos/punto-inicio/activar-app.component.ts, src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts, src/app/modules/mpi/components/paciente-buscar.component.ts, src/app/modules/rup/components/ejecucion/internacion/iniciarInternacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/internacion/mapa-de-camas/cama/cama-create-update.component.ts
* Actualizar las llamadas de plex.alert por plex.info. Plex alert esta en desuso.
=> plex: actualiza plex.alert por plex.info

src/app/components/inicio/inicio.html, src/app/components/inicio/inicio.scss, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
* Visualización de los cuadrados del inicio de Andes
1. Se aplican clases de boostrap para acomodar los botones de los modulos del inicio de Andes.
Revisado con @JSantarelli
=> Pantalla de inicio: ajusta estilos en pantalla de inicio

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* fix #745 
1. Se copia el motivo de la solicitud en el motivo del turno
=> CITAS - Valor de motivo de la solicitud en el motivo del turno

src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
* https://pm.andes.gob.ar/projects/top/work_packages/581/activity
1. Se agregan filtros en módulo TOP
=> Nuevos filtros top

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html
* En una consulta se están pudiendo registrar conceptos repetidos. 
* Corregir un bug al evolucionar trastornos o hallazgos
1. Se Corrigen filtros al ejecutar conceptos para evitar repetidos (sin odontología).
2. Se corrige búsqueda de relaciones para armar el árbol de relaciones en la validación.
3. Se elimina el label repetido para los radios.
=> RUP - Registros repetidos en una consulta y evolución de trastornos

src/app/components/usuario/busquedaUsuario.html, src/app/components/usuario/usuarioUpdate.component.ts, src/app/components/usuario/usuarioUpdate.html
Issue #916
Issue #926
Issue #927 
1. Asignar permisos a un efector ya habilitado: se filtra el nombre de los efectores ya asignados para no poder seleccionarlos nuevamente.
2. Mejora en la búsqueda de efectores: se agregó el nombre de la localidad en los select de efectores.
3. Perfil de usuario: ocultamos el árbol de permisos cuando no hay un efector seleccionado.
=> Gestión de usuario - Asignación de permisos

src/app/components/paciente/paciente-detalle.ts
* issue #778
1. Se contempla el caso de que un usuario intente validar por renaper un "nuevo paciente" temporal que en realidad ya es un paciente validado por otra fuente auténtica o scanner.
=> MPI - Validación por ReNaPer de un temporal ya validado por otra FA

src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
* Se agrega código de la obra social, para que se visualice el pdf de arancelamiento.  Fix issue https://github.com/andes/app/issues/978
=> Código de obra social

src/app/app.module.ts
* Solucionar error procedente de paciente-detalle
1. Se agrega el componente paciente-create-update a providers en app.module
=> Se incorpora PacienteCreateUpdateComponent a app.module -> providers

src/app/components/paciente/paciente-search.component.ts
* Se revierten cambios del pull request https://github.com/andes/app/pull/833, debido a inconvenientes con scaneos que se realizan luego del botón cancelar. 
1. Se quita last request
=> MPI: Búsqueda de Pacientes

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
* Fix issue #919 
* Corrige problema en orden de los bloques
=> fix Issue #919

src/app/components/puco/puco.component.ts, src/app/components/puco/puco.html, src/app/services/documentos.service.ts
* Sin User Story.
Dado un afiliado en un determinado padrón (Mes), se requiere poder imprimir los datos que se muestran por pantalla.
1. Nueva columna en la vista de un afiliado con la opción 'imprimir'.
=> PUCO - Generación constancia de afiliado

src/app/services/paciente.service.ts
1. Fix PUT path en el save de paciente service
=> Arregla path en service paciente

src/app/components/paciente/paciente-search.component.ts, src/app/modules/mpi/components/paciente-buscar.component.ts, src/app/services/pacienteSearch.interface.ts
* Pasar la funcionalidad de filtrado de pacientes inactivos a la api, directamente en la query de elastic.
1. Quitamos los filters para pacientes en todos los componentes buscadores.
2. Es posible obtener los pacientes inactivos desde el paciente.get agregando incluirInactivos:true al objeto query
**Es necesario setear todos los pacientes en las BD's MPI y ANDES con el campo activo:true y regenerar la base de elastic para actualizar el campo activo de todos los pacientes**
=> Filtrado de pacientes inactivos

src/app/components/top/solicitudes/nuevaSolicitud.component.ts, src/app/components/top/solicitudes/nuevaSolicitud.html
* issue #945 
1. Generando una nueva solicitud de entrada, una vez completados los campos 'organizacion origen' y profesional origen y destino, se realiza un chequeo para corroborar que si es autocitación no se trate de organizaciones distintas.
=> TOP - No permitir cargar el mismo profesional

package-lock.json, package.json, src/app/app.module.ts, src/app/app.routing.ts, src/app/app.routings-guard.class.ts, src/app/apps/campaniaSalud/components/campania-create-update.component.ts, src/app/components/paciente/headerPaciente.scss, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/modules/rup/components/ejecucion/internacion/ocuparCama.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/resumen.component.ts, src/app/modules/rup/components/ejecucion/resumen.html, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts, src/app/modules/rup/components/ejecucion/vistaHuds.html
* El header de paciente incide en el titulo del navbar.
1.  Implementa nueva funcionalidad de Plex para agregar una componente al navbar.
=> Custom navbar item de plex para header-paciente

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/elementos/SelectPorRefset.component.ts, src/app/modules/rup/interfaces/prestacionGetParams.interface.ts
* Corregir los filtros de búsqueda de prestaciones pendientes en el punto de inicio
1. Se corrigen los filtros de búsqueda de prestaciones pendientes en el punto de inicio
2. 
3.
=> RUP - Agrega filtros para prestaciones pendientes PI

src/app/components/paciente/paciente-create-update.component.ts
* Corregir plex info que aparecen sin formato y guardado de pacientes sin dni (No se guardan).
=> MPI - Se corrigen plex info y guardado de paciente sin dni

src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
Requerimiento
* Fix Issue #1031
1. Agrega información en la auditoría de prestaciones fuera de agenda
2. Filtra prestaciones por organización
=> CITAS - Auditoría de prestaciones fuera de agenda

src/app/app.routing.ts
* Corregir issue #1036
1.  Se agrega middleware faltante a algunas rutas.
=> app: limpia header del paciente

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
1. Quita control de agenda suspendida para reasignar dejando solo el control de turnos suspendidos
2. 
3.
=> RUP: Quita control de agenda suspendida para reasignar

src/app/modules/rup/components/ejecucion/puntoInicio.html
* Solución del bug #995
* Solución del bug #999 
1. Desde un paciente con sobreturno, registrarle la inasistencia.
2. Visualizar que se puede iniciar prestación
3. Visualizar que el botón revertir inasistencia no se visualiza
4. Cuando inicio prestación por error y vuelvo a la agenda que no se inhabilite el botón "NO ASISTIO".
=> RUP: Sobreturnos - Registrar inasistencia

src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/punto-inicio/turnos-paciente.html
* Se agrega información de espacio físico en el punto de inicio de CITAS y en la confirmación del turno
=> CITAS - mostrar información de espacio fisico

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
* Issue #929 
1. Se agrega control para verificar si existe dentro de la agenda seleccionada un turno con asistencia concretada.
=> CITAS - Suspender Agenda ya codificada

src/app/components/reportes/reporteC2.component.ts, src/app/components/reportes/reporteC2.html
* Se modificó simplemente unas cuestiones estéticas de la pantalla para generar reportes C2
1. 
2. 
3. 
Pull request API: https://github.com/andes/api/pull/573
=> Prestacion fuera agenda

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://github.com/andes/app/issues/1051
1. Se cambia el filtro de fecha de creación por fecha de ejecución
2. 
3.
=> RUP: Filtros de fuera de agenda en punto de inicio

src/app/modules/rup/components/elementos/observaciones.component.ts, src/app/modules/rup/components/elementos/observaciones.html, src/app/modules/rup/components/elementos/registrarMedicamentoDefault.html
https://pm.andes.gob.ar/projects/rup/work_packages/639/activity
=> RUP- Colonoscopia: Mejoras de estilos

src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
* Corrige bug en condición de btn suspender
=> CITAS - Corrige bug en condición de btn suspender

src/app/modules/rup/components/ejecucion/buscador.scss, src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html
* Se requiere poder filtrar las prestaciones de la huds por tipo de prestacion y por fecha
1. Se agrega un boton para mostrar u ocultar los filtros de las prestaciones.
2. Se agrega un filtro por tipo de prestación
3. Se agregan dos filtros de fecha. Una fecha desde y otra fecha hasta
4. Queda comentado el código de un buscador básico. Se implementara en el futuro
=> RUP- Filtros en el buscador de la HUDS

src/app/app.module.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/buscador.scss
* Cuando se busca en RUP terminos que devuelven muchos resultados se alentece el navegador por la cantidad de resultados que se renderizan en el DOM.
1. Implementa el componente `cdk-virtual-scroll-viewport` para generar una lista virtual.
=> rup: virtual scroll en listado de conceptos.

src/app/components/profesional/profesional-create-update.component.ts, src/app/components/profesional/profesional.html
1. Se agrega condición para cuando el sexo es undefined al momento de crear un profesional. 
2. Se agrega hover en el listado de profesionales.
=> TM - Arreglo en create-update de profesionales

src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
=> CITAS - close #1073

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html
* Corregir error que ocurre al ingresar en el efector "centro médico integral" el número de afiliado sin tener seleccionada la OS
=> CITAS - Agrega condición en OS del turno

src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts
* Responde a la resolución del issue #1072
=> CITAS: Resuelve bug de mostrar el espacio físico si la agenda es suspendida.

src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/dashboard/turnos-paciente.html, src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html, src/app/components/turnos/punto-inicio/turnos-paciente.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.html, src/app/services/facturacionAutomatica.service.ts, src/environments/environment.ts
* Se reemplaza pull request https://github.com/andes/app/pull/1100
1. Soluciona la visualización del nomenclador de la prestación en el Formulario de Recupero
2. fix https://github.com/andes/app/issues/805
(Actualizar colección configFacturacionAutomatica)
https://github.com/andes/api/pull/598
=> Recupero: Orden de Prestación

src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
* Se comenta la llamada al servicio para generar orden de prestación hasta cambiar por las rutas definitivas
=> Recupero: se quita la llamada al servicio de generar orden

src/app/components/login/selectOrganizacion.component.ts, src/app/components/login/selectOrganizacion.html
=> organizaciones: ajusta layout selección de efector

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* Se requiere que se haga una búsqueda correcta del número de carpeta del paciente.
=> CITAS -  Arreglo búsqueda de nroCarpeta

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
desuscribir get de agendas cuando se recorren las agendas por día
1. Se asigna subscripcion de agendas a una variable, se cancela dicha subscripcion antes de ejecutar un get de agendas.
=> RUP - unsubscribe de get de agendas en puntoInicio 

src/app/apps/rup/internacion/components/cama-create-update.component.ts, src/app/apps/rup/internacion/components/cama-create-update.html, src/app/apps/rup/internacion/components/censoMensual.component.ts, src/app/apps/rup/internacion/components/censoMensual.html, src/app/apps/rup/internacion/components/egresoInternacion.component.ts, src/app/apps/rup/internacion/components/egresoInternacion.html, src/app/apps/rup/internacion/components/iniciarInternacion.component.ts, src/app/apps/rup/internacion/components/iniciarInternacion.html, src/app/apps/rup/internacion/components/listado-internacion.component.ts, src/app/apps/rup/internacion/components/mapa-de-camas.component.ts, src/app/apps/rup/internacion/components/resumenInternacion.component.ts, src/app/apps/rup/internacion/components/resumenInternacion.html, src/app/apps/rup/internacion/services/camas.service.ts, src/app/components/organizacion/organizacion-create-update.component.ts, src/app/services/documentos.service.ts, src/app/services/ocupacion/ocupacion.service.ts
* Censo mensual y arreglos de funcionalidad
1. Arreglo en la consulta cuando trae camas con el mismo nombre.
2. Vista del censo mensual
3. Sacar organizaciones en consultorio externo en el egreso
4. Botones de la cama en fechas anteriores
5. Ordena por fecha el listado de movimiento de camas
6. Arreglo en la consulta de unidades organizativas en la organización
7. Arreglo en botón editar en lista de internación.
8. Búsqueda por código y nombre de ocupaciones en ingreso y procedimientos en egreso
9. Restricciones en determinados diagnosticos obstétricos
10. Control de si el diagnostico principal es primera vez o no.
=> RUP: Internación - Censo Mensual y otros arreglos

src/app/components/carpeta-paciente/carpeta-paciente.component.ts
* Se agrega condición  para que te sugiera nro de carpeta del paciente en la pestaña "Carpetas" del punto de inicio de Gestión de Pacientes.
=> CITAS - Arreglo Nro carpeta en Punto Inicio

src/app/apps/rup/internacion/components/egresoInternacion.component.ts, src/app/apps/rup/internacion/components/egresoInternacion.html, src/app/apps/rup/internacion/components/listado-internacion.component.ts
* Mejoras de visualización en el listado de internaciones
1. Visualización de procedimientos quirúrgicos en caso que se hayan cargado únicamente.
2. Visualización de los datos obstetricos, ya sea en diagnostico principal como en otros diagnósticos.
=> RUP- Internación-Arreglos de visualizacion en listado y egreso

src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/components/buscadorTurnosPrestaciones/interfaces/turnos-prestaciones.interface.ts, src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html, src/app/modules/rup/components/ejecucion/vistaPrestacion.component.ts, src/app/modules/rup/components/ejecucion/vistaPrestacion.html
* https://pm.andes.gob.ar/projects/citas/work_packages/716/activity
1. Agrega opción en menu hamburguesa (requiere permisos)
2. Agrega componente buscador de turnos y prestaciones
=> CITAS - Buscador de turnos y prestaciones

src/app/components/login/selectOrganizacion.html, src/app/components/login/selectOrganizacion.scss, src/environments/environment.ts
1. Cambia el handler click de tag para reaccionar en toda el area del item.
2. Limpieza de código.
=> inicio: ajusta click en item de seleccion de efector

src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts, src/app/modules/rup/components/elementos/adjuntarDocumento.html
https://pm.andes.gob.ar/projects/rup/work_packages/202/activity
1. Se actualizó elemento RUP Adjuntar documento. Ahora solicita se ingrese una descripción del documento adjuntado y permite cargar una fecha de referencia del documento
=> RUP - Mejora en documentos adjuntos

src/app/app.component.ts, src/app/apps/rup/internacion/components/cama.component.html, src/app/apps/rup/internacion/components/cama.component.scss, src/app/apps/rup/internacion/components/cama.component.ts, src/app/apps/rup/internacion/components/mapa-de-camas.component.html, src/app/apps/rup/internacion/components/mapa-de-camas.component.scss, src/app/apps/rup/internacion/components/mapa-de-camas.component.ts, src/app/components/inicio/inicio.component.ts, src/app/components/inicio/inicio.html, src/app/modules/estadisticas/components/home.scss
1. listado internacion modo flat
2. permisos
=> INTERNACION - listado internacion y permisos

src/app/components/top/solicitudes/nuevaSolicitud.component.ts, src/app/components/top/solicitudes/nuevaSolicitud.html
* Agrega un wizard para en el campo "fecha de la solicitud" que se muestra al momento de crear una nueva solicitud.
1. Se agrega el wizard
2. Se modifica label
=> Agrega wizard en la fecha de la solicitud

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoM2A.html
* Corregir punto inicio turnos y visualización de consulta de niño sano
=> Corrige punto inicio turnos y visualización de consulta de niño sano

src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts, src/app/modules/rup/components/elementos/adjuntarDocumento.html
* Se solicitó que permitiera guardar la prestación sin adjuntar documentos para aquellas prestaciones donde este elemento RUP viene cargado por defecto (actividades con la comunidad)
1. Se quitó la validación de que tuviera un documento adjunto para poder guardar la prestación
2. 
3.
=> RUP - Elemento Adjuntar Documento

src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts, src/app/modules/estadisticas/components/rup/rup-pacientes.html, src/app/modules/estadisticas/components/rup/rup-pacientes.scss, src/app/modules/estadisticas/estadistica.module.ts, src/app/modules/estadisticas/pipes/sum.pipe.ts, src/app/modules/estadisticas/services/rup-estadisticas.service.ts, src/app/modules/estadisticas/services/snomed.service.ts
* Navegación de registros RUP según la jerarquía de Snomed
=> Dashboard: Navegación Snomed

src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts, src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/detalle-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/detalle-agenda.html
Agregar en el mapa de espacios fisicos las agendas planificadas y pausadas.
1. Se agrega la visualización de las agendas pausadas y en planificación al mapa de espacios fisicos
2. Se agrega la visualización del estado de la agenda en el detalle de agenda
3.
=> CITAS: Agendas planificadas y pausadas en mapa de espacios físicos

src/app/components/paciente/headerPaciente.html
* Issue https://github.com/andes/app/issues/1123
1. Se elimina del header del paciente el detalle de las notas.
=> MPI: Notas

src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/components/inicio/inicio.html, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html, src/app/core/mpi/components/paciente-cru.component.ts, src/app/services/previous-url.service.ts
* Updates requeridos luego de testear nueva funcionalidad MPI2
1. Selecciona el paciente en pto de inicio turnos luego de la secuencia: escanear un paciente no existente > navegar a mpi > darlo de alta > navegar hacia atrás.
2. Se implementa un servicio temporal  (hasta actualizar a Angular 7.2) para guardar la url desde donde se inicia la navegación.
3. Agrega chequeos de existencia para variables en componente estadísticas.
=> Updates v450

src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/core/mpi/services/paciente.service.ts
* Solucionar el hecho de que algunos pacientes inactivos no puedan volver a activarse desde auditoria mpi.
1. Se agregó un nuevo método en el servicio de pacientes.
=> MPI - Refactor activar/desactivar pacientes por auditoria

src/app/components/turnos/gestor-agendas/turnos.html, src/app/interfaces/turnos/ITurno.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
Se agrega campo horaAsistencia en el turno y se carga cuando se registra que el paciente asistió y lo borra cuando se borra la asistencia, tanto por citas como por rup.
1. Se muestra en punto de inicio de CITAS, en el badge de asistió, la hora de asistencia (en tooltip)
2. Se muestra en punto de inicio de RUP un nuevo badge con la hora de asistencia del paciente.
3. 
- [x ] No
https://github.com/andes/api/pull/644
=> CITAS - Agrega hora asistencia y lo muestra en inicio rup y citas

src/app/components/turnos/gestor-agendas/turnos.html, src/app/interfaces/turnos/ITurno.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
Quitamos los commit de hora de agenda que no entran en este release.
=> Revert "Merge pull request #1166 from andes/horaAsistencia"

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Realiza la verificación en el efector donde estoy creando la agenda, y en caso que no tenga el campo mobile, no aparece el check para la habilitación de cupos.
=> CITAS: Verifica que el efector tenga habilitación para cupo mobile

src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
* Corregir error que ocurría al editar el espacio físico de una agenda ya publicada
* Permitir clonar una agenda cuyo espacio físico se superpone con el de otra agenda en estado suspendida.
=> CITAS: Corrección de Issues relacionados con los espacios físicos

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
Arreglar condición cuando la asistencia del turno seleccionado es null.
=> CITAS - Arreglo selección asistencia

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* Resolución de issue #709 
- Mantiene actualizada la cache de búsquedas del usuario según la organización donde se encuentra.
=> Citas: Resolución de Issue709

src/app/modules/estadisticas/components/citas/citas.component.ts, src/app/modules/estadisticas/components/citas/citas.html, src/app/modules/estadisticas/components/citas/filtros.component.ts, src/app/modules/estadisticas/components/citas/graficos.component.ts, src/app/modules/estadisticas/components/citas/graficos.html, src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts, src/app/modules/estadisticas/components/tabla-2d/tabla-2d.html, src/app/modules/estadisticas/services/agenda.service.ts
Mejorar visualización de gráficos
1. Se cambian los colores y achican gráficos
2. Se hacen pequeños cambios en la estructura html
3. Se fijan los filtros y se colapsa
4. Se separa el llamado a la consulta de turnos por localidad
=> DASHBOARD - Mejoras dashboard citas

src/app/app.component.ts, src/app/apps/campaniaSalud/components/campania-create-update.component.ts, src/app/apps/campaniaSalud/components/campania-create-update.html, src/app/apps/campaniaSalud/components/campaniaSalud.component.ts, src/app/apps/campaniaSalud/components/campaniaSalud.html, src/app/apps/campaniaSalud/components/campaniaVisualizacion.component.ts, src/app/apps/campaniaSalud/components/campaniaVisualizacion.html
1. Se mejoró la interfaz de usuario y la experiencia
2. Se implementó los permisos para crear/editar y visualizar las campañas de salud
=> Campaña salud

package.json
=> v448: Tag version

src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
Quita el acceso a la obra social para los sobre turnos usando el servicio cache
1. 
2. 
3.
=> CITAS: Quita el acceso a la obra social para los sobre turnos

src/app/components/profesional/profesional-create-update.component.ts
* Verifica el sexo del profesional, para el caso que el profesional no pueda validarse con la fuente auténtica Renaper
1. Agrega conversión para enumerado del sexo del profesional
=> TM Profesional: agrega control para nuevo profesional

package-lock.json, package.json, src/app/apps/rup/internacion/components/mapa-de-camas.component.html, src/app/components/organizacion/organizacion.html, src/app/components/paciente/dashboard.html, src/app/components/paciente/paciente-create-update.html, src/app/components/paciente/paciente-search.html, src/app/components/top/reglas/reglas.component.html, src/app/components/top/solicitudes/nuevaSolicitud.html, src/app/components/top/solicitudes/solicitudes.html, src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html, src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html, src/app/components/usuario/busquedaUsuario.html, src/app/components/usuario/usuarioCreate.html, src/app/components/usuario/usuarioUpdate.html, src/app/modules/rup/components/ejecucion/prestacionCrear.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/puntoInicio.html
* Ajustar layout a las nuevas versiones.
Nota: Puede quedar alguna pantalla que no adaptamos. Hay que actualizar todo al layout de plex.
=> layout: Ajuste de layout y footer.

src/app/modules/rup/components/formulas/riesgoCardiovascular.service.ts
Reparar el calculo del riesgo cardiovascular. Daba mal los resultados de la formula.
1. Se reparo la función del riesgo cardiovascular.
2. 
3.
=> RUP- Riesgo cardiovascular

src/app/components/organizacion/organizacion-create-update.html
Agregar a backlog para usar plex-layout.
=> Organización: Arregla el problema de botones flotantes

src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/core/mpi/components/paciente-cru.component.ts
* Resolver conflicto en búsqueda paciente en sobreturno
1. Navegabilidad mpi-sobreturnos
=> Corrección de bug en búsqueda de pacientes dentro del componente Sobreturnos

src/app/core/mpi/components/bebe-cru.component.ts, src/app/core/mpi/components/extranjero-nn-cru.component.ts, src/app/core/mpi/components/google-map.html, src/app/core/mpi/components/paciente-cru.component.ts
* Se requiere revisar la carga de la geoReferencia de los efectores cuando éstos ya tienen una geoReferencia cargada en BD. 
1. Si un efector ya tiene una geoReferencia cargada en BD que no invoque al servicio de google para obtener las coordenadas.
=> MPI - geoReferencia de efectores

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
1. Se agrega un filtro para ver las prestaciones sin comprobante en pacientes Sumar
=> Se agrega filtro Sin Comprobante de Sumar

.github/pull_request_template.md
Se actualizó la plantilla de los PR de la app para agregar si es necesario actualizar el repositorio de Cypress de la misma forma que está hecho con la API
1. 
2. 
3.
=> Github - Actualiza plantilla

src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.html, src/app/components/turnos/punto-inicio/turnos-paciente.scss
1. Mejora interacción del hover en pestaña turnos (pto inicio turnos)
2. Agrega validación al presionar el btn recupero cuando se selecciona "prepaga"
=> Mejoras tag 4.4.10

src/app/components/turnos/punto-inicio/turnos-paciente.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.html, src/app/components/turnos/punto-inicio/turnos-paciente.scss
1. Cambia styles cuando se hace hover sobre turnos de un paciente en pto de inicio
2. Cambia condiciones para imprimir constancia recupero
=> Mejoras facturacion

src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
issue #1237 
1. Se desuscriben queries anteriores en filtro por fecha de manera de quedarse sólo con la última.
- [] Si
- [] No
- [] Si
- [] Si
- [] No
=> CITAS - Corrige issue #1237

package.json
Actualiza script del build de producción para circle/ci
1. Cambia el modo de compilación de producción en package.json
=> chore(circleci): Actualiza script de build para producción

src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico-vista.component.ts, src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico-vista.html
Issue #1075 
1. Se cambió parámetro para filtrar espacios físicos por edificio.
- [] Si
- [] No
- [] Si
- [] No
- [] No
=> CITAS - Corrige issue #1075

src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Bug: Al momento de clonar una agenda que no posee profesional aparece un error por consola.
1. Se agrega chequeo de profesional.
- [] Si
- [] No
- [] Si
- [] Si
- [] Si
=> CITAS -Clonacion de agendas (Issue#1237 bis)

src/app/components/paciente/paciente-search.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
Agregar validación de acceso a gestor de usuario en HUDS.
andes/app#1152
1. Validación de acceso a gestor de usuario en HUDS.
=> HUDS: Validación permiso búsqueda de paciente

src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico-vista.component.ts
Corregir nuevo bug generado a partir del fix de issue #1075 
- [] Si
- [] No
- [] Si
- [] No
LINK: https://github.com/andes/api/pull/698
- [] Si
=> CITAS - Corrige nuevo bug en espacios físicos (issue#1075)

src/app/app.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
Se había roto los permisos en un fix. Están funcionando como estaban antes
1. 
2. 
3. 
- [] Si
- [] No
- [] No corresponde
- [] Si
- [] No
- [] Si
- [] No
- [] Si
- [] No
=> Corrige permisos modificados en rup/huds

src/app/core/mpi/components/bebe-cru.html, src/app/core/mpi/components/extranjero-nn-cru.component.ts, src/app/core/mpi/components/extranjero-nn-cru.html, src/app/core/mpi/components/paciente-cru.html, src/app/core/mpi/components/relaciones-pacientes.component.ts, src/app/modules/mpi/components/paciente-panel.html
Issues de MPI
1. fix #1229
- [] Si
- [] No
- [] No corresponde
- [] Si
- [] No
- [] No
- [] Si
- [] No
=> Mejoras y correcciones para v4.5.0 en test

src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/dashboard/update-contacto-direccion.component.ts, src/app/components/turnos/dashboard/update-contacto-direccion.html, src/app/core/mpi/components/bebe-cru.component.ts, src/app/core/mpi/components/bebe-cru.html, src/app/core/mpi/components/paciente-cru.component.ts, src/app/core/mpi/components/paciente-cru.html
En el último merge con master se perdió este fix, va nuevamente
1. En estadísticas de paciente se valida la existencia del paciente antes de acceder a sus atributos
- [] No
- [] No corresponde
- [] Si
https://github.com/andes/api/pull/705
- [] Si
=> Actualización MPI 2

src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico.html, src/app/modules/rup/components/elementos/valorNumerico.html, src/app/modules/rup/components/formulas/riesgoCardiovascular.service.ts
https://github.com/andes/app/issues/1222
1. Se agrego el porcentaje de Riesgo de enfermedad cardiovascular
2. Se agrego fecha de actualizacion del Riesgo de enfermedad cardiovascular
- [] Si
- [] No
- [] No
- [] Si
- [] Si
=> RUP - Calculo de la Evaluación de RCV - issue #1222

src/app/modules/rup/components/huds/vistaContextoPrestacion.html, src/app/modules/rup/components/huds/vistaContextoPrestacion.ts, src/app/modules/rup/components/huds/vistaRegistro.html, src/app/modules/rup/components/huds/vistaRegistro.ts
issue #1240 
1. Se actualizan inputs del contexto de la prestación en cada navegación por las evoluciones.
=> HUDS - corrige issue #1240 (Evolución de un concepto Snomed)

src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
- Punto de inicio no refresca la dirección en la sección de actualizar dirección cuando se cambia de paciente
1. Se actualiza el input con un get/set para refrescar el componente según los cambios en el input
=> fix - al cambiar de paciente no refresca direccion pto inicio turnos

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
1. Se aplicó filtro de 'activo' en la query del buscador de e.f.
=> AGENDAS: Filtrar espacios físicos inactivos

src/app/modules/rup/components/ejecucion/buscador.html
https://github.com/andes/app/issues/1277
1. Se corrigió el estilo de los resultados filtrados como 'solicitud'  ya que se visualizaban con formato de procedimiento
=> RUP - Corrección issue #1277 (Estilo de solicitudes)

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
fix #1292
1. Previo al guardado de la agenda se verifica si la agenda es nominalizada y caso contrario, se vuelven a cero todos los contadores de turnos.
=> AGENDAS: Borrar datos de turno para agendas no nominalizadas

src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
#1300
1. En evolucionProblemaDefault.html se agregó entre las lineas 22 y 27 un control ver si la fecha existe o no, caso negativo muestra leyenda 'Sin registro'
=> RUP: Fecha inicio de hallazgo no registrada

src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico-nino.component.ts
#1303
1. Se arregló la tabla de registro visitas para que muestre la selección correcta de valores de lactancia y desarrollo psicomotor.
=> HUDS: Niño sano, datos seleccionados de lactancia

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Resetea los turnos de los bloques de las agendas no nominalizadas, corrigiendo el error que se producía al pasar una agenda nominalizada a no nominalizada.
1. Se reemplazo el push de turno de no nominalizada en el save, por reasignación completa del array de turnos por un nuevo array con una posición conteniendo un turno con idéntico estado al turno anteriormente mencionado.
=> Reset turnos no nominalizada

src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts, src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/dashboard/update-contacto-direccion.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html, src/app/core/mpi/components/bebe-cru.component.ts, src/app/core/mpi/components/busqueda-mpi.component.ts, src/app/core/mpi/components/extranjero-nn-cru.component.ts, src/app/core/mpi/components/paciente-cru.component.ts, src/app/modules/mpi/components/paciente-listado.html, src/app/modules/mpi/components/paciente-panel.html, src/app/modules/rup/components/internacion/puntoInicio-internacion.html
Bugs reportados:
- MPI- Punto de inicio (Paciente con y sin DNI)
cuando ingreso un paciente nuevo, luego de completar la planilla de MPI el sistema devuelve a apps/mpi/búsqueda en lugar de devolver a citas/punto-inicio
- Punto de inicio tipo de contacto no muestra el tipo de contacto e-mail
- Modificar el estilo del botón agregar contacto, dejar solo icono igual que MPI
-  Al validar un paciente con RENAPER, trae mal la fecha de nacimiento (un día antes del que está en el plástico del DNI)
1. Se fixean los bugs encontrados
=> Mejoras v4.5.0

src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico-nino.component.ts
Se limpió un poco el código según los comentarios de Hugo
1. 
2. 
3.
=> Aplica cambios de comentarios en la versión

src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
Al editar una agenda se podía seleccionar un espacio físico inactivo. Sse utiliza el filtro de la API que se creó para la misma función dentro de la creación de la agenda
1. 
2. 
3.
=> CITAS - Espacios físicos al editar la agenda

src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico-nino.component.ts
Después del commit 46b2c60 empezó a romper la consola al ver la huds de los niños donde se le registró una consulta de niño sano (2 semanas, 2 meses, 3 meses, 4, etc). Lo que hice fue agregar una validación que se había sacado en dicho commit. Ahora se está mostrando bien en el registro de visita la opción seleccionada en lactancia al cargar el concepto snomed.
1. 
2. 
3.
=> RUP - Componente niño sano, registro de visita

src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
Fix #1236 
1. Olvidar la búsqueda al reingresar a la página de registro de consulta.
=> RUP: Limpiar buscador snomed

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
issue #1213 
1. Al intentar crear una agenda dinámica para más de una prestación el sistema arrojaba un error por no tener prestaciones activas. Se corrige este caso activando por defecto todas las prestaciones seleccionadas para las agendas dinámicas.
=> CITAS - Activación de prestaciones en agendas dinámicas

src/app/components/top/solicitudes/solicitudes.component.ts
Ordenar resultados de búsqueda de solicitudes por fecha.
1. Inclusión de filtro de orden de fecha de solicitud en query del request al endpoit de get de solicitudes
=> TOP: Ordena solicitudes por fecha

src/app/components/turnos/dar-turnos/dar-turnos.html
Corregir error en cambio de horario de un turno: El botón "Cambiar horario" del sidebar parecía no realizar ninguna acción pero por consola arrojaba error por agenda indefinida.
1. Se corrige llamado al método de selección de agenda.
=> CITAS - Cambio de horario de turno

src/app/components/turnos/dashboard/estadisticas-pacientes.html, src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
Luego de dar un turno, en el punto de inicio los pacientes validados figuran como temporales
No hay issue abierto
1. Refactor en el código ejecutado luego de dar turnos para resolver el error
2. Refactor en html componente estadisticas-paciente para evitar que el layout se modifique cuando los ngIf ocultan col's
=> Punto de inicio turnos: Error en datos del paciente luego de dar turno.

src/app/components/turnos/gestor-agendas/gestor-agendas.html
#1087
1. Quita la deshabilitación de selección de fechas según máximo y mínimo para fechas desde/hasta.
=> AGENDAS: Remoción de fechas límites

src/app/core/mpi/components/bebe-cru.html, src/app/core/mpi/components/paciente-cru.html
Resulta confuso que la localidad figure como requerida y la provincia no
1. Queda como requerido el campo provincia en formulario de paciente y de bebé
=> Agrega el campo provincia como requerido en paciente

src/app/components/turnos/dar-turnos/dar-turnos.html
Se corrige linea de codigo repetida por error resolviendo conflictos
1. Se corrige linea de codigo repetida por error resolviendo conflictos
=> CITAS - Correccion doble flecha

src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts
Cerrar el panel de la carga de solicitudes al finalizar la carga para evitar errores cuando se cambia el paciente
=> fix(CITAS): Cambia el output al cargar solicitudes desde PI citas

src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/components/turnos/punto-inicio/puntoInicio-turnos.html, src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts, src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html, src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts, src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.html
Arreglar funcionalidad solicitudes desde punto de inicio turnos
1. Se vuelve a mostrar el listado de solicitudes con posibilidad de dar turno para la solicitud.
=> Recupera funcionalidad dar solicitudes desde punto de inicio de turnos

src/app/components/turnos/dar-turnos/dar-turnos.html
Mejora visualizacion entre agendas
1. Cambio de label
=> CITAS - Correccion etiqueta en turnos

src/app/components/turnos/dar-turnos/calendario-dia.class.ts, src/app/components/turnos/dar-turnos/calendario.html
Se arregla vista de las agendas dinámicas en el calendario de turnos
=> CITAS: Agendas Dinámicas

src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts, src/app/services/profesional.service.ts
Agregar firma del profesional en impresión de arancelamiento.
=> feat(arancelamiento): agrega firma profesional en impresion

src/app/core/mpi/components/paciente-cru.component.ts
Permitir el ingreso de documentos con otro formato
1. Se contemplan documentos con 6 dígitos o comienzo en cero para los casos de escaneo de pacientes con libretas cívicas o de enrolamiento.
=> MPI - Formato de documento

src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
Agrega plex alert cuando falla la liberación de un turno
1. Error handler asociado a la liberación de turno
[PR EN API]( https://github.com/andes/api/pull/753)
=> Agrega error handler en liberación de turno

src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Anteriormente al intentar clonar una agenda no se visualizaba el primer dia de los meses que comiencen en domingo. Por ejemplo septiembre y diciembre.
fix #1194
Issue #1194 
1. Se corrigió la carga de los dias en el calendario de clonación de agendas.
=> CITAS - Calendario en clonación de agendas (Issue #1194)

src/app/components/top/reglas/reglas.component.html, src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts, src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts, src/app/components/turnos/gestor-agendas/turnos.component.ts
Evitar llamados al servicio de SMS con pacientes sin teléfono
1. Agrega un if para chequear la existencia del teléfono antes de llamar al servicio de SMS
=> Verifica la existencia de telefono antes de llamar al servicio de SMS

src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts, src/app/modules/mpi/components/paciente-buscar.component.ts
- Buscador de pacientes falla cuando el dni scaneado da match alto con temporal
1. Mejora en emitters para los casos en que el dni scaneado da match alto para un paciente temporal o validado
=> MPI - buscador de pacientes falla cuando el scan da match alto con temporal

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.scss, src/app/modules/rup/components/elementos/elementoDeRegistro.html, src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts, src/app/modules/rup/components/internacion/puntoInicio-internacion.html
1. Cuando se trate de una epicrisis o colonoscopia aparecerán arriba de las mismas los c2 correspondientes para definir primera vez
2. 
3.
=> RUP - indicar la primera vez en los C2 en epicrisis y colonoscopia

src/app/modules/rup/components/formulas/riesgoCardiovascular.service.ts
Corregir cálculo de porcentaje de riesgo en algunos pacientes en los que no se resuelve.
1. Se especifica chequeo de contenido de variable contra 'null' para que en caso de contener cero no devuelva false
=> RUP - Riesgo de enfermedad cardiovascular

src/app/apps/rup/internacion/components/iniciarInternacion.component.ts, src/app/components/paciente/paciente-detalle.ts, src/app/components/turnos/autocitar/autocitar.component.ts, src/app/components/turnos/autocitar/dinamica.component.ts, src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts, src/app/components/turnos/punto-inicio/turnos-paciente.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/services/obraSocial.service.ts
Verificar los parámetros necesarios antes de realizar la llamada al servicio getObrasSociales
1. Agrega chequeos
2. Modifica servicio para enviar los datos necesarios como params
3. Elimina funciones no utilizadas en servicio de obras sociales
=> OBRAS SOCIALES - chequea parámetros al llamar a service getObrasSociales

src/app/services/obraSocial.service.ts
1. Update de la url que apunta el endpoint de consultas a puco
Requiere update en [API](https://github.com/andes/api/pull/769)
=> OBRAS SOCIALES actualiza ruta en service obras sociales

src/app/components/turnos/gestor-agendas/operaciones-agenda/buscador-cie10.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
https://pm.andes.gob.ar/projects/lab/work_packages/819/activity
1. Muestra el 'nombre' de diagnostico CIE10, en vez del 'sinonimo'.
=> CITAS: muestra nombre CIE10

Dockerfile
Actualizar el archivo DockerFile para permitir compilar la app 
1. Copia el archivo apiKeyMaps.ts
PR https://github.com/andes/andes-test-integracion/pull/24
=> chore(docker): actualiza DockerFile

src/app/app.module.ts, src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/elementos/lugarDeNacimiento.component.ts, src/app/modules/rup/components/elementos/lugarDeNacimiento.html
[USER STORY](https://pm.andes.gob.ar/projects/rup/work_packages/821/activity
)
1. nuevo elemento RUP: Lugar de nacimiento
2. 
3. 
```
{
"componente" : "LugarDeNacimientoComponent",
"style" : {
"columns" : 6.0,
},
{
"fsn" : "lugar de nacimiento (entidad observable)",
"semanticTag" : "entidad observable",
"conceptId" : "169812000",
"term" : "lugar de nacimiento",
"refsetIds" : [ 
"900000000000497000"
]
}
],
"frecuentes" : []
}
```
=> RUP: elementoRUP lugar de nacimiento

src/app/modules/rup/components/elementos/procedimientoDeEnfermeria.html
issue #1362 
1. Se setea cada campo del formulario 'procedimientoDeEnfermeria' con atributo readonly según el valor de 'soloValores'.
=> RUP - Corrige procedimiento de enfermería editable en prestación

src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Agrega filtro de DNI de paciente al buscador de turnos y prestaciones
https://pm.andes.gob.ar/projects/lab/work_packages/814/activity
1. Se incluye un filtro de DNI de paciente, y se agrega dicho parámetro al request de GET de prestaciones.
=> BUSCADOR: agrega filtro dni al buscador

src/app/components/turnos/punto-inicio/arancelamiento/arancelamiento-form.component.ts
1. Se modifica la llamada a configFacturacionAutomatica pasando por parámetro la prestación turneable para poder ver el código de nomenclador en la planilla de arancelamiento
=> Se modifica llamada a configFacturacionAutomatica

src/app/components/prestamosHC/historial/historial-hc.component.html, src/app/components/prestamosHC/prestamos-hc.component.html, src/app/components/prestamosHC/prestamos-hc.component.ts, src/app/components/prestamosHC/prestamos/devolver-hc.component.ts, src/app/components/prestamosHC/prestamos/listar-prestamos.component.html, src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts, src/app/components/prestamosHC/solicitudes/prestar-hc.component.ts, src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.html, src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.ts
1. Arregla buscador MPI en módulo de prestamos de carpetas.
2. Mejora el armado de las tabs plex.
=> Prestamos - Arregla buscador MPI

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://pm.andes.gob.ar/projects/mobile-app/work_packages/826/activity
1. Oculta botón 'BORRAR' bloques de agenda, cuando la agenda posee únicamente un solo bloque.
=> CITAS - Oculta botón "BORRAR" bloques de agenda.

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/modules/rup/components/elementos/graficoLineal.component.ts, src/app/modules/rup/services/prestaciones.service.ts
issue #1346
issue #1349 
issue https://github.com/andes/api/issues/611
1. En HUDS de un paciente, muestra la fecha de ejecución de la prestación en lugar de la de carga.
2. En el gráfico lineal de peso corporal, corrige rango de fechas registradas.
3. Iniciando la carga de una prestación al menos un día después de realizada, corrige fecha de ejecución guardando la del turno en lugar de la de carga.
https://github.com/andes/api/pull/736
=> RUP - Corrige varios issues

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
#1320 #1322
1. Bloque que verifica si la API devolvió algún mensaje. Si es el caso, muestra el mensaje y permanece en la pantalla.
=> CITAS: solapamiento  de agendas

src/app/components/top/reglas/reglas.component.ts
Evitar la creación de reglas duplicadas. #1340
1. Se verifica que la regla que se quiere incluir no exista antes de ser agregada.
=> TOP: corrección de creación de reglas duplicadas

package.json, src/app/app.module.ts, src/app/app.routing.ts, src/app/apps/rup/plantillas-rup/plantillas-rup.component.html, src/app/apps/rup/plantillas-rup/plantillas-rup.component.scss, src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts, src/app/modules/rup/components/core/_rup.scss, src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/services/conceptObserver.service.ts, src/app/modules/rup/services/plantillas.service.ts
https://pm.andes.gob.ar/projects/rup/work_packages/847/activity
1. Agrega un servicio de Plantillas.
2. Agrega un Dropdown en el header del concepto para seleccionar la plantilla.
3. Se actualiza el dato del procedimiento mediante ConceptObserverService.
https://github.com/andes/api/pull/760
=> feat(rup): agrega plantillas para procedimientos con observaciones

src/app/components/inicio/inicio.html, src/app/modules/estadisticas/components/citas/citas.component.ts, src/app/modules/estadisticas/components/citas/citas.html, src/app/modules/estadisticas/components/citas/filtros.component.ts, src/app/modules/estadisticas/components/citas/graficos.component.ts, src/app/modules/estadisticas/components/citas/graficos.html, src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts, src/app/modules/estadisticas/components/tabla-2d/tabla-2d.html, src/app/modules/estadisticas/estadistica.module.ts, src/app/modules/estadisticas/services/agenda.service.ts, src/app/modules/estadisticas/utils/comboLabelFiltro.component.ts
* Mejoras de visualización, agregar turnos "appMobile" y descarga de csv
1. Se ocultan gráficos cuando hay un solo valor y tiene 0.
2. Se agrega detalle e icono del panel del inicio para ingresar a seccion de los dashboard
3. Se agrega tipo de turno "App Mobile" en filtros
https://github.com/andes/api/pull/685
=> CITAS - Dashboard mejoras

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Que al validar una prestación correspondiente a una agenda no nominalizada, dicha agenda pase a estado auditada.
1. Al momento de validar la prestación se chequea que si es no nominalizada entonces su agenda correspondiente se patchea con estado 'auditada'
PR: https://github.com/andes/api/pull/771
=> (RUP-CITAS) - auditoria de agendas no nominalizadas

src/app/components/top/solicitudes/nuevaSolicitud.component.ts
#1338
1. Se agregó el parámetro faltante de "organización destino" en el GET de reglas, en componente de nuevaSolicitud, para la generación de solicitud de salida.
=> TOP - Filtro de organización destino en generación de solicitud de salida

src/app/modules/rup/components/ejecucion/puntoInicio.html
Muestra hora de asistencia en el detalle de agenda del punto de inicio de consultorio
https://pm.andes.gob.ar/projects/mobile-app/work_packages/891/activity
1. Muestra la fecha de asistencia del turno en el detalle de agenda de punto de inicio de consultorio
=> RUP: Muestra hora de asistencia de turno

src/app/modules/rup/components/huds/vistaPrestacion.html
issue #1431 
1. Validada una consulta de odontologia donde vinculaban varias piezas/caras a un concepto, luego visualizando en la HUDS dicha consulta, solo se visualiza la primer pieza/cara vinculada por cada concepto.
=> RUP - Visualizacion de piezas relacionadas en HUDS de odontograma

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Manejar el mensaje de error desde la api.
1. Reemplaza el mensaje de error por el handleado en la api.
Si bien no es estrictamente necesario, este PR va de la mano de https://github.com/andes/api/pull/775
=> RUP - mensaje de error iniciando registro de prestación

src/app/components/turnos/gestor-agendas/turnos.component.ts
issue #1432 
1. Actualiza los bloques de la agenda seleccionada luego de dar la asistencia
=> CITAS - Actualizacion asistencia paciente en gestor de agendas

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html, src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
#1438
1.Reemplaza sinonimo CIE10 x nombre CIE10 en página de fuera de agenda y revisión de agendas
=> Agendas: Muestra nombre CIE10 en lugar de sinonimo CIE10

src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/elementos/calculoDeBoston.component.ts, src/app/modules/rup/components/elementos/calculoDeBoston.html, src/app/modules/rup/components/elementos/elementoDeRegistro.component.ts, src/app/modules/rup/components/elementos/elementoDeRegistro.html, src/app/modules/rup/components/elementos/seleccionBinaria.component.ts, src/app/modules/rup/components/elementos/seleccionBinaria.html
U.S.: https://pm.andes.gob.ar/projects/rup/work_packages/815/activity
1. Se modifican/agregan conceptos y campos en formulario de colonoscopía de control.
2. Se modifica el átomo de selección binaria para visualizar opciones adicionales.
En la colección de elementosRUP, el concepto de colonoscopia de control debería quedar de la siguiente manera:
```
{
"_id" : ObjectId("5bbe18a59a963a8793ae8725"),
"componente" : "MoleculaBaseComponent",
"tipo" : "molecula",
"style" : {
"columnas" : 6,
},
{
"conceptId" : "310634005",
"term" : "colonoscopia de control",
"fsn" : "colonoscopia de control (procedimiento)",
"semanticTag" : "procedimiento"
}
],
"requeridos" : [ 
{
"elementoRUP" : ObjectId("5bbf5df161c1660cee7a754c"), …
```
=> RUP - Mejoras en registro de colonoscopía

src/app/app.module.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.html, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/vistaHuds.html, src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts, src/app/modules/rup/components/elementos/adjuntarDocumento.html, src/app/modules/rup/components/huds/vistaSolicitudTop.html, src/app/modules/rup/components/huds/vistaSolicitudTop.ts, src/app/modules/rup/services/huds.service.ts, src/app/modules/rup/services/prestaciones.service.ts
https://pm.andes.gob.ar/projects/huds/work_packages/818/activity
Pull request generado a partir de antiguo pull request de HUDS https://github.com/andes/app/pull/1391
1. Separa la visualización de solicitudes
2. Muestra el origen en cada una (RUP, TOP)
3. Muestra el detalle de la solicitud al seleccionarla.
=> HUDS: Agrega solicitudes de TOP a HUDS

src/app/apps/rup/internacion/components/egresoInternacion.component.ts, src/app/apps/rup/internacion/components/egresoInternacion.html, src/app/apps/rup/internacion/components/iniciarInternacion.component.ts, src/app/apps/rup/internacion/components/iniciarInternacion.html, src/app/apps/rup/internacion/components/resumenInternacion.html
issues #1414, #1416, #1417, #1418)
1. Minimiza datos del profesional, paciente y organizacion de origen/destino en caso de traslado
2. Corrige calculo de dias de estada
3. Agrega codigos Y35 a Y98 en la causa externa del diagnostico de egreso
4. Cuando se va a internar un paciente que ya tiene un egreso pero dicha internacion aun esta 'en ejecucion', la nueva internacion autocompleta solo los datos del paciente en lugar de los de la ultima internacion.
https://github.com/andes/api/pull/798
=> Internacion - corrección de varios issues

src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts, src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html, src/app/modules/rup/services/prestaciones.service.ts
[pm.andes.gob.ar/projects/huds/work_packages/1031/activity](url)
1. 
2. 
3. 
Se modificó el elemento rup de las solicitudes, filtrando las organizaciones destino coincidiendo con las reglas (si no hay regla que permita crear la solicitud, se oculta la organización destino).
Si la solicitud tiene organización destino, se crea la solicitud en TOP
=> RUP - Registro de Solicitud para TOP

package-lock.json, package.json, src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts, src/app/modules/rup/services/prestaciones.service.ts
Solucionar este problema visual:
1.  Actualizar a la ultima versión de plex. Hubo un tema de con Angular 8 y aplicaba mágicamente algunas directivas CSS.
=> chore(package): bump @andes/plex 5.0.3 to 5.1.3

src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
1. La corrección es que al seleccionar una prepaga, después no sepodía seleccionar otro tipo de obra social.
=> Se corrige bug en selección de prepaga

src/app/components/puco/puco.component.ts, src/app/components/puco/puco.html, src/app/services/obraSocial.service.ts
https://pm.andes.gob.ar/projects/bi/work_packages/929/activity
1. Se permite buscar paciente en Sumar 
2. Se genera constancia Sumar
https://github.com/andes/api/pull/783
=> feat(SUMAR): genera constancia sumar

src/app/app.module.ts, src/app/modules/rup/components/elementos/valorFecha.component.ts, src/app/modules/rup/components/elementos/valorFecha.html
Creación de átomo para registrar fechas.
1. Atomo para registro de fecha.
Elemento RUP
{ 
"_id" : ObjectId("5caf3fd4acdc9016ec1d1dc5"), 
"activo" : true, 
"componente" : "ValorFechaComponent", 
"tipo" : "atomo", 
"esSolicitud" : false, 
"style" : {
"columnas" : NumberInt(6), 
}, 
"conceptos" : [
{
"fsn" : "último período menstrual (entidad observable)", 
"semanticTag" : "entidad observable", 
"refsetIds" : [
"900000000000497000"
], 
"conceptId" : "21840007", 
"term" : "último período menstrual"
}
], 
"requeridos" : [
], 
"frecuentes" : [
], 
"params" : {
"title" : "Fecha", 
"type" : "date"
}
}
=> RUP - Crea átomo para registrar una fecha

src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/services/documentos.service.ts
Dada una prestación validada, poder generar documentos PDF de los Procedimientos individuales.
1. A cada Procedimiento se le agrega un botón para descargarlo como PDF
=> RUP ~ Procedimientos PDF

src/app/modules/rup/components/huds/vistaPrestacion.html
Arregla minutos en la fecha de la prestacion, en el detalle de prestacion de la HUDS
#1409
1. Corrección del formato de la fecha en vistas de prestaciones.
=> HUDS: Corrección en hora de prestación

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html
#1380
1. Oculta el botón "Ver Resumen" de una prestación para profesionales que no sean el profesional que validó dicha prestación. Este botón solo es visible para el profesional que validó y ejecutó la prestación.
=> fix(RUP): Oculta botón Ver Resumen

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Se agrega control en la validación de prestaciones no nominalizadas que se registran como fuera de agenda. 
1. Se agrego un control para saber si en la prestación no nominalizada viene de una agenda o no, en el caso de venir de la agenda es que hay que actualizar la agenda para pasarla a auditada 
2. 
3. 
- [] No
=> RUP: Agrega control en la validación de prestaciones no nominalizadas

src/app/components/top/solicitudes/nuevaSolicitud.html
close #1450
1. Muestra alertas faltantes de campo requerido para inputs de prestaciones
=> TOP: Muestra alerta de campo requerido para inputs de prestaciones

src/app/modules/rup/components/ejecucion/puntoInicio.html
Corrige error en el punto de inicio de rup al iniciar prestación  pendiente (que viene desde una solicitud)
1. 
2. 
3.
=> fix(RUP): Corrige parametro al iniciar prestación pendiente

src/app/components/top/solicitudes/auditarSolicitud.html, src/app/components/top/solicitudes/detalleSolicitud.html
https://proyectos.andes.gob.ar/projects/TOP/issues/TOP-9?filter=allopenissues
1. Muestra datos de createdBy y createdAt de prestación en detalle y auditoria de solicitud.
=> TOP: Muestra usuario y fecha de creación en detalle de solicitud

src/app/apps/rup/internacion/components/iniciarInternacion.html, src/app/apps/rup/internacion/components/listado-internacion.component.ts, src/app/apps/rup/internacion/components/listado-internacion.html, src/app/apps/rup/internacion/components/mapa-de-camas.component.ts, src/app/services/documentos.service.ts
Dado un efector, poder descargar un listado de sus internaciones según filtros de búsqueda.
1. Se agregó un boton en '/internacion/listado' para poder descargar los resultados de la búsqueda en formato .csv
Modificación detallada en PR de API
https://github.com/andes/api/pull/800
=> Internacion - Descarga listado internaciones

src/app/app.module.ts, src/app/app.routing.ts, src/app/components/organizacion/organizacion-prestaciones.component.ts, src/app/components/organizacion/organizacion-prestaciones.html, src/app/components/organizacion/organizacion.component.ts, src/app/components/organizacion/organizacion.html, src/app/interfaces/IOrganizacion.ts, src/app/services/organizacion.service.ts
User Story: https://pm.andes.gob.ar/projects/tablas-maestras/work_packages/1066/activity 
1. Se realizó una vista general de ofertas prestacionales por organización
2. Se realizó lo necesario para poder agregar nuevas ofertas prestacionales en cada organización
3. Se realizó lo necesario para poder editar las ofertas prestacionales de cada organización
4. Se realizó lo necesario para poder eliminar las ofertas prestacionales de cada organización
=> feat(oferta-prestacional): ABM de ofertas prestacionales

src/app/modules/rup/services/prestaciones.service.ts
- Se corrige un bug en la validación de una prestación cuando se generan solicitudes desde ella.  Agrega un control para cuando la regla que se aplica indica que es auditable, el estado de la prestación generada es "auditoria" y no "pendiente" como se estaban generando. En caso que la regla no indique auditoria el estado de la solicitud si es "pendiente"
1. Control en la validacion al momento de generar las nuevas solicitudes, si son auditables se corrige el estado por defecto a "auditoria".
2. 
3.
=> fix(RUP): Control para solicitudes con pedido de auditoria

src/app/modules/rup/interfaces/prestacion.registro.interface.ts
Se agrega un control, al momento de generar un registro para una prestación, en caso que no llegue un elementoRUP, como en el caso de la internación.
=> fix(Internacion): Control para elementoRup en null

src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Cambia bagdes de origen de solicitud
RUP x 'Registrado por profesional'
TOP x 'Registrado por gestión'
1. Cambia bagdes de origen de solicitud
RUP x 'Registrado por profesional'
TOP x 'Registrado por gestión'
=> HUDS: cambia bagdes de origen de solicitud

src/app/modules/rup/components/ejecucion/buscador.component.ts
https://proyectos.andes.gob.ar/browse/RUP-3
1. Si existen conceptos en "mis frecuentes" activar dicho botón por defecto. Sino chequea si existen conceptos en "sugeridos" y activar dicho botón. Sino, activa el botón "buscador básico" por defecto.
=> RUP: Muestra frecuentes por defecto

src/app/components/top/solicitudes/auditarSolicitud.component.ts, src/app/components/top/solicitudes/auditarSolicitud.html, src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
https://pm.andes.gob.ar/projects/mobile-app/work_packages/1058/activity
- Incorpora la posibilidad de asignarle prioridad 'prioritario' a una solicitud al momento de la auditoria
- incorpora filtro de búsqueda de solicitudes por prioridad
- incluye columna de prioridad en tabla de resultados de búsqueda de solicitudes.
- los resultados de la búsqueda se ordenan por prioridad y antigüedad
- Mejoras en manejo de arrays y arrow functions
=> TOP: Incluye prioridad de solicitud

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html, src/app/components/turnos/gestor-agendas/turnos.html
* https://proyectos.andes.gob.ar/browse/CIT-8
1.  Se modifica el label de 'Cupo para aplicación Mobile' a 'Ventanilla virtual'
=> CITAS: label ventanilla virtual

src/app/components/top/solicitudes/anularSolicitud.html, src/app/components/top/solicitudes/auditarSolicitud.html, src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html, src/app/modules/estadisticas/components/top/filtrosSolicitudes.component.ts, src/app/modules/estadisticas/components/top/top.component.ts, src/app/modules/rup/components/huds/vistaSolicitudTop.html
TOP: cambia literales 'rechazo' x 'respuesta'. Cambia nombre de estado "Rechazada" por "Contrarreferida"
1. TOP: cambia literales 'rechazo' x 'respuesta'
2. Cambia nombre de estado "Rechazada" por "Contrarreferida"
=> TOP: cambia literales 'rechazo' x 'respuesta'

src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-13
1. Muestra estado "Registo en HUDS" para las solicitudes con turno dado y  prestación validada.
2. Incluye filtro "Registo en HUDS", que busca la solicitudes con turno dado y  prestación validada.
=> TOP: Muestra estado "Registro en HUDS"

src/app/modules/rup/components/elementos/informe.component.ts, src/app/modules/rup/components/elementos/informe.html, src/app/modules/rup/components/elementos/observaciones.component.ts, src/app/modules/rup/components/elementos/observaciones.html
ISSUE #1435
No se mantiene el formato HTML de ObservacionesComponent.
1. Se agrega un pequeño timeout al cargar el componente si tiene valor. 
2. Cargue una tarea en Jira para actualizar la librería de edición HTML y ver si se soluciona.
=> fix(rup): matiene formato HTML es ObservacionesComponent

src/app/core/mpi/components/paciente-cru.component.ts, src/app/core/mpi/services/paciente.service.ts
Al momento de crear un paciente, si se ingresaba mismo documento y sexo que un paciente temporal, el sistema solicitaba que se seleccione ese en lugar de crear uno nuevo. Ahora esa validación omite a los pacientes temporales
1. 
2. 
3.
=> MPI - Excluir pacientes temporales en pacientes candidatos

src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Retoma PR  https://github.com/andes/app/pull/1410 donde se habían perdido algunos cambios y quita la funcionalidad de restringir la selección de al menos un filtro (consensuado de esta manera con Hugo y Silvina.
=> Restringe buscador ii

src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/shared/assets/wizard/styles.scss
[https://proyectos.andes.gob.ar/browse/CIT-18](url)
1. Se saca de la app el mensaje de ayuda al crear una agenda
=> CITAS: Sacar mensaje amistoso de ayuda 

src/app/app.module.ts, src/app/app.routing.ts, src/app/components/profesional/profesional-create-update.component.ts, src/app/components/profesional/profesional-create-update.html, src/app/components/profesional/profesional.component.ts, src/app/components/profesional/profesional.html, src/app/interfaces/ISiisa.ts, src/app/services/profesional.service.ts, src/app/services/siisa.service.ts
Se pidió que, desde la app, se pudiera agregar a los profesionales no matriculados desde matriculaciones, la profesión que tienen y la matrícula.
1. La posibilidad de editar un profesional no matriculado porque antes no estaba
2. Al formulario de profesional le agregué los dos campos nuevos: profesión y matrícula externos
3. Agregar al sidebar en el listado de profesionales la información nueva para aquellos profesionales que tengan cargado algo en estos campos
=> TM - Editar profesionales no matriculados

package-lock.json, src/app/components/turnos/gestor-agendas/turnos.html
* https://pm.andes.gob.ar/projects/ui-ux/work_packages/836
1.  Utilizar el componente plex-help para visualizar los detalles de la agenda
1.  Se requiere actualizar la versión de Plex a la 4.6.2
2.  Se suben en el commit los archivos package-lock.json y package.json
=> CITAS: Reformular panel detalles de agenda

src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=4575
En el icono que informa el origen de las solicitudes, el tittle se cambia de la derecha a la izquierda
=> fix(rup): se posiciona el title a la izquierda de las solicitudes

src/app/app.module.ts, src/app/app.routing.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-2
1. Componente "AgregarPaciente".
2. Botón y funcionalidad para asignar un paciente a una agenda dinámica durante su revisión.
=> CITAS: agrega paciente a agenda dinámica

src/app/components/prestamosHC/prestamos-hc.component.html, src/app/components/prestamosHC/prestamos-hc.component.ts, src/app/components/prestamosHC/prestamos/listar-prestamos.component.html, src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
Incorpora unsubscribe en request de GET de solicitudes de prestamos de carpetas. Incluye botón prestar todas y devolver todas en header.
1. Incorpora unsubscribe en request de GET de solicitudes de prestamos de carpetas
2.  Incluye botón prestar todas y devolver todas en header
=> Prestamos HC: incorpora unsubscribe en request

src/app/components/puco/puco.component.ts
Al seleccionar la última versión para el buscador de obras sociales de puco, debido a que por usar formato UTC, a la versión le resta 3 horas lo que, no solo pasa al día anterior, sino también al mes anterior, luego trabaja con esto y por lo tanto busca el DNI del paciente en la versión anterior a la última actualizada.
1. Corrección del formato para trabajar con la última versión actualizada.
2. 
3. 
- [ x] Si
- [ x] No
- [ x] No
- [ x] No
=> PUCO: correcion de periodo puco por formato UTC

src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
Al clonar una agenda, cuando se clona en una fecha donde ya existe una agenda con características similares el sistema no muestra conflicto y se puede clonar.
1.  Se modifica la posición del llamado a _cargarCalendario()_ dentro de la función _actualizar()_ para que realice la comprobación de conflictos antes de cargar el calendario para seleccionar el día a clonar
GLPI: [https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=4623](url)
=> CITAS: solución al clonar con conexion lenta

src/app/components/top/solicitudes/anularSolicitud.component.ts, src/app/components/top/solicitudes/auditarSolicitud.component.ts, src/app/components/top/solicitudes/auditarSolicitud.html, src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/modules/rup/components/huds/vistaSolicitudTop.html, src/app/modules/rup/components/huds/vistaSolicitudTop.ts
incluye observaciones en aceptacion de solicitud en la auditoria de solicitudes
https://proyectos.andes.gob.ar/browse/TOP-2
1. Se agrega campo observaciones cuando de acepta solicitud en auditoría
2. Se unificó 'motivo de rechazo' con 'observaciones', quedando este primero deprecado
3. Se muestra el 'motivo de rechazo' cuando no posee registro de observaciones. Esos código se deben remover cuando queden 'los motivos de rechazo' reemplazados por observaciones.
=> TOP: incluye observaciones en aceptación de solicitud

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts, src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
1. Se pasan bien los parametros
=> fix(rup): iniciar prestacion desde solicitud

src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts
Resolución de incidente en la generación de epicrisis
1. Se genera el token cuando se realiza la selección del paciente en el punto de inicio de internación
3.
=> fix(epicrisis): genera token para epicrisis

src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
Corrige bug para agregar la organización en la ejecución de las prestaciones fuera de agenda
=> fix(RUP): Agregar la organización en la ejecución de las prestaciones fuera de agenda

package-lock.json, package.json, src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
Hay un input `[selectable]="true"` en
https://github.com/andes/app/blob/master/src/app/apps/rup/plantillas-rup/plantillas-rup.component.html#L102
que no corresponde porque ya no existe en PLEX (plex-item)
1. Se quitó el input
=> fix(plex-item) input sin uso rompe la compilación

src/app/app.component.ts
Agrega acceso de visualizar HUDS
1. 
2. 
3.
=> HUDS: Agrega acceso a la visualización de la HUDS

src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
Agrega verificación en la generación del token en el Buscador de Prestaciones y Turnos
1. 
2. 
3.
=> fix(buscador): agrega verificación en la generación del token

src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/CIT-30
1. Se modifica el campo del financiador de un paciente que se muestra en el buscador de prestaciones y turnos. En vez de _busqueda.financiador.financiador_ se utiliza _busqueda.financiador.nombre para su correcta visualización.
2. Se corrigen errores de linteo.
=> CITAS: Financiador en revisión de agenda dinámica

src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/huds/vistaProcedimiento.html, src/app/modules/rup/services/prestaciones.service.ts
https://github.com/andes/app/issues/1519
1. Corrige el display de badge de privacidad
=> RUP: Corrige el display de badge de privacidad

src/app/apps/rup/internacion/components/iniciarInternacion.component.ts, src/app/apps/rup/internacion/components/listado-internacion.component.ts, src/app/apps/rup/internacion/components/mapa-de-camas.component.ts, src/app/apps/rup/internacion/components/resumenInternacion.component.ts
Reporte de efector añelo sobre error en la generación del documento.
1. Corrección en consulta por internaciones anteriores de un paciente (Registrando un nuevo ingreso).
2. Corrección de inconsistencia desocupando una cama (Registrando un egreso).
=> Internacion - Ingreso y egreso de paciente

src/app/core/mpi/components/relaciones-pacientes.component.ts, src/app/core/mpi/components/relaciones-pacientes.html
Corrige issue #1487. Al editarle al paciente A el tipo de relación con un paciente B, al paciente B no se le actualizaba su relación con A
1. 
2. 
3.
=> MPI -  fix modificar relaciones pacientes

src/app/components/top/solicitudes/anularSolicitud.html, src/app/components/top/solicitudes/auditarSolicitud.html, src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/nuevaSolicitud.html, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
Refactorizar pantalla de solicitudes con plex-layout.
1.  Se refactorizó la pantalla de solicitudes con plex-layout
2.  Se refactorizó la pantalla de nueva solicitud con plex-layout
3.  Se corrigió la fecha que mostraba al anular/auditar una solicitud
=> TOP: refactorizar pantalla de solicitudes con plex-layout

src/app/app.component.ts, src/app/app.module.ts, src/app/apps/auth/components/login/login.component.ts, src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts, src/app/apps/gestor-usuarios/services/usuarios.http.ts, src/app/shared/services/hotJar.service.ts, src/environments/apiKeyMaps.ts.example, src/environments/environment.demo.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
Agrega configuraciones generales para el usaurio. En este momento es para poder activar hotjar a ciertos usuarios.
1. Agrega servicio que inyecta el script de Hotjar. 
https://github.com/andes/api/pull/870
=> feat(hotjar): add hotjar service

src/app/app.component.ts
No todos los usarios tienen permiso a la ruta de usuarios. 
1. 
2. 
3.
=> feat(hotjar):: desactiva hotjar

src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
=> fix(hotjar): remueve hotjar

src/app/components/turnos/dashboard/update-contacto-direccion.component.ts, src/app/core/mpi/components/paciente-cru.component.ts, src/app/core/mpi/components/paciente-cru.html
https://proyectos.andes.gob.ar/projects/MPI/issues/MPI-11?filter=allopenissues
https://proyectos.andes.gob.ar/projects/MPI/issues/MPI-12?filter=allopenissues
https://proyectos.andes.gob.ar/projects/MPI/issues/MPI-13?filter=allopenissues
1. Se almacena como dirección legal la obtenida desde una validación por fuente auténtica.
https://github.com/andes/api/pull/846
=> MPI - Dirección legal en pacientes

src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html, src/app/components/top/solicitudes/solicitudes.scss
TOP: Mejora la búsqueda de solicitudes
1. Migra funcionalidad de filtrado de resultados de la app (filtrado de arrays x tipo de solicitud de entrada o salida y filtrado por paciente) a la api (parametros de busqueda al get de solicitudes).
2. Implementa scroll infinito en tabla de resultados
3. Fija cabecera de la tabla de resultados
=> TOP: Mejora la búsqueda de solicitudes

src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/RUP-8
1. En el punto de inicio de RUP, se recarga la agenda seleccionada cada 30 segundos.
2. Se modularizó la parte de código que carga las prestaciones a los turnos, a fin de poder reutilizar la funcionalidad.
3. Se implementó el decorator unsubscribe en el componente de punto de inicio, para evitar solapamiento de requests de agendas.
=> RUP: Recarga agenda seleccionada

package.json, src/app/app.module.ts, src/app/components/reportesDiarios/encabezadoReportesDiarios.component.ts, src/app/components/reportesDiarios/encabezadoReportesDiarios.html, src/app/services/xlsx.service.ts
1.  Exportacion a excel del reporte generado en la pantalla reportesDiarios
2. Planilla C1
3. Resumen Diario Mensual
=> Reportes Diarios - Exportacion a excel

src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/HUDS-1
https://proyectos.andes.gob.ar/browse/HUDS-2
https://github.com/andes/app/issues/1468
1.  Toda vez que se le valida una prestación en RUP, se borran los registros de memoria (cache) asociados a ese usuario, para que los mismos sean recargados al reingresar a su historia clínica.
2. Implementa el ngAfterContentInit en lugar de ngOnInit, para refrescar la información del paciente cada vez que visita la página, y no solo cuando la inicia.
=> HUDS: Actualiza los conceptos en memoria

src/app/components/turnos/dar-turnos/dar-turnos.component.ts
#1466
1. Arregla el filtro de prestaciones por defecto cuando no se selecciona ningún tipo de prestación
=> fix(CITAS): arregla filtros por tipo de prestación al dar un turno

src/app/apps/auth/components/login/login.component.ts
Elimina control de huso horario x problemas con las configuraciones de los equipos
1. se revierten cambios de control de huso horario
2. 
3.
=> fix(login): elimina control de huso horario

src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
RUP: Hot fix en limpieza de cache de paciente en validación de no nominalizada
1. RUP: Hot fix en limpieza de cache de paciente en validación de no nominalizada
=> RUP: Hot fix en limpieza de cache de paciente en validación de no nominalizada

src/app/components/turnos/dashboard/update-contacto-direccion.html, src/app/modules/mpi/components/paciente-detalle.ts
https://proyectos.andes.gob.ar/browse/MPI-48
1. Agrega la información de la dirección legal (solo lectura) debajo de Dirección
https://github.com/andes/andes-test-integracion/pull/113
=> CITAS - Agrega dirección legal en detalles del paciente

src/app/components/turnos/dar-turnos/dar-turnos.component.ts, src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-41
1. Agrega check en sidebar al momento de sacar un turno, para poder registrar que dicho turno fue sacado via telefónica.
=> CITAS - Agrega check de turno telefónico

package-lock.json, package.json, src/app/modules/rup/components/ejecucion/prestacionCrear.html
https://pm.andes.gob.ar/projects/ui-ux/work_packages/1025/activity
1. Se hizo un reordenamiento de los elementos de formulario
2. Se reformuló el flujo interactivo
=> RUP: Mejoras al crear Prestación fuera de Agenda

src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts, src/app/modules/rup/components/internacion/puntoInicio-internacion.html, src/app/modules/rup/services/elementosRUP.service.ts, src/app/modules/rup/services/prestaciones.service.ts
Cargar, además de epicrisis, evaluación inicial, evolución y indicaciones. 
1. Se parametriza los tipos de prestaciones posibles a cargar.
=> feat(internacion): permite crear otros tipos de prestaciones

package-lock.json, package.json, src/app/app.module.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html, src/app/components/top/reglas/visualizacionReglas.component.ts, src/app/components/top/reglas/visualizacionReglas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html, src/app/directives/financiador-select-directive.ts, src/app/directives/organizacion-select.directive.ts, src/app/directives/prestaciones-select.directive.ts, src/app/directives/profesionales-select.directive.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/services/conceptos-turneables.service.ts, tslint.json
Implementa directivas Angular para simplificar y estandarizar el uso de los plex-select. Se realiza un commit de ejemplo por cada directiva.
1. Select Organizaciones
2. Select Profesionales 
3. Select Prestaciones
4. Select Financiadores
Un cambio de APIs en las prestaciones: https://github.com/andes/api/pull/847
=> CORE: directivas para plex-select

.github/workflows/build.yml, src/app/components/formularioTerapeutico/add-form-terapeutico.ts, src/app/components/snomed/snomed-buscar.component.ts, src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/interfaces/semantic-tag.type.ts, src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/MIT-7
Agregar al buscar el semantic Tag: _fármaco de uso clínico_
=> feat(RUP): Agregar al buscador el semantic Tag: fármaco de uso clínico

src/app/app.module.ts, src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/elementos/rupers/select-base-component.html, src/app/modules/rup/components/elementos/rupers/select-base.component.html, src/app/modules/rup/components/elementos/rupers/select-base.component.ts, src/app/modules/rup/components/elementos/rupers/select-organizacion.component.ts, src/app/modules/rup/components/elementos/rupers/select-prestacion.component.ts, src/app/modules/rup/components/elementos/rupers/select-profesional.component.ts, src/app/modules/rup/components/elementos/rupers/select-snomed.component.ts, src/app/modules/rup/components/elementos/rupers/select-statico.component.ts
Atomos de selección de:
1. Organización.
2. Profesionales.
3. Prestaciones.
4. Snomed.
5. Estático.
=> Rupers: elementos rup de seleccion de entidades

src/app/apps/rup/plantillas-rup/plantillas-rup.component.html, src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/elementos/informe.component.ts, src/environments/environment.dev.ts
Se agrega elemento de registro a las plantillas RUP.
=> feat(rup): agrega elemento de registro a las plantillas

src/app/core/mpi/components/paciente-cru.component.ts
Agrega control de la variable disableGuardar en el momento de guardar el paciente
1. 
2. 
3. 
https://github.com/andes/api/pull/948
=> fix(mpi): check disableGuardar en save paciente

src/app/modules/rup/components/ejecucion/prestacionValidacion.html
https://proyectos.andes.gob.ar/browse/RUP-27
1. Se agrega botón "previsualizar resumen pdf" una vez guardada la prestación (Similar al que se muestra una vez validada la prestación).
https://github.com/andes/api/pull/888
=> RUP - Previsualización de informe de prestación

src/app/core/mpi/components/paciente-cru.component.ts
Quita control sobre el valor disabledGuardar, por error en pacientes similares
1. 
2. 
3.
=> fix(mpi): quita verificación disableGuardar

src/app/components/top/solicitudes/auditarSolicitud.component.ts
https://proyectos.andes.gob.ar/browse/TOP-37 (3er item)
1. Al asignar una solicitud a un profesional, si en la misma ya se indicaba un profesional destino, este se carga por defecto, con la posibilidad de modificarlo.
=> TOP: profesional destino x defecto

package-lock.json, package.json, src/app/components/auditoria/prestacionPaciente/auditoria-prestacionPaciente.html, src/app/components/inicio/inicio.html, src/app/components/paciente/headerPaciente.scss, src/app/components/turnos/gestor-agendas/turnos.html, src/app/components/turnos/lista-espera/listaEspera.html, src/app/components/turnos/punto-inicio/paciente-search-turnos.html, src/styles.scss
Depende de:
https://github.com/andes/plex/pull/145
**IMPORTANTE**
Al depender de una versión de Plex no publicada al momento de crear este PR, se debe esperar a que salga la publicación y actualizar el package.json con la nueva versión, luego recién se puede revisar y aprobar este PR.
1. Se actualizaron nombre de íconos según la versión 5.0.45 de @mdi/font, usada por Plex.
=> Actualización de nombres de íconos de mdi

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/carpeta-paciente/carpeta-paciente.html
Mediante el cambio de estilo en internacion, otras vistas se vieron afectadas y no se veía correctamente la carpeta (fondo y letra en blanco).
1. Corregir el estilo condicionandolo solo si el sidebar está invertido, caso contrario sigue con el estilo por defecto del componente.
2. 
3.
=> CARPETA PACIENTE: corrige estilo del componente solo si hay invert en sidebar

src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-40
1. Muestra cantidad de turnos virtuales en el detalle de configuración inicial de agenda, en gestor de agendas
=> CITAS: muestra cantidad de turno virtuales en detalle

src/app/components/carpeta-paciente/carpeta-paciente.component.ts, src/app/components/carpeta-paciente/carpeta-paciente.html
https://github.com/andes/app/issues/1488
1. Arregla limpieza de numero de carpeta
2. Deshabilita el botón guardar si no existen cambios
=> CITAS: Arregla limpieza de numero de carpeta

src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts, src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts, src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Permitir realizar el egreso desde el listado de internación
1. Cambia la forma de buscar los snapshot cuando se va a egresar un paciente
Pull request  https://github.com/andes/api/pull/953
=> Mapa camas fix egreso

src/app/app.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-37
1. Agrega control de permiso para emisión de comprobante
=> feat(BUSCADOR): agrega control de permiso para emisión de comprobante

src/app/apps/mitos/services/snomed.service.ts, src/app/modules/estadisticas/services/snomed.service.ts
https://proyectos.andes.gob.ar/browse/RUP-15
1. Cambia método de ruta de CIE10 de GET a POST
2. En src/app/modules/estadisticas/services/snomed.service.ts, remueve método "getCie10", duplicado y nunca invocado. Remueve rutas en desuso.
=> RUP: Corrige ruta de mapeo CIE10

src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html, src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
Corregir error en censo diario, cuando hay un pase de un paciente y en la unidad organizativa ya existe un paciente internado, no se visualiza correctamente el Pasa A
1. Agrega control por paciente anteriormente listado cuando agrega el Pase A de un paciente en el censo diario
=> fix(Internacion-censo): Corrige bug de censo diario, control de pases

src/app/components/especialidad/especialidad.component.ts, src/app/components/profesional/profesional.component.ts
https://github.com/andes/app/issues/1573
1. Se verifica si el usuario logueado tiene permiso de acceso en _EspecialidadComponent_ y _ProfesionalComponent_ al iniciar cada componente.
2. Se corrieron los test _/tm/profesional_
=> Tablas-maestras: Ingreso a tablas maestras sin permisos

src/app/components/top/solicitudes/solicitudes.component.ts
Corregir filtros de fecha. Actualmente el filtro "fecha desde"  a veces queda con hora distinta de 0, y no trae las solicitudes del día. (El bug se evidenció corriendo el test https://github.com/andes/andes-test-integracion/pull/120)
1. Se reemplaza el seteo de fechas por default de `new Date()` a `moment().startOf('day')` para asegurar la hora 0.
=> TOP: arregla filtros de fecha con hora diferente de 0

src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
https://github.com/andes/app/issues/1566
1. En revisión de agendas, se modificaron los *ngIf de select de prestaciones para mostrarse siempre que exista mas de una prestación en el turno
- [xx] No
=> AGENDAS: arregla selección de prestación

package-lock.json, package.json
Se perdio al plex-loader del navbar. 
1. Actualiza la versión de plex
=> chore(package): @andes/plex@6.0.3

src/app/apps/mitos/constantes.ts
En el componente de camas de internacion que se busquen las especialidades descendientes de <<394658006
1. Cambia la constante de búsqueda de especialidades
2. 
3. 
- [] No
PR: https://github.com/andes/andes-test-integracion/pull/147
=> INTERNACION - Nueva query para especialidades de camas

src/app/components/top/solicitudes/auditarSolicitud.component.ts
https://github.com/andes/app/issues/1472
1. Apaga los flags cada vez q se va a auditar una solicitud diferente
=> TOP: oculta panel de prioridad al auditar otra solicitud

src/app/components/top/solicitudes/solicitudes.component.ts
Corrige párametros de búsqueda para selección de estado "Turno dado", que está provocando perdida de resultados en búsqueda de solicitudes.
1. Asigna estados por defecto. Caso que la selección sea "Turno dado", remueve estado 'validado', para filtrar aquellas solicitudes con turno dado que ya posean registro en HUDS.
=> TOP: corrige filtro estados x defecto

src/app/components/top/solicitudes/solicitudes.component.ts
Corregir bug al momento de carga de solicitudes en las fechas default
1. Se agrega conversión a Date
=> fix(solicitudes): formatea fechas default a Date

src/app/components/top/solicitudes/solicitudes.component.ts
arregla filtro de turno dado con tipo de prestación
1. Arregla bug, que al filtrar solicitudes (de entrada o salida) por tipo de prestación y turno dado, no trae resultados.
=> TOP: arregla filtro de turno dado con tipo de prestación

src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts, src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
La fechaActual no se estaba actualizando, así que no te dejaba cargar ningún movimiento después de la hora que ingresaste al mapa de cama.
1. Re ordena los pipes de RxJS.
=> fix(mapa-camas): fecha actual

src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Corregir error al internar pacientes temporales que no tienen documento cargado
1. Se agrega control de documento al consultar obra social de paciente
2. 
3.
=> fix(Internacion): Agrega control de paciente sin documento

src/app/components/reportesDiarios/encabezadoReportesDiarios.component.ts, src/app/components/reportesDiarios/encabezadoReportesDiarios.html, src/app/components/reportesDiarios/resumenDiarioMensual.component.ts, src/app/components/reportesDiarios/resumenDiarioMensual.html, src/app/services/xlsx.service.ts
1. División de turnos (mañana, tarde, noche)
2. Exportación a excel en un solo archivo
- [x ] No
[API Pull Request](https://github.com/andes/api/pull/959)
[Test Integracion Pull Request](https://github.com/andes/andes-test-integracion/pull/146)
=> Reportes diarios - Division de turnos

src/app/services/documentos.service.ts
Corrige la descarga del listado de internación
1. Cambia el envio de parametros para la descarga del listado de internación
2. 
3.
=> Internación: Corrige el envio de parametros para el listado de internación

src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/RUP-70
1. Se modifica la visualización de filtros Ambulatorio/Internación en el buscador de la HUDS
=> RUP - modifica visualización filtros

src/app/app.module.ts, src/app/app.routing.ts, src/app/apps/rup/mapa-camas/mapa-camas.module.ts, src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.html, src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html, src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html, src/app/apps/rup/mapa-camas/views/lista-espera/lista-espera.component.html, src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html, src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/elementos/consultaDeNinoSanoE2Y3A.html, src/app/modules/rup/components/elementos/consultaDeNinoSanoE3Y6A.html, src/app/modules/rup/components/elementos/consultaDeNinoSanoM2A.html, src/app/modules/rup/components/elementos/evolucionProblemaDefault.html, src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html, src/app/modules/rup/components/huds/vistaPrestacion.html, src/app/modules/rup/elementos-rup.module.ts
Crear modulo Angular de Elementos RUP y activar nuevamente el de internación.
=> rup: crea modulo angular

src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts, src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
Actualización de combo de tématicas según https://proyectos.andes.gob.ar/browse/RUP-48
Corrige bug https://proyectos.andes.gob.ar/browse/RUP-86
1. Actualiza opciones de combo estático de temáticas en elemento RUP de No Nominalizada.
2. Oculta y limpia valor de campo "otra temática", en caso de deseleccionar esa opción.
3. Corrige bug https://proyectos.andes.gob.ar/browse/RUP-86
https://proyectos.andes.gob.ar/browse/RUP-48 
https://proyectos.andes.gob.ar/browse/RUP-86
=> RUP: Actualiza combo de temáticas de actividades

src/app/app.module.ts, src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/historialSolicitud.component.ts, src/app/components/top/solicitudes/historialSolicitud.html, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/modules/rup/components/huds/vistaSolicitudTop.html
https://proyectos.andes.gob.ar/browse/TOP-27
https://proyectos.andes.gob.ar/browse/TOP-37 (items 1 y2)
1.Nuevo componente de historial de solicitud: Junta la información de historial de solicitud y estados de prestación, la ordena por fecha y la muestra en el detalle de solicitud.
La información de historial incluye: acción realizada, fecha y usuario de ejecución, y notas u observaciones.
2. Implementa componente de historial de solicitud en HUDS de RUP
3. Implementa componente de historial de solicitud en detalle de solicitud de TOP.
https://proyectos.andes.gob.ar/browse/TOP-37 (items 1 y2)
=> TOP: Historial de solicitudes

src/app/core/mpi/components/paciente-cru.component.ts, src/app/core/mpi/components/paciente-cru.html
https://proyectos.andes.gob.ar/browse/MPI-69
1. Se asoció la visualización y la propiedad 'disabled' del botón 'ignorar y guardar' a variables distintas.
=> MPI - Botón 'ignorar y guardar'

src/app/app.module.ts, src/app/components/turnos/dar-turnos/dar-turnos.html, src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts, src/app/components/turnos/gestor-agendas/gestor-agendas.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts, src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html, src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html, src/app/components/turnos/gestor-agendas/turnos.html, src/app/components/turnos/punto-inicio/turnos-paciente.html, src/app/interfaces/turnos/IAgenda.ts, src/app/interfaces/turnos/IInstitucion.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/pipes/espacioFisico.pipe.ts, src/app/services/turnos/institucion.service.ts
[https://proyectos.andes.gob.ar/browse/CIT-1](https://proyectos.andes.gob.ar/browse/CIT-1)
1. Se crea el EspacioFisicoPipe para la visualización del espacio físico según el tipo que corresponda
2. Se modifica el PanelAgendaComponent para que al editar el espacio físico de una agenda se pueda seleccionar entre instituciones o espacios dentro de la organización. Al elegir una opción se anula la otra.
3. Se modifica el PlanificarAgendaComponent para que al crear una agenda se pueda seleccionar entre instituciones o espacios dentro de la organización. Al elegir una opcion se anula la otra.
4. Se solucionan errores de linteo
Adjunto archivo con la consulta para insertar en la base de datos las instituciones:
[jsonFinalInstituciones.txt](https://github.com/andes/app/files/4036582/jsonFinalInstit …
=> CITAS: Visualizacion de otros espacios fisicos

src/app/components/top/solicitudes/detalleSolicitud.component.ts, src/app/components/top/solicitudes/detalleSolicitud.html, src/app/components/top/solicitudes/historialSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-32
1. Se reemplaza el antiguo visualizador por el de plex
=> TOP - plex-visualizador en documentos

package-lock.json, package.json, src/app/apps/rup/mapa-camas/constantes-internacion.ts, src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html, src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
COMO personal de salud QUIERO identificar las camas con oxigeno PARA para actuar rápidamente contra el COVID-19.
1. Distingue con un icono las camas que tienen aporte central de oxígeno.
2. 
3.
=> INTERNACION - Icono distintivo para camas con aporte de oxigeno

src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts, src/app/apps/rup/mapa-camas/views/cama/cama.component.html, src/app/apps/rup/mapa-camas/views/cama/cama.component.ts, src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
Poder elegir un sector superior y que te muestre todas camas de ese sector.
1. Modifica el ABM de camas para que guarde el arbol de sectores
2. Modifica el filtro de sectores para incluir sectores superiores.
3. Modifica la aplicación del filtro de sectores para verificar todos los niveles.
Script actualizar sectores de camas: https://gist.github.com/GaboCancellieri/00ad65f6a93f365495cba2c31fbc4382
PR: https://github.com/andes/andes-test-integracion/pull/150
=> INTERNACION - Filtrar por sectores superiores

src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
Se fusionan (por ahora) las capas medicos/enfermería.
1.  Del lado de la app se evita inhabilitar o editar en la capa enfermeria desde el ABM de camas.
https://github.com/andes/api/pull/963
=> feat(mapa-camas): fusion medico/enfermero

src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-28
1. Arregla llamados repetidos a la API
=> TOP: Arregla llamados repetidos a la API

src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts, src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-63
1. Se agregan los controles necesarios para visualizar las prestaciones según los permisos que tiene cada usuario y si es profesional o no.
Cambios realizados segun comentario en https://github.com/andes/app/pull/1586
=> MISC: Permisos en el buscador de turnos y prestaciones

src/app/apps/rup/mapa-camas/mapa-camas.module.ts, src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html, src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts, src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html, src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts, src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html, src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts, src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html, src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts, src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html, src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts, src/app/modules/rup/interfaces/prestacion.estado.interface.ts, src/app/modules/rup/services/prestaciones.service.ts, src/environments/environment.dev.ts
Visualizar valores de los registros en seccionado.
https://proyectos.andes.gob.ar/browse/IN-139
https://proyectos.andes.gob.ar/browse/IN-140
https://proyectos.andes.gob.ar/browse/IN-141
https://proyectos.andes.gob.ar/browse/RUP-100
=> map-camas: visualizar valores y romper validacion

src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.html
Pasar el boton de iniciar prestación para la capa medica a label o abajo del sidebar.
1. Se modificó el botón de iniciar prestación para que sea mas visible
2. 
3.
=> INTERNACION - Modificar boton de iniciar prestacion

src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/modules/rup/components/ejecucion/buscador.scss, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts, src/app/modules/rup/components/ejecucion/prestacionValidacion.html, src/app/modules/rup/interfaces/snomedSearchResult.interface.ts, src/app/modules/rup/services/elementosRUP.service.ts
https://proyectos.andes.gob.ar/browse/RUP-38
1. Elimina código de búsqueda guiada
=> RUP: limpia código búsqueda guiada

src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
En el filtro de paciente porder filtrar por nombre/apellido o por nro de documento.
1. Agrega un control en el filtro de paciente, si el usuario escribe un numero se filtra por documento, caso contrario se filtra por nombre o apellido.
2. 
3. 
PR: https://github.com/andes/andes-test-integracion/pull/159
=> INTERNACION - Filtrar por documento de paciente

src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-87
1. El crear los objetos de evoluciones, incluye los registros sin valor, y, en el objeto de evolución, setea en null los atributos relacionados al valor del registro.
=> HUDS: muestra registros sin valor

src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/RUP-58
1.  Arregla cancelación de desvinculación de pieza en odontrograma
=> RUP: Arregla cancelar desvinculación de pieza

src/app/components/auditoria/auditoria.component.ts, src/app/components/auditoria/auditoria.html, src/app/components/auditoria/auditoria.scss
https://proyectos.andes.gob.ar/browse/MPI-54
1. Visualización de nota de error de un paciente, mediante nueva columna en la tabla y tooltip.
https://github.com/andes/api/pull/940
=> MPI (Auditoría) - Visualización de nota de error

package-lock.json, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routings-guard.class.ts, src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts, src/app/modules/rup/components/ejecucion/buscador.component.ts, src/app/modules/rup/components/ejecucion/buscador.html, src/app/shared/services/analytics.service.ts, src/app/shared/services/hotJar.service.ts, src/environments/apiKeyMaps.ts.example, src/environments/environment.demo.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
1. Flujo de sesion reactivo. 
2. Servicio Hotjar
3. Servicio google analytics
4. Primeras pruebas con el buscador de Snomed.
=> core: hotjar y google analytvis

src/app/components/auditoria/auditoria.html, src/app/components/paciente/headerPaciente.html, src/app/core/mpi/components/paciente-cru.component.ts, src/app/core/mpi/components/relaciones-pacientes.component.ts, src/app/core/mpi/components/relaciones-pacientes.html, src/app/modules/mpi/components/paciente-detalle-foto.directive.ts, src/app/modules/mpi/components/paciente-detalle.html, src/app/modules/mpi/components/paciente-detalle.scss, src/app/modules/mpi/components/paciente-listado.html, src/app/modules/mpi/components/paciente-panel.html, src/app/modules/mpi/mpi-lib.module.ts
https://proyectos.andes.gob.ar/browse/MPI-60
https://proyectos.andes.gob.ar/browse/MPI-61
1. Reemplaza la visualización de la foto de pacientes en paciente-panel, paciente-header y paciente-listado utilizando foto-directive.
No es estrictamente necesario pero debería estar: https://github.com/andes/api/pull/958
=> MPI/RUP - Carga de foto del paciente mediante foto-directive

src/app/app.module.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/seguimiento-paciente/seguimientoPaciente.component.ts, src/app/modules/rup/components/ejecucion/seguimiento-paciente/seguimientoPaciente.html, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts, src/app/modules/rup/components/ejecucion/vistaHuds.html, src/app/modules/rup/interfaces/seguimientoPaciente.interface.ts, src/app/modules/rup/services/seguimientoPaciente.service.ts
Seguimiento de Pacientes
Debido a la pandemia actual, la provincia de San Juan se prepara para hacer el seguimiento de pacientes que den positivo al COVID19, pero que realicen internación domiciliaria. Para ello el paciente cargará de manera independiente su registro de estado. Para que el profesional de salud pueda observar estos datos, se requiere que sean visualizados en ANDES.
1. Servicio de seguimiento de pacientes que trae la información desde la api.
2. Pestaña nueva con registros de seguimiento. La misma aparece tanto en el HUDS, como en las prestaciones en ejecución. Cuando el paciente no presenta registros de seguimiento esta pestaña no aparece.
- [x ] Si
- [x ] Si
Se crea la colección seguimiento de pacientes en la base de datos
- [x ] Si: https://github.com/andes/api/pull/973 …
=> RUP - Seguimiento de paciente por autoregistros

src/app/app.component.ts, src/app/components/novedades/header-novedades/header-novedades.component.ts, src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.ts, src/app/components/novedades/lista-novedades/lista-novedades.component.ts
Quita el 'http' inicial y sacamos el token por ahora ya que estan las API publicas.
[ ] Si
[ ] Si
=> fix(novedades): cambia URL por ahora

src/app/components/inicio/inicio.html
Actualiza el inicio a plex-layout
=> fix(inicio): actualizxa a plex-layout

src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Al tener seleccionada una cama disponible: tanto las acciones 'internar paciente', 'editar cama' como 'bloquear cama' retornar al usuario al panel de estadísticas de dotación cuando en teoría se debería regresar al panel de detalle de la cama seleccionada.
1. Arregla el ruteo al volver de internar paciente y bloquear cama
NOTA: el fix del ruteo en "editar cama" está en el PR: https://github.com/andes/app/pull/1685
=> INTERNACION - Arregla ruteos defectuosos UI/UX en mapa de camas

src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
Se necesita que el historial no liste los estados de la cama que no son movimientos y cuando dos estados coinciden en la fecha, listarlos por orden de creación.
1. En historial se agrega filtro de estado cuando no es movimiento
2. Si dos estados coinciden en fecha, se ordena por la fecha de creación (createdAt)
3. 
PR: https://github.com/andes/api/pull/972
=> INTERNACION - Historial filtra los movimientos y ordena por createdAt

src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
Al grabar la edición de egreso se pierde el plex-options.
1. Modifica la llamada para desabilitar el plex-options al editar egreso
2. 
3.
=> INTERNACION - Arregla la desaparicion de plex options en egreso

src/app/apps/rup/plantillas-rup/plantillas-rup.component.html, src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts, src/app/modules/rup/services/plantillas.service.ts
ver los conceptos con el color correspondiente según semanticTag
para su correcta identificación
agrandar campo de texto enriquecido 
1. se importa PrestacionesService a plantillas-rup.component para utilizar getCssClass.
2. 
3.
=> refactor(rup):plantillas semantic-tag rup-110,rup-55,rup-57

src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.ts
https://proyectos.andes.gob.ar/browse/RUP-106
1. Se ejecuta el código correspondiente en el ngOnInit.
=> rup: activa por defecto primera sección

src/app/modules/rup/components/elementos/rupers/select-base.component.html, src/app/modules/rup/components/elementos/rupers/select-base.component.ts
https://proyectos.andes.gob.ar/browse/RUP-105
1. Se verifica si el paramentró "otros" es verdadero.
=> elementos-rup: select snomed mostraba "otros" al editar

src/app/components/inicio/inicio.html
Que se vea la caja de Analytics
1. Quita ngIf innecesario porque llevaron la funcionalidad al TS
=> fix(inicio): analytics no se ve

src/app/components/inicio/inicio.component.ts
1. Analytics estaba mal escrito.
=> fix(home): analytics type

src/app/modules/mpi/components/paciente-detalle.ts
https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=5001
1. Si el paciente tiene asignado un financiador se setea la "cache" de obras sociales para que al consultar el _BehaviorSubject_ ( _getFinanciadorPacienteCache()_ ) muestre la obra social del paciente seleccionado.
=> CITAS: fix visualizacion de obras sociales

src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html, src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/MISC-41
1. Valida permisos de CDA para adjuntar HUDS
- [] Si
=> Prestamos HC: Permisos para adjuntar HUDS

src/app/components/top/solicitudes/historialSolicitud.component.ts
https://proyectos.andes.gob.ar/browse/TOP-43
1. Se cambió orden de entradas de historial de solicitudes, de manera que se visualicen primero las más recientes.
=> TOP: invierte orden de items de historial

src/app/modules/estadisticas/services/agenda.service.ts
Se reportó que no se podía descargar el csv desde https://andes.sanjuan.gob.ar/dashboard/citas
1. Se agrego como option al post que descarga el csv _responseType='blob'_
=> Dashboard - Citas: Arreglo para descargar el CSV

src/app/app.component.ts, src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts, src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/ejecucion/puntoInicio.component.ts, src/app/modules/rup/components/ejecucion/puntoInicio.html, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
https://proyectos.andes.gob.ar/browse/PRIV-30
* Agrega controles de permisos de acceso a HUDS en:
1. Menu hamburguesa: Botón de acceso a HUDS
2. En RUP, tab de HISTORIA DE PACIENTE en ejecución de prestación
3. En RUP, tab de RESUMEN DEL PACIENTE, en ejecución de prestación. 
4. En RUP, tab de RESUMEN DEL PACIENTE, en visualización de prestación. 
5. En RUP, botón de HUDS de Paciente en punto de inicio
6. En RUP, botón de VER HUDS en panel lateral derecho de detalles 
7. En Punto de inicio, controlar token al "Continuar registro"
8. HudsBusquedaPacienteComponent: Arregla control de permisos.
* Al iniciar prestación, agrega controles de permisos de acceso a HUDS para evitar el registro de acceso por defecto en caso de no poseer permisos.
NOTA: Script de mongo para otorgar permiso de acceso …
=> PRIV: agrega controles de permisos de acceso a HUDS

src/app/core/mpi/components/paciente-cru.component.ts
https://proyectos.andes.gob.ar/browse/MPI-67
1. Se asigna la subscripción del servicio de validacion a una variable que luego, al cancelar, se utiliza para desubscribir el evento.
=> MPI - Desubscribe validación de paciente al cancelar

src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.html, src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
Se percibe conflictiva la configuración de la y fecha/hora al estar ambos datos alojados en un mismo input. Se propone desglosar en dos inputs diferenciados.
1.  Se divide el input de fecha en: Fecha y Hora y se concatenan al momento de iniciar la prestación.
2. 
3.
=> INTERNACION - División de input de fecha y hora en registros medicos

src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Guardar en el estado que se almacena al egresar al paciente el dato del tipo de egreso
1. 
2. 
3.
=> Mapa-camas: Agrega el dato de tipo de egreso al estado

src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
El problema es que a veces el usuario está realizando cambios en una fecha que no es la actual y necesita ver los movimientos a 7 dias de dicha fecha.
1. El componente de movimientos toma la fecha en uso como referencia.
2. 
3.
=> INTERNACION - Obtiene movimientos a 7 dias de la fecha en uso

src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.html
Para facilitar la interpretación del usuario, se proponer que el orden de los filtros (en la primera línea del wrapper) se corresponda con la columnas del listado.
1.  Cambia el orden de la primera línea de filtros para que coincidan con la tabla inferior.
2. 
3.
=> INTERNACION - Nuevo orden visual de filtros

src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts, src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
Acceso a la HUDS depende del permiso unicamente.
=> fix(huds): acceso huds depende del permiso unicamente

src/app/core/mpi/components/paciente-cru.component.ts, src/app/modules/mpi/components/paciente-panel.html
1. VIsualizar la foto obtenida desde renaper al momento de la validacion de un paciente
=> MPI - Fix visualizar foto de renaper

src/app/modules/mpi/components/paciente-detalle.ts
https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=5023
1. Se agrega el loadObraSocial() al ngOnChanges() para que se carguen las obras sociales cada vez que se modifiquen los inputs.
=> CITAS:visualizacion obra social en revision agendas

src/app/core/mpi/components/bebe-cru.component.ts, src/app/core/mpi/components/bebe-cru.html, src/app/core/mpi/components/extranjero-nn-cru.component.ts, src/app/core/mpi/components/extranjero-nn-cru.html, src/app/core/mpi/components/paciente-cru.component.ts, src/app/core/mpi/components/paciente-cru.html
Adaptar la app a las respuestas del nuevo paquete georeference
1. Agregua chequeo por objeto vacio
2. Corrige posicion de botón 'geolocalizar' en vista de registro de bebe
=> MPI - Modificacion para paquete georeference

src/app/components/top/solicitudes/auditarSolicitud.component.ts, src/app/components/top/solicitudes/auditarSolicitud.html, src/app/components/top/solicitudes/historialSolicitud.component.ts, src/app/components/top/solicitudes/solicitudes.component.ts, src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-11
https://proyectos.andes.gob.ar/browse/TOP-12
1. Nueva funcionalidad de remitir solicitud en auditoría de TOP
https://proyectos.andes.gob.ar/browse/TOP-12
=> TOP: Incluye operación "Remitir" al PATCH de prestaciones

package-lock.json, package.json, src/app/app.module.ts, src/app/apps/rup/plantillas-rup/plantillas-rup.component.html, src/app/components/organizacion/sectores-item/sectores-item.scss, src/app/modules/rup/components/core/_rup.scss
=> chore(plex): update V6.5.0

src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.html, src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
Al validar prestación el loader del navbar nunca terminaba.
=> fix(rup): al validar prestacion plex-loader nunca acaba

src/app/modules/rup/components/core/rup.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts, src/app/modules/rup/components/ejecucion/prestacionEjecucion.html, src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoE2Y3A.component.ts, src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoE3Y6A.component.ts, src/app/modules/rup/components/elementos/RegistrarMedidasAntropometricasNinoM2A.component.ts, src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts, src/app/modules/rup/components/elementos/calculoDeBoston.component.ts, src/app/modules/rup/components/elementos/chart.component.ts, src/app/modules/rup/components/elementos/consultaDeNinoSanoE2Y3A.component.ts, src/app/modules/rup/components/elementos/consultaDeNinoSanoE3Y6A.component.ts, src/app/modules/rup/components/elementos/consultaDeNinoSanoM2A.component.ts, src/app/modules/rup/components/elementos/desarrolloPsicomotor.component.ts, src/app/modules/rup/components/elementos/graficoLineal.component.ts, src/app/modules/rup/components/elementos/indiceDeMasaCorporal.component.ts, src/app/modules/rup/components/elementos/lactancia.component.ts, src/app/modules/rup/components/elementos/observaciones.component.ts, src/app/modules/rup/components/elementos/resumenHistoriaClinica.component.ts, src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html, src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts, src/app/modules/rup/components/elementos/tensionArterialPediatrica.component.ts, src/app/modules/rup/interfaces/prestacion.registro.interface.ts
https://proyectos.andes.gob.ar/browse/RUP-96
Flag empty que determina si un registro esta vacío.
1. Función general que determina si un registro esta vacío.  
2. Cada _ElementoRUP_ puede implementar su particularidad.
=> feat(rup): add isEmpty flag
