- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
Se requiere mostrar en un principio el historial de movimientos a 7 dias de la fecha en la que el usuario está trabajando.
1. El historial busca desde 7 dias antes de la fecha seleccionada y hasta la fecha seleccionada.
2. 
3.
> INTERNACION - Historial de movimientos a 7 dias de la fecha elegida

- src/app/components/organizacion/organizacion-sectores.component.ts
Mantener sincronizado el árbol de sectores con el listado de unidades organizativas. Al grabar sectores, ver las unidades organizativas y si no están en la organización agregarlos. Solo agregar si no estan.
1.  Al guardar, verifica que las unidades organizativas de los sectores se correspondan con la organización.
2. 
3.
> INTERNACION - Agrega las unidades organizativas faltantes en la organizacion

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
https://proyectos.andes.gob.ar/browse/RUP-112
1. Se incluye en el array de planes las solicitudes de los registros de secciones.
2. Post validación, se verifica la existencia de solicitudes dentro de las secciones de registro para mostrar el modal de confirmación de solicitud en bandeja de salida.
> RUP: generar solicitudes de secciones de registros de ejecución

- package-lock.json
- package.json
> chore(plex): V6.6.0

- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/solicitudes/solicitudes.scss
https://proyectos.andes.gob.ar/browse/TOP-44
1. Centra los headers de las columnas de badges y botones en concordancia con el alineado de las columnas. Mejora la visual de la tabla, a pesar de que el alineado no es perfecto, ya que el ancho de la barra de scroll del body de la tabla hace que se desajuste levemente hacia la izquierda.  
- [x ] No
> TOP: centrado de headers tabla solicitudes

- src/app/modules/rup/components/ejecucion/buscador.scss
1. Se quitó z-index de contador de resultados
~~z-index: 1000;~~
> Fix contador huds

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Como usuario necesito poder filtrar los registros médicos de una internacion por tipo de prestacion.
1. Agrega filtro de prestacion para la lista de registros medicos.
2. 
3.
> INTERNACION - Agrega filtro de prestacion en registros medicos

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss
1.  Agrega historial HUDS en ejecución de prestación
> RUP: Agrega historial HUDS en ejecución de prestación

- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaPrestacion.ts
https://proyectos.andes.gob.ar/browse/PRIV-46
1. Agrega botón de descarga de informe de RUP en HUDS de paciente.
2. Agrega control de permisos para habilitar el botón de descarga
**NOTA**: importante pasarse a API https://github.com/andes/api/pull/1005 y darse/quitarse permisos en el gestor de usuario para testearlo
> PRIV: agrega botón descarga informe

- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/inicio/inicio.component.ts
https://proyectos.andes.gob.ar/browse/MISC-69
https://proyectos.andes.gob.ar/browse/MISC-71
1. Se ordenan los módulos en el inicio
2. Se muestran solo los que están activos
3. Se llama una única vez a módulos al cargar los permisos.
4. Se oculta la campana de novedades si no hay novedades
> HOME: ordenamiento de módulos y ocultar inactivos

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
https://proyectos.andes.gob.ar/browse/TOP-49
1. Cambia push de estados por reemplazo de array
> TOP: Arregla duplicidad de estados de nueva solicitud

- src/app/components/top/solicitudes/detalleSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-46
1. Se incluyen las indicaciones con un pleh-help en el detalle de solicitud.
> TOP: indicaciones solicitud en plex-help

- src/app/components/profesional/profesional-create-update.component.ts
https://proyectos.andes.gob.ar/browse/MPI-149
1. Se actualizó el modo en que se obtienen los datos del response.
> MPI: Fix en validación RENAPER de profesionales 

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
Se quitó del método `actualizar` el parametro "etiqueta" en desuso. Poner especial atención a la evaluación lógica en https://github.com/andes/app/blob/eb560640bd3612a8c1c96c624fdabd6c99510c4a/src/app/components/turnos/dar-turnos/dar-turnos.component.ts#L372 cuál será la evaluación correcta?
> TOP: boyscouting en Dar Turnos

- src/app/modules/rup/services/prestaciones.service.ts
No me permite asignar turno el ir al resumen de la prestación para las solicitudes autocitadas.
1. Se define como organización destino la del profesional logueado.
2. Guarda las solicitudes como prestaciones al validar una prestación si son autocitaciones y no tienen organización destino.
> RUP: guardar prestación si es una solicitud autocitada y no tiene organización destino

- src/app/components/turnos/punto-inicio/activar-app.html
https://proyectos.andes.gob.ar/browse/MPI-150
1. Se agrega el formularioValidacion en _activar-app.html_ para realizar las verificaciones de formato correspondiente tanto en email como en teléfono.
Si bien no estaba marcado en la user, se paso el campo celular a plex-phone para realizar la verificación del formato correctamente.
> MPI: Validar email para activar la app mobile

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-51
1. cambia a operacion citar en PATCH de solicitud
> TOP: cambia a operacion citar en PATCH de solicitud

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
https://proyectos.andes.gob.ar/browse/TOP-52
1. Corrige los filtrados en los combos de organización destino y prestación destino según reglas TOP
2. 
3.
> fix(TOP): Corrige filtros según reglas de solicitudes

- src/app/core/mpi/components/paciente-cru.component.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/mpi-lib.module.ts
https://proyectos.andes.gob.ar/browse/MPI-63
1. Se agrega input en false. Cuando el componente paciente-detalle sea llamado seteando este input en true, realiza un get del paciente actual.
> MPI - Reload en componente paciente-detalle

- src/app/apps/rup/mapa-camas/constantes-internacion.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/interfaces/IRegla.ts
- src/app/interfaces/turnos/IEspacioFisico.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/core/rup.html
- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/elementos/FormulaBase.html
- src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts
- src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
- src/app/modules/rup/components/huds/vistaDetalleRegistro.ts
- src/app/modules/rup/interfaces/snomed-concept.interface.ts
- src/app/modules/rup/services/prestaciones.service.ts
Borra código de transformación de conceptos
> refactor(rup): remueve código de transformacion

- src/app/components/inicio/inicio.component.ts
- src/app/components/novedades/common-novedades.service.ts
- src/app/components/novedades/header-novedades/header-novedades.component.html
- src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.html
- src/app/components/novedades/lista-novedades/lista-novedades.component.html
- src/app/components/novedades/novedades.component.ts
https://proyectos.andes.gob.ar/browse/MISC-68
1. Se permite la visualización de novedades sin módulos asociados
> NOVEDADES: mostrar novedades sin módulo asignado

- src/app/components/reportesDiarios/encabezadoReportesDiarios.component.ts
- src/app/components/reportesDiarios/encabezadoReportesDiarios.html
- src/app/components/reportesDiarios/planillaC1.html
Agregar un filtro por profesional al momento de consultar la Planilla C1
1. Filtro por profesional en la planilla C1
2. Mostrar mensaje de "SIN DATOS" al momento de traer datos vacíos en la planilla C1
> Reporte diarios: Filtrar por profesional y mostrar msj cuando no hay datos en la Planilla C1

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/HUDS-10
1.  muestra fecha última evolución en item de trastorno
2. 
3.
> HUDS: muestra fecha última evolución

- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
agregar "seleccionar plantillas" a seccion
1.
2. 
3.
> feat(RUP):se agrega seleccionar plantillas a sección

- package-lock.json
- package.json
- src/app/components/top/reglas/listaReglas.component.ts
- src/app/components/top/reglas/visualizacionReglas.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/services/conceptos-turneables.service.ts
https://proyectos.andes.gob.ar/browse/RUP-126
1. En el get de reglas, deja de enviar todos los ids de prestaciones permitidas y en su lugar envía un query de permisos para que lo resuelva la API.
> RUP: GET de reglas, cambia parámetros de ids de prestación a query auth

- src/app/app.component.ts
https://proyectos.andes.gob.ar/browse/MISC-60
1. Se  refactorizó el menú hamburguesa para que cargué las opciones desde _módulos_
Parte de la rama 'abm-modulos' https://github.com/andes/app/pull/1720
> MENU: armado dinámico del menú hamburguesa

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-50
1. Si un profesional que no posee ningún permiso de TOP intenta acceder al buscador de solicitudes, por defecto se lo re encamina a "MIS SOLICITUDES"
2. Remueve evaluación de permiso de acceso a solicitudes asignadas
> TOP: profesional sin permisos acceso mis asignadas por defecto

- src/app/components/organizacion/organizacion.component.ts
https://proyectos.andes.gob.ar/browse/TM-8
1. Refresca lista de organizaciones al retornar de la pagina de creación.
> TM: refresca lista de organizaciones al retornar de creacion

- src/app/components/turnos/dar-turnos/calendario.html
- src/app/components/turnos/dar-turnos/calendario.scss
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-59
1. Cambios en elementos de pantalla dar turno
2. Se arregla bug en calendario al ocultar sábados y domingos
> CITAS: cambios visuales en pantalla dar turno

- src/app/components/organizacion/organizacion-create-update.component.ts
- src/app/components/organizacion/organizacion-create-update.html
https://proyectos.andes.gob.ar/browse/TM-10
1. Agrega provincia a edición de organización
2. Arregla bug de selección por defecto de items de ubicación vacíos, que impide la escritura del plex-select
> TM: agrega provincia a edición de organización

- src/app/interfaces/pacienteSearch.interface.ts
- src/app/modules/mpi/components/paciente-buscar.html
Demorar el request para la busqueda mientras el usuario tipea
1. Se agrega debounce en plex-text
> MPI - Agrega retardo en busqueda

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-54
1. Se cambia filtro de organizaciones origen a selección múltiple.
2. Se oculta filtro de organizaciones origen en bandeja de salida (actualmente se muestra, pero no tiene ningún efecto sobre la búsqueda de solicitudes de salida)
> TOP: filtro múltiple de organizaciones origen en buscador solicitudes

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Detectar cuando es una relación del odontograma, y cuando es una secciones.
> fix(rup): mezcla odontograma y seccionado

- src/app/app.module.ts
- src/app/modules/rup/components/ejecucion/help-solicitud.component.ts
- src/app/modules/rup/components/ejecucion/help-solicitud.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
https://proyectos.andes.gob.ar/browse/RUP-22
1. Se muestra la información de solicitud en plex-help
> RUP: información de solicitud en plex-help

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
Guardar los últimos filtros seteados en el mapa de cama y presentarselos al usuario cuando entra de nuevo. Por el momento, se va a guardar  solo para la sessión activa. Luego se pierde.
1.  Modifica el mapa de camas para que guarde los filtros en el sessionStorage y aplica los filtros cada vez que se ingresa al mismo.
2. 
3.
> INTERNACION - Guarda los filtros hasta que dure la sesion

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
Desde el listado de internación, aunque se hayan completado los datos del egreso para validar la prestación, no es posible hacerlo al menos que se recargue la pagina (recién ahí habilita el botón validar).
1. Al guardar un egreso chequea si la internacion puede ser validad o no y habilita o deshabilita el botón correspondientemente
2. 
3.
> INTERNACION - Habilita/Deshabilita el botón de validar internacion al guardar egreso

- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-125
1. Agrega filtro de estado 'auditables' en control de planes generados, al momento de la validación.
> RUP: Arregla duplicación solicitudes auditables

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-91
https://proyectos.andes.gob.ar/browse/RUP-116
1. Cambia la condición para mostrar una agenda en la lista de resultados:
- Se muestran las agendas sin pacientes (sean del tipo que sean), en tanto no se aplique filtro de paciente.
- Si se aplica filtro de paciente, solo se muestran las agendas (sean del tipo que sean) que contengan paciente que matcheen con el filtro.
2. Agrega un flag `matcheaPaciente`, para parchear la situación en que hay resultados, pero se ocultan por no pasar el filtro de pacientes.
https://proyectos.andes.gob.ar/browse/RUP-116
> RUP: Pto inicio, arreglo de filtrado por pacientes

- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Los días de estada se deben calcular por cada estadía en un servicio. Si una internación no tiene pases de servicio entonces los días de estada se calculan al egreso. Si la internación tiene pases los días de estada se calculan cuando se realiza el pase, es decir cuantos días estuvo en el servicio. Mostrar en el resumen del censo mensual la sumatoria de días de estada de los pacientes que se muestran en el servicio. Mostrar una columna mas en el censo mensual
1.  En los censos diarios se realiza y muestra el cálculo de los días de estada por internación y al final la suma de los mismos.
2.  En los censos mensuales se agrega una nueva columna que ilustra la suma de todos los dias de estada del servicio.
3.
> INTERNACION - Incorporar los dias de estada en los censos con su calculo

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/TOP-30
1. Agrega plex-help de reglas en ejecución de prestación
> TOP: help de reglas en ejecución de prestación

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-62
1. Se reemplaza el preview existente en nueva solicitud por plex-visualizador
> TOP: plex-visualizador en nueva solicitud

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-146
1. Al ver resumen de prestación fuera de agenda, evita el control de token de acceso a HUDS si se trata de una prestación no nominalizada.
> fix(RUP): ver resumen fuera de agenda no nominalizada

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/HUDS-19
1. Agrega tipo de prestación a registros de HUDS y lo exhibe en los cards de trastornos, hallazgo, procedimientos y productos.
2. En el caso de hallazgos, muestra el tipo de prestación de la última evolución
> HUDS: muestra tipo de prestación en registros de HUDS

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Total de prestaciones errónea
1. se corrige el total modificando prestaciones.length por prestacionesCopia.length
2. 
3.
> fix(huds): total de prestaciones

- src/app/components/top/solicitudes/prestacionSolicitud.component.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-69
1. Remueve código que crea y postea nuevo objeto de prestación al iniciar una solicitud, y lo reemplaza por patch de estado de ejecución + parametro de fecha de ejecución
2. Agrega a los estados de busqueda "ejecución", para ṕoder visualizar en bandeja de entrada las solicitudes que hayan sido ejecutadas pero nunca validadas.
> fix(TOP): Arregla duplicacion de prestacion al iniciar solicitud asignada

- src/app/components/inicio/inicio.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/shared/services/analytics.service.ts
Agrega algunas metricas mas de Google Analytics. 
Tipo de concepto abren en la HUDS y quien lo abre.
> feat(huds): agrega eventos de google analytics

- src/app/modules/rup/components/ejecucion/buscador.component.ts
… conceptos
#1521
1. Asigna el tipo de buscador por defecto solo después de cargar todos los conceptos.
> RUP: Selecciona tab por defecto solo después de cargar todos los conceptos

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-57
https://proyectos.andes.gob.ar/browse/TOP-60
1. Filtro organizaciones destino en bandeja de salida
2. Columna organizaciones destino en bandeja de salida
https://proyectos.andes.gob.ar/browse/TOP-60
> feat(TOP): organizaciones destino en bandeja de salida

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Filtrar por texto conceptos de la HUDS.
1. se agrego un plex-text para la busqueda en los filtros hallazgos , trastornos ,productos y procedimientos
2. 
3.
> feat(huds): filtrar por texto conceptos de la HUDS

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.ts
Mostrar el telefono y direccion del paciente en internacion.
1.  Agrega los campos telefono y direccion en el mapa de camas y listado de internacion
2. 
3.
> INTERNACION - Agrega telefono y direccion en detalle de paciente

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos.component.html
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
https://proyectos.andes.gob.ar/browse/GDU-4
1. Quita event emit de onChange, que repercute en que se recarguen los items de permisos.
> GDU: quita event emit de onChange

- src/app/modules/rup/components/elementos/ultimaFecha.component.ts
- src/app/modules/rup/components/elementos/ultimaFecha.html
- src/app/modules/rup/elementos-rup.module.ts
Componete para elemento RUP última fecha de PAP, que busca la última fecha de pap cargada previamente y la muestra para que el médico pueda visualizar si corresponde que la paciente se realice un nuevo estudio o no.
1. Última Fecha (UltimaFechaComponent): este componente, similar con consulta de niño sano, busca en las prestaciones anteriores. Las diferencias son dos. La primera es que sólo busca un concepto SNOMED. La segunda es que no busca sólo en la última prestación sino que sigue buscando hasta que encuentra el último registro de dicho concepto, o que revisa todas las prestaciones. Además, calcula la diferencia de tiempo entre el día de la prestación en ejecución y la última fecha guardada. En este caso le sirve al médico para ver la última fecha en que la paciente se realizó un PAP …
> RUP-Componente-Ultima-Fecha

- src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico.component.ts
resumen-paciente: agregar gráfico de temperatura
1. Se agrega un elemento gráfico a elementosRUP para mostrar el seguimiento de la temperatura en resumen-paciente
2. 
3. 
```
{
"componente" : "GraficoLinealComponent",
"style" : {
"columnas" : 12.0,
},
"conceptos" : [
{
conceptId: '211000246108',
fsn: 'curva de temperatura corporal (elemento de registro)',
semanticTag: 'elemento de registro',
term: 'curva de temperatura corporal'
}
],
"params" : [
{
"query" : "56342008 OR 415882003 OR  386725007 OR 307047009",
"label" : "Temperatura",
"unidad" : "ºc"
}
]
}
```
> feat:(HUDS):se agrega grafico de temperatura a resumen-paciente

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Corregir error: No se están visualizando las solicitudes en la HUDS del paciente
1. Quita un ngIf de una variable que ya no existe en la visualización de solicitudes en la HUDS
2. 
3.
> fix(HUDS): Quita un control de una variable que ya existe

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
No aparece el plex-radio de diagnostico principal en ambito internacion.
> fix(rup): diagnostico principal en internacion

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.html
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/TOP-65
1. Refactor de pantalla de Nueva Solicitud en base al mockup presentado
> TOP: refactor de pantalla nueva solicitud

- src/app/core/mpi/components/paciente.component.ts
Cambios en pacientes similares
1. 
2. 
3.
> fix(mpi): fix pacientes similares

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-74
1. Arregla duplicación de carga inicial de solicitudes.
> TOP: Arregla duplicación carga inicial de solicitudes

- src/app/components/top/solicitudes/auditarSolicitud.html
Agregar un control para no permitir asignar una solicitud sin tener seleccionado un profesional
1. Se agrega un control para habilitar el botón de confirmar solo cuando ya se haya elegido un profesional
> fix(TOP): Agrega control en la selección del profesional

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
https://proyectos.andes.gob.ar/browse/TOP-52
1. Limpia la selección de organización cada vez que cambia la selección de prestación (origen o destino, según corresponda la bandeja)
> TOP: limpia organización al cambiar de prestación

- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-76
1. Nueva columna en listado de solicitudes con la fecha de registro
> TOP: nueva columna con fecha de registro

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-70
1. Busca por solicitudes por mas de una prestacion destino
> TOP: busca por mas de una prestacion destino

- src/app/core/mpi/components/busqueda-mpi.component.ts
- src/app/core/mpi/components/busqueda-mpi.html
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/MPI-205
1. Se agregaron los datos de conectacto y dirección del paciente para visualizarlo en el sidebar de mpi y punto de inicio de citas
> MPI - Visualizacion de contacto y dirección en detalles del paciente

- src/app/components/turnos/punto-inicio/activar-app.component.ts
- src/app/components/turnos/punto-inicio/activar-app.html
1. Al chequear si el email ingresado para activar la app mobile no se visualiza el badge con el resultado de esta verificación.
2. https://proyectos.andes.gob.ar/browse/MPI-204
1. Se modificó la condicion para mostrar el badge
2. Agrega chequeo del valor del campo contacto/celular.
> MPI - Fixes en activacion mobile

- src/app/components/top/solicitudes/historialSolicitud.component.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-67
1. Agrega nueva acción de devolver solicitud asignada para profesionales
> TOP: nueva acción responder para profesionales

- package-lock.json
- package.json
Actualiza version plex. que incluye mejoras de performance. 
Y se soluciona un bug en el scroll del buscador de RUP.
> feat(plex): v6.11.4

- src/app/app.component.ts
**Problema de seguridad**: Al cerrar el tab o el navegador, Google Chrome tiene una opción de restaurar Tab cerrada, la cual trae todos los datos de sesión del usuario. Como muchas maquinas nos compartidas se puede acceder a la sesión del usuario anterior. 
1. En el método onbeforeunload se borra el token de sesión.
> feat(core): delete session data before close

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/modules/mpi/components/paciente-panel.html
- src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
https://proyectos.andes.gob.ar/browse/MPI-203
1. Se agrega atributo correspondiente al numero de identificacion de un paciente (Progenitor/a) en la relación del bebe.
2. Se agrega campo numero de identificación para visualizar el dato anterior.
OBSERVACION: Chequear que en la coleccion 'parentesco' exista el doc
{
"nombre" : "tutelado",
"opuesto" : "tutor"
}
> MPI - Fix alta de bebe con progenitor/a extranjero/a

- src/app/components/top/solicitudes/solicitudes.html
hot fix asignadas sin profesional
1. hot fix asignadas sin profesional
> TOP: hot fix asignadas sin profesional

- src/app/components/auditoria/auditoria.html
- src/app/components/auditoria/auditoria.scss
- src/app/components/paciente/headerPaciente.html
- src/app/components/paciente/headerPaciente.scss
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/paciente.html
- src/app/core/mpi/components/paciente.scss
- src/app/core/mpi/components/relaciones-pacientes.component.ts
- src/app/core/mpi/components/relaciones-pacientes.html
- src/app/core/mpi/components/relaciones-pacientes.scss
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/modules/mpi/components/paciente-detalle.html
- src/app/modules/mpi/components/paciente-detalle.scss
- src/app/modules/mpi/components/paciente-listado.html
- src/app/modules/mpi/components/paciente-listado.scss
- src/app/modules/mpi/components/paciente-panel.component.ts
- src/app/modules/mpi/components/paciente-panel.html
- src/app/modules/mpi/components/paciente-panel.scss
https://github.com/andes/api/pull/1071
1. Agrega badge de estado 'fallecido' y fecha de fallecimiento en detalles del paciente, listas, otros.
2. Agrega fecha de fallecimiento a las relaciones de pacientes para vinculación con fallecidos.
> MPI - Visualización de paciente fallecido

- src/app/app.component.ts
El evento se ejecutaba en mas lugares de donde estaba planeado.
> fix(core): remove beforeupload

- src/app/apps/mitos/services/snomed.service.ts
- src/app/components/snomed/snomed-buscar.component.ts
- src/app/components/snomed/snomed-buscar.service.ts
- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
Permite buscar por descendiente dentro de RUP. [RUP-144](https://proyectos.andes.gob.ar/browse/RUP-144)
1. Aplica la expresion de descendientes de un concepto.
> feat(rup): buscador filtrar por descendientes

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
Se requiere separar los permisos de crear cama y editar cama en internación.
1. Agrega control en el componente de camas que deshabilita el botón de guardar cambios, en caso de estar editando una cama creada.
2. 
3.
> INTERNACION - Agrega control de permiso para editar camas de internacion

- src/app/app.module.ts
- src/app/components/organizacion/organizacion-sectores.component.ts
- src/app/components/organizacion/organizacion-sectores.html
- src/app/components/organizacion/organizacion.component.ts
- src/app/components/organizacion/organizacion.html
- src/app/components/organizacion/sectores-item/sectores-item.component.ts
- src/app/components/organizacion/sectores-item/sectores-item.html
- src/app/interfaces/IOrganizacion.ts
- src/app/services/organizacion.service.ts
- src/app/services/sectores.service.ts
Se requiere controlar que los sectores en las camas se actualicen al modificar un sector y al eliminar se debe controlar que no hayan camas siendo utilizadas en el mismo. https://proyectos.andes.gob.ar/browse/IN-155
1. Separa las rutas de acceso a los sectores de la organizacion.
2. Cambia la dinámica del ABM de sectores: ya no se puede hacer muchos cambios y luego guardar todo junto. Por cada accion que se hace, se guardan los cambios.
3.
> INTERNACION - Controlar las camas al editar/eliminar sector

- src/app/app.module.ts
- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/directives/snomed-link.ts
[MIT-26](https://proyectos.andes.gob.ar/browse/MIT-26)
1. Se agrega link del concepto buscado al browser de snomed.
> feat(rup): link a snomed browser en buscardor

- src/app/components/top/solicitudes/auditarSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-71
1.  Permite registar Observaciones al referir solicitud
2. 
3.
> TOP: Observaciones en referir solicitud

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/components/snomed/snomed-buscar.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
Mostrar modal de acceso a los registros HUDS en el mapa de camas. 
1. refactor del modal, llamadas a la API y demás. 
2. Queda un TOC visual por resolver en el plex-options.
> feat(mapa-camas): agrega modal acceso a registros medicos

- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
Agregar un texto sobre legales al modal HUDS.
> feat(huds): add legal warning modal

- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-82
1. Quita condición de comparación de ids de profesionales para mostrar botón devolver, de manera que sea visible para el auditor sin importar a quien esté asignada (si no es auditor, por defecto verá solo sus asignadas)
- [xx] No
> TOP: devolver asignadas para auditor

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/turnos/autocitar/autocitar.component.ts
- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/MISC-74
1. Se eliminan los llamados en los módulos correspondientes al getObraSocial.
2. Se realizan las modificaciones necesarias para mostrar los datos de las obras sociales correspondientes a cada paciente de forma correcta en base a los cambios en la api.
> Obra Social: Elimina llamadas a getObraSocial

- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
> feat(huds): modal acceso v2

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
https://proyectos.andes.gob.ar/browse/RUP-155
1. Aplicar el layout de plex en la pantalla de validación.
> RUP: elementos plex en validación

- src/app/modules/rup/components/ejecucion/help-solicitud.html
- src/environments/environment.dev.ts
En la visualización de datos de solicitud se deberían mostrar los datos de origen (prestación, organización, profesional) en caso que existan (es el caso de las que se cargan como solicitudes y luego se ejecutan)
1. Se visualizan los datos de del origen de la solicitud
2. 
3.
> fix(RUP):Visualización de datos de solicitud al ejecutar una prestación

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Refactor a componente de ingreso para descomprimir el servicio MapaCamasService
> mapa-camas: refactor ingreso 

- src/app/modules/rup/components/elementos/graficoLineal.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Filtrar por valores null antes de generar el gráfico.
1. se envía un parámetro para indicar que se filtren los null a la api
2. 
3.
> fix(rup): filtrar valores null de los graficos

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/components/organizacion/organizacion-create-update.component.ts
- src/app/components/organizacion/organizacion-create-update.html
Desde la edición de una organización es posible eliminar unidades organizativas que tiene camas activas, incluso ocupadas. Esto genera inconsistencias en la información.
1.  Se modificó el componente de ediar organización para que controle y deshabilite el boton de eliminar unidad organizativa cuando en caso de ser utilizada por alguna cama que no está inactiva.  
2. 
3.
> ORGANIZACIONES - Deshabilitar boton de eliminar UO que esta en uso en una cama

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Poder ordenar las columnas del listado del mapa de cama. Así puede decidir si quiero agrupar por sector, unidar organizativa, estados, etc. Le da más poder de decisión al usuario.
1. Permite clickear una columna y ordenar la tabla por esa columna, en orden descendente o ascendente
2. 
3.
> INTERNACION - Ordenar la tabla por columna

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/environments/environment.dev.ts
> fix(mapa-camas): no se visualiza la huds

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-80
1.  remueve condición `tieneTurno` de búsqueda de solicitudes validadas
2. Oculta badge de estado 'validado' (duplicado con ''Registro en HUDS')
3.
> TOP: remueve condición tieneTurno de búsqueda de solicitudes validadas

- src/app/core/mpi/components/datos-contacto.component.ts
- src/app/core/mpi/components/datos-contacto.html
https://proyectos.andes.gob.ar/browse/MPI-218
1. Incorpora label con dirección legal del paciente en tab 'datos de contacto'
> MPI -Muestra dirección legal del paciente

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/core/rup.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.component.ts
- src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.component.ts
- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
- src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.ts
- src/app/modules/rup/interfaces/elementoRUP.interface.ts
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
- src/app/modules/rup/services/elementosRUP.service.ts
1. Filtrar requeridos por sexo del paciente
2. Popula los requeridos a demanda.
3. Los requeridos ya no necesitan un elemento-rup obligatoriamente.
> elementos-rup: requeridos filtros por sexo

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
Estaba mal importado un modulo.
1.
> fix(mapa-camas): missing DragAndDrop service

- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
https://proyectos.andes.gob.ar/browse/MPI-201
1. Modifica tamaño de columna en archivo de actividades con la comunidad
> RUP - Modifica ancho de listado de pacientes

- src/app/core/mpi/components/busqueda-mpi.component.ts
- src/app/core/mpi/components/busqueda-mpi.html
- src/app/modules/mpi/components/paciente-buscar.component.ts
- src/app/modules/mpi/components/paciente-listado.component.ts
- src/app/modules/mpi/components/paciente-listado.html
- src/app/modules/mpi/components/paciente-panel.html
Sacar scroll infinito de paciente-listado y paciente-buscar
> MPI - fix scroll-infinito

- src/app/components/top/solicitudes/historialSolicitud.component.ts
- src/app/components/top/solicitudes/historialSolicitud.html
- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Si https://proyectos.andes.gob.ar/browse/TOP-41
1. Remueve código que arma registros de historial a partir de estados.
2. Muestra datos de destino original
> TOP: refactor historial solicitud

- src/app/components/top/solicitudes/detalleSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-84
1. cambia referencias a estadoActual
> TOP: cambia referencias a estadoActual

- package-lock.json
- package.json
- src/app/core/mpi/components/notas-paciente.html
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/MPI-226
Se requiere mostrar información de las notas destacadas en el detalle del paciente. Además, en el listado de notas de un paciente (tab notas) poder visualizar de forma más clara las notas que se destacan del resto.
1. Se agrega listado de notas destacadas en el detalle de un paciente.
2. Se cambia visualización de la nota destacada del paciente, para que resalte un poco más de las no destacadas.
> MPI: Mostrar nota destacada

- src/app/core/mpi/components/busqueda-mpi.html
https://proyectos.andes.gob.ar/browse/MPI-211
1. Agrega botón para edición de datos de un paciente junto al título del sidebar 'Detalles del paciente'
> MPI - Agrega botón 'editar datos' en sidebar

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts
- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
- src/app/components/reportesDiarios/encabezadoReportesDiarios.component.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/RUP-165
1. Cambiar en la api todas las búsquedas que se realizan por tipoPrestacion.id y reemplazarlas por conceptId
> CORE: tipoPrestacion.id por conceptId

- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
Permitir filtrar por fecha de egreso en el listado de internación.
1.  Se incorporó plex-wrapper en los filtros del listado de internacion.
2.  Se integró el filtro de "documento" y "apellido" en un solo input que puede filtrar segun documento, nombre o apellido. Esto es para disminuir un poco la cantidad de filtros y el espacio que ocupan. 
3. Se agregaron dos filtros (desde y hasta) para la fecha de egreso.
> INTERNACION - Listado de internación agrega filtros distintos para fechas de ingreso y egreso

- src/app/modules/rup/components/elementos/valorNumerico.component.ts
- src/app/modules/rup/components/elementos/valorNumerico.html
agregar required a ValorNumerico
1. se agrego required 
2. 
3.
> fix(RUP):Se agrega required a ValorNumerico

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/huds/vistaSolicitudTop.html
https://proyectos.andes.gob.ar/browse/TOP-58
1. Muestra nombre correcto de concepto de solicitud
> HUDS: Muestra nombre correcto de concepto de solicitud

- package.json
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.html
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.scss
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/iconito-cama/icono-camita.component.ts
Sacar los colores hardcodeados del componente estado de servicio en el mapa de camas.
1. Se utilizan los colores que trae el estado de la bd y se saca el hardcodeo en el css.
2. 
3.
> INTERNACION - Quita el hardcodeo de colores en el estado de servicio

- package-lock.json
- package.json
- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
Se necesita guardar una nota en los movimientos de las camas y que persista hasta que se realiza el egreso del paciente.
1. Permite agregar y editar un nota en el detalle de una cama ocupada
2. 
3.
> INTERNACION - Agregar y editar una nota en las camas ocupadas

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/components/organizacion/organizacion-create-email.component.ts
- src/app/components/organizacion/organizacion-create-email.html
- src/app/components/organizacion/organizacion-lib.module.ts
- src/app/components/organizacion/organizacion.component.ts
- src/app/components/organizacion/organizacion.html
- src/app/components/organizacion/organizacion.module.ts
- src/app/modules/rup/components/ejecucion/modal-seleccion-email.html
Configurar cuentas de email asociadas al efector
1. se crea un abm (crud) para los emails asociados al efector
2. 
3.
> feat(rup): configurar cuentas de email asociadas al efector

- package-lock.json
- package.json
- src/app/app.module.ts
Actualiza a la ultima version de plex.
1.  Botones disable se podian tocar.
2.  Se desplegaba el calendario al tabear. 
3.  Optimización de calendarios.
> chore(plex): last verion

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
- src/app/apps/gestor-usuarios/views/usuarios-list.view.html
https://proyectos.andes.gob.ar/browse/GDU-21
1. Arregla sincro de permisos y perfiles
> GDU: arregla sincro de permisos y perfiles

- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/services/paciente.service.ts
> MPI - Fix ignorar y guardar paciente

- src/app/app.routing.ts
- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/modules/estadisticas/components/home.component.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
- src/app/modules/visualizacion-informacion/components/visualizacion-informacion.component.html
- src/app/modules/visualizacion-informacion/components/visualizacion-informacion.component.ts
- src/app/modules/visualizacion-informacion/components/visualizacion-informacion.scss
- src/app/modules/visualizacion-informacion/visualizacion-informacion.module.ts
- src/app/modules/visualizacion-informacion/visualizacion-informacion.routing.ts
https://proyectos.andes.gob.ar/browse/BI-50
1. Se crea el nuevo modulo lazy loading _Visualización de información_.
2. Se modifica la verificación de permisos teniendo en cuenta las modificaciones en la base de datos.
3. Se crea el nuevo componente _bi-queries_ (queda vació para continuar trabajando) que tendrá distintas consultas de la colección _queries_.
4. Se agregan las "cajas" al inicio del nuevo modulo: _Reportes_, _Dashboard_ y _Bi-queries_ con su respectivo ruteo.
> Visualizacion-Infomacion:  Nuevo modulo para englobar la salida de informacion

- package-lock.json
- package.json
> chore(plex): @andes/plex@6.16.0

- src/app/components/auditoria/vincular-pacientes.component.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
Se realizaron dos Fix en MPI:
Nota destacada del paciente: https://proyectos.andes.gob.ar/browse/MPI-239 (1)
Auditoria
1. Se corrige un bug que hay en el detalle de paciente, que ocurre en aquellos que no tienen notas destacadas (1).
2. Se corrige otro bug en auditoría que ocurría al vincular dos pacientes sin documentos.
> MPI: Dos fixes en auditoria y en la nota de un paciente

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-228
1. El botón 'Validar Paciente' permanece habilitado en cada edición y en caso de re-validar un paciente solo se actualizan los datos de domicilio, foto y fecha de fallecimiento.
> MPI - re-validacion de pacientes

- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/modules/mpi/components/paciente-panel.component.ts
https://proyectos.andes.gob.ar/browse/MPI-212
1. Corrige visualización de fecha/hora de nacimiento que se encontraban 'desincronizadas' en distintas vistas
2. Nuevo campo en formulario de alta de bebé para ingresar hora de nacimiento
> MPI - Nuevo campo 'hora de nacimiento'

- src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
- src/app/modules/estadisticas/components/rup/rup-pacientes.html
- src/app/modules/estadisticas/components/rup/rup-pacientes.scss
https://proyectos.andes.gob.ar/browse/BI-37
1. Se modifica el llamado a _snomedService_ por el de _conceptosTurneablesService_ para que traiga todos los conceptos turneables que están en la base de datos.
2. Se corrige linteo.
3. Se agrega limite de 10 descendentes para evitar errores al hacer el llamado.
> Dashboard HUDS: mejora en filtro de prestaciones

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
El botón de cambiar unidad organizativa debería decir "Pase de unidad organizativa".
1. Renombra 'cambiar UO' a 'pase de UO'
2. 
3.
> INTERNACION - Renombra 'cambiar UO' a 'pase de UO'

- package-lock.json
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/components/puco/puco.component.ts
- src/app/components/puco/puco.html
- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/modules/estadisticas/components/citas/graficos.component.ts
- src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts
- src/app/modules/estadisticas/services/agenda.service.ts
- src/app/services/documentos.service.ts
- src/app/services/xlsx.service.ts
https://proyectos.andes.gob.ar/browse/CORE-39
1. Se elimina el uso de file-saver en descarga de censo diario/mensual
2. Se elimina el uso de file-saver en descarga de listado de internación
3. Se elimina el uso de file-saver en descarga de csv en dashboard de citas
3. Se elimina el uso de file-saver en descarga de constancia puso
4. Se actualiza la versión de @andes/shared
> CORE: eliminar el uso de file-saver y reemplazar por saveAs

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
Se requiere agregar la unidad organizativa de origen al hacer un movimiento de cambio de servicio.
1. Agrega la unidad organizativa original al extras del nuevo estado de la cama.
2. 
3.
> INTERNACION - Agrega UO origen al extra al hacer movimiento

- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
Corrige bug al borrar una ubicación de la cama.
https://dashboard.cypress.io/projects/xr7gft/runs/1008/test-results/9b36aa0b-4122-4644-a0d1-4346ed317a22
> fix(mapa-camas): handler null ubicacion

- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/directives/snomed-link.ts
- src/app/modules/rup/directives/snomed-sinonimo.ts
- src/app/modules/rup/rup.module.ts
mostrar fsn cuando no coicide con el term
1. Comparar el fsn sin semantic tags con el term. Si no coiciden mostrar en un segundo renglón el FSN. 
2. 
3.
> feat(rup): buscador, mostrar fsn cuando no coicide con el term.

- src/app/apps/gestor-usuarios/components/perfiles-detail.component.ts
- src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
https://proyectos.andes.gob.ar/browse/GDU-22
1. actualiza control de permisos de GDU a `usuarios:perfiles`
2. 
3.
> GDU: actualiza control de permisos de GDU

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Se necesita el virtual scroll en el mapa de camas ya que hay hospitales con más de 300 camas y puede tardar en cargar al seguir escalando.
1. Agrega el componente cdk vitual scroll en el mapa de camas.
2. Modifica el componente item-cama, queda como componente presentacional ya que la lógica interna del mismo interfería con el virtual scroll en la tabla.
3.
> INTERNACIÓN - Agrega virtual scroll en tabla de camas

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-79
1. En nueva solicitud, implementa directiva `tmPrestaciones` para traer solo las prestaciones de los permisos de TOP.
> TOP: nueva solicitud traer prestaciones permitidas

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-70
1. Separa la verificación de profesional y espacio físico modificando la frecuencia con que ocurren.
> CITAS - Corrige consulta repetitiva a api

- package-lock.json
- package.json
Actualiza versión de plex a 7.0.2
1. fix en herencia CSS en plex-modal que afectaba a plex-icon
> chore(plex): v7.0.2

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Error al visualizar las prestaciones de un paciente al acceder a la HUDs, se muestran datos incorrectos en la cantidad de prestaciones , no corresponde con el total contando las prestaciones CDA . 
Una ecografia no validada mostraba un error de parámetros ,fue borrada de la bd por que estaba modificada y podía listarse en prestaciones aunque no estuviera validada.
1. Se agrega parametro solicitud a CDA con el valor "ambulatorio"
2. Se borra prestacion ecografia no validada
3. Se setea la variable variable prestacionesCopia en el metodo buscarCDAPacientes para corregir el error del total de prestaciones.
> fix(HUDS):error al visualizar prestaciones de un paciente inicialmente

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.component.ts
- src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.component.ts
- src/app/modules/rup/components/elementos/deprecated/informeEpicrisis.html
- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
- src/app/modules/rup/components/elementos/rupers/seccionado/seccionado.component.ts
- src/app/modules/rup/components/elementos/rupers/texto-enriquecido/observaciones.component.ts
- src/app/modules/rup/services/ejecucion.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
Se necesitaba poder evolucionar un concepto desde las secciones.
1. Refactor del todo el sistema de ejecución de conceptos y drag and drop
> feat(rup): flujo de datos al ejecutar un concepto

- src/app/apps/rup/mapa-camas/constantes-internacion.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-destino-generico/cama-destino-generico.component.ts
Se necesita quitar "otros" de razón de alta y motivo de bloqueo.
1. Quita "otros" de razon de alta y motivo de bloqueo
2. 
3.
> INTERNACION - Quitar "otros" de razon de alta y motivo de bloqueo

- src/app/apps/auth/components/login/login.component.ts
Chequea huso horario en el login para dar mejor mensajes de error.  Se trae la funcionalidad de https://github.com/andes/app/pull/1778
> feat(core): check timezone

- src/app/components/turnos/autocitar/autocitar.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
https://proyectos.andes.gob.ar/browse/CIT-72
> ValidationError: prestacion validation failed: paciente.obraSocial: Cast to Embedded failed for value "[ { _id: '5d4980dc2b44729e784a6c35' } ]" at path "paciente.obraSocial"
> fix(citas): error obra social al autocitar

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Se desea controlar que haya un permiso para bloquear las camas en el mapa de camas.
1. Agrega controles de permiso de bloqueo para mostrar los botones de bloqueo.
2. 
3.
> INTERNACION - Controla el permiso de bloqueo de camas

- projects/shared/src/lib/components/popover-audit/popover-audit.component.ts
- src/app/app.routing.ts
- src/app/interfaces/IOrganizacion.ts
- src/app/modules/com/com.module.ts
- src/app/modules/com/com.routing.ts
- src/app/modules/com/components/adjuntos.scss
- src/app/modules/com/components/busqueda-paciente.component.ts
- src/app/modules/com/components/busqueda-paciente.html
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/historial-derivacion.component.ts
- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
- src/app/modules/com/interfaces/IDerivacion.interface.ts
- src/app/modules/com/interfaces/IDerivacionHistorial.interface.ts
- src/app/services/com/adjuntos.service.ts
- src/app/services/com/derivaciones.service.ts
- src/app/services/com/reglasDerivaciones.service.ts
https://proyectos.andes.gob.ar/browse/COM-3
https://proyectos.andes.gob.ar/browse/COM-5
1. Nuevo módulo _Centro Operativo Médico_
Crear nueva colección _reglasDerivación_ y correr:
https://gist.github.com/juuliotero/6d7a90f08269f4d650f6e79f72557875
https://gist.github.com/juuliotero/8b477da2bf01783d658ba8f06d7ca8ec
> COM: nuevo módulo centro operativo médico

- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
- src/app/services/organizacion.service.ts
Al dar de alta una cama visualizar todo el nombre del sector en el plex-select. Como ocurre al seleccionar una cama al ingresar paciente. 
1. Se obtiene la ruta completa del sector para mostrarla en el select.
2. 
3.
> INTERNACION - Agrega el nombre completo de los sectores.

- src/app/modules/rup/components/elementos/rupers/select-snomed.component.ts
https://proyectos.andes.gob.ar/browse/RUP-169
1. Permitir realizar filtros por semanticTag 
2. Cambio de ruta por la del buscador básico
> RUP: filtros por semanticTag a SelectSnomedComponent

- src/app/components/organizacion/organizacion-create-update.html
https://proyectos.andes.gob.ar/browse/TM-13
1. se suma al editor de organizaciones un switch para indicar si acepta derivaciones
> TM: configurar aceptaDerivacion en organizaciones

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-46
1. Se agrega al árbol de permisos, el nuevo _type "queries"_ para que figure en el gestor de usuarios y poder seleccionar las consultas que el usuario podrá ver y ejecutar en el _bi-queries-component_.
2. Se crea _bi-queries-component.html_ para crear filtros de entrada (_plex-select_) y filtros de salidas(_plex-bool_) de forma dinámica según la query seleccionada.
3. Se crea el _bi-queries-component_ para obtener los datos de los filtros según la query seleccionada.
> Bi-queries: Módulo para englobar todo tipo de salida de informacion 

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/punto-inicio.component.ts
https://proyectos.andes.gob.ar/browse/COM-16
1. Redirige a inicio si el usuario no tiene permisos para el módulo COM
> COM: control de permisos

- src/app/modules/com/com.module.ts
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/actualizar-estado.html
- src/app/modules/com/components/historial-derivacion.component.ts
- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-17
1. Se agrega botón de agregar notas/adjuntos
2. Se muestran en el historial las notas/adjuntos agregados sin indicar el estado
> COM: permitir sumar notas/adjuntos a estado actual

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-18
1. Las derivaciones nuevas se crean en estado _solicitada_
> COM: cambio de nombre de estado pendiente por solicitada

- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.html
https://proyectos.andes.gob.ar/browse/RUP-195
1. se redefine el método onValidate() para controlar que el archivo adjunto no sea vació.
2. se agrega un <plex-badge> para indicar que no hay archivos adjuntos seleccionados.
3.
> fix(RUP):control de requerido en atomo adjuntar documento

- projects/auth/src/lib/auth.service.ts
- projects/shared/src/lib/decorator/cache.ts
- projects/shared/src/lib/operators/cache-storage.ts
- projects/shared/src/lib/operators/index.ts
- projects/shared/src/lib/operators/not-null.ts
- projects/shared/src/lib/server/server.service.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/app.routings-guard.class.ts
- src/app/apps/auth/components/accept-disclaimer/modal-disclaimer.component.ts
- src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/services/elementosRUP.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/services/barrio.service.ts
- src/app/services/conceptos-turneables.service.ts
- src/app/services/disclaimer.service.ts
- src/app/services/localidad.service.ts
- src/app/services/obraSocial.service.ts
- src/app/services/pais.service.ts
- src/app/services/parentesco.service.ts
- src/app/services/provincia.service.ts
Mejoras de performance al reducir la cantidad de request que se hacen al backend. Todos ganan. La app más ligera, el servidor deja de contestar pequeñas request que son muchas al final del día. 
Además corrige [RUP-158](https://proyectos.andes.gob.ar/browse/RUP-158).
1. Se crea un nuevo operador RxJS que cachea la request usando sessionStorage o localStorage. Permite agregar un TTL.
2. Resuelve multiples subscripciones a un mismo observable de forma más transparente. 
3. En RUP, se estaban haciendo dos GET de HUDS iguales del mismo paciente (al ejecutar).
4. Lazy load de resumen-paciente, algunos pacientes tienen más de 500 prestaciones ya lo que generar mucho trafico y no se visualiza de primera mano (esta en una tab oculta.  Se pretende evaluar cuanto disminuye los GET con esta mejora. …
> Performance

- package-lock.json
- package.json
Actualiza PLEX a v7.2.0
https://proyectos.andes.gob.ar/browse/PLEX-144
https://proyectos.andes.gob.ar/browse/PLEX-154
1. PLEX: mejora alineamiento en plex-detail
2. PLEX: mejora visual en plex-select[multiple]
> chore(plex): v7.2.0

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
https://proyectos.andes.gob.ar/browse/UIUX-81
1. feat(panel-agenda): actualiza layout (plex-title)
2. feat(editar-agenda): se mejora layout (camba de 8 a 4 cols)
3. chore(gestor-agendas): lint y formateo
> feat(gestor-agendas): mejora interactividad al editar agendas

- src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
- src/app/components/turnos/dashboard/estadisticas-pacientes.html
https://proyectos.andes.gob.ar/browse/CIT-68
1. Quita la carga de historial de turnos inicial por defecto, y la realiza solo cuando se accede a los tabs de turno e historial.
2. Limpia código duplicado.
3. Remueve atributos `anulaciones` y `contactos`, y sus cargas. No son consumidos en la página o en ningún componente.
> CITAS: Lazy load de historial de turno + limpieza de código

- src/app/modules/com/components/punto-inicio.component.ts
Se cambian los enumerados correspondientes a los nuevos nombres de estado.
> fix(COM): Se modifican los filtros que habían quedado con los enumerados anteriores

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos.component.ts
- src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
- src/app/services/organizacion.service.ts
https://proyectos.andes.gob.ar/browse/GDU-18
1. Incluye tipo de `unidad-organizativa` en `arbol-permisos-item`
2. 
3.
> GDU: permisos unidades organizativas de internacion

- src/app/components/top/solicitudes/historialSolicitud.html
En Demo hay algunas solicitudes referidas sin prestación destino original. Se agrega este chequeo
> fix(top):agrega control en historial

- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
https://proyectos.andes.gob.ar/browse/RUP-200
1. se replica solución de SolicitudesDefualt ,con un  setTimeout se soluciona el  problema
2. 
3.
> fix(RUP): al continuar registro, la solicitud pierde el formato

- src/app/components/turnos/dar-turnos/calendario-dia.class.ts
- src/app/components/turnos/dar-turnos/calendario.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
- src/app/interfaces/turnos/IBloque.ts
https://proyectos.andes.gob.ar/browse/CIT-69
1. Verifica si un turno solicitado desde TOP pertenece a una agenda (Del dia) configurada **solo con turnos de gestion** para permitirle dar turnos.
2. Permite visualizar desde el gestor de agendas este tipo de turnos (Solo en agendas exclusivas de gestion)
> CITAS - Habilita turnos de gestion en agendas del dia

- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-22
1. Se muestran fechas en listado de derivaciones
> COM: se suma fecha de creación/actualización a listado de derivaciones

- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
https://proyectos.andes.gob.ar/browse/COM-20
1. Se limpian campos al moverse de derivación en detalle/adjuntar notas
> COM: limpiar sidebars al cambiar de derivación

- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-21
1. Permitir al com cancelar sus derivaciones solicitadas
> COM: permitir al com cancelar sus derivaciones solicitadas

- src/app/apps/rup/mapa-camas/interfaces/mapa-camas.internface.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
A demás de las columnas que se muestran ahora(fijas), poder elegir otras columnas para visualizar. Columnas extras: fecha ultimo movimiento, usuario movimiento, sector completo (arrancar de arriba a abajo así se puede sortear), Documento, Sexo
1. Agrega columnas adicionales a la tabla
2. Permite ordenar la tabla por estas columnas también
3.
> INTERNACION - Agregar o sacar columnas adicionales de la tabla

- src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.html
- src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
Se necesita visualizar el nombre del sector completo en el abm de salas comunes
1. Agrega el nombre completo de los sectores al abm de las salas.
2. 
3.
> INTERNACION - Agrega sector completo al abm de sala comun

- src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
Error de plex-select al borrar un sector.
> fix(mapa-camas): handle null al borrar sector

- src/app/modules/com/components/busqueda-paciente.html
https://proyectos.andes.gob.ar/browse/COM-23
1.Se reemplaza el componente de búsqueda de paciente por el nuevo componente de MPI
> COM: uso de componente paciente-busqueda en com

- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-26
1. Marcar derivación seleccionada en plex-list
2. Se ocultan los iconos de organizaciones al abrir el sidebar
> COM: marcar derivación seleccionada en plex-list

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
No se debería poder egresar un paciente en una fecha en la que la cama este ocupada por otro paciente.
1. Agrega control para determinar la fecha máxima de egreso según el historial de la cama.
2. 
3.
> INTERNACION - Controla la fecha de egreso con el historial de la cama

- src/app/components/carpeta-paciente/carpeta-paciente.html
https://proyectos.andes.gob.ar/browse/MISC-102
1. Refactorización del html del componente 'carpeta-paciente'.
2. Incorporación de componentes plex y redistribución de elementos.
> refactor(carpeta-paciente): incorpora componentes plex

- projects/shared/src/lib/server/error-handler.service.ts
- projects/shared/src/public-api.ts
- src/app/app.module.ts
Logguear los errores de la consola de angular.
Se busca tener una respuesta rápida a los errores por consola del navegador.
> CORE: angular handler error

- src/app/app.component.ts
Evitar que aparezcan items repetidos en el menú hamburguesa
1. Se filtran items en loop de permisos
> fix(menu): se evitan items repetidos

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
Agrega componente que se quitó por error en un refactor
1. 
2. 
3.
> Revision de agenda dinámicas

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/relaciones-pacientes.component.ts
- src/app/core/mpi/components/relaciones-pacientes.html
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-panel.component.ts
- src/app/modules/mpi/components/paciente-panel.html
- src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
https://proyectos.andes.gob.ar/browse/MPI-258
1. Modifica carga/guardado de la foto de pacientes. Reemplaza tipo string por { id, img: string }
2. Modifica directiva de carga *foto.directive*: Si el paciente tiene un objeto 'foto' que contiene un id entonces realiza la peticion a la api para traer la foto (string)
3. Los cambios efectuados implican listados de paciente, detalle, panel lateral (en edición), foto en relaciones de pacientes.
> MPI - modifica formato de foto de pacientes

- src/app/components/inicio/inicio.component.ts
1.  Soporte para links externos
> fix(inicio): soporte para links externos

- src/app/components/top/pipes/estado-solicitud.pipe.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-97
1. Se quita un control en el pipe de estado-solicitud para asignadas
2. Se arregla bug en dropdown
> TOP: arreglo de dropdown en solicitudes asignada

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
https://proyectos.andes.gob.ar/browse/COM-27
1. Al crear una nueva derivación, por defecto se selecciona el profesional logueado
> COM: seleccionar por defecto el profesional logueado

- src/app/components/top/solicitudes/busquedaPaciente.html
https://proyectos.andes.gob.ar/browse/TOP-94
1. Se usa el componente de MPI paciente-busqueda en top
> TOP: uso de componente mpi paciente-busqueda

- src/app/core/mpi/components/busqueda-mpi.component.ts
- src/app/core/mpi/components/busqueda-mpi.html
- src/app/modules/mpi/components/paciente-detalle.component.ts
https://proyectos.andes.gob.ar/browse/MPI-272
1. Agrega telefono y direccion en el array 'fields' de campos a mostrar en pacienteDetalleComponent
> MPI - Direccion y telefono por defecto en sidebar detalles

- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-79
1. incluye createdBy en detalle de agenda
2. 
3.
> CIT: incluye createdBy en detalle de agenda

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-89
1.  guarda organización al iniciar prestación
2. 
3.
> TOP: guarda organización al iniciar prestación

- package-lock.json
- package.json
Actualizar PLEX v7.2.0 => v7.3.0
1. mejora visual de plex-bool en sidebar invert
2. mejora visual de plex-item en sidebar invert
3. fix visual de botones dentro de plex-item
> chore(plex): v7.3.0

- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
En el mapa de camas cuando se hace click sobre el botón de "actualizar al presente", desaparece la fecha y hora del sidebar y el botón también.
1. Cambia la accion del boton saltar al presente que asignaba la fecha con undefined.
2. 
3.
> INTERNACION - Corrige accion saltar al presente que quitaba la fecha

- src/app/app.component.ts
Corregir items de menu por permisos
1. Comprueba que no falten ni se repitan items en el menu hamburguesa
> fix(menu): comprueba módulos con permisos múltiples

- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.scss
https://proyectos.andes.gob.ar/browse/MPI-255
1. Actualiza a componente plex-list listado de pacientes seleccionados para prestacion no nominalizada
> MPI - Pacientes agregados a prestacion no nominalizada

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-91
1. Fix en eliminar adjunto de nueva solicitud.
> TOP: fix en eliminar adjunto

- src/app/app.component.ts
- src/app/components/inicio/inicio.component.ts
- src/app/components/inicio/inicio.html
Que se vean los hints de novedades
1. Se usa un array diferente para las novedades
> fix(novedades): se separa array de novedades

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
Refactorizar html a partir de componentes plex. html compuesto por: plex-grid o plex-wrapper (según corresponda)
1. Aplica plex-wrapper en los formularios de egreso e ingreso de pacientes.
2. 
3.
> INTERNACION - Aplica plex-wrapper en form egreso e ingreso de pacientes

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Ahora que existe el flag anulada en las prestaciones, marcar como anulada la prestación de internación cuando se deshace. 
1. Anula la prestación al deshacer internación.
2. Generaliza el método invalidarPrestacion del punto-inicio hacia el service de prestaciones.
3.
> INTERNACION - Anula prestacion al deshacer internacion

- package-lock.json
- package.json
Arreglar bug en accordion (visible especialmente en gestor de usuarios)
1. Se cambio la hoja de estilos de accordion
2. Algunas mejoras visuales (efecto hover, font-size)
> chore(plex): v7.3.1

- src/app/components/top/pipes/botones.pipe.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
Agrega nuevo pipe para unificar controles en los botones de las operaciones
1. Se agrega pipe BotonesSolicitudPipe en módulo TOP
2. Se eliminan arrays de solicitudes de entrada/salida que ya no se utilizaban
3. Se modifica html con nuevas condiciones
> feat(solicitudes): agrega nuevo pipe para unificar controles 

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
https://proyectos.andes.gob.ar/browse/RUP-209
1. Se agrega control a fecha en fuera de agenda para que no se ingresen fechas futuras. 
2. 
3.
> refactor(RUP):punto-inicio,control de fecha en fuera de agenda

- src/app/components/turnos/autocitar/dinamica.component.ts
https://proyectos.andes.gob.ar/browse/RUP-207
1. se implementa un setTimeOut para dar tiempo a que se cargue toda la información necesaria  
2. 
3.
> fix(RUP):punto-inicio, erro al guardar turno

- src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.scss
https://proyectos.andes.gob.ar/browse/BI-60
1. Se agrega nueva clase y se modifica la vista del buscador de turnos y prestaciones para que cada titulo de la columna sea "clickeable"
2. Se agrega la función _sortPrestaciones_ en el _service_ que sera llamada cada vez que se modifica alguna variable de ordenamiento.
3. Se realizan las modificaciones necesarias en el component, tanto en la funcion _mostrarPrestaciones_( Al seleccionar una ) como en _busquedaPrestacion_
No se permite el ordenamiento de la columna "Financiador" ya que los datos vienen en distinto formato según la prestación.  Luego de un refactor se puede agregar.
> Turnos-Prestaciones: Ordenar columnas en el buscador de turnos y prestaciones

- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
- src/app/modules/rup/services/prestaciones.service.ts
[IN-176](https://proyectos.andes.gob.ar/browse/IN-176)
Enlace entre el ID de internación y las prestaciones creadas.
También empiezo a crear una colleccion con el resumen de la internación.
> feat(mapa-camas): trackId en prestaciones

- src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.html
- src/app/components/prestamosHC/prestamos-hc.component.html
- src/app/components/top/solicitudes/busquedaPaciente.html
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/turnos/autocitar/dinamica.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/core/mpi/components/busqueda-mpi.html
- src/app/core/mpi/components/paciente.html
- src/app/core/mpi/components/relaciones-pacientes.component.ts
- src/app/core/mpi/components/relaciones-pacientes.html
- src/app/modules/auditoria/component/vincular-pacientes.html
- src/app/modules/com/components/busqueda-paciente.html
- src/app/modules/com/components/punto-inicio.html
- src/app/modules/mpi/components/paciente-busqueda.component.ts
- src/app/modules/mpi/components/paciente-busqueda.html
- src/app/modules/mpi/components/paciente-busqueda.scss
- src/app/modules/mpi/components/paciente-listado.component.ts
- src/app/modules/mpi/components/paciente-listado.html
- src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.html
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
- src/app/modules/rup/components/internacion/puntoInicio-internacion.html
https://proyectos.andes.gob.ar/browse/MPI-271
1. Se agrega contendedor con altura fija al listado de pacientes
2. Se utiliza la modificacion anterior para corregir el doble scroll generado en agregarPacienteComponent
> Mpi - Contenedor de altura fija para evitar doble scroll

- projects/shared/src/lib/pipes/edad.pipe.ts
https://proyectos.andes.gob.ar/browse/MPI-265
1. Contempla fecha de nacimiento para calcular la edad del paciente
2. Si el paciente tiene horas de edad, tambien muestra los minutos
> MPI - Agrega funcionalidad a pipe edad

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/interfaces/IDerivacion.interface.ts
https://proyectos.andes.gob.ar/browse/COM-28
1. Guardar obra social del paciente al crear derivación
> COM: guardar obra social del paciente

- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-29
1. Cambio en llamada a derivaciones en punto de inicio
> COM: cambio en llamado a derivaciónes en listado

- src/app/modules/com/components/historial-derivacion.component.ts
- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/interfaces/IDerivacionHistorial.interface.ts
https://proyectos.andes.gob.ar/browse/COM-24
1. Permitir eliminar notas generadas por el usuario logueado
> COM: permitir eliminar notas generadas por el usuario logueado

- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
https://proyectos.andes.gob.ar/browse/COM-30
1. Uso del componente pacienteDetalle en sidebar de detalle derivación
> COM: uso de componente paciente-detalle

- src/app/components/turnos/punto-inicio/activar-app.component.ts
- src/app/components/turnos/punto-inicio/activar-app.html
- src/app/core/mpi/components/datos-contacto.html
- src/app/modules/mpi/components/paciente-buscar.component.ts
https://proyectos.andes.gob.ar/browse/MPI-266
https://proyectos.andes.gob.ar/browse/MPI-270
1. Re-estructura template de datosContactoComponent para mostrar dos columnas si el usuario tiene usuario ANDES (app-mobile)
2. Corrige bug agregando primer contacto en donde se almacenaba el tipo como un objeto
3. Corrige bug de búsqueda 'vacia'
> MPI - re-ordenamiento campos telefono/usuario ANDES

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-278
1. Actualiza los datos del paciente recién validado cuando este ya existe
> MPI - Fix validación de paciente existente sin dirección/contacto

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/RUP-188
1. se agrega arrastrar a los conceptos de la huds (trastornos)
2. 
3.
> refactor(RUP): arrastrar conceptos de la HUDS (trastornos)

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/RUP-193
1. Registra el acceso a la huds del paciente sólo si la prestación pudo ser iniciada.
> RUP - Inicio de prestación para turno con múltiples profesionales

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.ts
- src/app/modules/rup/operators/populate-relaciones.ts
- src/app/modules/rup/services/ejecucion.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/pipes/relacionRUP.pipe.ts
https://proyectos.andes.gob.ar/browse/RUP-199
1. Se guarda solo el id del registro con el que esta relacionado y el termino del concepto.
2. 
3.
> fix(RUP): relaciones no se guarda como ID

- src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
- src/app/modules/estadisticas/components/rup/rup-pacientes.html
1. Si son mas de 10 las prestaciones hijas, se setea como hija la prestacion padre para ver correctamente los datos.
2. Se Modifica el encabezado de la tabla para que se distinga el botón filtrar y se agrega un title.
> DASHBOARD: Totalizado por rango etario

- src/app/components/top/solicitudes/auditarSolicitud.html
- src/app/components/top/solicitudes/detalleSolicitud.component.ts
- src/app/components/top/solicitudes/detalleSolicitud.html
- src/app/components/top/solicitudes/historialSolicitud.html
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-90
1. Se muestra en un tab el historial en el detalle de solicitud
> TOP: tab para historial en detalle

- src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-listado.html
IntersectionObserverApi es una funcionalidad de los navegadores que te notifican cuando un elemento es visible en la pantalla o no. De esta forma las imágenes se pueden cargar de forma lazy cuando se están por mostrar. De lo contrario no se descargar. 
**Motivación**: probar la funcionalidad y de paso bajar un poquito más el consumo de la foto (otra vez).
> feat(mpi): IntersectionObserverApi foto paciente

- src/app/components/top/solicitudes/detalleSolicitud.component.ts
- src/app/components/top/solicitudes/detalleSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-92
1. Se agrega el componente pacienteDetalle al detalle de solicitud en TOP
2. Se modifican top.routing y top.module para importar todo en module
> TOP: se agrega paciente-detalle al detalle de solicitud

- src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts
- src/app/modules/rup/services/conceptObserver.service.ts
- src/app/modules/rup/services/plantillas.service.ts
Intentando resolver este error con los observable de RUP.
```
RangeError: Maximum call stack size exceeded
at c.__tryOrUnsub (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:241592)
at c.next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:240699)
at u._next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:239870)
at u.next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:239644)
at r._next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:2081351)
at r.next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:239644)
at o.next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:1360699)
at o.next (https://app.andes.gob.ar/main-es2015.6f45077c012162897a25.js:1:100626)
at o.notify …
```
> feat(rup): complete Subject before delete

- src/app/modules/rup/components/elementos/evolucionProblemaDefault.component.ts
https://proyectos.andes.gob.ar/browse/RUP-208
1. Se agrega un control para corregir el error.
2. 
3.
> fix(RUP): elmentos-rup , error en fecha (trastorno)

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Se han duplicado los movimientos de ingreso y egreso de una paciente. Es necesario bloquear el boton de guardar y/o agregar un control porque, en el caso del ingreso duplicado, por ejemplo, luego no permite egresar al paciente.
1. Agrega control para deshabilitar el boton de guardar movimiento
2. 
3.
> INTERNACION - deshabilita el boton para evitar el doble click en movimientos

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
https://proyectos.andes.gob.ar/browse/RUP-215
1. no se muestra en los resultados el tipo de la prestación sobre la que estoy trabajando .
2. 
3.
> refactor(RUP):que el tipo de prestación no pueda ser buscado

- src/app/components/inicio/inicio.component.ts
- src/app/components/inicio/inicio.html
- src/app/components/inicio/inicio.scss
- src/environments/environment.dev.ts
[![Documento de percepciones de usuarios !](https://img.shields.io/badge/Documento-UI%2FUX-sucess)](https://docs.google.com/document/d/1bjPlJzfI28g-rii56U5B5AtVGoQB3VBKfpx3miZIppE/edit)
1. Se incrementó cuerpo tipográfico de algunos títulos y descripciones
2. Se agrandaron las cajas contenedoras de submódulos
3. Se agregó nombre del efector junto al nombre del usuario
4. Mejoras en la versión mobile
**Desktop**
**Mobile**
> Punto Inicio Andes revisión 1

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-274
1. Borra pacientes candidatos cuando se deshace una validación
2. Corrige restauración de otros datos del paciente al deshacer validación
> MPI - Fix restaurar datos deshaciendo validacion

- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
https://proyectos.andes.gob.ar/browse/RUP-214
1. se agrega hallazgo y trastorno la opción de mandar email para notificar a los servicios que deben enterarse de la detección de alguna patología en particular
2. 
3.
> refactor(RUP): enviar por email hallazgo/trastorno

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-98
1. Remueve referidas de la búsqueda de solicitudes de entrada
> TOP: remueve referidas de búsqueda de entrada

- src/app/components/turnos/dashboard/estadisticas-pacientes.html
https://proyectos.andes.gob.ar/browse/CIT-76
1. incluye bagde fuera de agenda en histórico de citas
2. 
3.
> CIT: bagde fuera de agenda

- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/COM-31
1. Se agrega la impresión de comprobante para derivaciones finalizadas
> COM: impresión de comprobante

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.html
https://proyectos.andes.gob.ar/browse/RUP-216
1. se agrega un control para diferenciar si requiere diagnostico principal .
2.
3.
> fix(RUP):vista-prestacion,se visualizan mal las relaciones y diagnostico

- package-lock.json
- package.json
1. fix(plex-grid): realiza ajuste en el height de las celdas nivelando los altos.
2. feat(plex-card): extiende el tipo de elementos que acepta el componente.
3. feat(plex-layout): permite expandir/contraer el sidebar.
**Update 17/11/20**
**Fixes**
1. fix(plex-layout): restringe animation solo a paneles expansibles.
2. fix(plex-card):  reordena contenido y agrega margenes.
**Feat**
1. feat(aligned): agrega directiva de alineamiento vertical.
2. feat(case): agrega directiva case
3. feat(responsive): tests header y nav principal
> chore(plex): actualiza plex a v7.5.0

- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
- projects/shared/src/lib/shared.module.ts
- projects/shared/src/public-api.ts
- src/app/components/top/solicitudes/anularSolicitud.component.ts
- src/app/components/top/solicitudes/auditarSolicitud.component.ts
- src/app/components/top/solicitudes/detalleSolicitud.component.ts
- src/app/components/top/solicitudes/detalleSolicitud.html
- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/components/top/solicitudes/formNuevaSolicitud.html
- src/app/components/top/solicitudes/prestacionSolicitud.component.ts
- src/app/components/top/top.module.ts
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/historial-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
- src/app/modules/rup/services/adjuntos.service.ts
- src/environments/environment.dev.ts
https://proyectos.andes.gob.ar/browse/PLEX-180
**IMPORTANTE:** Este PR necesita la última versión de Plex (v7.5.0)
1. Se crea el componente `<shared-galeria-archivos>`
2. Se refactoriza galería de adjuntos al crear nueva solicitud (TOP)
> feat(shared): crea componente shared-galeria-archivos

- src/app/app.component.ts
- src/app/app.routing.ts
- src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Desharcodear el ámbito 'internacion' del mapa de camas.
1. Cambia las rutas del mapa de camas para que el ámbito pueda variar.
2. Se toma el ámbito de la ruta y lo setea en el servicio del mapa de camas, el resto de los componentes lo consumen de ahí.
3. 
En la colección de modulos hay que cambiar el acceso del mapa de camas de `internacion/mapa-camas` a `mapa-camas/internacion` (propiedad **linkAcceso**)
> INTERNACION - Cambia ruteo del mapa de camas para adaptar el ambito

- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-33
1. Scroll infinito en listado de derivaciónes en COM
> COM: scroll infinito en punto de inicio

- src/app/components/profesional/profesional-create-update.component.ts
Se agrega un control sobre la foto para los casos en que la validación no retorne foto del profesional.
1. Se agrega un control para los casos en que la validación no retorne la foto del profesional validado, por ejemplo cuando solo se valida por Sisa ya que renaper no está disponible.
2. 
3.
> profesionales: se agrega control al validar un profesional

- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/components/paciente.scss
https://proyectos.andes.gob.ar/browse/MPI-240
1. Agrega estilos a clase 'loadMode' para deshabilitar interacción con usuario durante el proceso de validación
> MPI - Deshabilitar campos durante validación

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
Después de egresar un paciente desde el mapa de cama, al buscar la internación en el listado de internación no te muestra los datos de egreso que se cargaron en la primer etapa.
1. Asigna la fecha correcta al editar un egreso en el listado de internacion.
2. 
3.
> INTERNACION - Muestra la fecha correcta al editar egreso en el listado de internacion

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/apps/rup/mapa-camas/views/sala-comun/sala-comun.component.ts
Actualmente los permisos son de esta forma:  "internacion:ingreso" deberian ser todos así: `${ambito}:ingreso`. Propongo crear un servicio internmedios donde se hagan estos calculos.
1. Agrega servicio de permisos para manejar los permisos del mapa de camas.
2. 
3.
> INTERNACION - Deshardcodear los permisos

- package-lock.json
- package.json
Actualiza a plex 7.6.0
https://github.com/andes/plex/releases/tag/v7.6.0
> chore(plex):  v7.6.0

- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
https://proyectos.andes.gob.ar/browse/CIT-84
1. https://proyectos.andes.gob.ar/browse/CIT-84
2. 
3.
> CIT: Cannot read property nombre of undefined at showArancelamiento

- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
- src/app/modules/com/interfaces/IDerivacion.interface.ts
https://proyectos.andes.gob.ar/browse/COM-38
1. Cambio de palabra gravedad por prioridad
> COM: cambio de palabra gravedad por prioridad

- src/app/apps/rup/mapa-camas/sidebar/cama-destino-generico/cama-destino-generico.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined. TypeError: Cannot read property 'unsubscribe' of undefined at r.ngOnDestroy (https://app.andes.gob.ar/main-es2015.38440742c3318cc2e0b0.js:1:820610).
1. Controla si existe una subsripcion antes de hacer el unsubscribe
2. 
3.
> INTERNACION - Controla las subscripciones en los ngOnDestroy

- src/app/modules/com/components/historial-derivacion.html
https://proyectos.andes.gob.ar/browse/COM-32
1. Se modifica el historial de las derivaciones para que usen plex-accordion
> COM: refactor de historial

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
> fix(mapa-camas): no se ve el boton de censo

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
https://proyectos.andes.gob.ar/browse/CIT-73
1. Se pone en 0 skip y en false el scrollEnd para que siga funcionando el scroll infinito al actualizar el estado de una agenda
> CIT - scroll infinito al actualizar estado de agenda

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Bug: TypeError: Cannot read property 'getTime' of null at r.project (https://app.andes.gob.ar/11-es2015.e56311195d1b4313e3de.js:1:73709)
1. Agrega un control para asegurar que la fecha desde esté inicializada.
2. 
3.
> INTERNACION - Controla que la fecha desde esté inicializada

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/punto-inicio.component.ts
https://proyectos.andes.gob.ar/browse/COM-40
1. Evitar cargar una nueva derivación si ya existe una en curso para el paciente
> COM: evitar cargar derivaciones si hay otra en curso para el paciente

- package-lock.json
- package.json
- projects/shared/src/lib/pipes/edad.pipe.ts
- projects/shared/src/public-api.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/core/rup.html
- src/app/modules/rup/components/elementos/moleculaBase.component.ts
- src/app/modules/rup/components/elementos/peso.component.ts
- src/app/modules/rup/components/elementos/rupers/check-list/checklist.component.ts
- src/app/modules/rup/components/elementos/rupers/select-base.component.html
- src/app/modules/rup/components/elementos/rupers/select-base.component.ts
- src/app/modules/rup/components/elementos/valorNumerico.component.ts
- src/app/modules/rup/components/elementos/valorNumerico.html
- src/app/modules/rup/interfaces/elementoRUP.interface.ts
- src/app/modules/rup/services/elementosRUP.service.ts
Agrega reglas dinamicas en Elementos RUP para validar, e interactuar entre elementos.
> feat(elementos-rup): add rules

- src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
- src/app/modules/estadisticas/components/rup/rup-pacientes.html
https://proyectos.andes.gob.ar/browse/MISC-113
1. Se agrega condicional por el bug en el que se hayan guardado relaciones null.
2. Se obtienen las prestaciones dentro del ngOnInit() por error encontrado al ir y volver del componente.
> DASHBOARD: Error al filtrar por una prestacion

- src/app/app.module.ts
- src/app/components/carpeta-paciente/carpeta-paciente.component.ts
- src/app/components/prestamosHC/historial/historial-hc.component.ts
- src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
- src/app/core/mpi/services/carpeta-paciente.service.ts
- src/app/core/mpi/services/paciente.service.ts
https://proyectos.andes.gob.ar/browse/MPI-301
1. Se crea nuevo servicio para carpeta de paciente con funciones que anteriormente se encontraban en servicio de paciente
2. Se eliminan funciones en desuso del servicio de paciente: 'getConsultas' y 'getTemporales'
> MPI - Nuevo servicio para carpeta de paciente

- src/app/modules/rup/components/core/_rup.scss
- src/app/modules/rup/components/huds/vistaContextoPrestacion.html
- src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
https://proyectos.andes.gob.ar/browse/HUDS-31
1. se agrega funcionalidad para poder abrir los registros de una prestación. 
2. también se agrega link para abrir la prestación desde los registros
3.
> refactor(HUDS):registros, agregar links a otros registros y a prestacion

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/paciente.component.ts
> MPI - permite dni con 5 digitos

- src/app/components/profesional/profesional-create-update.component.ts
https://proyectos.andes.gob.ar/browse/MPI-302
1. Adaptacion de código por cambio de respuesta de paquete de FA
> TM - Modifica response en validación por FA

- src/app/modules/auditoria/auditoria.module.ts
- src/app/modules/auditoria/component/auditoria-listado.component.ts
- src/app/modules/auditoria/component/auditoria-listado.html
- src/app/modules/auditoria/component/auditoria.component.ts
- src/app/modules/auditoria/component/auditoria.html
- src/app/modules/auditoria/component/modal-correccion-paciente.component.ts
- src/app/modules/auditoria/component/modal-correccion-paciente.html
- src/app/modules/auditoria/component/reporte-errores.component.ts
- src/app/modules/auditoria/component/reporte-errores.html
https://proyectos.andes.gob.ar/browse/MPI-115
1. Agrega detalles al listado de reportes de error (Y sidebar) desde logs de reportes guardados en logPaciente
2. Nuevo componente para reporte de errores
> MPI - Visualizacion datos reporte de error

- src/app/core/mpi/components/relaciones-pacientes.component.ts
- src/app/core/mpi/components/relaciones-pacientes.html
Editando una relación ya existente, se puede borrar el select que asigna parentesco y guardar el paciente al que se le esta editando las relaciones.
1. Se crea una copia de la relación al momento de editar, si la edición fue completada se reemplaza la relación original por esta
> MPI - Corrige guardado de relación sin parentesco (editando)

- projects/shared/src/lib/shared.module.ts
- src/app/app.module.ts
- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/actualizar-estado.html
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/historial-derivacion.component.ts
- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
- src/app/shared/components/upload-file.component.ts
https://proyectos.andes.gob.ar/browse/COM-43
https://proyectos.andes.gob.ar/browse/COM-42
https://proyectos.andes.gob.ar/browse/COM-45
1. Reemplazo de visualizador por shared-galería de archivos en COM
2. Almacenamiento de archivos con andesDrive
3. Sumar módulo al UploadFileComponent
> COM: refactor de archivos con andesDrive y shared-galeria-archivos

- package-lock.json
- package.json
**Bug Fixes**
**plex-grid:** corrige valores cols fijas https://proyectos.andes.gob.ar/browse/PLEX-199
**plex-text:** mejora visualización invert https://proyectos.andes.gob.ar/browse/PLEX-195
**Features**
**plex-grid:** extiende sizes y agrega noGap https://proyectos.andes.gob.ar/browse/PLEX-142
**plex-label:** permite caracteres en lugar de icono https://proyectos.andes.gob.ar/browse/PLEX-181
**wrapper:** agrega input activeFilters https://proyectos.andes.gob.ar/browse/PLEX-162
**wrapper:** cambia evento y agrega animacion
> chore(plex): actualiza a v7.9.0

- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
Un error muy recurrente en la api "TypeError: Cannot read property 'term' of undefined" en el componente de informe-censo. A partir de este error se descubrió que el botón de descarga de censo está habilitado siempre, sin haber generado un censo previamente. Entonces el usuario puede descargar un censo sin unidad organizativa y sin datos de censo lo cual produce errores al generar dicho informe.
1. Deshabilita el botón de descarga de censo si el usuario no generó el censo.
2. 
3.
> INTERNACION - Controla que se haya generado el censo para poder descargarlo

- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
- src/app/components/turnos/punto-inicio/turnos-paciente.html
https://proyectos.andes.gob.ar/browse/CIT-89
1. Se cambió la condición de if ya que cuando el paciente no tiene obra social turno.obraSocial no existe en el turno
> fix(CITAS): poder seleccionar prepaga cuando el paciente no tiene obra social

- src/app/modules/auditoria/component/auditoria.html
- src/app/modules/auditoria/component/modal-correccion-paciente.component.ts
- src/app/modules/auditoria/component/modal-correccion-paciente.html
Tests fallidos: https://dashboard.cypress.io/projects/xr7gft/runs/1987/test-results
1. Corrige referencias de objetos paciente donde se realizaban las modificaciones
> MPI - Corrección de datos de un paciente en modal

- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
- src/app/components/turnos/gestor-agendas/turnos.html
- src/app/utils/enumerados.ts
https://proyectos.andes.gob.ar/browse/CIT-67
https://proyectos.andes.gob.ar/browse/CIT-91
https://proyectos.andes.gob.ar/browse/TOP-100
1.  Registra motivo liberación turno
2. Incluye nuevas opciones de motivo de liberación de turno
> CIT: registrar motivo liberación turno

- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-94
1. Muestra espacio físico de la agenda en dación de turno 
2. 
3.
> feat(CIT): mostrar espacio fisico dacion turno

- package-lock.json
- src/app/modules/com/com.module.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
- src/app/modules/com/components/punto-inicio.scss
- src/app/modules/com/services/punto-inicio.service.ts
https://proyectos.andes.gob.ar/browse/COM-37
1. En el listado de derivaciones, permitir ordenar por cualquier columna.
> COM: Ordenar listado por columnas

- src/app/modules/rup/components/elementos/adjuntarDocumento.html
- src/app/modules/rup/components/huds/vistaProcedimiento.html
- src/app/modules/rup/components/huds/vistaProcedimiento.ts
- src/app/modules/rup/components/huds/vistaRegistro.html
- src/app/modules/rup/components/huds/vistaRegistro.ts
https://proyectos.andes.gob.ar/browse/HUDS-32
1. se agrega funcionalidad para ver los archivos adjuntos si esta relacionado.
2. 
3. 
X
> feat(HUDS): registros, mostrar adjuntos si esta relacionado

- src/app/components/top/pipes/auditorias-solicitud.pipe.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
https://proyectos.andes.gob.ar/browse/TOP-101
1. Agrega contador de movimientos de auditoria de solicitud
2. 
3.
> feat(TOP): mostrar cantidad auditoria

- src/app/apps/gestor-usuarios/views/usuarios-list.view.html
- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
https://proyectos.andes.gob.ar/browse/GDU-27
1. Cambio de algunos elementos por componentes plex
2. Mejora de feedback al usuario
> GDU: feedback al usuario cuando no encuentra resultados

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/vacunas.component.ts
- src/app/modules/rup/components/elementos/vacunas.html
- src/app/modules/rup/elementos-rup.module.ts
- src/app/services/vacunas.service.ts
Realizar el registro en rup de las vacunas según formulario de nomivac.
[https://proyectos.andes.gob.ar/browse/RUP-229](https://proyectos.andes.gob.ar/browse/RUP-229)
1. Se agrega componente RUP para el registro de la vacuna covid
2. 
3.
> feat(RUP): Agregar registro de vacuna covid

- package-lock.json
- package.json
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/integridad/detalle/detalle-integridad.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Se saltan los controles de fecha al egreso: quitar debounce y agregar disable al botón.
1. Se agregan controles manuales al modificar la fecha de egreso.
2. 
3.
> INTERNACION - Controla manualmente la fecha de egreso ingresada

- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/components/top/solicitudes/formNuevaSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-102
1. Modificar la carga de archivos en TOP para que usen AndesDrive
> TOP: subir archivos a andesDrive

- src/app/core/mpi/components/paciente.component.ts
Se obtiene el número de trámite del dni al validar un paciente.
Se guarda o actualizan los datos en el array de identificadores con los obtenido de FA
https://proyectos.andes.gob.ar/browse/MPI-310
1. Se guarda el número de trámite del dni al validar un paciente
2. Se agrega el contenido del scan del paciente
> MPI: Se obtiene el número de trámite de dni del paciente

- src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/elementos/deprecated/elementoDeRegistro.component.ts
- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.ts
- src/app/modules/rup/services/elementosRUP.service.ts
- src/app/modules/rup/services/plantillas.service.ts
Permite cargar plantillas desde una molecula.
> feat(rup): plantillas moleculas

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- Agrega un filtro para poder iniciar derivaciones nuevas, filtrando aquellas que fueron iniciadas y canceladas por el usuario.
Si una derivación fue cancelada, al querer gestionar una nueva para ese mismo paciente daba error diciendo que ya existía una derivación en curso.
> fix(com): Filtra las derivaciones canceladas

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
- src/app/apps/mitos/directives/select-expression/select-expression.directive.ts
- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
- src/app/components/turnos/punto-inicio/turnos-paciente.html
- src/app/modules/auditoria/component/auditoria.component.ts
- src/app/modules/auditoria/component/reporte-errores.component.ts
- src/app/modules/rup/components/elementos/autocitado.html
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
- src/app/modules/rup/components/elementos/talla.html
- src/app/modules/rup/components/elementos/temperatura.html
- tsconfig.json
Mágicamente se acomodaron los astro y funciona la compilación con IVY. Después de esto podemos actualizar a Angular 11.
> feat(chore): activa ivy

- src/app/modules/rup/components/elementos/vacunas.component.ts
Agregar control que verifique si el paciente no tiene cargada ninguna dosis y en ese caso solo muestre la primera dosis para cargar.
1. Control en loadDosis()
> feat(vacunacion): agrega control en dosis

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Por un acento no se estaban mapeando las situaciones.
> fix(rup): mapeo situaciones

- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/actualizar-estado.html
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/historial-derivacion.component.ts
- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-49
1. Permite a los usuarios del COM modificar la prioridad actual de la derivación
2. Registro del cambio en el historial de la derivación
> COM: permitir modificar la prioridad

- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/services/com/derivaciones.service.ts
https://proyectos.andes.gob.ar/browse/COM-50
1. Se actualiza la derivación antes de guardar cambios para evitar pisar datos
> COM: arreglo al actualizar datos simultaneamente

- package-lock.json
- package.json
Actualiza plex a la ultima version para hotfixear el gestor de usuario.
> chore(plex): v7.11

- src/app/apps/mitos/directives/select-expression/select-expression.directive.ts
- src/app/modules/rup/components/elementos/rupers/check-list/checklist.component.ts
- src/app/modules/rup/components/elementos/rupers/check-list/checklist.html
- src/app/modules/rup/elementos-rup.module.ts
- src/styles.scss
https://proyectos.andes.gob.ar/browse/RUP-233
Poder elegir otros conceptos, además de los sugeridos por el checklist. 
La idea es que se pueda sumar otros hallazgos en ESAVI (mutaciones de la vacuna COVID).
Ejemplo de elemento rup: 
```
{
"_id" : ObjectId("5fecbc347f2eee4812ad22f1"),
"defaultFor" : [],
"requiereDiagnosticoPrincipal" : true,
"permiteRepetidos" : false,
"rules" : [],
"nombre" : "covid ESAVI",
"componente" : "ChecklistComponent",
{
"_id" : ObjectId("5fecbc347f2eee4812ad22f2"),
"conceptId" : "1901000246102",
"term" : "descripción de ESAVI local",
"fsn" : "descripción de ESAVI local (elemento de registro)",
"semanticTag" : "elemento de registro"
}
],
"params" : { …
```
> feat(rup): opción otros para checklist

- src/app/components/organizacion/organizacion-create-update.component.ts
Muestra toast de existo al sincronizar una organización con SISA
1. Muestra toast de existo al sincronizar una organización con SISA
2. 
3.
> TM: toast success en sincro sisa de organizacion

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Deshabilita el boton de confirmar hasta que no se realizaron los controles pertinentes.
> feat(mapa-camas): control request en ingresos

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.html
- src/app/shared/components/upload-file.component.ts
Cambia donde se guardan los adjuntos de RUP.  De RUPStore a Andes Drive.
> feat(rup): cambia a drive los archivos adjuntos

- src/app/modules/rup/components/elementos/vacunas.component.ts
Modifica la diferencia entre fecha actual de prestación y la aplicación de dosis 
1. 
2. 
3.
> fix(rup):  modifica diferencia entre fechas

- src/app/modules/rup/components/elementos/vacunas.component.ts
Quita load de esquemas, vacunas y dosis, para solucionar el incidente de la selección de la dosis
1. 
2. 
3.
> fix(rup): quita loads de esquemas y vacunas

- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-81
1. Se muestra el usuarioDacion de turnos en revisión de agenda
> CITAS: mostrar quien da el turno en revisión de agenda

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.html
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Funcionalidad para prestar/devolver camas sin tener que editar.
> feat(mapa-camas): agrega operacion para prestar y devolver camas

- package-lock.json
- package.json
- projects/shared/src/lib/server/resource-base.ts
- src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
- src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso-dinamico/ingreso-dinamico.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Se agrega a la capa estadística, un listado de movimientos de la capa medica.
> mapa-camas: historial movimientos capa medica

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/paciente.html
- src/app/core/mpi/components/relaciones-pacientes.component.ts
- src/app/core/mpi/components/relaciones-pacientes.html
- src/app/core/mpi/services/paciente-buscar.service.ts
- src/app/core/mpi/services/paciente.service.ts
- src/app/modules/auditoria/component/auditoria.component.ts
- src/app/modules/auditoria/component/reporte-errores.component.ts
- src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
- src/app/modules/mpi/interfaces/IPacienteMatch.inteface.ts
- src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
https://proyectos.andes.gob.ar/browse/MPI-308
1. Actualiza servicio apuntando a api nueva
2. Corrige bug en relaciones de paciente
3. Actualiza interfaces
> MPI - Adaptacion a rutas de core-v2/mpi

- src/app/shared/components/upload-file.component.ts
https://proyectos.andes.gob.ar/browse/CORE-59
1. Conversión a minúsculas al verificar si se encuentra entre las extensiones válidas
> CORE - Carga de archivos con extensión en mayúscula

- src/app/core/mpi/components/paciente.component.ts
Mejorar tiempo en verificación de paciente existente
1. Reemplaza match por get
> MPI - Reemplaza busqueda match por get

- src/app/core/mpi/components/paciente.component.ts
Corrige asignacion de fotoId al obtenerlo de la validacion, ya que cuando se da de alta un paciente no se está guardando ese dato. 
1. 
2. 
3.
> Corrige asignacion de fotoId al obtenerlo de la validacion

- src/app/components/turnos/autocitar/dinamica.component.ts
- src/app/services/turnos/turno.service.ts
https://proyectos.andes.gob.ar/browse/CIT-104
1. Se modificó servicio de turno para que 'saveDinamica' retorne turno en lugar de agenda
2. Uso de funciones rxjs en funcion 'guardarDatosTurno'
> CITAS - Fix solapamiento de turnos en agendas dinámicas

- package-lock.json
- package.json
https://proyectos.andes.gob.ar/browse/PLEX-218
https://proyectos.andes.gob.ar/browse/PLEX-219
1. **Classes:** agrega clase global disabled
> Crea clase que visualmente deshabilita componentes PLEX
2. **plex-card:** permite custom colors
> Posibilita customizar los colores del background de las plex-cards
3. **plex-grid:** extiende encolumnado y spanDirective
> Se extiende encolumnado a 12 columnas (grid-template-columns). Se extienden valores de directiva Span a 12 (grid-column).
> chore(plex): actualiza plex a v7.13.0

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/HUDS-33
1. Se agrega el filtro de organizaciones para la busqueda.
2. 
3.
> refactor(HUDS): se agrega filtro organizaciones

- package-lock.json
- package.json
- src/app/interfaces/IOrganizacion.ts
- src/app/interfaces/ITipoTraslado.ts
- src/app/modules/com/com.module.ts
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
- src/app/modules/com/components/tipo-traslado/tipo-traslado.html
- src/app/modules/com/components/tipo-traslado/tipo-traslado.ts
- src/app/services/com/derivaciones.service.ts
- src/app/services/com/tipoTraslados.service.ts
https://proyectos.andes.gob.ar/browse/COM-53
https://proyectos.andes.gob.ar/browse/COM-56
https://proyectos.andes.gob.ar/browse/COM-57
1. Incluye combo de tipo de traslado en nueva derivación.
2. Si la organización realiza traslados especiales, desde el COM visualiza las derivaciones que requieren traslados especiales.
3. Las derivaciones filtradas, pueden ser "actualizadas", registrar observaciones.
> feat(COM): incluye traslados especiales

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/interfaces/turnos/IAgenda.ts
- src/app/services/turnos/agenda.service.ts
https://proyectos.andes.gob.ar/browse/CIT-88
1. Nuevo bool para activar/desactivar envío de sms de la agenda
2. Uso de plex-title en pantalla de planificación de agendas
> CITAS - Activar/desactivar envío de sms de una agenda

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/TOP-104
1.
> TOP - Permite modificar profesional al dar turno

- src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
- src/app/components/top/solicitudes/busquedaPaciente.component.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/turnos/autocitar/dinamica.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/services/paciente.service.ts
- src/app/modules/com/components/busqueda-paciente.component.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.component.ts
- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
https://proyectos.andes.gob.ar/browse/MPI-324
1. Se agrega un cartel invasivo en caso de haber seleccionado un paciente fallecido al momento de dar un turno o iniciar una prestación.
> CITAS/RUP/TOP/COM - Aviso ante selección de paciente fallecido

- src/app/modules/rup/components/core/_rup.scss
- src/app/modules/rup/components/huds/vistaPrestacion.html
https://proyectos.andes.gob.ar/browse/MISC-123
https://proyectos.andes.gob.ar/browse/MISC-127
1. Se incorporan componentes PLEX: plex-wrapper, plex-title, plex-label, plex-grid
2. Ajustes visuales: se remueve marginación, se reduce tamaño título.
3. Se agrega mensaje hacia el usuario al no recuperar registros.
4. Se adapta uso anidado en panel lateral 'invert'.
**Nota:** para testear visualmente dirigirse a los lugares en los que se encuentra implementado el componente:
- src\app\apps\rup\mapa-camas\views\listado-internacion-capas\listado-internacion-capas.component.html
- src\app\apps\rup\mapa-camas\views\mapa-camas-capa\mapa-camas-capa.component.html
- src\app\components\buscadorTurnosPrestaciones\turnos-prestaciones.html
- src\app\modules\rup\components\ejecucion\prestacionEjecucion.htm …
> refactor(vista-prestacion): incorpora componentes plex

- src/app/components/carpeta-paciente/carpeta-paciente.component.ts
- src/app/components/carpeta-paciente/carpeta-paciente.html
- src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
- src/app/components/turnos/dashboard/update-contacto-direccion.html
- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-103
1. se agrega permiso soloLectura a punto de inicio y gestor de agenda
2. 
3.
> feat(CITAS): se agrega permiso soloLectura

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-329
1. Agrega condición de paciente "activo: true" durante la verificación de paciente existente previo a validación.
> MPI - Agrega verificación de paciente activo antes de validar

- src/app/modules/rup/components/elementos/vacunas.html
Se agrega un plex-bool tipo checkbox en el componente para indicar si el procedimiento de la vacuna fue realizado en domicilio. 
Obs: Faltaría agregar el caso de test
> feat(vacuna):Se agrega un check para dejar constancia que se realizó en domicilio

- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.html
- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Nombre del sector en el listado de movimientos.
Fechas automáticas en el listado de movimientos.
Ordena prestaciones por fecha en los registros de la internación.
https://proyectos.andes.gob.ar/browse/IN-253
https://proyectos.andes.gob.ar/browse/IN-248
https://proyectos.andes.gob.ar/browse/IN-254
https://proyectos.andes.gob.ar/browse/IN-257
> feat(mapa-camas): varios ajustes

- src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
- src/app/components/turnos/dashboard/update-contacto-direccion.html
- src/app/core/mpi/components/datos-contacto.component.ts
- src/app/core/mpi/components/datos-contacto.html
https://proyectos.andes.gob.ar/browse/MPI-327
1. Actualización de template de edición de contactos
2. Agrega patrón de contenido al valor de contacto
3. Corrige visibilidad de select al borrar el tipo de contacto (bug)
> MPI - Corrige edición de contactos en ventanilla

- src/app/components/turnos/dashboard/update-contacto-direccion.component.ts
- src/app/components/turnos/dashboard/update-contacto-direccion.html
Seleccionando un paciente que tenga solo MAIL de contacto, en ventanilla no figura ningún campo (tipo, valor) inicialmente
1. Si el paciente no posee celular o fijo se agrega un contacto vacío
> MPI - Bug actualizando contactos en ventanilla

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
https://proyectos.andes.gob.ar/browse/IN-255
1. filtros no actualizaban sus valores , ejemplo : si selecciono una unidad organizativa el filtro sectores seguía mostrando sectores que no pertenencian a esa unidad .
2. 
3.
> fix(mapa-camas): filtrar sectores a partir de la unidad organizativa

- src/app/components/prestamosHC/historial/historial-hc.component.html
- src/app/components/prestamosHC/historial/historial-hc.component.ts
- src/app/components/prestamosHC/prestamos-hc.component.html
- src/app/components/prestamosHC/prestamos-hc.component.ts
- src/app/components/prestamosHC/prestamos-hc.scss
- src/app/components/prestamosHC/prestamos/devolver-hc.component.html
- src/app/components/prestamosHC/prestamos/listar-prestamos.component.html
- src/app/components/prestamosHC/prestamos/listar-prestamos.component.ts
- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.html
- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
- src/app/components/prestamosHC/solicitudes/prestar-hc.component.html
- src/app/components/prestamosHC/solicitudes/solicitud-manual-hc.component.html
https://proyectos.andes.gob.ar/browse/MISC-90
1. Fix del error reportado modificando control del valor ingresado en filtro de prestaciones
2. Reemplazo de código para uso de algunos componentes plex
3. Se agrega botón para cierre de sidebar en búsqueda de paciente
> Prestamo de carpetas - Fix en filtro de prestaciones y actualización (uso) de componentes plex

- src/app/components/turnos/autocitar/dinamica.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
https://github.com/andes/api/pull/1279#issuecomment-782017873
1. Cuando se inicia una prestación de un turno de agenda dinámica, se verifica si la fecha de turno es anterior a la fecha actual.
2. Caso afirmativo, se guarda fechaHora de ejecución la fechaHora del turno, caso negativo, new date.
2. 
3.
> CIT: new date fecha prestacion dinamica

- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
- src/app/modules/forms-builder/components/forms-crud/forms-crud.scss
Problemas para usar plex select en virtual scroll
1. Se asigna altura extra a contenedor de scroll para cada item nuevo
> fix(forms-crud): altura extra para plex-select

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Se agregan campos en la ficha necesarios del paciente.
> fix(ficha-epidemiologica): agregamos información que falta en el test

- src/app/apps/vacunacion/components/inscripcion.component.ts
El grupo de adultos con discapacidad no debe tener límite de fecha hasta
1. Se quita control en calendario
> Inscripción Vacunas: Quita restricción a grupo discapacidad para limite de edad máxima

- src/app/core/mpi/components/paciente.component.ts
Se reporta que en algunos casos los usuarios no alcanzan a ver el toast 'ciudadano no encontrado' cuando el paciente a validar no esta en los registros de renaper y/o sisa. 
Se pide reemplazar el toast por un cartel invasivo.
> MPI - Reemplaza toast de ciudadano no encontrado

- src/app/modules/rup/components/ejecucion/help-solicitud.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/RUP-160
1. Mueve los botones al nivel del `plex-tabs` ganando más espacio.
> feat(rup): ajuste visual botones en ejecucion

- src/app/modules/rup/components/elementos/vacunas.component.ts
Error: no es posible modificar algun dato de una primer dosis si ya tiene una segunda dosis validada
1. Se agrega un control para saber si dosis elegida requiere control interdosis o no
2. 
3.
> fix(RUP): Vacunas covid control interdosis

- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/inscripcion.component.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
https://proyectos.andes.gob.ar/browse/VAC-6
1. Si fue enviado por url el grupo poblacional al que se quiere inscribir, entonces en el formulario aparece pre-seleccionado dicho grupo y en modo readlonly
> VAC - Selección de  grupo poblacional por url

- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/inscripcion.component.ts
- src/environments/apiKeyMaps.ts.example
Poder habilitar/deshabilitar el control del captcha al inscribirse para vacunación
1. Variable en apiKeyMaps para habilitar/deshabilitar control de captcha
> VAC: variable para deshabilitar control de captcha

- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/inscripcion.component.ts
- src/app/apps/vacunacion/interfaces/ICiudadano.ts
- Agrega la selección de factores de riesgo en la inscripción
1. 
2. 
3.
> fix(VAC): Agrega la selección de factores de riesgo en la inscripción

- src/app/apps/vacunacion/components/inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-14
1. Arreglo de seteo de fechas cuando el grupo viene por parámetro
> VAC: arreglo de seteo de fechas cuando el grupo viene por parámetro

- src/app/components/turnos/dashboard/estadisticas-pacientes.html
https://proyectos.andes.gob.ar/browse/CIT-106
> fix(CITAS):cambio de lugar de input en turnos paciente

- src/app/apps/vacunacion/components/inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-17
1. En caso de que api devuelva un error, se resguardan los factores de riesgo seleccionados para que no se pierdan esos datos al solucionar dicho error.
> fix(VAC): agrega variable para resguardar los factores de riesgo seleccionados

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/CORE-78
1. Setea el filtro de búsqueda al fecha del día.  
En teoría antes había algunas restricciones que ya no existe.
> fix(rup): controles de fechas

- package-lock.json
- package.json
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
- src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.html
- src/app/components/novedades/lista-novedades/detalle-novedad/detalle-novedad.component.ts
- src/app/components/top/solicitudes/anularSolicitud.component.ts
- src/app/components/top/solicitudes/anularSolicitud.html
- src/app/components/top/solicitudes/auditarSolicitud.component.ts
- src/app/components/top/solicitudes/auditarSolicitud.html
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.html
https://proyectos.andes.gob.ar/browse/PLEX-186
1. plex-visualizador como servicio
> feat(plex): v7.14

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> fix(citas): type permisos

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-112
1. Nuevo estado en combo de estados en solicitudes
> TOP: se suma estado ejecución a filtros en solicitudes

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/CORE-48
1. Controla que la APP pase fechas, para optimizar las consultas.
> feat(top): control de fechas vacias

- src/app/apps/vacunacion/components/consulta.component.html
- src/app/apps/vacunacion/components/consulta.component.ts
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
https://proyectos.andes.gob.ar/browse/VAC-8
1. Se crea una pantalla para consultar si una persona está registrada para vacunarse y si lo está, muestra el estado.
> VAC: pantalla para consultar el estado de inscripciones

- projects/shared/src/lib/directives/autosave.directives.ts
- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/filtros-vacunacion.html
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/components/listado-inscriptos.scss
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
https://proyectos.andes.gob.ar/browse/VAC-1
1. Se muestra el listado de inscriptos para vacunación y un conjunto de filtros de búsqueda
> VAC - Listado de inscriptos

- src/app/apps/vacunacion/components/inscripcion.component.ts
Agrega factores de riesgo
1. Se agregan factores de riesgo
> feat(inscripcion): Agrega morbilidades

- src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/CIT-107
1. Se saca print de pantalla al imprimir agendas
2. Se deja configuración para enviar los datos de la agenda a la api y generar el informe.
> feat(CITAS):Imprimir agenda

- src/app/apps/vacunacion/components/consulta.component.html
https://proyectos.andes.gob.ar/browse/VAC-22
1. Mostrar datos del inscripto al consultar por la inscripción
> VAC: mostrar los datos del inscripto al consultar por la inscripción

- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
Agregar imágenes de ayúda para verificar el número de tramite del dni.
1. Se agrega al html las imágenes y se modifica el mismo para que quede acomodado con la nueva funcionalidad.
2. Se agrega función en el componente para abrir y cerrar ayuda.
> VACUNACIÓN: Agrega ayuda número de tramite

- src/app/apps/vacunacion/components/consulta.component.html
- src/app/apps/vacunacion/components/consulta.component.ts
Mejorar la visualización de mensaje de respuesta en navegadores mobile
1. El subtítulo principal cambia según se muestre el formulario o el mensaje
2. Se corrige el tamaño del mensaje (responsive)
> feat(vac): responsive, se mejora subtítulo ppal

- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-18
1. Se deshabilita el botón después de hacer click hasta que recibe respuesta de la api
2. Nuevo botón para ir a la pantalla de consultas
> VAC: acceso a consultas de inscripción desde el formulario de registro

- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
- src/app/modules/forms-builder/components/forms-crud/forms-crud.scss
Mejorar el funcionamiento general de virtual scroll
1. Se calcula la altura del contendor padre (evita scroll doble)
2. Se calcula la altura del contedor virtual (items encajan ok)
3. Se agrega un margin al item final para que plex-select se visualize correctamente
> fix(virtual-scroll): corrige variables generales

- src/app/modules/mpi/components/paciente-detalle.component.ts
Se corrige bug que mostraba badge "sin dni" en pacietes validados menores a 5 años.
La incosistencia de los datos se visualizaba al mostrar badge "sin dni" en pacientes menores a 5 años con al menos una relación asociada y de edad menor a 5 años
1. 
2. 
3.
> MPI: se corrige error al mostrar badge "sin dni" en pacietes validados

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-339
1. Se modifica funcion 'validarPaciente' para actualizar datos de pacientes validados anteriormente
> MPI - Fix revalidación de paciente

- src/app/apps/vacunacion/components/inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-32
1. Se agrega Factor de riesgo asociado a vacunación contra COVID-19 a la colección de grupo-poblacional
**Para probar funcionalidad agregar en la coleccion grupo-poblacional de factores-riesgo el siguiente arreglo de morbilidades**
"morbilidades" : [ 
{"id" : "diabetes", "label" : "Diabetes (insulinodependiente y no insulinodependiente)"}, 
{"id" : "obesidad","label" : "Obesidad grado 2 o mayor (índice de masa corporal -IMC- mayor a 35)"}, 
{"id" : "cardiovascular","label" : "Enfermedad cardiovascular (NO incluye la hipertensión arterial como único antecedente)"}, 
{"id" : "renal","label" : "Enfermedad renal crónica, incluidos pacientes en diálisis crónica"}, 
{"id" : "respiratoria","label" : "Enfermedad respiratoria crónica"}, 
{ "id" : …
> feat(VAC):agrega morbilidades a base de datos

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-25
1. Se actualizan los campos de la ficha COVID 19.
2. Se actualiza la operación de clasificación final en base a los nuevos campos.
3. Se corrigen errores visuales.
- Agregar en la colección forms de la base de datos el siguiente archivo:
[fichaCovid19.txt](https://github.com/andes/app/files/6280615/fichaCovid19.txt)
- Agregar en la colección módulos:
[epidemiologia.txt](https://github.com/andes/app/files/6280629/epidemiologia.txt)
- Para el acceso, dentro del gestor de usuarios ir al modulo epidemiología y asignar los permisos.
> FICHA-EPIDEMIOLOGICA: Actualizazión ficha COVID 19

- projects/auth/src/lib/auth.service.ts
- projects/portal/src/app/app.routings-guard.class.ts
https://proyectos.andes.gob.ar/browse/PDP-36
1. al refrescar la pantalla mantiene la sesión abierta
2. 
3.
> feat(PDP):al refrescar la pantalla mantener sesión abierta

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts
Notifica ruta volver a mapa de camas.
1. Notifica ruta volver a mapa de camas.
2. 
3.
> INT: notifica ruta volver a mapa de camas

- projects/portal/src/app/components/portal-titulo/portal-titulo.component.html
- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/filtros-vacunacion.html
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/components/listado-inscriptos.scss
- src/app/apps/vacunacion/services/inscripcion.service.ts
tambien agrega filtro por fecha de registro al listado de inscriptos y filtra por defecto pacientes no vacunados
https://proyectos.andes.gob.ar/browse/VAC-23
1. Opción en el sidebar de asociar un paciente ya registrado
2. Agrega filtros por fecha de registro y paciente vacunado/no vacunado (Por defecto)
> VAC - Asociar paciente a inscripción

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
- src/app/apps/gestor-usuarios/gestor-usuarios.module.ts
- src/app/apps/gestor-usuarios/gestor-usuarios.providers.ts
- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/apps/vacunacion/components/editar-inscripcion.html
- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/apps/vacunacion/vacunacion.module.ts
https://proyectos.andes.gob.ar/browse/VAC-21
1. Permitir sanear errores en el tipeo en alguno de los datos de las inscripciones para vacunación
2. Controlar según permisos de usuario la información a editar
Cargar nuevo módulo:
{
"nombre" : "Vacunación COVID-19",
"descripcion" : "Permite administrar las incripciones a la campaña de vacunación",
"subtitulo" : "Campaña de vacunación",
"linkAcceso" : "/vacunacion/listado",
"color" : "#A74482",
"icono" : "documento-paciente",
"permisos" : [ 
"vacunacion:?"
],
"orden" : 16
}
> VAC: permitir editar inscripciones

- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
Cambia inicialización de variable de fecha
1. 
2. 
3.
> fix(inscripcion): cambia formato de fechaRegistro

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-75
1. Biquery para ficha epidemiológica
2. Cambio de type de ficha por `{ id, name }`
3. 
- nuevo registro de query:
[biquery-fichaEpidemio.txt](https://github.com/andes/app/files/6305027/biquery-fichaEpidemio.txt)
-  editar registros preexistentes de formEpidemiologia y cambiar type a nuevo schema
> BI: biquery ficha epidemio

- src/app/interfaces/IOrganizacion.ts
- src/app/interfaces/IZonaSanitaria.ts
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/epidemiologia/epidemiologia.routing.ts
- src/app/services/zonaSanitaria.service.ts
https://proyectos.andes.gob.ar/browse/EP-15
https://proyectos.andes.gob.ar/browse/EP-26
1. Se agrega pantalla para buscador de fichas epidemiologicas.
2. Se agrega la interfaz zona sanitaria para usar en organizaciones y y fichas epidemiológicas.
3. Se agrega el campo identificadorpcr como dependencia para la ficha COVID19.
- Los permisos para ver el buscador son epidemiologia:update o epidemiologia:read
> EPIDEMIOLOGÍA: Buscador de fichas epidemiologicas

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-27
https://proyectos.andes.gob.ar/browse/EP-28
1. Se actualizan nuevos campos de la ficha COVID 19.
2. Se eliminan el campo sort de plex-table.
[fichacovid.txt](https://github.com/andes/app/files/6311170/fichacovid.txt)
> FICHA EPIDEMIOLÓGICA: Nuevas actualizaciones

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Modificar el campo localidades para que tengo coorelacion con la selección en el campo provincia.
Agregar una funcion que al "deseleccionar" alguna de las opciones que tenga dependencias, elimine las mismas.
1. Se modifica la ficha y la vista para que al seleccionar una provincia, muestre en el combo "localidades" las pertenecientes a esta.
2. Se agrega la funcion clearDependencias para limpiar las dependencias.
3. Se actualiza la ficha covid 19. IMPORTANTE: ACTUALIZAR LA COLECCIÓN FORMS CON EL TXT ADJUNTO.
[fichacovid.txt](https://github.com/andes/app/files/6320349/fichacovid.txt)
> FICHA EPIDEMIOLOGICA: Modificación localidades

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/huds.module.ts
- src/app/modules/rup/services/huds.service.ts
https://proyectos.andes.gob.ar/browse/EP-24
1. Incluye fichas epidemiológicas en listado de prestaciones en HUDS de paciente.
2. Corrige ordenamiento de prestaciones por fecha
3.
> HUDS: visualiza fichas epidemiologicas

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Corrige display de nombres de tipo de fichas en buscador  de fichas por paciente
1. 
2. 
3.
> EP: Fix nombre tipo de ficha en buscador

- src/app/apps/vacunacion/components/detalle-inscripcion.component.ts
- src/app/apps/vacunacion/components/detalle-inscripcion.html
- src/app/apps/vacunacion/components/editar-inscripcion.html
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/vacunacion.module.ts
https://proyectos.andes.gob.ar/browse/VAC-39
1. Si no hay paciente asociado a la inscripción, poder editar datos básicos
> VAC: editar datos básicos si no tiene paciente asociado

- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/components/listado-inscriptos.scss
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/apps/vacunacion/vacunacion.module.ts
https://proyectos.andes.gob.ar/browse/VAC-43
1. Agrega columna 'vacunado'
2. Muestra con badges el estado de la inscipción
> VAC - Incluir vacunados en el listado

- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
Poder agregar una nota a las inscripciones
1. Se agrega opcion en el sidebar para agregar una nota en texto libre
2. Se observa un icon 'comment' en la columna 'grupo' si la inscripción posee una nota
> VAC - Agregar nota a una inscripción

- src/app/modules/com/com.module.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/rup/services/elementosRUP.service.ts
https://proyectos.andes.gob.ar/browse/COM-52
1. Reemplaza 'detalle' de derivación por prestación
2. Incluye workflow de registro de prestación en RUP al momento de crear un nueva derivación.
3.
> COM: crea derivación como prestación

- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/filtros-vacunacion.html
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/services/inscripcion.service.ts
https://proyectos.andes.gob.ar/browse/VAC-36
1. Nuevo filtro buscar inscripciones si tienen certificado
> VAC: filtro por certificado en listado de inscripciones

- src/app/core/mpi/components/datos-contacto.component.ts
En el formulario de contactos, cambia patrón email para que considere otros caracteres.
https://proyectos.andes.gob.ar/browse/MPI-340
1. 
2. 
3.
> MPI: Cambia patrón email de contactos

- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/apps/vacunacion/components/editar-inscripcion.html
Agrega la posibilidad de cambiar la localidad del inscripto a la vacunación
1. 
2. 
3.
> feat(inscripcion): permite modificar localidad

- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
https://proyectos.andes.gob.ar/browse/PDP-46
1. ordenar turnos 
2. 
3.
> fix(PDP):ordenar turnos de mas reciente a los mas viejos ultimos

- projects/portal/src/app/services/laboratorio.service.ts
- projects/portal/src/app/services/turno.service.ts
- projects/portal/src/app/services/vacuna.service.ts
https://proyectos.andes.gob.ar/browse/PDP-47
1. cache de la consulta de turnos, laboratorios y vacunas
2. 
3.
> feat(PDP):cache de la consulta de turnos, laboratorios y vacunas

- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/components/nueva-inscripcion/busqueda-paciente.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/busqueda-paciente.html
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.html
- src/app/apps/vacunacion/interfaces/ICiudadano.ts
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
https://proyectos.andes.gob.ar/browse/VAC-28
1. Permitir cargar una nueva inscripción a partir de un paciente
> VAC: Nueva inscripción

- projects/portal/src/index.html
- src/index.html
https://proyectos.andes.gob.ar/browse/ACC-2
https://proyectos.andes.gob.ar/browse/ACC-8
1. Se modifica meta tag "viewport" para permitir zoom en dispositivos móviles, tanto en la app principal como en el portal de paciente.
2. Se modifica el idioma de la página (en app no estaba, en portal estaba puesto en inglés)
- Se debe instalar la extensión de chrome/firefox [axe coconut](https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp)
- Abrir la consola, entrar en el tab de la extensión
- Correr los checks, no deberían listarse problemas críticos de zoom ni de idioma
- Para el caso del zoom, debe correrse la app de manera que pueda navegarse desde un browser mobile (por IP), y comprobar que se puede hacer _pinch_ para aplicar zoom: `npx ng serve …
> Accesibilidad general (idioma y zoom)

- src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/modules/rup/services/plantillas.service.ts
https://proyectos.andes.gob.ar/browse/IN-266
https://proyectos.andes.gob.ar/browse/IN-265
1.  Correcion mensaje de error "Argument passed in must be a single String of 12 bytes or a string of 24 hex characters"
2. Filtro por paciente en historial medico
3.  Filtro por organizacion
4. Ajustes de fechas
5. Resetea totales de los censos
> fix(mapa-camas): varios fix internacion

- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/filtros-vacunacion.html
- src/app/apps/vacunacion/services/inscripcion.service.ts
https://proyectos.andes.gob.ar/browse/VAC-41
1. Modifica filtro dni para permitir también por nombre y apellido
> VAC - Filtro por nombre y apellido

- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
Labels en fields de form builder
1. 
2. 
3.
> EP: labels en form builder

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-33
1. Se agrega scroll infinito y las funciones sort para cada columna.
Queda pendiente una mejora en la UI al seleccionar un paciente.
> EPIDEMIOLOGÍA: Scroll infinito buscador 

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/EP-31
Funcionalidad desarrollada
1. Se agrega el pcr select en convivencia con plex-bool pcrM
2. Se realizan cambios en la lógica de clasificación para este último punto de acuerdo a la información que se recibe desde laboratorio.
OBS: Ver PR de API
https://github.com/andes/api/pull/1351
> Events ficha epidemio

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-34
https://proyectos.andes.gob.ar/browse/EP-36
https://proyectos.andes.gob.ar/browse/EP-37
https://proyectos.andes.gob.ar/browse/EP-38
https://proyectos.andes.gob.ar/browse/EP-39
https://proyectos.andes.gob.ar/browse/EP-40
https://proyectos.andes.gob.ar/browse/EP-41
https://proyectos.andes.gob.ar/browse/EP-43
1. Se actualizan campos y funciones de la ficha epidemiológica según nuevos requerimientos.
[fichacovid.txt](https://github.com/andes/app/files/6391808/fichacovid.txt)
> FICHA EPIDEMIOLOGICA: Actualizaciones

- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/historial-derivacion.html
https://proyectos.andes.gob.ar/browse/COM-70
1. Incluye unidad destino a derivación
2. 
3.
> COM: unidad destino derivación

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
EP: fix provincia id en ficha
1. 
2. 
3.
> EP: fix provincia id en ficha

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-271
1. 
2. 
3.
> fix(mapa-camas): ajuste control fecha maximo de egreso

- src/app/services/parentesco.service.ts
Cambia la ubicación de la ruta de parentesco.
1. 
2. 
3. 
https://github.com/andes/api/pull/1348
> refactor(mpi): elimina rutas en desuso

- src/app/components/turnos/autocitar/dinamica.html
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/CIT-110
1. Se acomoda código para que quedara fijo el plex-title al hacer scroll
2. Se cambia legend por plex-title en el componente que busca al paciente para agenda dinámica en sidebar
> refactor(RUP): botón agregar paciente visible

- src/app/modules/rup/components/elementos/vacunas.component.ts
https://proyectos.andes.gob.ar/browse/RUP-249
1. Limpieza de campos al cambiar de vacuna/categoría
> RUP: limpieza de campos al cambiar vacuna/categoría

- src/app/apps/vacunacion/components/filtros-vacunacion.html
- src/app/apps/vacunacion/components/listado-inscriptos.html
https://proyectos.andes.gob.ar/browse/VAC-44
1. Arreglo de implementación de plex-table en listado de inscriptos
> VAC: corrección de plex-table

- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/apps/vacunacion/components/editar-inscripcion.html
- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
https://proyectos.andes.gob.ar/browse/VAC-50
1. Permite cambiar de grupo en cualquier caso al editar inscripción
> VAC: permitir cambiar el grupo de inscripciones

- package-lock.json
- package.json
- Implementaciones y fixe varios (plex-grid, plex-wrapper, plex-modal, sidebar invert, directiva align)
1. **plex-modal:** se evita herencia desde invert
2. directiva **align:** inernamente setea altura del contenedor con `calc()`
3. **plex-grid:** agrega mixins + encolumnado manual, agrega size auto y breakpoints
4. **title de página:** aplica TitleCasePipe (automático)
> feat(plex): v7.16.0

- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
https://proyectos.andes.gob.ar/browse/VAC-52
1. Poder elegir entra notas predefinidas o ingresar una personalizada
2. No permitir ingresar notas vacías
> VAC: poder elegir notas predefinidas o escribir una personalizada

- src/app/shared/components/upload-file.component.ts
https://proyectos.andes.gob.ar/browse/MPI-331
1.En la ventana de popUp al momento de navegar el sistema de archivos, En lugar de permitirte seleccionar "todos", se  restringe a los tipo de datos que soporta, para que el usuario no elija un formato inválido 
2. 
3.
> feat(MPI): se restringe tipos de datos en ventana popUp

- src/app/apps/rup/plantillas-rup/plantillas-rup.component.html
- src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
- src/app/modules/rup/services/conceptObserver.service.ts
- src/app/modules/rup/services/plantillas.service.ts
https://proyectos.andes.gob.ar/browse/RUP-231
1. se pueden agregar links a archivos en plantillas-rup , para luego desde rup poder desplegar el dropdown y seleccionar un item-link y poder visualizar el archivo en una nueva pestaña .
2. 
3.
> feat(RUP):rup-card, links a informacion

- src/app/apps/vacunacion/components/listado-inscriptos.html
https://proyectos.andes.gob.ar/browse/VAC-62
1. No permitir la edición de inscripciones para pacientes vacunados
-
> VAC: no permitir editar inscripciones de pacientes ya vacunados

- src/app/modules/mpi/components/paciente-detalle.component.ts
Cuando el domicilio del paciente no pertenece a la provincia de neuquen, entonces mostrar la provincia en el detalle del paciente
1. Agrega provincia en el detalle de domicilio cuando el paciente no posee localidad
> MPI - Muestra detalle de provincia en sidebar

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-49
1.  Cuando se ingresa a editar una ficha, se modifican los datos del usuario con los del login actual.
> FICHA-EPIDEMIOLOGICA: Setea datos usuario logueado

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/epidemiologia/pipes/codigoSisa.pipe.ts
https://proyectos.andes.gob.ar/browse/EP-47
1. Muestra el código SISA de la ficha en el búscador
2. botón para editar codificación SISA
3. form de código SISA en side bar  de buscador
[formResource_Operaciones.txt](https://github.com/andes/app/files/6442420/formResource_Operaciones.txt)
> EP: muestra y edita código SISA en buscador

- src/app/apps/vacunacion/components/gestion-turnos/dacion-turno.component.ts
- src/app/apps/vacunacion/components/gestion-turnos/dacion-turno.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/components/notas.component.ts
- src/app/apps/vacunacion/components/notas.html
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
https://proyectos.andes.gob.ar/browse/VAC-58
https://proyectos.andes.gob.ar/browse/VAC-59
1.Nueva pantalla para monitoreo de inscripciones y gestionar turnos 
Reemplazar en la colección _modulos_ el llamado Vacunación COVID-19 por:
{
"nombre" : "Vacunación COVID-19",
"descripcion" : "Campaña de vacunación",
"subtitulo" : "Campaña de vacunación",
"linkAcceso" : "/vacunacion/listado",
"color" : "#A74482",
"icono" : null,
"permisos" : [ 
"vacunacion:?"
],
"orden" : 5,
"submodulos" : [ 
{
"permisos" : [ 
"vacunacion:?"
],
"nombre" : "Monitoreo de inscriptos",
"linkAcceso" : "/vacunacion/listado",
"color" : "#413839",
"icono" : "file-tree",
"orden" : 1
}, 
{
"permisos" : [ 
"vacunacion:dacion-turnos"
],
"nombre" : "Llamador de inscriptos", …
> VAC: monitoreo de inscriptos y gestión de turnos

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-273
https://proyectos.andes.gob.ar/browse/IN-261
1. Se obtiene el paciente desde la prestación para poder pedir el token de huds
2. Agrega botón volver en censo diario y mesual
> INT - Fixes registros médicos en listado de internación y boton volver

- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/elementos/FormulaBase.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.html
- src/app/modules/rup/services/ejecucion.service.ts
https://proyectos.andes.gob.ar/browse/RUP-88
La idea es proveer mensajes dinámicos y ofrecerle al usuario registrar ciertos conceptos. En este caso los hallazgos del riesgo cardiovascular 
1. Se utilizan las reglas dinamicas de rup para generar los mensajes.  
Modificar el elemento rup: 
{ 'conceptos.conceptId' : '441829007' }
```
"rules" : [ 
{
"conditions" : {
"all" : [ 
{
"fact" : "value",
"operator" : "equal",
"value" : 1
}
]
},
"event" : {
"type" : "alert",
"params" : {
"message" : "Riesgo bajo (<10%)",
"type" : "info",
"add" : {
"conceptId" : "601000246108",
"term" : "paciente con riesgo cardiovascular bajo",
"fsn" : "paciente con riesgo cardiovascular (hallazgo)",
"semanticTag" : "hallazgo"
}
}
}
}, 
{
"conditions" : {
"all" : [ 
{
"fact" : "value",
"operator" : "equal",
"value" : …
```
> rup: configurar mensajes y badges en formulas

- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/apps/vacunacion/components/editar-inscripcion.html
https://proyectos.andes.gob.ar/browse/VAC-63
1. Poder editar el estado a 'fallecido'.
2. A un inscripto en estado fallecido solo se le puede editar el estado.
> VAC - Nuevo estado 'fallecido' editando inscripción

- src/app/apps/vacunacion/components/detalle-inscripcion.html
https://proyectos.andes.gob.ar/browse/VAC-65
1. Agrega badge con estado de validacion de domicilio
2. Modifica bi-queries para agregar nueva columna 'domicilioVerificado'. (Queries en db demo)
> VAC - Agrega badge con estado de validacion de domicilio

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-278
1. Busca registros de ingresos anteriores y pre-setea combos de datos estadísticos
> INT - Carga datos de internación anterior en nuevo ingreso

- src/app/app.component.ts
- src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
- src/app/apps/auth/components/select-organizacion/select-organizacion.html
- src/app/apps/auth/components/select-organizacion/select-organizacion.scss
- src/app/components/inicio/inicio.component.ts
https://proyectos.andes.gob.ar/browse/MISC-158
1. Se oculta navbar en pantalla de selección de Organización/Efector
2. Se usa plex-title en su lugar
> Se actualiza layout de selección de Organización

- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/app.module.ts
- projects/portal/src/app/components/portal-menu/portal-menu.component.ts
- projects/portal/src/app/pages/login/login-portal-paciente.ts
- projects/portal/src/app/pages/mis-certificados/mis-certificados-detalle.component.html
- projects/portal/src/app/pages/mis-certificados/mis-certificados-detalle.component.ts
- projects/portal/src/app/pages/mis-certificados/mis-certificados.component.html
- projects/portal/src/app/pages/mis-certificados/mis-certificados.component.ts
- projects/portal/src/app/services/categoria.service.ts
- projects/portal/src/app/services/certificado.service.ts
como paciente quiero ver mis certificados.
1. se agrega funcionalidad para visualizar mis certificados desde PDP
2. 
3.
> feat(PDP):visualizar mis certificados en PDP

- package-lock.json
- package.json
- projects/portal/src/app/components/paciente-detalle.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
- src/app/apps/vacunacion/components/consulta.component.html
https://proyectos.andes.gob.ar/browse/MISC-160
**1. Bug Fixes**
- plex-item: badge con wrap en responsive
**2. Features (ver task para testear)**
- plex-card: agrega version outlined
- plex-card: outlined + optimiza uso de colores
- plex-card: renombra attr styled por mode
- Define atributos ARIA en componentes plex-text, plex-int y plex-title
- projects\portal\src\app\components\paciente-detalle.html
- src\app\apps\vacunacion\components\consulta.component.html
- src\app\apps\rup\mapa-camas\views\mapa-camas-capa\recursos-listado\recursos-listado.component.html
> feat(plex): actualiza a v7.18.0

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.html
- src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.ts
- src/app/directives/feature-flag.directive.ts
Primerisima versión del Mapa Visual de Camas (Experimental)
Por ahora esta protegido mediante la featuere flag "mapaVisualCamas". (agregar en cofiguracion Authusers)
> feat(mapa-camas): visualizacion tipo timeline

- src/app/apps/vacunacion/components/editar-inscripcion.html
- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/inscripcion.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.html
- src/app/apps/vacunacion/interfaces/ICiudadano.ts
- src/app/apps/vacunacion/services/inscripcion.service.ts
- src/app/services/grupo-poblacional.service.ts
https://proyectos.andes.gob.ar/browse/VAC-66
1. Permite la inscripción de personas del grupo con factores de riesgo entre 57 y 59 años sin necesidad de certificado
> VAC - Inscripción de nuevo grupo 57 a 59 años

- src/app/components/organizacion/organizacion-create-update.component.ts
- src/app/components/organizacion/organizacion-create-update.html
https://proyectos.andes.gob.ar/browse/MISC-156
> feat(Organizacion): Agregar zonas sanitarias dentro de organizacion

- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-54
1. Se modifico el plex.select del html de planificar-agenda para que se puedan mostrar los nombres de los servicios de cada espacio físico.
2. Se modifico el plex.select del html de panel-agendas para sacar los paréntesis al momento de mostrar el espacio físico.
> refactor(CIT-54): Nombre de los servicios a los espacios fisicos

- src/app/modules/com/components/punto-inicio.component.ts
COM: incrementar limit de busqueda
1. 
2. 
3.
> COM: incrementar limit de busqueda

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Modificar la ficha con nuevos requerimientos
1. Se agregan funciones para setear select de pcr y semana epidemiologica.
[fichacovid.txt](https://github.com/andes/app/files/6517960/fichacovid.txt)
> FICHA EPIDEMIOLOGICA: Updates

- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
https://proyectos.andes.gob.ar/browse/VAC-71
1. Permitir ver en gestión de turnos mis inscripciones asignadas
> VAC: ver mis inscripciones asignadas

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Le agregamos información extra del paciente que es necesaria para el laboratorio central.
https://proyectos.andes.gob.ar/browse/EP-72
https://github.com/andes/api/pull/1400
> feat(fichaEpidemiologia): Se agrega al paciente de la ficha información de identificación si es extranjero y estado

- src/app/modules/com/components/punto-inicio.component.ts
https://proyectos.andes.gob.ar/browse/COM-82
1.  https://proyectos.andes.gob.ar/browse/COM-82
2. 
3.
> COM: fix bug buscar org origen

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/services/paciente.service.ts
https://proyectos.andes.gob.ar/browse/MPI-334
1. Se agrega patrón al campo de texto
2. Se eliminan los espacios en blanco iniciales
> MPI - Corrige patrón de nombre autopercibido

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-269
1. Agrega propiedad readonly en campos de egreso cuando la internación ya fue validada
> INT - Fix edición de egreso en internación validada

- src/app/modules/rup/components/huds/vistaPrestacion.html
https://proyectos.andes.gob.ar/browse/RUP-253
1. se cambia el titulo del plex-label . 
2. 
3.
> refactor(RUP):se cambia Solicitante por Profesional

- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-279
1. Nuevo select de prepagas que se visualiza cuando se selecciona que el paciente tiene plan de salud privado o mutual.
> INT - Seleccion de obra social prepaga

- src/app/core/mpi/components/datos-basicos.html
Quita regex de campo de nombre para pacientes validados
1. 
2. 
3.
> fix(mpi): quita regex del nombre

- src/app/components/top/reglas/reglas.component.html
- src/app/components/top/reglas/reglas.component.ts
https://proyectos.andes.gob.ar/browse/TOP-114
1. Se agrego control para deshabilitar el botón de guardar hasta que tenga todo los datos correspondientes (prestación destino, organización destino, prestaciones origen y organización origen)
> fix(TOP): control de datos para nueva regla de entrada

- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-295
> feat(mapa-camas): muestra la prestación de estadística en resumen de internación

- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/core/mpi/services/paciente.service.ts
Se agrega nuevo  atributo idPacientePrincipal en paciente utilizado en link-unlink de pacientes
https://proyectos.andes.gob.ar/browse/MPI-352
1. Atributo idPacientePrincipal en un paciente vinculado (paciente secundario) que mantiene el id del paciente principal al vincularlos y queda en null al desvincularlos
2. 
3.
> MPI:Nuevo atriburo idPacientePrincipal en paciente para linkeo

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
1. Se agrega loader y mensaje al no encontrar un paciente luego de realizada la búsqueda.
2. Se limpian las dependencias antes de calcular el resultado final de la ficha para limpiar el campo que indica el resultado del caso.
3. Agrego un mensaje en el punto de inicio si el paciente no tiene ficha registradas.
> FICHA EPIDEMIOLÓGICA: Loader en buscador de pacientes

- src/app/apps/vacunacion/components/inscripcion.component.ts
Agrega control de edad según las excepciones configuradas en el grupo
1. 
2. 
3.
> feat(inscripcion): agrega control de edad por reglas

- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.html
- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-292
1. se sincroniza plex-datetime con timeline . 
2. 
3.
> feat(mapa-camas): sincronizar plex-datetime en resumen internación

- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
https://proyectos.andes.gob.ar/browse/IN-297
1. 
2. 
3.
> IN - Agrega fecha de ingreso en censo diario

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
https://proyectos.andes.gob.ar/browse/COM-80
1.  Asignación de origen desde organización COM
2. 
3.
> COM: asignar origen desde org COM

- src/app/apps/vacunacion/components/consulta.component.html
- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
Agrega grupo sin factores de riesgo.  Queda pendiente un refactor para realizar estas verificaciones a partir de las reglas incluidas en cada grupo.
1. Soluciona error en la consulta de inscripción
2. 
3.
> fix(inscripcion): agrega grupo sin FR

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
https://proyectos.andes.gob.ar/browse/IN-274
1. Agrega columna 'unidad organizativa' en listado de internación
2. Agrega filtros por unidad organizativa
> INT - Agregar columna 'unidad organizativa'

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-71
1. Se agrega función para chequear que la ultima ficha del paciente haya sido creada hace mas de 14 dias.
2. Se elimina temporalmente la opción activo de localidades.
3. Se agrega un síntoma (rinitis) nuevo en la ficha COVID19 (Actualización base de datos)
[fichacovid.txt](https://github.com/andes/app/files/6599318/fichacovid.txt)
> FICHA EPIDEMIOLOGICA: Check días

- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
https://proyectos.andes.gob.ar/browse/IN-298
1. Suma los dias de estada de la columna
> IN - Fix dias de estada totales en censo mensual

- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
https://proyectos.andes.gob.ar/browse/VAC-69
1. Se suma botón para poder desvincular paciente de inscripción en el listado de inscriptos
> VAC: desvincular paciente de inscripción

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-293
1. Implementa plex-table con sorting en listado de internacion
> mapa-camas:  implementa plex-table en listado de internación

- src/app/apps/rup/mapa-camas/constantes-internacion.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
https://proyectos.andes.gob.ar/browse/IN-288
https://proyectos.andes.gob.ar/browse/IN-262
1. Se agrega opción 'otro' a a la constante de internación 'listaTipoegreso'.
2. Nuevo campo de texto libre para ingresar 'otra' organización destino en caso de egreso por traslado.
> IN - Nueva opción 'otro' en tipo de egreso y organización destino

- package-lock.json
- package.json
- src/app/modules/com/com.module.ts
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/actualizar-estado.html
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/historial-derivacion.html
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
- src/app/modules/dispositivo/dispositivo.component.ts
- src/app/modules/dispositivo/dispositivo.html
- src/app/services/dispositivo/dispositivo.service.ts
1. Posibilidad de crear una derivación con algún dispositivo de oxígeno.
2. Permite la evolución del dispositivo de oxígeno en cada cambio de estado.
3. Permite visualizar el dispositivo de oxigeno tanto en: detalle, listado, historial y reportes.
4. Se agrega al reporte general, si se utilizó el dispositivo de oxígeno en la derivación.
https://proyectos.andes.gob.ar/browse/COM-83
Obs: Ver PR de API
https://github.com/andes/api/pull/1413
> feat(com): Se agrega la posibilidad de asignar dispositivo de oxigeno al proceso de derivación

- src/app/components/inicio/inicio.component.ts
- src/app/components/inicio/inicio.html
- src/app/interfaces/novedades/IModulo.interface.ts
https://proyectos.andes.gob.ar/browse/MISC-128
1. Se muestra módulo cuando hay permisos sólo de submódulos
2. Se incluye un fix en la comprobación de permisos (caso en que hay un submódulo con más de 1 permiso)
> Mostrar submódulos como módulos

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
https://proyectos.andes.gob.ar/browse/IN-299
1. Cambia a la vista de la prestación al clickear un registro
> Listado-internación - Visualizar detalle de registros

- package-lock.json
- package.json
Actualizar a plex v7.18.1
1. Actualiza a plex v7.18
2. Corrige un problema con íconos anidados en tags `span` (un spanto)
> chore(plex): v7.18.1

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.html
- src/app/apps/rup/mapa-camas/views/timelinea-mapa-camas/timeline-mapa-camas.component.ts
https://proyectos.andes.gob.ar/browse/IN-289
1. 
2. 
3.
> feat(mapa-camas):filtros por unidad organizativa y paciente

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- Resuelve el error cuando en el com se selecciona otra institución origen
> fix(COM): Fix error en merge para instituciones de com

- src/app/modules/perinatal/components/alertas-perinatal.component.ts
- src/app/modules/perinatal/components/detalle-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
https://proyectos.andes.gob.ar/browse/PER-27
> refactor(PER):  Alertas Fecha Fin Embarazo

- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-300
1. Corrige la posición de los botones cancelar/guardar.
2. Reemplaza row/col por plex-grid
> Mapa-camas: Actualiza unidad organizativa original al editar una cama

- src/app/app.routing.ts
- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.html
- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-305
1. Agrega propiedad  runGuardsAndResolvers: 'always' para limpiar header con detalle del paciente al salir del resumen de internación
2. Agrega botón 'volver' en resumen de internacion
> Resumen-internación - Limpia header de paciente al volver

- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
https://proyectos.andes.gob.ar/browse/COM-90
1. 
2. 
3.
> COM: remover COM de origen

- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.html
- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.ts
- src/environments/environment.dev.ts
https://proyectos.andes.gob.ar/browse/IN-294
1. Pasa por parametro la prestacion en lugar de su id, para evitar volver a cargarla.
> Resumen-internación - Evita recargar prestación nuevamente

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/services/elementosRUP.service.ts
https://proyectos.andes.gob.ar/browse/RUP-255
1. 
2. 
3.
> rup: conceptos requeridos dinámicos

- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.scss
- src/app/modules/com/services/punto-inicio.service.ts
- Se agrega la posiblidad de clasificar y ordenar por prioridad intermedia (naranja)
> feat(COM): Se le agrega nuevo color para identificar prioridades intermedias, se le agrega también el filtro de ordenamiento

- src/app/core/mpi/components/datos-contacto.component.ts
- src/app/core/mpi/components/datos-contacto.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/interfaces/IUbicacion.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/MPI-349
1. Se suma en la solapa de Datos de contacto los datos del lugar de nacimiento
> MPI: cargar lugar de nacimiento a paciente

- src/app/apps/vacunacion/components/listado-inscriptos.html
https://proyectos.andes.gob.ar/browse/VAC-82
1. Saca la condición que evaluaba si el paciente ya tenia cargada fecha de vacunación
> fix(VAC): Editar la inscripción

- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-87
1. Se agrega nuevo grupo para personas gestantes
> feat(VAC):agrega nuevo grupo de personas gestantes

- src/app/modules/rup/components/elementos/FormulaBase.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.html
- src/app/modules/rup/components/formulas/index.ts
Al incorporar las reglas dinamicas se perdio el label del resultado. 
https://proyectos.andes.gob.ar/browse/RUP-260
Agregar estos dos elementos rup:
```json
{
"_id" : ObjectId("60cb3bf4d4a35f914a42a839"),
"componente" : "ValorNumericoComponent",
"style" : {
"columns" : 6.0,
},
{
"conceptId" : "710001002",
"fsn" : "número de diente (entidad observable)",
"semanticTag" : "entidad observable",
"term" : "número de diente"
}, 
{
"conceptId" : "251318008",
"fsn" : "recuento de dientes obturados (entidad observable)",
"semanticTag" : "entidad observable",
"term" : "conteo de dientes arreglados"
}
],
"params" : {
"numericType" : "integer",
"max" : 100.0,
"min" : 0.0, …
```
> fix(rup): muestra resultado de la formula

- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
https://proyectos.andes.gob.ar/browse/IN-308
1. Elimina controles
- [] No
> IN - Elimina controles de movimientos para préstamos de camas

- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.html
https://proyectos.andes.gob.ar/browse/IN-259
1. Agrega un identificador común (idMovimiento) al realizar un cambio de cama, tanto a la cama origen como a la destino.
2. Permite anular una internación con mas de un movimiento.
> IN - Anular internación con varios movimientos

- package-lock.json
- package.json
> chore(icons): Update andes icons

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/huds/vistaContextoPrestacion.html
- src/app/modules/rup/services/prestaciones.service.ts
No se visualizan los trastornos como "resueltos".
Esta mal la fecha de la evolución que se usa. 
https://proyectos.andes.gob.ar/browse/HUDS-20
> fix(huds): evoluciones

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
Permisos especiales para validar prestaciones no creadas por mí. Ejemplos de uso:
1. Residentes-Medicos a cargo.
2. Edición de vacunas cuando la carga un NN.
> feat(rup): permisos especiales para validar

- src/app/apps/vacunacion/components/lote/lote.component.html
- src/app/apps/vacunacion/components/lote/lote.component.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
- src/app/services/vacunas.service.ts
https://proyectos.andes.gob.ar/browse/VAC-77
1. Una vez que se pueden ver las vacunas en el listado, seleccionar una para ver sus detalles como así también los lotes que tiene asociada. 
2. Una vez seleccionada la vacuna se puede agregar un nuevo lote mediante un código y descripción que son obligatorios.
> feat(VAC-77) Mostrar las vacunas con sus lotes y agregar un nuevo lote

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-309
1. Corrige bug en fecha maxima para agregar procedimientos quirúrgicos durante el egreso del paciente
2. Correcciones varias para evitar errores por consola
> IN - Fix fecha 'hoy' en egreso de paciente

- src/app/components/inicio/inicio.component.ts
- src/app/components/inicio/inicio.html
- src/app/components/inicio/inicio.scss
https://proyectos.andes.gob.ar/browse/MISC-152
1. Los submódulos se muestran comprimidos si son más de 3 para evitar solapamientos
> Punto inicio Andes: mejoras visuales cuando hay 4 o más submódulos

- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
https://proyectos.andes.gob.ar/browse/VAC-85
1. Se agrego en sidebar del detalle del paciente una forma de visualizar, la cantidad de intentos de llamados que le hicieron al paciente y la fecha del último intento.
> feat(VAC):agrega registro de llamados

- src/app/apps/campaniaSalud/components/campania-create-update.component.ts
https://proyectos.andes.gob.ar/browse/MISC-173
1. Se modifico el tamaño de la imagen de la campaña y tambien se modifico el mensaje de error cuando el tamaño de dicha imagen no es la especificada.
> refactor(MISC-173) modificando campañas de salud

- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/interfaces/mapa-camas.internface.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/recursos-listado/recursos-listado.component.ts
https://proyectos.andes.gob.ar/browse/IN-287
1. Agrega columna 'Dias de estada' en el mapa de camas. Tambien para la visualización por sectores.
2. Agrega dato de fecha de ingreso del paciente al ocupar una cama
> Mapa-camas - Días de estada en el listado

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
- src/app/components/top/reglas/reglas.component.ts
- src/app/components/turnos/dar-turnos/calendario-dia.class.ts
- src/app/components/turnos/dar-turnos/calendario.component.ts
- src/app/components/turnos/dar-turnos/calendario.html
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
- src/app/modules/rup/components/ejecucion/help-solicitud.html
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaPrestacion.ts
- src/app/modules/rup/components/servicio-intermedio/servicio-intermedio-alta.component.html
- src/app/modules/rup/components/servicio-intermedio/servicio-intermedio-alta.component.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
- src/app/modules/rup/rup.module.ts
- src/app/modules/rup/services/huds.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/modules/rup/services/servicio-intermedio.service.ts
- Integración con servidor de imagenes
- Noción de servicio intermedios
- Solicitudes que no van al listado de TOP sino a los servicios intermedios
> pacs: primera version

- projects/auth/src/lib/auth.service.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
https://proyectos.andes.gob.ar/browse/RUP-262
Permite romper validación si tengo el permisos de validar extras
> feat(rup): romper validacion si tengo permisos

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
Fix mostrar ficha de epidemio en HUDS
1. 
2. 
3.
> HUDS: Fix Mostrar ficha epidemio

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
https://proyectos.andes.gob.ar/browse/IN-310
1. Filtra los sectores del combo para que muestre solo aquellos que tienen al menos una cama activa
> IN - Fix filtrar sectores sin camas activas

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
Deshabilitar submit cuando el request está en proceso.
https://proyectos.andes.gob.ar/browse/EP-102
1. 
2. 
3.
> EP: fix duplicidad de save

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-96
https://proyectos.andes.gob.ar/browse/EP-95
1. En el caso que se ingrese a visualizar una ficha epidemiologica, el bool de ficha parcial se pone en modo readonly.
2. Se agrega al clearDependencias la fecha de muestra para que no se guarde la sección. si esta tildada la ficha parcial.
3. Se agrega modal para ingresar a la huds de un paciente desde el modulo epidemiologia.
> Ficha Epidemio: Disabled carga parcial ficha 

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-313
1.  Agrega un retry por si falla la conexión.
> feat(mapa-camas): retry operation

- src/app/apps/vacunacion/components/filtros-vacunacion.component.ts
- src/app/apps/vacunacion/components/filtros-vacunacion.html
- src/app/apps/vacunacion/services/inscripcion.service.ts
https://proyectos.andes.gob.ar/browse/VAC-95
> vacunas: optimización de llamados a la api

- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/app.module.ts
- projects/portal/src/app/components/paciente-detalle.html
- projects/portal/src/app/pages/mis-datos-personales/mis-datos-personales.component.html
- projects/portal/src/app/pages/mis-datos-personales/mis-datos-personales.component.ts
- projects/portal/src/app/pages/mis-familiares/mis-familiares.component.ts
- projects/portal/src/app/services/paciente-portal.service.ts
https://proyectos.andes.gob.ar/browse/PDP-39
1. Se crea un componente nuevo para pode editar los datos personales del usuario (datos de contacto y de domicilio real)
> feat(PDP): Actualizar datos personales

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
https://proyectos.andes.gob.ar/browse/IN-314
1.  La internación tiene un limite de fecha implicito, se aumento a 12 meses.
> fix(mapa-camas): hisotrial de un año maxima

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Se agrega la posiblidad de filtrar por tipo de clasificación, para permitir a los data entries buscar el tipo de clasificación que les interesa.
https://proyectos.andes.gob.ar/browse/EP-91
https://proyectos.andes.gob.ar/browse/EP-101
1. 
2. 
3. 
https://github.com/andes/api/pull/1441/files
> feat(ficha): Se agrega el filtrado por clasificación en search de la ficha

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
https://proyectos.andes.gob.ar/browse/EP-97
1. Resize de sidebar de paciente en carga de ficha
2. 
3.
> EP: resize sidebar paciente

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-105
1. Se agregan las modificaciones en la vista para ocultar/visualizar según se seleccione o no un caso asintomático.
2. Se actualiza la función clearDependencias para tener la opción de ocultar toda la sección.
3. Se modifica la ficha COVID19 de acuerdo a los nuevos requerimientos.
> Ficha Epidemiologica: Caso asintomático

- src/app/components/carpeta-paciente/carpeta-paciente.component.ts
- src/app/components/carpeta-paciente/carpeta-paciente.html
https://proyectos.andes.gob.ar/browse/MISC-166
1. Se arreglo un bug que aparece cuando el usuario guarda el campo del número de carpeta con caracteres de "espacios en blanco" y esto generaba que no se visualizara el botón "REGISTRAR NUEVA CARPETA" 
2. Se verifica que al momento de editar el numero de carpeta no exista.
> fix(MISC-166): Bug al cargar numero de carpeta a un paciente

- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
https://proyectos.andes.gob.ar/browse/IN-301
1. Se agrega botón en formulario de ingreso para convertir una internación en censable
2. Si la internacion ya es censable se visualiza un badge en el formulario de ingreso junto a un botón 'deshacer'
3. Actualiza form de ingreso con componentes plex
> Mapa-camas - Marcar una internación como censable aunque la cama no lo sea

- src/app/apps/vacunacion/components/inscripcion.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
Modifica rango de edad para grupo de factores de riesgo
(queda pendiente realizar un refactor para tomar la edad desde la reglas en el grupo)
1. 
2. 
3.
> fix(inscripcion): modifica rango edad de FR

- src/app/components/paciente/headerPaciente.html
- src/app/components/paciente/headerPaciente.scss
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/MISC-178
1. Permite setear atributos 'size' e 'items' del componente plex-detail desde su componente padre paciente-detalle.
> MPI - Seteo de atributos en paciente-detalle

- src/app/utils/enumerados.ts
1.  Restaura la regla de estilo para prioridad intermedia que se perdio
2. 
3.
> COM: color prioridad intermedia

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/profesional/firma/firma-profesional.component.ts
- src/app/components/profesional/firma/firma-profesional.html
- src/app/components/profesional/firma/firma-profesional.scss
- src/app/components/profesional/profesional-create-update.component.ts
- src/app/components/profesional/profesional-create-update.html
- src/app/components/profesional/profesional.html
- src/app/services/profesional.service.ts
agrega libreria ng2ImgMax y componente firma-profesional para cargar/visualizar firma
https://proyectos.andes.gob.ar/browse/TM-15
1. Se agrega librería ng2ImgMax
2. Nuevo componente para editar/visualizar firma
> TM - Cargar firma de profesional fuera de matriculaciones 

- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/inscripcion.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/busqueda-paciente.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
- src/app/apps/vacunacion/interfaces/ICiudadano.ts
https://proyectos.andes.gob.ar/browse/VAC-91
https://proyectos.andes.gob.ar/browse/VAC-92
1. Al momento de seleccionar pasaporte el documento y el numero de tramite de se ocultan para que solo complete el numero de identificación
2. Queda en estado inhabilitado
> feat(VAC):inscripcion para extranjeros

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
```
TypeError: Cannot read property 'length' of null\n    at e.refreshSelection (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:3756998)\n    at https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:3744905\n    at Nl (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:1600347)\n    at r (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:1600507)\n    at u.i [as _next] (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:1671911)\n    at u.__tryOrUnsub (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:265546)\n    at u.next (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:264767)\n    at c._next (https://app.andes.gob.ar/main-es2015.bf565d8924cb94ebf2be.js:1:263938)\n    at c.next …
```
> fix(citas): corrige error de filtros

- package-lock.json
- package.json
Bump Plex v7.18.1 => v7.18.2
1. Plex con mejoras de accesibilidad en tabs
2. Algunos fixes visuales
> chore(plex): v7.18.2

- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
https://proyectos.andes.gob.ar/browse/VAC-86
1. Agrega botón para seleccionar fecha de próximo llamado.
2. Se reagrupan los botones y se agrega dropdown para distribuirlos.
> Vacunación -  Registrar fecha de próximo llamado

- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
- src/app/modules/perinatal/perinatal.module.ts
- src/app/modules/perinatal/services/carnet-perinatal.service.ts
https://proyectos.andes.gob.ar/browse/PER-32
1. Se agregaron dos filtros nuevos en el modulo de perinatal para buscar a un paciente por organizacion y/o por un profesional
> feat(PER-32): agregar filtros en modulo perinatal

- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
- src/app/apps/vacunacion/services/inscripcion.service.ts
https://proyectos.andes.gob.ar/browse/VAC-84
**IMPORTANTE: La funcionalidad del fechaProximoLlamado está implementado en este PR https://github.com/andes/app/pull/2344**
1. Agregar un botón para desasignar todos aquellos inscriptos que no tienen un turno asignado ni fechaProximoLlamado
2. Botón solo aparece con el permiso especial
> feat(VAC):agrega boton para desasignar inscriptos

- src/app/apps/vacunacion/components/nueva-inscripcion/busqueda-paciente.component.ts
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-74
1. Se controla los grupos según la edad del paciente
> feat(VAC):control de edades en nueva inscripción

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/rup.module.ts
Visualizar las ficha epidemiologica en HUDS de ejecución de RUP
1. 
2. 
3.
> EP fix: visualizar ficha en huds de rup

- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.component.ts
Linea borrada en rebase, donde en caso de que el documento sea igual a vació toma el numero de identificación para poder inscribir a personas extranjeras que tengan documentación en trámite.
> fix(VAC):número identificacion en caso documento en blanco

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
> EP: buscador fecha tipo date

- src/app/apps/vacunacion/components/editar-inscripcion.html
- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.html
En la inscripciones a la vacunación con factores de riesgo, a partir de  no es necesario presentar la prescripción médica
1. 
2. 
3.
> fix(inscripcion-vacunas): se quita requisito de certificado

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-316
1. se agrega idMovimiento al hacer un pase de servicio no se estaba guardando en la bd
2. 
3.
> fix(in): se agrega idMovimiento al hacer un pase de servicio

- src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/huds-lib.module.ts
- src/app/modules/rup/huds.module.ts
- src/app/modules/rup/services/frecuentesProfesional.service.ts
- src/app/modules/rup/services/huds.service.ts
- src/app/modules/rup/services/huds.store.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/modules/rup/views/huds-timeline/huds-timeline.component.html
- src/app/modules/rup/views/huds-timeline/huds-timeline.component.ts
Primer prototipo de visualización de la HUDS con Timeline. 
A revisar cosas visuales
> feat(huds): timeline

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/environments/environment.dev.ts
https://proyectos.andes.gob.ar/browse/IN-315
1. En el listado de internación se agrega un botón para anular la internación
2. 
3.
> feat(mapa-camas): listado-internación, deshacer egreso

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/historial-ficha/historial-ficha.component.html
- src/app/modules/epidemiologia/components/historial-ficha/historial-ficha.component.ts
Se remueve el save de historial de fichas del lado de la app, para delegarlo a la api
1. 
2. 
3.
> EP: refactor de historial de ficha

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-116
> feat(TOP): Control permisos

- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaPrestacion.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
https://proyectos.andes.gob.ar/browse/MISC-130
1. Botón editar prestación para vista-prestacion
2. 
3.
> feat(MISC): vista-prestacion boton editar

- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/projects/EP/issues/EP-106
1. 
2. 
3.
> EP: clasificación final en HUDS

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
Fix  en duplicidad de sidebar al visualizar un historial de ficha
1. 
2. 
3.
> EP: fix duplicidad sidebars buscador

- src/app/apps/vacunacion/components/inscripcion.component.html
- src/app/core/mpi/components/datos-basicos.html
https://proyectos.andes.gob.ar/browse/MPI-358
1. Admite letras en los campos de número de identificación de extranjeros
> MPI - Permite letras en nro. de identificación de extranjero

- src/app/apps/vacunacion/components/lote/lote-esquemas.compone.ts
- src/app/apps/vacunacion/components/lote/lote-esquemas.component.ts
- src/app/apps/vacunacion/components/lote/lote-esquemas.html
- src/app/apps/vacunacion/components/lote/lote.component.html
- src/app/apps/vacunacion/components/lote/lote.component.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/services/vacunas.service.ts
https://proyectos.andes.gob.ar/browse/VAC-88
1. Se muestran los esquemas y las condiciones de una dosis perteneciente a una vacuna.
2. Se incorporo la función de poder agregar una nueva dosis.
> VAC-88: Mostrar esquemas y condiciones de una dosis

- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/PER-37
1. Botón 'descargar' que se habilita filtrando por fechas desde-hasta para descargar un csv del listado
Agregar en colección 'queries'
{
"_id" : ObjectId("61016adf9dede83e3e6e0a1a"),
"nombre" : "listado-perinatal",
"coleccion" : "carnet-perinatal",
"query" : [ 
{
"!match" : {
"fecha" : {
"!gte" : "#fechaDesde",
"!lte" : "#fechaHasta"
}
}
}, 
{
"!addFields" : {
"ultimoControl" : {
"!arrayElemAt" : [ 
"$controles", 
-1
]
}
}
}, 
{
"!match" : {
"#profesional" : true,
"#organizacion" : true
}
}, 
{
"!project" : {
"_id" : 1,
"fechaControl" : {
"!dateToString" : {
"format" : "%d-%m-%Y %H:%M",
"date" : "$ultimoControl.fechaControl",
"timezone" : "America/Argentina/Buenos_Aires"
}
},
"apellido" : "$paciente.apellido",
"nombre" : "$paciente.nombre", …
> PER - Descargar listado de controles

- projects/auth/src/lib/auth.service.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
https://proyectos.andes.gob.ar/browse/COM-64
1. Al momento de iniciar una nueva derivación, invocar al componente de RUP para cargarlo como una prestación. 
2. 
3.
> COM: llamar directamente a pestación

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/huds/vistaContextoPrestacion.html
- src/app/modules/rup/components/huds/vistaContextoPrestacion.ts
- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaProcedimiento.html
- src/app/modules/rup/components/huds/vistaProcedimiento.ts
- src/app/modules/rup/components/huds/vistaRegistro.html
- src/app/modules/rup/components/huds/vistaSolicitudTop.html
- src/app/modules/rup/components/huds/vistaSolicitudTop.ts
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
https://proyectos.andes.gob.ar/browse/HUDS-39
1. : Se agrega estado solicitud en el listado y un link a la prestación si esta validada
2. 
3.
> feat(HUDS): se agrega estado solicitud y link a la prestación

- src/app/components/organizacion/organizacion-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-191
1. Se realizo cambio en if que evalua el dato fsn de la prestacion, ya que en en la BD de Produccion las ofertas prestacionales tienen un formato distinto a como están en Demo, esto soluciona que no salgan errores por  consola, pero habría que evaluar el formato correcto de las ofertas prestacionales en producción.
> TM - Error fsn undefined

- src/app/modules/rup/components/ejecucion/buscador.component.ts
https://proyectos.andes.gob.ar/browse/RUP-270
1. Los sugeridos se estaban ordenando de forma inversa a como están en la Base de Datos.
> RUP - Invierte el orden de los sugeridos 

- src/app/modules/rup/components/elementos/vacunas.component.ts
https://proyectos.andes.gob.ar/browse/RUP-273
1. Filtra las solicitudes durante el historial de vacunas para que no se las detecte como dosis aplicadas
> VAC - Solicitudes de Campaña de Vacunación

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-109
https://proyectos.andes.gob.ar/browse/EP-110
https://proyectos.andes.gob.ar/browse/EP-111
1. Se actualizo el select del filtro de clasificación de acuerdo a la actualizacion de la ficha.
2. Se agrega el type date al plex-datetime de la vacuna antigripal para que no aparezca la hora.
3. Se cambia la forma de guardar la organizacion en la seccion "Usuario" para que quede de la forma:
`organizacion:{
id: idOrganizacion,
nombre: nombreOrganizacion
}`
[fichaLaboratorio.txt](https://github.com/andes/app/files/6879338/fichaLaboratorio.txt)
> Epidemiología: Save organización y actualizacion filtro clasificación

- src/app/modules/rup/views/huds-timeline/huds-timeline.component.html
- src/app/modules/rup/views/huds-timeline/huds-timeline.component.ts
- src/app/modules/rup/views/huds-timeline/huds-timeline.scss
https://proyectos.andes.gob.ar/browse/HUDS-42
Navegar a http://localhost:4200/huds/timeline/:id (id del paciente seleccionado)
1. Se estilizan componentes del timeline (items, segmentos, grupos y sus estados interactivos).
2. Se estiliza listado incorporando plex-labels e iconografía.
3. Se estiliza sidebar y registros que allí se visualizan.
> feat(huds): aplica estilos a timeline

- src/app/components/organizacion/organizacion.component.ts
- src/app/components/organizacion/organizacion.html
https://proyectos.andes.gob.ar/browse/MISC-189
1. Envía nombre de usuario en lugar de ids de organizaciones para obtener el listado de efectores
> TM - Control de permisos cargando organizaciones del usuario

- src/app/modules/rup/components/elementos/vacunas.component.ts
Permite detectar la primera dosis desde RUP o desde Nomivac para el caso de que la primera dosis haya sido aplicada en otra provincia. 
https://proyectos.andes.gob.ar/browse/VAC-100
1. Permite combinar aplicaciones con dosis de otras vacunas
> VAC - FIX Registro de segundas dosis combinadas

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
https://proyectos.andes.gob.ar/browse/EP-124
1. Se eliminan row y col para que solo quede plex y se calcula la altura del plex-list para eliminar el espacio en blanco que se veia al final de la lista.
> Epidemiología - Espacio en blanco al final de la tabla de seguimiento

- src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.component.ts
- src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
- src/app/modules/epidemiologia/components/seguimiento/detalle-seguimiento/detalle-seguimiento.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
https://proyectos.andes.gob.ar/browse/EP-125
1. Modo auditor: se reestringe actualización de seguimiento (excepto contactos), para permisos de auditor
2. 
3.
> EP: audición de seguimientos

- src/app/modules/rup/components/elementos/vacunas.component.ts
https://proyectos.andes.gob.ar/browse/RUP-279
1. Recarga valores al iniciar el componente.
> RUP - Seleccion de dosis despues de romper validacion

- src/app/modules/estadisticas/components/citas/graficos.component.ts
- src/app/modules/estadisticas/components/top/top.html
https://proyectos.andes.gob.ar/browse/BI-81
1.  Se arregla el dashboard de TOP
2. 
3.
> BI: arreglar dashboard TOP

- src/app/modules/epidemiologia/pipes/checkEdit.pipe.ts
https://proyectos.andes.gob.ar/browse/EP-135
1. Se busca las organizaciones dentro del auth del usuario para cheuquear las organizaciones activas correctamente.
> Epidemiología - No se muestra boton editar

- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-99
1. Al momento de editar inscripción que en el combo de grupos poblacionales salgan filtrados los grupos correspondientes a las reglas según la edad del paciente.
> VAC - Control reglas grupo poblacional

- src/app/modules/estadisticas/components/citas/graficos.component.ts
- src/app/modules/estadisticas/components/citas/graficos.html
https://proyectos.andes.gob.ar/browse/BI-79
https://proyectos.andes.gob.ar/browse/BI-80
1. Setea un maximo de prestaciones y profesionales para mostrar en el grafico
> Dashboards CITAS - Turnos por Prestación/Profesional

- src/app/components/organizacion/organizacion.component.ts
- src/app/components/organizacion/organizacion.html
- src/app/services/organizacion.service.ts
https://proyectos.andes.gob.ar/browse/MISC-190
1. Actualiza template de organizaciones.component, implementa plex-table con scroll infinito.
> TM organizaciones: Agregar permiso global

- src/app/modules/rup/components/elementos/vacunas.component.ts
En listado de dosis aplicadas aparecen duplicadas el registro de la prestación y el que figura en nomivac.  El filtro no estaba funcionando debido a que fallaba la comparación de vacunas por código
1. 
2. 
3.
> fix(vacuna): filtra vacunas por código

- src/app/components/inicio/inicio.html
- src/app/components/inicio/inicio.scss
1. Se incrementa automáticamente la altura de contenedor de módulo si tiene 4 o más submódulos (evita superposición)
2. Se acelera animación de splash
3. Se mejora ubicación de hints en Secciones
> Módulos inicio: mejoras visuales en contendedores y hints en secciones

- src/app/components/inicio/inicio.html
Corregir bug en inicio (carga de módulos)
1. 
2. 
3.
> fix(inicio): Agrega control en submodulos

- src/app/apps/vacunacion/components/detalle-inscripcion.html
- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
https://proyectos.andes.gob.ar/browse/VAC-103
1. Nuevo estado "no completa esquema"
> VAC - Agrega nuevo estado de inscripción

- src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.component.ts
- src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
- src/app/modules/epidemiologia/components/seguimiento/asignar-seguimientos/asignar-seguimientos.component.ts
- src/app/modules/epidemiologia/components/seguimiento/asignar-seguimientos/asignar-seguimientos.html
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
- src/app/modules/epidemiologia/contantes.ts
- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/epidemiologia/pipes/seguimientoFields.pipe.ts
- src/app/modules/epidemiologia/services/seguimiento-pacientes.service.ts
https://proyectos.andes.gob.ar/browse/EP-123
1. Se agrega la posibilidad de asignar profesional a seguimientos por parte de auditor
2. FIltro de profesional
3.
> EP: Asignar seguimiento a profesional

- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/components/reportes/encabezadoReportes.html
https://proyectos.andes.gob.ar/browse/MISC-188
1. Filtro opcional de organizacion para reporte C2
2. 
3.
> Visualizador: filtrar reportes c2 x organización

- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/MISC-185
(Al cancelar la dación de un turno para vacunación, no se agregaba el paciente a la lista de espera)
1. Se agrega registro con datos de paciente, prestacion, etc a lista de espera
> MISC (VAC) - Demanda rechazada

- projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.html
- projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.ts
- projects/portal/src/app/components/dar-turno/dar-turno.component.html
- projects/portal/src/app/components/dar-turno/dar-turno.component.ts
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
https://proyectos.andes.gob.ar/browse/PDP-63
https://proyectos.andes.gob.ar/browse/PDP-75
1- Corrige visualización de datos al confirmar turno
2- Corrige filtro de turnos del paciente previo a mostrar las agendas futuras
> PDP - Visualización de datos en confirmación de turno

- projects/portal/src/app/pages/registro-cuenta/registro-cuenta.component.html
En el https://github.com/andes/app/pull/2443 quedó mal el formato de la imágen del frente del dni.
> PORTAL - Arreglo en formato de imagen 

- projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
- projects/portal/src/app/services/turno.service.ts
https://proyectos.andes.gob.ar/browse/PDP-72
1. Se separa la visualización de turnos pendientes e historicos
> PDP - Visualizacion de turnos pendientes

- src/app/components/reportes/encabezadoReportes.component.ts
Agrega reporte de consulta por prestación
1. 
2. 
3.
> fix(reporte): agrega reporte por prestación

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/pipes/seguimientoFields.pipe.ts
https://proyectos.andes.gob.ar/browse/EP-137
1.  Fix en limpieza de items chequeados al realizar nueva búsqueda
2. 
3.
> EP: fixes mergeo asignacion

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
https://proyectos.andes.gob.ar/browse/EP-140
1. 
2. 
3.
> EP: filtrar seguimientos activos

- projects/portal/src/app/app.module.ts
- projects/portal/src/app/components/paciente-detalle.component.ts
- projects/portal/src/app/components/paciente-detalle.html
- src/app/services/logPaciente.service.ts
https://proyectos.andes.gob.ar/browse/PDP-73
1. Guarda reporte, importa servicio logPaciente
> PDP - Guarda reporte de error

- projects/portal/src/app/pages/mis-turnos/mis-turnos-detalle.component.ts
- projects/portal/src/app/pages/mis-turnos/mis-turnos-detalles.component.html
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
- src/app/directives/feature-flag.directive.ts
- src/app/interfaces/turnos/IAgenda.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/CIT-113
1. se agrega campo link para generar una agenda virtual 
2. se agrega icono para acceder a esa agenda virtual si la agenda es virtual desde inicio de RUP 
3.
> feat(CIT): consultorio virtual

- src/app/apps/vacunacion/components/detalle-inscripcion.component.ts
- src/app/apps/vacunacion/components/detalle-inscripcion.html
https://proyectos.andes.gob.ar/browse/VAC-75
1. Se muestran los datos del certificado en detalle de inscripción en los casos en que corresponda
> VAC: datos de certificado en detalle inscripción

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
https://proyectos.andes.gob.ar/browse/EP-142
1. Agrego opción multiple en select de instituciones.
2. 
3.
> EPIDEMIOLOGÍA -Permitir seleccionar mas de una institucion en ficha COVID 19

- src/app/modules/estadisticas/components/citas/graficos.component.ts
https://proyectos.andes.gob.ar/browse/BI-90
> BI Fix- No se limpian datos de leyenda

- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/components/reportes/encabezadoReportes.html
- src/app/components/reportes/reporteC2.component.ts
- src/app/components/reportes/reporteC2.html
https://proyectos.andes.gob.ar/browse/BI-89
1. Mejora visual, muestra detalle de pacientes de diagnosticos en sidebar
2. <a href="https://www.loom.com/share/50d61b282141469f903b5deb12ec1c40">
<p>Andes | Apps De Salud - Watch Video</p>
</a>
2. 
3.
> BI: mejora visual reportes c2

- .eslintrc.js
- projects/portal/src/app/components/paciente-detalle.component.ts
- src/app/components/puco/puco.component.ts
Nuevas reglas de espaciado y formateo de código.
> chore(eslint): reglas espaciados

- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
https://proyectos.andes.gob.ar/browse/RUP-259
1. Al continuar con la consulta en el RUP el array de organizaciones no se volvía a cargar , se hizo un cambio en el control y quedo funcionando
2. 
3.
> rup: se corrige error al seleccionar una organización en solicitudes
