- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/components/reportes/encabezadoReportes.html
https://proyectos.andes.gob.ar/browse/BI-87
1.  FIltro de zona sanitaria en generador de reportes
2. 
3.
> BI: filtro de zona para reportes

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
- src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
…nes el permiso de ver mapaDeCama
https://proyectos.andes.gob.ar/browse/IN-323
1. se agrega funcion para agregar el permiso ver registros si tenes permisos de mapa de cama 
2. 
3. 
- [] No corresponde
- [] No
> feat(mapa-camas): permisos para ver registros

- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
- src/app/apps/vacunacion/components/notas.component.ts
- src/app/apps/vacunacion/components/notas.html
https://proyectos.andes.gob.ar/browse/VAC-61
1. Se realizó una reunión para el diseño de esta sección en el sidebar ya que se agrego la opción de eliminar notas. La cual cuenta con una versión para cuando el inscripto tiene o no tiene una nota cargada.
> VAC - Permitir borrar notas

- src/app/modules/perinatal/services/carnet-perinatal.service.ts
https://proyectos.andes.gob.ar/browse/PER-49
1. Se cambio el filtro de la busqueda de fechas donde anteriormente lo hacia por fechas del carnet y ahora por fechas de la colección de controles.
> refactor(PER-49): filtro por fechas de control

- src/app/modules/epidemiologia/components/seguimiento/asignar-seguimientos/asignar-seguimientos.html
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
https://proyectos.andes.gob.ar/browse/EP-131
1. Se crea un filtro para ocultar los seguimientos asignados.
2. Refactor de variables.
> Epidemiología -  Crear filtro en seguimientos para pacientes asignados

- src/app/modules/mpi/components/paciente-detalle.html
- src/app/modules/mpi/components/paciente-listado.html
- src/app/modules/mpi/components/paciente-panel.html
https://proyectos.andes.gob.ar/browse/MPI-361
1. Elimina el formato 'utc' para mostrar fecha de nacimiento del paciente
> MPI (Fix) - Error al visualizar fecha de nacimiento

- src/app/modules/rup/components/huds/vista-ips.component.html
- src/app/modules/rup/components/huds/vista-ips.component.ts
https://proyectos.andes.gob.ar/browse/IO-18
> fix(ips): handler de secciones vacías

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/services/servicio-intermedio.service.ts
Agrupa las solicitudes pendientes por servicio intermedio en el punto de inicio RUP  
https://proyectos.andes.gob.ar/browse/PACS-32
> RUP: separa items por servicio intermedio

- src/app/components/top/reglas/visualizacionReglas.component.ts
- src/app/components/top/reglas/visualizacionReglas.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/RUP-278
1. en el listado de reglas se agrega un botón 
2. Al hacer click en el botón debe agregar el concepto a la consulta en modo solicitud.
3.
> feat(RUP): acceso rapido a solicitud desde reglas

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
- src/app/apps/gestor-usuarios/views/usuarios-list.view.html
https://proyectos.andes.gob.ar/browse/GDU-34
1. Que el detalle del usuario no scrollee con el resto del contenido
> GDU: mejoras usabilidad

- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
- src/app/interfaces/IProfesional.ts
- src/app/services/profesional.service.ts
https://proyectos.andes.gob.ar/browse/GDU-32
1. Mostrar información de matriculación en detalle de usuario
> GDU: mostrar en detalle si el profesional esta matriculado

- src/app/modules/rup/components/elementos/rupers/select-base.component.ts
https://proyectos.andes.gob.ar/browse/RUP-285
En RUP al estar registrando una prestación, se agrega un concepto automaticamente con el "select". Necesario para precargar un concepto elegido con "SelectSnomed".
Para probarlo agregar "addRegister" : true en "params" de la molécula.
1. 
2. 
3.
> RUP: agrega concepto en select

- src/app/directives/organizacion-select.directive.ts
https://proyectos.andes.gob.ar/browse/BI-92
> Dashboard TOP (Fix) - Filtro de organización

- src/app/modules/epidemiologia/components/seguimiento/actualizar-seguimiento/actualizar-seguimiento.html
https://proyectos.andes.gob.ar/browse/EP-147
1. Se habilita el semáforo de repriorización para usuarios de seguimiento
> EP: habilitar priorización a seguimiento

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-127
1. Si se hace click en ventanilla virtual, verificar que definan una cantidad de turnos mobile mayor a 0
2. Al cambiar la cantidad de turnos, si los programados terminan en 0 limpiar la selección de ventanilla virtual y los turnos asociados.
> CIT: validaciones de turnos ventanilla virtual

- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-45
1. se agrega un timestamps al _id para corregir el error .
2. 
3.
> HUDS:error al cargar dos historias clínicas el mismo día

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
https://proyectos.andes.gob.ar/browse/RUP-277
1. se agrega control en el botón validar , paciente existe puedo validar.
2. 
3. 
- [] No
> RUP: error,propiedad id indefinida

- src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
- src/app/modules/estadisticas/components/rup/rup-pacientes.html
- src/app/modules/estadisticas/components/rup/rup-pacientes.scss
se encapsulan filtros en un plex-help para aprovechar mejro el espacio
https://proyectos.andes.gob.ar/browse/BI-93
1. Se reemplaza la sección de filtros por un un plex-help con el fin de aprovechar el espacio de la pantalla. Des esta manera también se soluciona el el requerimiento de la tarea.
> Dashboard HUDS (Fix) - Filtros que se ocultan

- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
ademas se realiza un refactor visual
https://proyectos.andes.gob.ar/browse/CIT-128
1. Agrega filtro por ámbito origen (ambulatorio)
> CITAS (Fix) - Auditar fuera de Agenda: trae registros de internación

- src/app/app.routing.ts
- src/app/apps/mitos/directives/select-semantic/select-semantic.directive.ts
- src/app/apps/mitos/mitos.module.ts
- src/app/apps/servicios-intermedio/pipes/servicio-intermedio-nombre.pipes.ts
- src/app/apps/servicios-intermedio/servicios-intermedio.module.ts
- src/app/apps/servicios-intermedio/views/servicio-intermedio-crud/servicio-intermedio-crud.component.html
- src/app/apps/servicios-intermedio/views/servicio-intermedio-crud/servicio-intermedio-crud.component.ts
- src/app/apps/servicios-intermedio/views/servicio-intermedio-listado/servicio-intermedio-listado.component.html
- src/app/apps/servicios-intermedio/views/servicio-intermedio-listado/servicio-intermedio-listado.component.ts
- src/app/directives/directives.module.ts
- src/app/directives/servicio-intermedio.directive.ts
- src/app/modules/rup/services/servicio-intermedio.service.ts
- src/app/services/conceptos-turneables.service.ts
- src/app/services/top/reglas.service.ts
https://proyectos.andes.gob.ar/browse/PACS-29
> TOP: abm reglas servicio intermedio

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-162
1. Filtrar fichas sin clasificación final
2. 
3.
> EP: filtro sin clasificación final

- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
https://proyectos.andes.gob.ar/browse/RUP-293
1. Se agrego una condición en el método enviarPDF para controlar si lo que viene es un objeto con parámetros cargados o si es nulo.
> Error en la consola al abrir modal de envio de PDF

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-contactos/ficha-epidemiologica-contactos.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/constantes.ts
- src/app/modules/epidemiologia/pipes/codigoSisa.pipe.ts
- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
https://proyectos.andes.gob.ar/browse/EP-163
1. Parametrización de nombre de sección clasificación final
2. 
3.
> EP: parametrización clasificación final

- src/app/modules/estadisticas/components/citas/citas.component.ts
- src/app/modules/estadisticas/components/citas/citas.html
- src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
- src/app/modules/estadisticas/components/rup/rup-pacientes.html
- src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts
- src/app/modules/estadisticas/components/tabla-2d/tabla-2d.html
- src/app/modules/estadisticas/components/top/filtrosSolicitudes.component.html
- src/app/modules/estadisticas/components/top/top.component.ts
- src/app/modules/estadisticas/components/top/top.html
https://proyectos.andes.gob.ar/browse/BI-107
1. Dashboard solicitudes: Se aplico plex-wrapper para los filtros y plex-label para mensaje inicial de la pantalla
2. Dashboard citas: se aplicó plex-table para la tabla de localidades
3. Dashboard huds: plex-table para las prestaciones y registros, actualización plex-sidebar general de los conceptos utilizados en registros y plex-label para mensaje inicial de la pantalla.
4. Se sacó del navbar /Dashboard/ ya que esta pantalla quedo en blanco luego de la actualización que se en la pantalla inicial de ANDES.
> BI -  Actualización plex-layout en dashboard

- src/app/components/organizacion/organizacion-create-email.component.ts
- src/app/components/organizacion/organizacion-create-email.html
- src/app/components/organizacion/organizacion.html
- src/app/services/organizacion.service.ts
https://proyectos.andes.gob.ar/browse/TM-17
1. Agrega label en caso de efector sin servicios
2. Elimina footer. Los botones quedan en el title, a la derecha
3. Agrega botón editar. Mientras no se este editando ningun servicio, los campos no pueden modificarse
4. Agrega boton volver
5. Al guardar cambios, redirecciona al listado de organizaciones
> TM - Refactor de pantalla de configuración de servicios

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-167
1. eliminar ficha con permiso restrictivo
2. 
3.
> EP: eliminar ficha

- package-lock.json
- package.json
- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
https://proyectos.andes.gob.ar/browse/PER-57
1. Se realizó un pequeño cambio en la columna del estado, agregandole un label y una función vacia ya que el sorteable:false no funcionaba. Sin esto, si se le hacia click a esa columna ocurria que se rompia el listado (scroll y sort de las demas columnas)
2. Por sugerencia de UI/UX se realizo cambio de badge para que en lugar de un boton que no tenia acción, sea solo con ícono.
> PER - Arreglo en columna de ausente

- src/app/modules/rup/components/elementos/vacunas.component.ts
https://proyectos.andes.gob.ar/browse/VAC-10
1. Emite un aviso al usuario cuando las dosis permitidas ya estan aplicadas
> VAC (Fix) - Avisa al usuario acerca de dosis ya aplicadas

- src/app/components/inicio/inicio.scss
Se detectó una altura incorrecta en el listado de módulos
1. Se fuerza un alto máximo para mantener el contenedor de submódulos alineados.
> fix(inicio): corrige altura de módulos reducidos

- angular.json
- projects/form-builder/README.md
- projects/form-builder/karma.conf.js
- projects/form-builder/ng-package.json
- projects/form-builder/package.json
- projects/form-builder/src/lib/form-builder-item/form-builder-item.component.html
- projects/form-builder/src/lib/form-builder-item/form-builder-item.component.ts
- projects/form-builder/src/lib/form-builder.module.ts
- projects/form-builder/src/lib/form-builder.service.ts
- projects/form-builder/src/lib/form-builder/form-builder.component.html
- projects/form-builder/src/lib/form-builder/form-builder.component.ts
- projects/form-builder/src/lib/interfaces.ts
- projects/form-builder/src/public-api.ts
- projects/form-builder/src/test.ts
- projects/form-builder/tsconfig.lib.json
- projects/form-builder/tsconfig.lib.prod.json
- projects/form-builder/tsconfig.spec.json
- projects/form-builder/tslint.json
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
- src/app/modules/rup/elementos-rup.module.ts
- tsconfig.json
Campos especificos para diferentes tipos de solicitudes. Queda un ejemplo en DEMO (no real). Concepto a solicitar (prueba de laboratorio).
1.  Se crea un modulo de formuladrios dinámicos.
2.  Se agrega a las reglas de solicitudes templates dinamicos de formularios.
3.  Se adapta la molécula de solicitudes para renderizar estos formularios.
4.  Se modifica la impresión de solicitudes.
> rup: campos dinámicos para solicitudes

- src/app/components/profesional/profesional-create-update.component.ts
- src/app/components/profesional/profesional-create-update.html
https://proyectos.andes.gob.ar/browse/TM-18
1. Nuevo campo observaciones en profesional
> TM: nuevo campo observaciones en profesional

- src/app/modules/perinatal/components/listado-perinatal.component.ts
- src/app/modules/perinatal/services/carnet-perinatal.service.ts
https://proyectos.andes.gob.ar/browse/PER-56
1. Se corrigió el error de que al ingresar una fecha te lo autocompletaba, en los filtros "fecha de cita" y "fecha ultimo control".
2. Dentro de los filtros "fecha de cita" y "fecha ultimo control" tambien se corrigio para que trajera mas de un elemento en caso de tener misma fecha.
> Arreglando filtros en el modulo perinatal

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-340
> IN (Fix) - Corregir los códigos de causa externa en el formulario de egreso - capa estadística

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
https://proyectos.andes.gob.ar/browse/GDU-41
1. Plex-confirm al borrar los permisos de una organización
> GDU: confirmación al eliminar los permisos de una organización

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
[IN - resumen-internación: navegación con flechas
](https://proyectos.andes.gob.ar/browse/IN-296
)
1. Al seleccionar un procedimiento en la linea del tiempo del resumen, se puede navegar entre los items con las flechas del teclado
2. Fix de permisos no reconocidos para acceder a mapa-camas cuando tus permisos son '*'
> feat(mapa-camas): navegación con flechas en resumen de internación

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/TOP-120
1. Se buscaron desde la base las solicitudes de top y se lo concatena al arreglo de prestaciones.
2.
> Visualización de solicitudes en ejecución en RUP

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-352
> IN (Fix) - Error capa médica días estada

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-144
1. Se cambio la condición de la operación ternaria que verificaba si existía una fecha de una agenda seleccionada. También se cambio el atributo fecha de la constante listaEspera para que esta misma no dependiera de la fecha de la agenda.
> CIT: Guardar prestación en demanda rechazada

- src/app/modules/rup/components/elementos/vacunas.component.ts
https://proyectos.andes.gob.ar/browse/VAC-105
1. Controla que la edad del paciente este dentro del rango especificado por la dosis
> VAC - Agrega control etareo segun dosis

- src/app/apps/campaniaSalud/components/campania-create-update.html
- src/app/apps/campaniaSalud/components/campaniaSalud.component.ts
- src/app/apps/campaniaSalud/components/campaniaSalud.html
- src/app/apps/campaniaSalud/components/campaniaVisualizacion.component.ts
- src/app/apps/campaniaSalud/components/campaniaVisualizacion.html
https://proyectos.andes.gob.ar/browse/MISC-204
1. Refactor de componentes de campañas de salud
> MISC:  refactor de componentes de campaña de salud

- src/app/components/puco/puco.component.ts
- src/app/components/puco/puco.html
https://proyectos.andes.gob.ar/browse/MISC-205
1. Refactor plex de pantalla de padrones
> MISC: refactor de pantalla de padrones

- src/app/components/top/reglas/reglas.component.html
- src/app/components/top/reglas/reglas.component.ts
- src/app/components/top/solicitudes/solicitudes.html
se actualiza además el uso de componentes plex en el template
https://proyectos.andes.gob.ar/browse/TOP-121
1. Actualiza uso de componentes plex
2. Refactor para eliminación de organización de origen (con todas sus reglas) o todas las prestaciones origen de una organizacion
> TOP (Fix) - Eliminación de ultima regla

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-152
1. 
2. 
3.
> CIT: fix frecuentes duplicados

- src/app/components/organizacion/organizacion-create-update.component.ts
- src/app/components/organizacion/organizacion-create-update.html
- src/app/components/organizacion/organizacion.html
- src/app/components/organizacion/organizacion.scss
- src/app/core/mpi/components/georref-map.scss
https://proyectos.andes.gob.ar/browse/TM-16
1. Refactor de pantalla de tablas maestras organizaciones
> TM: refactor pantalla organizaciones

- src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso-dinamico/ingreso-dinamico.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
https://proyectos.andes.gob.ar/browse/IN-355
1. Se visualiza diagnostico en historal
2. Se visualizan los conceptos de valoración inicial en capa estadistica con +- 12 horas.
3.
> feat(IN): mostrar registro de diagnostico al ingreso

- src/app/components/turnos/dar-turnos/calendario.scss
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-150
1. 
2. 
3.
> citas: refactor visual header dar turno

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/services/profesional.service.ts
- src/styles.scss
https://proyectos.andes.gob.ar/browse/MISC-203
1. Se muestra un detalle del profesional que se encuentra logueado con la información de sus profesiones. En caso de no estar logueado no se muestra nada de lo dicho anteriormente.
> MISC - Visualización de las matriculas de un profesional

- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
https://proyectos.andes.gob.ar/browse/TOP-26
1. Elimina código comentado y corrige título
> TOP - Suspensión de turno dado a solicitud

- src/app/modules/rup/components/core/rup.component.ts
Fix al levantar una molecula vieja no estaba buscando por el id del elementoRUP del registro, sino por el nuevo elementoRUP.
> fix(rup): busqueda de elementoRUP por id en molecula

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-357
1. Si esta en borrador, se edita directamente. 
2. Si ya esta validada, (internamente) se suspende la actual y se cargar una nueva.
3.
> feat(mapa-camas): plan-indicaciones, editar una indicación

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-141
1. Agrega select para filtrar agendas por profesional
> CITAS - Filtro por profesional en auditoría de fuera de agenda

- src/app/modules/perinatal/components/listado-perinatal.component.ts
https://proyectos.andes.gob.ar/browse/MISC-208
1. Se modificaron los mensajes del plex-toast cuando se crea y edita una nota en el modulo perinatal.
> MISC - Cambiar mensaje del toast al crear una nueva nota

- src/app/components/turnos/dar-turnos/calendario.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
https://proyectos.andes.gob.ar/browse/CIT-148
1. Permite dar un sobreturno desde una agenda sin turnos, en punto de inicio de Citas
2. 
3.
> CIT: dar sobreturno desde punto inicio

- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
se realiza refactor en proporcion de layout y algunos componentes plex
https://proyectos.andes.gob.ar/browse/CIT-137
1. Fix del bug descrito en la task
2. Refactor de pantalla, redimensión de layouts y se actualiza uso de algunos componentes plex en templates relacionados
> CITAS (Fix) - Turno en agenda no nominalizada ya auditada

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
- src/app/modules/rup/elementos-rup.module.ts
Nueva molécula para prescribir medicamentos en la internación. Se desacopla de los _formacos de uso clinicos_ ya que no eran representativos en la internación.
> feat(mapa-camas): prescripcion de medicamentos internacion

- src/app/interfaces/ITipoPrestacion.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-276
1. un turno es multiprestacion , ejemplo pueden ejecutar el mismo turno un psiquiatra y un psicólogo
2. la funcionalidad es la misma en sobreturnos
3. 
las prestaciones son : consulta de psiquiatría , consulta de psicología  y consulta con alergista
> RUP: turno Multiprestacion 

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
No controla quien hizo la prestacion.
> fix(rup): permisos turnos

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-299
1. Fix en envio de parametro de turno para creacion de prestación de agenda no-nommimnalizada
2. 
3.
> RUP: continuar registro no nominalizada

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-177
1. Se modifica el calculo de la semana epidemiologica para que funcione correctamente,
2. Se agrega debounce al campo fecha de inicio de síntomas para evitar llamados innecesarios a la funcion.
> Epidemiolgia - Error en semana epidemiológica

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
> fix(rup): controles de permisos

- src/app/modules/rup/components/elementos/vacunas.component.ts
Se deben poder visualizan todas las dosis de una vacunas con esquema de excepciones.
https://proyectos.andes.gob.ar/browse/VAC-121
1. 
2. 
3.
> VAC: se visualizan todas las dosis de una vacunas con excepciones

- src/app/modules/rup/components/elementos/FormulaBase.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.html
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
https://proyectos.andes.gob.ar/browse/PER-65
1. Agrega param 'valorEditable' en elementoRUP de formulaBase (edad gestacional) que permite editar manualmente el valor de edad gestacional.
2. Agrega bool en componente formulaBase para los registros que permitan ingresar el valor manualmente (valorEditable = true). Cuando el bool esta activo, desaparecen visualmente los registros requeridos y permite que el uss pueda ingresar a mano el valor final.
> RUP (Fix) - Poder editar valor de edad gestacional

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-116
1. Se agrego la propiedad multiple al html de turnos-prestaciones.
2. Se modifico el atributo financiadores y la condicion donde tipo es igual a financiador
> MISC - filtro multiple de obras sociales

- src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
- src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/interfaces/ITipoPrestacion.ts
- Desde internacion, si se quiere agregar un nuevo registro a una cama, mostrar prestaciones de RUP que:
- Tengan ambito internacion
- El usuario tiene permisos para verlas en RUP
- La capa en la que esta, tenga permisos para mostrar estas prestaciones
1. Se modificaron interface ITipoPrestacion, el shema conceptosTurneables y la API para saber los ambitos a los que pertenece una prestacion.
2. Se agrego nueva capa "interconsultores" 
3. Se checkean los permisos para mostrar las prestaciones que tenes permisos, en cada capa internacion con un flag checkRupTiposPrestacion en estado de cama 'ocupada'
> feat(in): nueva capa 'interconsultores'

- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/app.module.ts
- projects/portal/src/app/components/dar-turno/dar-turno.component.html
- projects/portal/src/app/components/dar-turno/dar-turno.component.ts
- projects/portal/src/app/pages/mis-turnos/mis-turnos-detalle.component.ts
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
- projects/portal/src/app/pages/mis-turnos/notificar-necesidad.component.html
- projects/portal/src/app/pages/mis-turnos/notificar-necesidad.component.ts
https://proyectos.andes.gob.ar/browse/PDP-76
1. Nuevo formulario para dejar constancia de una demanda insatisfecha de turno (mis turnos > boton 'notificar necesidad de turno')
> PDP - Demanda insastifecha

- src/app/core/mpi/components/datos-contacto.component.ts
https://proyectos.andes.gob.ar/browse/MPI-367
1. Como los datos de renaper no vienen correctamente se modifico la función direccionLegal() para que muestre solamente aquellos datos que si vienen de este mismo.
> MPI - Domicilio legal de un paciente

- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-378
> feat(mapa-camas): ajustes a prescripción de medicamentos

- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/CORE-101
1.  Se agrega parametro _idField_ a los argumentos de bi query.
> feat(bi-query): campo key configurable

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
https://proyectos.andes.gob.ar/browse/CIT-149
1. Se agrego un botón "comprobante" para aquellos pacientes que tienen obra social o cuando se selecciona una prepaga.
2. Si tiene una obra social o no, se puede seleccionar una prepaga y generar el comprobante.
MS Facturación: https://github.com/andes/andesMicroservices/pull/174
> CIT - Agregar botón de generar comprobante en el buscador de turnos y prestaciones

- .eslintrc.js
- projects/form-builder/src/lib/form-builder-item/form-builder-item.component.ts
- projects/form-builder/src/lib/form-builder.module.ts
- projects/form-builder/src/lib/form-builder/form-builder.component.ts
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/integridad/integridad.service.ts
- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
- src/app/components/organizacion/organizacion-create-email.component.ts
- src/app/components/organizacion/organizacion-create-update.component.ts
- src/app/modules/rup/components/huds/listado-internacion-huds.component.ts
- src/app/services/especialidad.service.ts
- src/app/services/formTerapeutico/formTerapeutico.service.ts
- src/app/services/xlsx.service.ts
https://proyectos.andes.gob.ar/browse/IN-365
https://proyectos.andes.gob.ar/browse/IN-306
> fix(mapa-camas): errores egresos

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-132
1. Se agregaron tooltips en los botones "exportar" y "descargas pendientes".
2. Al momento de exportar uno o varios elementos del listado se abre automáticamente el sidebar de descargas pendientes para evitar realizar varios clicks.
> MISC - Mejoras en el buscador de turnos y prestaciones

- src/app/app.module.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/modal-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/modal-agenda.scss
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/services/turnos/agenda.service.ts
https://proyectos.andes.gob.ar/browse/CIT-158
1. Se recupera el primer elemento del arreglo 'seleccionados' de tal forma que si se intento clonar sobre una agenda con el mismo profesional o espacio físico, pueda volver a seleccionar otras fechas y generar la acción clonar sin problemas.  
2. 
3.
> CIT - verificar solapamiento al clonar agendas

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Separar boton de exportar con el de descargar nuevo
1. 
2. 
3.
> fix(turnos-prestaciones): separa boton

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
https://proyectos.andes.gob.ar/browse/MISC-215
Corrige facturación sumar en turnos con agendas
1. Se quitan cambios realizados anteriormente, ya que ahora se resuelve desde el MS facturación https://github.com/andes/andesMicroservices/pull/175
2. 
3. 
https://github.com/andes/andesMicroservices/pull/175
> Buscador de Turnos: Corrige facturación sumar en turnos con agendas

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-186
1. Se elimina la automatización del campo "Estado de vacunación" de la ficha covid 19.
2. Se eliminan/agregan campos en la ficha covid 19 (Base de datos)
[fichacovid.txt](https://github.com/andes/app/files/7996081/fichacovid.txt)
> Epidemiología - Actualizaciones de campos en fichas epidemiologicas

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/modules/epidemiologia/components/validar-certificado/validar-certificado.component.html
- src/app/modules/epidemiologia/components/validar-certificado/validar-certificado.component.ts
- src/app/modules/epidemiologia/services/validar-certificado.service.ts
https://proyectos.andes.gob.ar/browse/EP-183
1. Se crea nueva pantalla que verifica si existe un certificado emitido para los datos ingresados (dni, sexo y fecha de validacion)
- Para ver la pantalla ingresar a la url servidor/validar-certificado
> Epidemiologia - Pantalla de consulta para certificados de aislamiento

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-154
1. Se cambia el componente "paciente-buscar" por "paciente-busqueda"
2. Se agrega directiva autosave a los filtros del buscador para que queden seteados dichos filtros mientras la sección siga activa y con esto hacer mas sencillo el trabajo de quienes actualizan la ficha desde el buscador.
> Epidemiología - Actualizaciones buscador de fichas epidemiologicas

- src/app/apps/vacunacion/components/aplicaciones-paciente/aplicaciones-paciente.component.html
- src/app/apps/vacunacion/components/aplicaciones-paciente/aplicaciones-paciente.component.ts
- src/app/apps/vacunacion/components/estado-paciente/estado-paciente.component.html
- src/app/apps/vacunacion/components/estado-paciente/estado-paciente.component.ts
- src/app/apps/vacunacion/vacunacion.module.ts
- src/app/apps/vacunacion/vacunacion.routing.ts
https://proyectos.andes.gob.ar/browse/VAC-123
1. Se agrega componente/vista para consultar el estado de vacunación de un paciente. (url: /vacunacion/estado)
> Vacunas - Crear pantalla para consultar estado de vacunacion de los pacientes

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.html
https://proyectos.andes.gob.ar/browse/MISC-213
1. Se achica sidebar de descargas pendientes
2. Se cambia el plex-list por plex-table, porque al achicar el sidebar el plex-item es muy restrictivo para acomodar los elementos por lo que ya no quedaba todo en una misma linea.
> TURNOS y PRESTACIONES - cambia visualización de descargas pendientes

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-122
1. Al momento de asignar un turno cuando una solicitud esta ene stado pendiente, verifica que no exista un turno para evitar que tenga dos turnos por error.
> TOP - Agenda suspendida

- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-124
1. Se cambia de lugar titulo y subtitulo en datos de origen/destino tanto en solicitudes de entrada como de salida
> TOP - Cambio de lugar titulo en label

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
https://proyectos.andes.gob.ar/browse/EP-190
1. 
2. 
3.
> EP: filtro score seguimiento

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
https://proyectos.andes.gob.ar/browse/EP-198
1. Se agrega ordenamiento por prioridad o fecha del listado de seguimiento.
2. Se pasan los nuevos filtros a un collapse para que quede mas acomodado.
3.
> Seguimiento - Agregar ordenamiento por fecha o prioridad

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
https://proyectos.andes.gob.ar/browse/CIT-162
1. Reemplaza filtro por id por conceptId
> CIT - Filtrar por conceptId en el gestor de agendas

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-371
1.  Al validar un paciente en MPI con dni y sexo, se habilita la opción "otro" como sexo no binario.
2. 
3. 
Para que funcione la validación por sexo no binario, necesita tenes atualizado api-tools con:
https://github.com/andes/api-tools/pull/50
> feat(mpi): se habilita la validación por sexo no binario

- src/app/components/paciente/headerPaciente.html
- src/app/components/paciente/headerPaciente.scss
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss
- src/app/modules/rup/components/ejecucion/prestacionValidacion-print.scss
https://proyectos.andes.gob.ar/browse/UIUX-67
1. Se saca padding para que los datos del paciente y foto ocupen el alto correcto al navbar
2. Se cambian los nombres de los contenedores para que sean mas descriptivos
> UIUX - Header paciente

- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-163
1. Se agrega icono en listado para identificar a las agendas virtuales
2. Adentro del plex-help se agrega el link de dicha agenda en caso de que sea una agenda virtual
> feat(CITAS): Agenda virtual en gestor agendas

- src/app/apps/vacunacion/components/nueva-inscripcion/nueva-inscripcion.html
[VAC-126](https://proyectos.andes.gob.ar/browse/VAC-126)
VAC - quitar requerido en el campo mail
1. Se quito el atributo de requerido en el campo de mail
2. 
3.
> refactor(vac): quitar como campo requerido el campo mail

- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
https://proyectos.andes.gob.ar/browse/PER-68
1. Se arregla problema del doble scroll cuando se abre collapse
2. Se agrega nueva columna de numero de embarazo.
> PER - Scroll y nueva columna

- src/app/modules/estadisticas/components/rup/rup-pacientes.component.ts
- src/app/modules/estadisticas/components/rup/rup-pacientes.html
https://proyectos.andes.gob.ar/browse/BI-109
1. Se modifico el html para poder mostrar la informacion de los padre y los aconceptos a agrupar. Tambien se hizo un refactor de la pantalla para visualizar mejor los datos y que esten de forma ordenada.
> BI - Proximos padres

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
https://proyectos.andes.gob.ar/browse/RUP-307
1. Se genera una nueva constante para almacenar los datos de la prestación y en caso de que la conexión falle, los datos de la prestación no se modifican.
> RUP - Error al eliminar registros vinculados

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.html
- src/app/modules/rup/components/elementos/valorFecha.component.ts
- src/app/modules/rup/components/elementos/valorFecha.html
https://proyectos.andes.gob.ar/browse/RUP-308
1. Se realizo un refactor sobre la edad gestacional dentro de RUP
> RUP - aplicar prototipo de edicion a formulas

- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-170
> CITAS - Aria Label en card de horarios

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/services/plantillas.service.ts
https://proyectos.andes.gob.ar/browse/IN-398
1. elimina código comentado
2. modifica tamaño e iconos de elementos (titulos, botones, etc)
3. 'refresca' sidebar al cambiar de sección
4. permite la edición de secciones por búsqueda
5. agrega algunos estilos
> IN (Plan indicaciones) - Permitir cambiar de secciones

- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
[GDU-45](https://proyectos.andes.gob.ar/browse/GDU-45) Revisar error en consola al actualizar usuario
1. Se agrego funcionalidad para que angular cheque la actualización de datos en el momento en el que lo precisamos
2. 
3.
> GDU-45 - Revisar error en consola al actualizar usuario

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/EP-193
1. Nueva funcion en servicio de documentos para descargar csv de listado de seguimiento
> EP - Permitir descarga de un csv con reporte de seguimientos

- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
> fix(RUP)hot fix indicaciones

- src/app/modules/rup/components/ejecucion/buscador.html
https://proyectos.andes.gob.ar/browse/RUP-311
1. En buscador de conceptos en RUP, corrige el badge de solicitudes en filtro 'todos'
2. 
3.
> RUP: fix buscador clasificacion rup card

- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-129
1. 
2. 
3.
> TOP: badge huds bandeja salida

- src/app/components/top/pipes/isEmpty.pipe.ts
- src/app/components/top/pipes/isNotEmpty.pipe.ts
- src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
[CIT-164](https://proyectos.andes.gob.ar/browse/CIT-164)
agendas-virtuales: en top visualizar que el turno dado es virtual
1. se agrega un icono de televisor en el listado de las consultas para indicar cuales son virtuales
2. 
3.
> feat:(CITAS): agregar icono si es un turno virtual

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-378
1. Se agregaron los atributos activo y fecha de nacimiento para que al momento de relacionar un recien nacido con un paciente figure el boton "relaciones"
> MPI - Relaciones de un paciente

- src/app/modules/rup/components/elementos/FormulaBase.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.html
https://proyectos.andes.gob.ar/browse/RUP-313
1. Se agregaron condiciones para verificar si el elemento rup tiene el atributo valor editable y de esta forma que se pueda editar manualmente el valor calculado.
> RUP - Error en formulas

- src/app/modules/rup/components/elementos/FormulaBase.component.ts
https://proyectos.andes.gob.ar/browse/RUP-303
1. Para una prestación de control de embarazo, se busca en la huds del paciente registros recientes del concepto, para precargar la fecha de ultima menstruación. 
**REQUERIDO:** Agregar al elementoRUP *ObjectId("61bb4eec5f9fcf783c44d377")*, en atributo params *buscarAnterior: true*
> RUP - Precarga de FUM en consulta de embarazo

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
[TOP-128](https://proyectos.andes.gob.ar/browse/TOP-128)
1. Se agrego un filtro por profesional para poder filtrar por profesional destino
2. 
3.
> feat(TOP): agregar campo de busqueda por profesional destino

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
https://proyectos.andes.gob.ar/browse/IN-414
1. Se actualiza la columna a mediante el servicio de mapa de camas.
> IN - Header de la tabla al volver a la pantalla

- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
- src/app/modules/forms-builder/components/select-static/select-static.component.html
- src/app/modules/forms-builder/components/select-static/select-static.component.ts
- src/app/modules/forms-builder/forms.module.ts
- src/app/modules/forms-builder/services/form.service.ts
https://proyectos.andes.gob.ar/browse/EP-107
1. Se realiza la primer etapa del refactor visual del form builder.
2. Se agrega select static y dependencias.
> Form - Refactor visual

- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/components/reportes/encabezadoReportes.html
https://proyectos.andes.gob.ar/browse/MISC-224
1. Se corrigió el filtro de organizaciones para que pueda filtrar por id y traer los valores correctamente
> MISC - No se muestran bien los resultados al filtrar por organizacion

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-432
1. Se descomenta la función que registra una prescripción.
> Plan de indicaciones - Habilitar la ejecucion de medicamentos

- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
- src/app/modules/forms-builder/services/preset.resources.service.ts
https://proyectos.andes.gob.ar/browse/EP-206
1. Seleccionar una seccion precarga en edicion de template de formulario
2. 
3.
> EP: secciones precargadas

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
[TOP-126](https://proyectos.andes.gob.ar/browse/TOP-126) Error al listar solicitudes Asignadas cuando se accede desde RUP
1. Se controla la fecha desde hasta para que no supere un intervalo de tiempo
2. 
3.
> TOP - Error al listar solicitudes Asignadas cuando se accede desde RUP 

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
https://proyectos.andes.gob.ar/browse/IN-431
1. Se agrego la fecha junto con la hora dentro del plex-title
> IN - Mostrar fecha y hora del mapa de cama

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
https://proyectos.andes.gob.ar/browse/IN-393
1. Suprime caché de observable para recargar datos del paciente en detalle de la cama
> IN (Fix) - Actualiza internación al modificar datos básicos del paciente en MPI

- src/app/components/top/reglas/reglas.component.html
- src/app/directives/prestaciones-select.directive.ts
https://proyectos.andes.gob.ar/browse/TOP-127
1. Se agrega un imput a la directiva tmPrestaciones para que pueda filtrar por el ambito que le corresponda.
> TOP - Agregar filtro por ámbito ambulatorio en reglas

- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.html
- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
https://proyectos.andes.gob.ar/browse/IN-402
1. Se agrega control en la fecha y hora de inicio de prestacion para una internacion. Se toma como fecha valida una que este dentro del periodo de internacion del paciente.
> IN - Controlar registro de prestaciones fuera del horario de internacion

- src/app/components/top/solicitudes/solicitudes.html
[RUP-316](https://proyectos.andes.gob.ar/browse/RUP-316): Modificar mensaje de error por fechas fuera de rango
1. Se modifica mensaje de error cuando las fechas exceden el rango determinado 
2. 
3.
> RUP: Modificar mensaje de error por fechas fuera de rango

- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-420
1. Se modifico la ruta de navegación.
> IN - Error al mostrar los modals al editar una cama

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
[IN-413](https://proyectos.andes.gob.ar/browse/IN-413) - Egreso de una internacion: Modificar label
1. Se modifican los labels de "Otras circunstancias" por "Otras circunstancias que prolongan la internación" y "Otro diagnostico" por "Otros diagnósticos"
2. 
3. 
https://github.com/andes/andes-test-integracion/pull/431
> style(IN): se cambian labels por mas descriptivos

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.component.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
https://proyectos.andes.gob.ar/browse/EP-184
1. Badge con detalle de total de fichas filtradas
2. Nueva ruta 'search' en servicio de seguimiento
**OBSERVACION:** Requiere https://github.com/andes/api-tools/pull/52 **por lo tanto, hasta no estar mergeado NO VAN A PASAR LOS TESTS**
> EP - Muestra el numero total de seguimientos filtrados por el buscador 

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
https://proyectos.andes.gob.ar/browse/IN-423
1. Se incluye información adicional de indicaciones en la visualización de plan de indaciones
2. 
3.
> INT: Visualizar información de indicaciones

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/services/conceptos-turneables.service.ts
https://proyectos.andes.gob.ar/browse/EP-195
1. Se incluye concept id de laboratorios externos para listar los mismos en los cdas descargables
2. 
3. 
```
{
"loinc" :
{ "code" : "34764-1", "codeSystem" : "2.16.840.1.113883.6.1", "codeSystemName" : "LOINC", "displayName" : "General medicine Consult note" }
,
"snomed" : {
"conceptId" : "3031000246109",
"term" : "reporte de resultado de test de covid-19 proveniente de SNVS",
"fsn" : "reporte de resultado de test de covid-19 proveniente de SNVS (procedimiento)",
"semanticTag" : "procedimiento"
},
"organizaciones" : []
}
```
> HUDS: incluir ctId labos externos

- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
https://proyectos.andes.gob.ar/browse/IN-408
1. Se agrego una nueva categoría "porcentaje de ocupación de camas" en el censo mensual de internación.
> IN - Censo mensual - porcentajes

- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/directives/prestaciones-select.directive.ts
- src/app/services/conceptos-turneables.service.ts
https://proyectos.andes.gob.ar/browse/CIT-168
1. Se agrego un filtro para que al momento de crear una nueva agenda, las prestaciones filtren solamente por ámbito ambulatorio
> CIT - Agregar filtro por ambito ambulatorio al crear una agenda

- src/app/directives/prestaciones-select.directive.ts
- src/app/services/conceptos-turneables.service.ts
https://proyectos.andes.gob.ar/browse/CIT-175
1. Se agrego el ambito ambulatorio a la directiva de prestaciones
2. se modificaron los filtros para que incluya el ambito ambulatorio en las busquedas de las prestaciones
> CIT - filtrar por ámbito ambulatorio en prestación fuera de agenda

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
https://proyectos.andes.gob.ar/browse/IN-443
1. Deshabilita botones para cambio de cama cuando la fecha es incorrecta
> IN (fix) - Se permite cargar un movimiento de cama a futuro

- src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
Error para mostrar el boton de revision de agendas en listado
> fix(CITAS): cambio función para botón de revisar agenda

- src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
Verificar paciente con internacion sin egreso
1. Agrega ruta con historial completo de paciente
> fix(in): check paciente internado

- src/app/apps/rup/mapa-camas/sidebar/ingreso/elegir-paciente.component.ts
> Internacion: permite internar paciente ya egresado

- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/components/reportes/encabezadoReportes.html
https://proyectos.andes.gob.ar/browse/MISC-233
1. Se agrego un label para informarle al usuario que no se encontró ningún resultado de la búsqueda
2. Se agrego un label para indicarle al usuario, una ves ingresado al modulo de reportes, que es lo que debe hacer.
> MISC - Label de resultados

- src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
https://proyectos.andes.gob.ar/browse/IN-405
https://proyectos.andes.gob.ar/browse/IN-407
1. Separa permisos de prestamo de camas con respecto a los de edicion
2. Agrega control de edicion de unidad organizativa habilitando este campo solo si la cama a editar esta disponible
> IN - Permisos de edicion de cama

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/pipes/espacioFisico.pipe.ts
https://proyectos.andes.gob.ar/browse/CIT-178
> CITAS - Agregar espacio físico en listado

- src/app/apps/rup/mapa-camas/pipes/plan-indicaciones/detalle-indicacion.pipe.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
https://proyectos.andes.gob.ar/browse/IN-446
1. Modificar la palabra ingrediente por Principio activo
En el listado de prescripciones creadas, se deberá sacar la palabra presentación, via y frecuencia , solo quedará lo que no esta en negrita.
Sacar de la grilla horaria la división de mañana tarde y noche.
2. 
3.
> INT: mejoras visuales plan ind

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-color.pipes.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-nombre.pipe.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-425
1. Dejar solo opción de: continuar y suspender.
Las indicaciones suspendidas: no se debe permitir ejecutar durante el día de la suspensión, a partir del siguiente día deben desaparecer del plan..
NO se pueden agregar indicaciones con fechas anteriores o futuras.
2. 
3.
> INT: plan indicaciones mejoras ejecución

- src/app/modules/mpi/components/paciente-relaciones.component.ts
[MPI-383](https://proyectos.andes.gob.ar/browse/MPI-383) - No mostrar pacientes inactivos en las relaciones de un paciente
1. Se modifico el componente de visualización de las relaciones de pacientes para que solo se incluyan los que estan activos
2. 
3.
> feat(MPI): No mostrar inactivos en las relaciones

- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-452
1. Corrige el request para conseguir el id de la internación
> In (Fix) -  Visualizacion de movimientos

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-450
1. Se agrego una condicion para chequear solamente las camas y no las salas.
(resuelve sobre capa medica)
> IN - Error al eliminar o modificar fecha de ingreso de una sala

- src/app/components/turnos/gestor-agendas/gestor-agendas.html
https://proyectos.andes.gob.ar/browse/CIT-180
> CITAS - Agrega nombre del día en listado de agendas

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
https://proyectos.andes.gob.ar/browse/IN-419
1. Se agrega scroll para la grilla horaria del plan de indicaciones.
> Plan de indicaciones - scroll en grilla horaria

- src/app/components/turnos/gestor-agendas/pipes/botonesAgendaGeneral.pipe.ts
[CIT-176](https://proyectos.andes.gob.ar/browse/CIT-176) - No corresponde ver boton "pasar a disponible"
1. Se modifican las pre condiciones para mostrar el botón agregando que este en estado **planificacion**
2. 
3.
> fix(CITAS): sacar btn disponible cuando ya lo esta

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
[CIT-179](https://proyectos.andes.gob.ar/browse/CIT-179) - De-seleccionar las agendas seleccionas en el listado de agendas luego de agregar una nueva
1. Al agregar una nueva agenda ahora se de-seleccionan las agendas previamente seleccionadas
2. 
3.
> CITAS - Limpiar historial de selección de agendas

- src/app/components/top/solicitudes/formNuevaSolicitud.html
[TOP-132](https://proyectos.andes.gob.ar/browse/TOP-132) - Evitar que se guarden solicitudes repetidas
1. Se agrega autodisable al boton de gurdar para que no se vuelva a presionar
2. Se verifico varias veces con ambos casos, cuando pide confirmación y cuando no lo hace 
3.
> TOP - Evitar que se guarden solicitudes repetidas

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-416
1. Dado un ingreso en cama censable, pasar la internacion a 'no censable' (excluirla de los censos)
2. 
3.
> INT: pasar a internacion no censable

- src/app/components/top/pipes/botones.pipe.ts
- src/app/components/top/solicitudes/solicitudes.html
[TOP-130](https://proyectos.andes.gob.ar/browse/TOP-130) - En el modulo de top, se visualiza in adecuadamente el botón continuar prestación, ya que se puede ver por cualquiera que utiliza el modulo
1. Se agregan controles para que el botón sea solo visible por quien inicio el registro de atención medica o quien tenga permisos elevados para ese tipo de prestación 
2. 
3.
>  TOP - Se visualiza botón continuar registro

- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-463
1. Se refactorean algunos request y se reemplaza una funcion por un observable ya que no se subscribia correctamente
2. Además se corrige la redireccion al guardar, ya que volvía a solicitar capa para ingresar al mapa de camas
> IN (Fix): Error al inactivar cama

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/modules/mpi/components/paciente-detalle.html
https://proyectos.andes.gob.ar/browse/IN-460
1. Se resetean variables que anteriormente quedaban pre-cargadas al visualizar otros egresos antes de realizar el egreso en cuestion.
2. Se fixea también la visualización del **origen** de la internacion en el informe de ingreso del paciente (estadistica)
3. Fix de obtencion de cama en capa estadistica-v2
> IN (Fix) - Error en fechas de egreso

- src/app/modules/rup/components/elementos/vacunas.component.ts
- src/app/modules/rup/components/elementos/vacunas.html
https://proyectos.andes.gob.ar/browse/VAC-127
1.  Se eliminó el control de dosis en el registro de vacunas de tal forma que cuando se vaya a cargar una vacuna figuren todas las dosis correspondiente al esquema seleccionado
> VAC - Quitar control de dosis

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
https://proyectos.andes.gob.ar/browse/IN-473
1. Agrega formulario a componente de nueva prescripción de internacion
2. Modifica funcion validateForm() de rupComponent para opcionalmente chequear solo campos requeridos
> IN - Plan indicaciones: Validación de formularios

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-472
1. Se corrigio el boton volver del plan de indicacion y se agrego en una nueva funcion la direccion a la cual debe volver.
> IN - boton volver en plan de indicaciones

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-177
1. Notificaciones que salían antes en el footer, ahora se pueden ver en el plex-layout-main y sidebar respectivamente en el sector de arriba.
> CITAS - Refactor creación de agenda

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.html
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/services/organizacion.service.ts
https://proyectos.andes.gob.ar/browse/IN-415
1. Se visualiza botón de préstamos de cama ocupada para efectores que esten usando capas unificadas
2. Se agrega atributo 'idMovimiento' a este tipo de préstamos para el caso de requerir deshacer el movimiento
> IN - Prestar cama ocupada (Efectores con capas unificadas)

- package-lock.json
- package.json
Actualizar plex a la ultima version.
1. Se actualiza plex a la version 7.23
2. EN caso de error en las dependencias, correr con npm i --legacy-peer-deps
> Core - Actualizacion plex

- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
- src/app/services/usuarios/usuario.service.ts
https://proyectos.andes.gob.ar/browse/MAT-95
1. En inscripcion de profesional para emision de certificado covid19, se elimina validacion de nro de tramite de dni
2. 
3.
> MAT: eliminar validacion nro tramite

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-187
> CITAS - Visualización correcta de bool agenda dinámica

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
> fix(internacion): prestar cama separado

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
- src/app/components/profesional/profesional-create-update.component.ts
- src/app/components/profesional/profesional-create-update.html
- src/app/core/mpi/components/datos-contacto.component.ts
https://proyectos.andes.gob.ar/browse/TM-24
1. Fix en validacion de formulario y contactos
2. 
3.
> TM: fix contactos profesionales

- src/app/modules/rup/components/elementos/vacunas.component.ts
No están pudiendo cargar vacunas para pacientes menores a 1 año
1. 
2. 
3.
> fix(vacunas): control para límite mínimo edad

- src/app/modules/rup/components/elementos/vacunas.html
https://proyectos.andes.gob.ar/browse/VAC-130
1. Se agrego una funcion para mostrar el historial de vacunas del paciente.
> VAC - mostrar historial de vacunas

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
https://proyectos.andes.gob.ar/browse/CIT-184
1. 
2. 
3.
> CIT: limpieza de permisos

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-478
1. Guarda motivo de suspencion (Fix)
2. Agrega visualización de motivo de suspención en el historial de la prescrición
> Plan indicaciones - Mostrar en el sidebar el motivo de suspension

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
> Revert "CIT: limpieza de permisos"

- src/app/modules/mpi/components/paciente-detalle.html
- src/app/modules/mpi/components/paciente-panel.html
https://proyectos.andes.gob.ar/browse/PLEX-320
1. Corrige alinieación fila/columna de componentes de visualización de detalle del paciente
> PLEX/MISC - Datos no alineados

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/alergias-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/alergias-paciente.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-317
1. Nuevo componente para visualizar las alergias del paciente registradas previamente en rup
> RUP - Componente para visualización de alergias

- src/app/components/turnos/dar-turnos/dar-turnos.html
> fix(citas): agendas sin profesionales

- src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
- src/app/services/constantes.service.ts
https://proyectos.andes.gob.ar/browse/IN-445
1. Al crear una nueva prescripción, se marcan los horarios de la indicación en la grilla  a modo de visualización.. Estos eventos quedan en espera ('on-hold').
2. Nuevo servicio para recurso 'constantes' que funcionan de insumo para el select de 'frecuencia'.
3. Se edita algun contenido visual en el sidebar.
> IN - Nueva prescripcion disponible hasta siguiente medio dia

- src/app/apps/mitos/directives/select-expression/select-expression.directive.ts
https://proyectos.andes.gob.ar/browse/IN-479
1. Se cachean las busquedas parciales en directiva de select por busqueda snomed
> IN - Plan indicaciones: Cacheo select de principio activo

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-475
1. Reemplaza subscribes anidados de funcion actualizar() por rxjs.
> IN - Plan indiaciones: Actualizar vista al validar indicaciones pendientes

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-474
1. Si se seleccionan solo indicaciones en estado **borrador** se habilita un dropdown _validar indicaciones -> seleccionadas_.
De lo contrario continúa vigente la opción de validar pendientes.
> IN - Permitir validar indicaciones seleccionadas

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-468
1. Restringe acciones y visualización de indicaciones para perfil enfermeria.
> IN - Plan indicaciones: Separar acciones segun perfil

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
https://proyectos.andes.gob.ar/browse/IN-469
1. Verificacion de prescripciones desde capa interconsultores
2. Edición de componente **motivoSuspencion** para hacerlo mas generico y poder editar motivos en casos necesarios
> IN - Perfil interconsultor para farmacia

- projects/shared/src/lib/server/resource-base.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/filtros-listado/filtros-listado-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
https://proyectos.andes.gob.ar/browse/IN-477
1. En los listados de interación, se modifica los filtros de manera que se pueda filtrar por opcionalmente por fecha de egreso o de ingreso, o  combinados, pero de manera que siempre es requerido algun rango de fechas completo. 
2. 
3.
> IN: listado internación rango fechas

- src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
- src/app/modules/rup/components/elementos/seleccionBinaria.html
- src/app/modules/rup/elementos-rup.module.ts
- src/app/modules/rup/pipes/elemento-rup-valor.pipes.ts
https://proyectos.andes.gob.ar/browse/RUP-323
1. Se hizo un fix para aquellos casos que no se elige un dato del plex-radio (no requerido).
2. Se agrega una condición de visualización para las prestaciones que se haya registrado el elemento como un campo de texto (casos actuales de prod, ya que no se estaba usando el componente Binario si el que viene por defecto). Esto es aquellos casos ya registrados en los que no existía un componente ya asociado al conceptId.
3. Se agrega pipe para visualizacion de elementos Rup en sólo valores.
> RUP: Se agregan nuevas condiciones en un componente de seleccion Binaria

- src/app/apps/mitos/services/snomed.service.ts
- src/app/apps/rup/mapa-camas/services/maquina-estados.http.ts
- src/app/components/organizacion/configuracion-internacion.component.ts
- src/app/components/organizacion/configuracion-internacion.html
- src/app/components/organizacion/organizacion.component.ts
- src/app/components/organizacion/organizacion.html
- src/app/components/organizacion/organizacion.module.ts
https://proyectos.andes.gob.ar/browse/IN-349
1. Agrega dropdown en listado de organizaciones para acceder a configuracion de servicios e internacion
2. Nueva pantalla para configurar los controles de internación de cada efector
> TM - ABM para configuración de internación

- src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
1. Devuelve foto de paciente en blanco en todos los casos para evitar que aparezca la imagen 'rota'
> fix(MPI): Se quita acceso a foto del paciente desde directiva

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
https://proyectos.andes.gob.ar/browse/IN-462
1. Se eliminaron los botones: desocupar, editar cama, admitir paciente, nuevo recurso, deshacer internacion, internar paciente, bloquear y prestar/desocupar
> IN - Agregar restricciones de visualizacion en capa interconsultores

- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.html
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
- src/app/apps/rup/mapa-camas/views/lista-espera/lista-espera.component.ts
https://proyectos.andes.gob.ar/browse/IN-491
1. Refactor de servicios de camas, separando el save del objeto cama por un lado y de sus estados por el otro.
2. Correccion de comportamiento de los componentes _cama_ y _prestar-devolver-recurso_ segun punto anterior.
**AL MERGEAR DAR POR SOLUCIONADO EL GLPI https://glpi.andes.gob.ar/front/ticket.form.php?id=3234**
> IN - Error al editar camas

- src/app/components/top/solicitudes/detalleSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-133
Al publicar, cerrar https://glpi.andes.gob.ar/front/ticket.form.php?id=2890
1. 
2. 
3.
> CIT label contrarreferida

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
https://proyectos.andes.gob.ar/browse/IN-485
> INT - Cambio filtro sector

- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
https://proyectos.andes.gob.ar/browse/CIT-195
1.  Se saco el método searchClear() y se deshabilita el botón de guardar una ves que se le asigna un sobreturno a un paciente. 
2.  Se achicaron los tamaños de los botones cancelar y guardar y tambien se separaron. (En el html de la clase asignar-turno.html se modificaron desde las filas 4 hasta las 7 solamente)
> CIT - sobreturnos sin pacientes

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
https://proyectos.andes.gob.ar/browse/CIT-188
> CITAS - Loader en gestor de agendas

- src/app/components/turnos/autocitar/autocitar.component.ts
- src/app/components/turnos/autocitar/autocitar.html
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
https://proyectos.andes.gob.ar/browse/RUP-318
> RUP - Refactor pantalla de paciente autocitado

- src/app/components/turnos/autocitar/autocitar.component.ts
1. Reemplaza check por getPermission
> RUP (Fix ) - Control de permisos autocitacion

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
https://proyectos.andes.gob.ar/browse/IN-490
1. FIltra la internación que se esta visualizando para que no aparezca en los registros de la huds
2. Agrega formulario para validación de fechas
> IN - Validar internacion capa Estadistica

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
https://proyectos.andes.gob.ar/browse/UIUX-351
1. Se cambio de posicion el boton de deshacer internacion dejandolo a la derecha. Tambien se modifico la posicion del tooltip de editar nota. Los cambios se encuentran en la linea 75 - 79 y 112 a 114
> UIUX - Tooltips recortados

- src/app/modules/rup/components/elementos/rupers/select-base.component.ts
[PER-72](https://proyectos.andes.gob.ar/browse/PER-72) - Molécula "embarazo" agregar numero
1. Se modifico SelectSnomedComponent para que acepte un param que permita agregar un registro que no este en la selección original
2. 
3. 
https://github.com/andes/andesMicroservices/pull/199
```json
{
"_id" : ObjectId("60708cdef46502014d97e7ff"),
"componente" : "SelectSnomedComponent",
"style" : {
"columns" : 12.0,
},
{
"fsn" : "embarazo (hallazgo)",
"semanticTag" : "hallazgo",
"conceptId" : "366321006",
"term" : "embarazo"
}
],
"params" : {
"titulo" : "Seleccione número de embarazo correspondiente:",
"query" : "<366321006",
"tipoSelect" : "select",
"multiple" : false, …
```
> PERINATAL - Molécula "embarazo" agregar numero

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
https://proyectos.andes.gob.ar/browse/IN-482
1. Agrega detalle del profesional que creó/actualizó el evento seleccionado. Ademas separa la vista editable de la solo lectura para eventos que hayan sido modificados.
> IN - Mostrar profesional que registro el evento en el plan de indicaciones

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-496
1. Agrega control al hacer click sobre una celula para determinar si se pueden agregar eventos
> IN - Plan de indicaciones - Bloqueo por el farmaceutico

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/prestar-devolver-recurso/prestar-devolver-recurso.component.ts
https://proyectos.andes.gob.ar/browse/IN-466
1. Filtra unidad organizativa actual al llenar el combo de unidad destino
> IN - Quitar unidad organizativa actual al prestar cama ocupada

- src/app/components/reportesDiarios/resumenDiarioMensual.scss
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/dar-turnos/dar-turnos.scss
- src/app/components/turnos/dashboard/estadisticas-agendas.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-202
1. Plexea botones (Que no eran botones xD) para trasladarse a la agenda siguiente/anterior
2. Plexea (yapa) sidebar de punto de inicio y corrige color/alineación de botones de accion en el listado
> CIT - Botón para visualizar siguiente agenda

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-476
1.  Se agregaron nuevos filtros para buscar los codigos cie10 según corresponda
> IN - formulario egreso estadistico

- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-190
1. Se agrego dentro del plex-help donde se visualiza algunos detalles de la agenda, las prestaciones asociadas que tiene cada bloque.
> CIT - mostrar prestaciones del bloque en el gestor de agendas

- src/app/components/top/reglas/visualizacionReglas.component.ts
- src/app/components/top/reglas/visualizacionReglas.html
https://proyectos.andes.gob.ar/browse/TOP-134
1. skip and limit en listado de reglas
2. Loader 
3. Mensaje de bienvenida
> TOP - Listado reglas

- src/app/components/turnos/dashboard/estadisticas-pacientes.html
- src/app/components/turnos/punto-inicio/turnos-paciente.html
https://proyectos.andes.gob.ar/browse/CIT-200
1. Se agregó un badge "NO ASISTIÓ" junto con las condiciones necesarias para que un paciente que no asistió a su turno no figure con el badge de ASIGNADO sino con el dicho al principio.
> CIT - Visualizar badge No asistió en historial de turnos

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
https://proyectos.andes.gob.ar/browse/CIT-191
1. Se agrega filtro por multiples prestaciones.  
2. Se revisan filtros por fechas.
https://github.com/andes/api/pull/1766
https://github.com/andes/andes-test-integracion/pull/458
> CITAS - Filtro por multiples prestaciones y revision filtros fechas.

- src/app/components/top/reglas/visualizacionReglas.component.ts
1. Corrige error al cargar reglas en RUP
2. 
3.
> fix(TOP): corrige error al cargar reglas desde RUP

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
> fix(CITAS): quita seleccion de multiple prestaciones

- src/app/components/top/reglas/visualizacionReglas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
1. Corrige parametros cuando el componente se ejecuta desde RUP
2. Reincorpora selección de multiples prestaciones en citas
> Fix en listado de reglas TOP/RUP

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/RUP-334
1. Se corrige chequeo de permisos. En lugar de consultar a auth por id de prestacion, se consulta a un array previamente cargado con permisos por conceptId.
> RUP - No se visualiza botón iniciar prestación

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-459
1. Se agrego una condicion para verificar si tiene que comparar por una cama seleccionada o por los ultimos movimientos que tiene el paciente.
> IN -  Error al cambiar de cama

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Agrega filtro por efector en get agendas
1. 
2. 
3.
> fix(CITAS): Agrega filtro por efector en get agendas

- src/app/components/top/reglas/visualizacionReglas.component.ts
Corrige error en el que no se visualizan reglas de solicitudes, en el listado que se utiliza dentro una prestación que está en ejecución 
1. 
2. 
3.
> TOP: Corrige visualización de reglas en RUP ejecución

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> RUP: corrige error boton turnero

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
> RUP: corrige error al mostrar boton turnero

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Quitar la opción de clasificación por contacto estrecho de la ficha epidemiológica de Covid
1. 
2. 
3.
> FIX(Epidemio): Quita la clasificacion por contacto estrecho

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/top.module.ts
- src/app/services/router.service.ts
https://proyectos.andes.gob.ar/browse/TOP-135
1. Cachea filtro de fechas Desde y Hasta para solicitudes de ENTRADA y SALIDA. Mantiene las fechas seleccionada y los resultados de búsqueda cuando se cambia de vista.
> TOP - cachear filtro de fechas para entrada/salida

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-193
1. Se agrega un plex-help con el detalle del paciente. Para turnos suspendidos.
2. Se muestra el número de celular o fijo en el listado de turnos suspendidos.
3. Se corrigen errores de condición de undefined y null.
4. Se reemplaza table por plex-table, línea 81 y 89.
5. Se corrige ubicación del tooltip "Detalle del paciente".
6. Se agrega plex-title para "Sobreturnos Suspendidos".
7. Se elimina color de selección al seleccionar el turno suspendido.
8. Se agrega margen al badge "Suspendida", línea 3 de supender-agenda.html.
> CIT - Visualizar datos del paciente en gestor de agendas

- src/app/apps/rup/mapa-camas/pipes/plan-indicaciones/detalle-indicacion.pipe.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-509
https://proyectos.andes.gob.ar/browse/IN-507
1. Actualiza pipe de detalles de la indicacion para poder ver la frecuencia en primera instancia
2. Se restringe la edición solo a indicaciones no validadas
3. Se restringe la ejecucion de eventos a la capa enfermeria exclusivamente
> IN - Plan de indicaciones: Restricciones sobre la carga de indicación

- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
https://proyectos.andes.gob.ar/browse/IN-492
1.  Se resto un minuto al valor minimo de la hora para que pueda generar un nuevo registro apenas se termina de internar a un paciente.
> IN - control de fechas de registro

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-51
Confirmar si la solución es valida, en tal caso cerrar https://github.com/andes/app/pull/2715 y https://github.com/andes/api/pull/1735
1.
> HUDS: badges solicitudes

- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.component.ts
- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-199
1. Se agrego el nombre de la prestación.
2. Se agrego un filtro de prestaciones dentro del sidebar.
NOTA: solamente se modificaron las lineas 6 - 8 del html donde se agrega el nuevo filtro y se borro el botón "borrarDiagnostico(i)" ya que el mismo no se encontraba definido en el .ts
> CIT - No se visualiza la prestacion al auditar fuera de agenda

- src/app/modules/rup/components/elementos/moleculaBase.component.ts
- src/app/modules/rup/components/elementos/moleculaBase.html
- src/app/modules/rup/components/elementos/valorFecha.component.ts
- src/app/modules/rup/components/huds/vistaRegistro.html
https://proyectos.andes.gob.ar/browse/RUP-329
1. Se crea nuevo elementoRup componente **MoleculaBaseComponent** y se edita **ValorFechaComponent**
preexistente para incluir horario
2. Nuevo template para componente de moleculaBase que permite evolucionar este trastorno
**--------------------- MODIFICACIONES EN LA DB (EN DEMO ESTA ACTUALIZADO) -------------------**
{
"_id" : ObjectId("6304f3625a17d31efdc7605b"),
"componente" : "MoleculaBaseComponent",
"tipo" : "molecula",
"style" : {
"columns" : 12.0,
},
"params" : {
"required" : true,
"title" : "ACV"
},
{
"conceptId" : "230690007",
"term" : "ACV",
"fsn" : "accidente cerebrovascular (trastorno)",
"semanticTag" : "trastorno"
}
],
"requeridos" : [ 
{
"elementoRUP" : …
> RUP - Nueva molecula ACV

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/solicitudes/solicitudes.scss
NOTA: se juntaron las dos tareas para evitar posibles conflictos a futuro, según lo charlado!
https://proyectos.andes.gob.ar/browse/TOP-147
https://proyectos.andes.gob.ar/browse/TOP-141
1. Se eliminó la palabra Tipo de prestación dentro de la columna "Datos destino"
2. Se agrego un dropdown que engloba todas las posibles acciones de cada solicitud.
3. Se agregaron dos nuevos filtros para buscar las solicitudes a partir de su fecha de actualización.
4. Se agrego un bool que muestra los filtros nuevos "Actualización desde" y "Actualización hasta".
5. Se hizo un refactor modificando la lista de solicitudes por una tabla, se agrego un plex-loader cada ves que se modifica un filtro, se agrega un label con el mensaje correspondiente en caso de que no obtener ninguna solicitud y se agrega un …
> TOP - Filtros fecha de actualización

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-192
1. Se agrega botón cerrar en el sidebar para que se cierre el mismo.  
2. Se oculta el sidebar para cuando se seleccionen más de una agenda. Salvo para la opción de Notas.
> CITAS - Bugs en sidebar de gestor de agenda

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/HUDS-64
1. Al ingresar a la HUDS de un paciente, es posible filtrar los trastornos por aquellos que se encuentran activos (por defecto) o todos los restantes.
> Huds - Filtrar trastornos activos en paciente

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/nota-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-194
1. Se edita la vista al crear y editar una nota.
2. Se cambia tooltip del ícono de notas.
3. Se mejora la vista de la información de las agendas seleccionadas (sidebar).
4. Se mejora código en nota-agenda.component.ts.
> CITAS - Refactor al crear una nota en el gestor de agendas

- src/app/components/turnos/gestor-agendas/pipes/botonesTurnos.pipe.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-201
1. Se agrega botón cambiar a disponible para turno suspendido.
> CITAS- Activar turno suspendido

- src/app/components/profesional/profesional-create-update.component.ts
- src/app/components/reportes/reporteC2.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/services/profesional.service.ts
https://proyectos.andes.gob.ar/browse/TM-23
1. limpieza service profesionales
2. 
3.
> TM: limpieza service profesionales

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-484
1.  Se modifico la condición que existe dentro del set de fechas
> IN - Error al visualizar datos de una cama

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-505
1. Se agrega un BehaviorSubject en el servicio de mapa de camas para verificar si se esta yendo al historial o al listado de internación. De esta forma podremos saber si es necesario asigarle el valor nulo a la cama dentro de un nuevo combinateLatest que se implemento. 
2. Se modifica el mensaje de los modal.
> IN - No se modifica correctamente la fecha de ingreso

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-506
1. Se crea una nueva variable booleana puedeEditar para verificar en otro componente si puede editar o no una prestacion. En caso de que este validad la misma no se podrá editar. 
2. 
3.
> IN- Se visualiza edición de internación en un informe de egreso validada

- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-196
1. Corrección de mensaje de error.
2. Corrección de error de función inexistente. Se agregó esa función.
> CITAS - Error en agenda dinámica

- projects/auth/src/lib/auth.service.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-127
1. Se modifico la ruta donde se obtienen las organizaciones en el modulo de bi-queries
2. Se agrego el select para unidades organizativas.
> BI - Permisos en organizaciones

- src/app/apps/gestor-usuarios/components/perfiles-detail.html
- src/app/apps/gestor-usuarios/gestor-usuarios.module.ts
- src/app/apps/gestor-usuarios/services/perfiles.http.ts
- src/app/apps/gestor-usuarios/views/perfiles-list.component.html
- src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
https://proyectos.andes.gob.ar/browse/GDU-51
https://proyectos.andes.gob.ar/browse/GDU-52
https://proyectos.andes.gob.ar/browse/GDU-54
1. Se ordena el listado de perfiles por el campo nombre en forma ascendente.
2. Se añade filtro de perfiles por nombre.
3. Se corrigió la parte de código que no mostraba "Desactivado" para dichos perfiles.
4. Se quita del listado de perfiles a los que están inactivos.
5. Se agrega fecha de última actualización de los perfiles.
6. Se realizan cambios en los _archivos perfiles-detail.html_ y _perfiles-list.component.html_ para tener una vista simétrica en ambos.
https://github.com/andes/andes-test-integracion/pull/462
> GDU - Agregar filtro en listado de perfiles

- src/app/components/top/pipes/estado-prestacion.pipe.ts
- src/app/components/top/solicitudes/detalleSolicitud.component.ts
- src/app/components/top/solicitudes/detalleSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
https://proyectos.andes.gob.ar/browse/TOP-148
1. Se aplica mockup para colores de bagdes en solicitudes
2. Se implementa estructura para obtener estados correctos de solicitud con sus colores
3. Se realiza una limpieza en el código para reducir condicionales
> TOP - Reemplaza colores de badges en solicitudes

- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/components/huds/vistaHistorialTurnos.component.ts
- src/app/modules/rup/components/huds/vistaHistorialTurnos.html
- src/app/modules/rup/huds-lib.module.ts
https://proyectos.andes.gob.ar/browse/HUDS-59
1. Se implementa un nuevo tab "Historial de turnos" en HUDS para la visualizacion, ordenada por fecha, de los turnos del paciente seleccionado.
2. 
3.
> HUDS - Visualizar historial de turnos de paciente

- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
https://proyectos.andes.gob.ar/browse/CIT-206
1.  Se corrige la función de suspender turnos cuando se selecciona más de un turno.
> CITAS - Error al suspender turnos de una agenda

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-470
1. Se permite registrar eventos solo para indicaciones validadas 
2. 
3.
> feat(INT): registra eventos solo validadas

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-508
1. Avisa al usuario al momento de registrar un nuevo evento en estado 'realizado' si no coincide con la indicación.
2. Agrega formulario para controlar campos requeridos y boton guardar.
> Plan de indicaciones - Control de hs (frecuencia) para ejecución de una indicación

- src/app/modules/rup/components/elementos/valorNumerico.component.ts
https://proyectos.andes.gob.ar/browse/RUP-343
Se modifica valor por defecto, para que sea null y no 0 como ocurre actualmente.
1. 
2. 
3.
> fix(RUP): Componente numerico se cambia valor por defecto a null

- src/app/components/top/solicitudes/solicitudes.html
https://glpi.andes.gob.ar/front/ticket.form.php?id=3722
Agrega filtro estado en bandeja de salida
1. 
2. 
3.
> TOP: corrige filtro estado bandeja salida 

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-530
1.  Al internar un paciente, se debe seleccionar una cama en una fecha determinada.
2.  Si hay un cambio de fecha pero no de cama, se muestra un error en caso de que la cama no posea disponibilidad en esa fecha.
3. El error se muestra siempre que haya una cama y fecha seleccionadas.
> IN - Fix condición de error para cama ocupada

- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
https://proyectos.andes.gob.ar/browse/CIT-207
GLPI asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=3638
1. Se deshabilita el botón _Clonar agenda_ para evitar agendas duplicadas.
- [] Si
> CITAS - Se duplica agenda al clonarla

- src/app/modules/rup/components/elementos/FormulaBase.component.ts
- src/app/modules/rup/components/elementos/FormulaBase.html
https://proyectos.andes.gob.ar/browse/RUP-327
1. Agrega cotas max y min al valor de edad gestacional cuando es ingresado manualmente
2. Inicializa el valor del registro en null (Edad gestacional) cuando se opta por calcularlo a partir del campo fecha
**elementoRUP queda de la siguiente manera (En demo ya está actualizado)**
https://proyectos.andes.gob.ar/secure/attachment/12601/formulaBase
> RUP: Control requerido en formulas editables

- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
- src/app/modules/perinatal/components/listado-perinatal.scss
- src/app/modules/perinatal/services/carnet-perinatal.service.ts
https://proyectos.andes.gob.ar/browse/PER-76
1. Se agrego un filtro para que pueda traer solamente los pacientes que se encuentran en estado ausente.
2. En la descarga del csv se agregaron dos columnas a query "listado-perinatal" : estado y efector
[listado-perinatal.txt](https://github.com/andes/app/files/10861524/listado-perinatal.txt)
> PER - cambios en seguimiento perinatal

- src/app/modules/rup/components/huds/vistaPrestacion.html
https://proyectos.andes.gob.ar/browse/TOP-149
https://proyectos.andes.gob.ar/browse/TOP-145
1. En la HUDS de un paciente se renombran y agregan datos relacionados a la solicitud según corresponda.
2. Se consideran los mockups creados para la tarea TOP-145 para la nomenclatura y organización de los datos.
> TOP - Agrega información en vista de prestación y solicitud

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-266
1. Se cambio el *cdkVirtualFor por un *ngFor 
2. Se modifica el filtro "Documento" por el llamado "Paciente" donde el mismo nos permite buscar por documento, nombre o apellido.
NOTA: el error que se observa en el listado ocurre cuando se modifican algunos de los filtros de las fechas, luego se busca por un documento, con dicho documento (y que no tenga obra social sumar) se selecciona el bool "SUMAR" y luego se quita dicha opción. De esa forma se puede observar que el listado no trae el resultado correspondiente.
> MISC - Error en filtros en el buscador de turnos y prestaciones

- src/app/components/turnos/dashboard/estadisticas-pacientes.html
https://proyectos.andes.gob.ar/browse/CIT-215
1.  Se muestra en Historial de Turnos la Obra Social con la que se dio el turno.
2. Archivo modificado: \app\src\app\components\turnos\dashboard\estadisticas-pacientes.html
> CIT - Mostrar Obra Social en Historial de Turnos

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.scss
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-531
1. Componente: ingresar-paciente.component
2. Se creó un archivo 'ingresar-paciente.component.css' con la clase '.title-fixed' para inmovilizar el Título y los botones del encabezado en el Ingreso de Pacientes de Internación, capa Estadística.
3. Se agregó la ref. a ese archivo en el 'styleUrls' del componente.
4. Se llama a la clase .title-fixed desde el .html
> IN - Inmovilizar Titulo c/Botones en Ingreso de Pacientes capa Estadística

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-223
1. Se muestra en el calendario, las agendas dinamicas que sean del dia y que no esten vencidas.
2. Se tiene en cuenta el cambio con restringir  agendas dinamicas posteriores a la fecha actual, ya que las agendas dinamicas anteriores ya estaban contempladas.
> (feat)CIT: Sacar agenda dinamica que no sea del dia

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
[RUP-325](https://proyectos.andes.gob.ar/browse/RUP-325) - Se visualiza la misma prestación que genera la consulta
1. Se filtran la practicas que se pueden registrar para que no coincida con la actual
2. 
3.
> RUP - Se visualiza la misma prestación que genera la consulta

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
https://proyectos.andes.gob.ar/browse/IN-526
1.  Se creó la clase '.title-fixed' para inmovilizar el Título y los botones del encabezado cuando se agrega una nueva indicación.
> IN - Fijar botones al cargar una indicación

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-519
En el plan de indicaciones, cuando agregamos una nueva indicación de medicación , y luego seleccionamos un horario de la grilla, se puede observar que dentro del sidebar se solapan las funcionalidades de las dos acciones anteriores como se observa en la imagen. 
1. Agregada bandera para evitar solapamiento.
> IN - Solapamiento de funcionalidades en el sidebar

- src/app/components/turnos/dar-turnos/dar-sobreturno.html
Al momento de seleccionar una agenda, si se selecciona enseguida el botón de sobre-turno (y la conexión es lenta), puede arrojar un error en la consola porque no se llega a cargar la "agenda", por lo que se agrega control sobre la misma.
1. 
2. 
3.
> CITAS: agrega control en sobreturno

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
- src/app/modules/rup/elementos-rup.module.ts
https://proyectos.andes.gob.ar/browse/IN-511
1. se corrigió el error de no poder guardar una indicación de hidratación (el error provenía de un forEach)
2. Se agregaron toast al momento de guardar y editar una indicación de hidratación y también se agregaron tooltips a los botones de guardar y cancelar.
3. Se hizo un pequeño refactor en los detalles del sidebar al momento de mostrar una indicación de hidratacion.
NOTA: La tarea solamente consiste en poder guardar y editar una indicación de hidratacion solamente. Existen algunos bugs dentro del plan de indicacion pero ya existen las tareas correspondientes para ir resolviendolo!
> IN - balance hidrico en el plan de indicaciones

- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
https://proyectos.andes.gob.ar/browse/IN-527
1. En el filtro de principios activos se cambio la expresión snomed por <410942007.
2. Se corrige error cuando se agrega una nueva indicación de hidratarlo.
> IN - Cambiar filtro de principios activos

- src/app/components/organizacion/organizacion-create-update.component.ts
Se agrega control al recibir lo datos de georeferencia como "null", cuando realiza la validación de un efector con SISA.
https://proyectos.andes.gob.ar/browse/TM-26
1. 
2. 
3.
> TM (Profesionales): corrección de georeferencia con formato invalido

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-528
1. Agrega controles para restringit las acciones sobre una indiacion al dia actual.
> In - Plan indicaciones - No se debería poder registrar indicaciones en el pasado

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
https://proyectos.andes.gob.ar/browse/CIT-216
1. Se agrega control para evitar mostrar turnos, cuando la operación es edición
> fix(CITAS): Agrega control para permitir editar agendas pendientes de asistencia

- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-521
1. Se realiza la corrección sobre el chequeo en la fecha de los movimientos para contemplar los casos en que la hora es 00.
> IN - Fix movimientos con ingreso de internación a las 00 hs

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-349
1.  Desde el HTML solamente se modificaron desde las lineas 237 hasta las 248 donde a la función se le paso por parametro el turno y se acomodo el boton de Revertir Cambios.
> RUP - No se visualizan todos los datos del turno

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-152
1. Se marca la solicitud seleccionada que antes  no aparecía como tal.
> TOP - Marcar solicitud seleccionada

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-537
1. Se agrego el id de la prestación para que el aggregate que se encuentra en la api pueda filtrar de forma mas explicita y no devuelva mas de un egreso.
> IN - Error al editar egreso

- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaPrestacion.ts
https://proyectos.andes.gob.ar/browse/HUDS-68
https://proyectos.andes.gob.ar/browse/HUDS-67
1. Se complementa la información con "Unidad Organizativa".
2. Se prioriza la visualización de la información relevante para ámbitos de Internación y Ambulatorio sin despliegue. 
3. Se crea un botón para desplegar la información restante y evitar acumulación masiva en pantalla.
> feat(HUDS): modifica muestra en info de prestación

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/forms-builder/components/form-config/form-config.component.html
- src/app/modules/forms-builder/components/form-config/form-config.component.ts
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
- src/app/modules/forms-builder/components/forms-crud/forms-crud.scss
- src/app/modules/forms-builder/components/forms-list/forms-list.component.html
- src/app/modules/forms-builder/components/select-static/select-static.component.html
- src/app/modules/forms-builder/components/select-static/select-static.component.ts
- src/app/modules/forms-builder/forms.module.ts
- src/app/modules/forms-builder/services/form.service.ts
- src/app/modules/forms-builder/services/preset.resources.service.ts
https://proyectos.andes.gob.ar/browse/EP-107
1. Se completa el refactor del form builder con componentes plex.
2. Se separa la ficha covid19 de las demás fichas que pueden ser creadas desde el form builder. Esto se hace porque la ficha covid tiene mucha lógica propia y se hace imposible generalizar todo.
3. Se agrega un componente para que desde el form builder se pueda configurar uno o mas eventos sisa que luego en la api mediante esta configuración abrirá el evento en el snvs.
4. Se agrega en el FormPresetResourcesService dos secciones que podrán agregarse en el formBuilder de manera automática, estas se definen por base de datos.
> FORM - Refactor Form Builder 

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-204
1.  En el sidebar del html, se agrego un contenedor con la info del usuario.
2.  Usando el componente paciente-detalle se obtuvo la info basica del usuario.
3.  Se modifico el array "busquedas" para visualizarlo en el sidebar, comprimiendolo a 5 prestaciones y ordenando en el caso de  prestaciones ya existentes en el campo "BUSQUEDAS RECIENTES".
4. NOTA: lineas 85, 175, 248, 307 del html fueron suprimidas por metodos en el componente (lineas 794-807).
> CIT - En accion de turnos agregar datos del usuario y ordenar busquedas en el sidebar

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-524
1. Se agrego una nueva función ngAfterContentChecked() para que un método de devolución de llamada que se invoca inmediatamente después de que el detector de cambios predeterminado haya completado la verificación de todo el contenido de la directiva.
2. Se borraron ciertas variables ya que no cumplían ninguna función dentro del HTML y generaban problemas al editar una indicación en estado de borrador (No especificado en la tarea)
> IN - Error en consola al agregar una nueva indicación

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
[https://proyectos.andes.gob.ar/browse/CIT-213](https://proyectos.andes.gob.ar/browse/CIT-213)
1. Quita el llamado a codificacion del turno desde la app...  se agregar la codificación en un evento en al api
2. 
3.
> fix(CITAS): quita el llamado a codificación desde la app

- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
- src/app/interfaces/ITipoPrestacion.ts
https://proyectos.andes.gob.ar/browse/CIT-189
1.  En el html  revision-agenda se modificaron solamente las lineas 107 donde se agrego una nueva función asistenciaVerificada(turno) para realizar múltiples comparaciones. También se modifico la linea 249 donde se agrego una condición mas al ngIf "!turnoSeleccionado?.auditable"
2. Si la agenda auditada tiene todos los conceptos turneables no auditados no se muestra el botón de revisión
3. Cuando se revisa una agenda cuyos conceptos turneables son no auditados al momento de darle asistencia a un paciente que se encuentra en un turno no se muestran los campos de codificación y pasara al estado auditada.
> CIT - Agendas auditadas

- src/app/components/top/solicitudes/historialSolicitud.html
- src/app/components/top/solicitudes/notificar-paciente.component.ts
- src/app/components/top/solicitudes/notificar-paciente.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
https://proyectos.andes.gob.ar/browse/TOP-131
1. Se agrego una nueva funcionalidad de tal forma que el usuario puede notificar las veces que sea necesario, completando los campo obligatorios de fecha y descripcion.
NOTA: Se debería agregar un nuevo test para controlar esta nueva funcionalidad.
> TOP - Seguimiento de llamados telefonicos a pacientes

- src/app/core/mpi/components/paciente.component.ts
> MPI (Fix) - chequeo de validacion fallida

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
https://proyectos.andes.gob.ar/browse/IN-522
1. Se agrega el botón con el llamado a la función de deshacer Internación en el Historial del listado de internaciones, para capa médica.
2. Se consideran los mismos chequeos para la muestra del botón que en mapa de camas.
> IN - Mostrar botón para anular internación desde historial

- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- Corregir bug para auditar agendas dinámicas, ya que al asignar un turno en una dinamica no queda registrado en dicho turno 
1. 
2. 
3.
> fix(CIT): Cambia  control de turno auditable por tipo de prestación auditable

- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-221
1.  Se quita el botón _Clonar_ para las agendas dinámicas. Esto en el listado de agendas creadas. Gestor de Agendas.
2.  Se quita el botón _Guardar y Clonar_ cuando se crean agendas dinámicas.
https://github.com/andes/andes-test-integracion/pull/471
> CITAS - No clonar agendas dinamicas

- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-533
1. Verifica si existe una internación futura en la cama que se esta ingresando un paciente. De ser asi, se da aviso de la fecha y hora de la misma.
> IN - Control en registro de una internacion

- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-208
1.  Actualizar la seccion de Agenda Original.
2.  Agregar boton info.
3.  Actualizar botones de clonar y cancelar agenda.
4. En el html gestor-agenda, se agregan solamente cambios de linteo.
> (refactor)CIT - Aplicar mockup en clonar agendas

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
https://proyectos.andes.gob.ar/browse/GDU-57
1.  Se contempla el caso para los permisos que tienen tipo de visibilidad "local-restricted"
2.  Permite dar permisos a otros usuarios en tanto la organización actual sea igual a la seleccionada para editar
> GDU - Incorpora visibilidad para local-restricted

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-539
1. Se agregaron condiciones para verificar si viene una fecha o un dato nulo, el cual no actualizara nada.
> IN - error al editar manualmente una fecha

- src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
https://proyectos.andes.gob.ar/browse/CIT-230
1. Se quito la condicion de agenda auditada en la botonera de agendas.
> mostrar boton revision agenda

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
https://proyectos.andes.gob.ar/browse/IN-514
1. Se agregaron restricciones para que los botones continuar y anular prestación solamente lo puedan hacer los usuarios con rol de profesional. También se corrigieron algunos títulos de los labels.
> Botón iniciar prestación

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/interfaces/turnos/IAgenda.ts
https://proyectos.andes.gob.ar/browse/CIT-218
1. Al momento de crear una agenda, se agrego un campo (plex-bool) llamado Multiprofesional, .
2. NOTA: en el html, se modifico las lineas 69-74, lo demas es cambios de linteo.
"multiprofesional": true,
> (feat) CIT - Agregar configuracion de multiprofesional en agendas

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Sacar la opción de clasificación por laboratorio privado
1. 
2. 
3.
> fix(EPI): Quita  la opción de clasificación por laboratorio privado

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-538
1. Se agregaron funciones de condicion para que al registrar un balance hidrico el medico pueda aceptarla sin necesidad de tener que pasar por el interconsultor.
> IN - dar opción para validar o no una indicación

- projects/auth/src/lib/auth.service.ts
- src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-535
1.  Se limpia los filtros de la cache al cambiar de organizacion.
> IN - Limpiar filtros

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/services/facturacionAutomatica.service.ts
https://proyectos.andes.gob.ar/browse/TYP-3
1.  Si la prestación no está configurado en los datos de Conceptos Turneables, se emite mensaje de que no tiene permitido generar comprobante.
> Feat - (TYP) Visualizar mensaje de comprobantes que no se migran

- src/app/components/novedades/catalogo-novedades/filtro-novedades/filtro-novedades.component.html
- src/app/components/novedades/catalogo-novedades/filtro-novedades/filtro-novedades.scss
- src/app/components/novedades/detalle-novedad/detalle-novedad.scss
- src/app/components/novedades/lista-novedades/calendario/calendario-novedades.component.ts
- src/app/components/novedades/lista-novedades/lista-novedades.component.html
- src/app/components/novedades/novedades.component.ts
https://proyectos.andes.gob.ar/browse/MISC-278
1. Se implementa la apertura de una novedad al hacer click sobre la campanita en el nav-bar principal
2. Se corrige el uso del botón volver al navegar por novedades y filtros
3. Se corrige el muestreo y borrado del campo de fecha al navegar
4. Se corrige scroll-bar en el muestreo de novedades con filtro por módulos
> MISC-278 - Repara filtros de vistas para las novedades

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
https://proyectos.andes.gob.ar/browse/TYP-6
1.  Se cambia el mensaje a un warning, cuando el tipo de prestacion no esta configurado.
> TYP - Modificar mensaje de comprobante

- src/app/components/organizacion/configuracion-internacion.component.ts
- src/app/components/organizacion/configuracion-internacion.html
- src/app/components/organizacion/organizacion.component.ts
https://proyectos.andes.gob.ar/browse/TM-25
1. Obtiene conceptos turneables solo de la DB
2. Agrega bool para 'nuevo registro' en capa interconsultores
3. Agrega botón 'reiniciar valores' para volver a los valores del efector de referencia la capa seleccionada
Agregar los siguientes conceptos en la coleccion **conceptosTurneables** (Demo ya está actualizado)
{
"conceptId" : "5491000013101",
"term" : "evaluación médica inicial",
"fsn" : "evaluación médica inicial (procedimiento)",
"semanticTag" : "procedimiento",
"ambito" : [ 
"internacion"
]
},
{
"conceptId" : "5971000013106",
"term" : "evolución médica",
"fsn" : "evolución médica (procedimiento)",
"semanticTag" : "procedimiento",
"ambito" : [ 
"internacion"
]
},
{
"conceptId" : "6881000013107",
"term" : "evolución no médica",
"fsn" : …
> TM - Configuracion de internacion por conceptos turneables

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
[ ](https://proyectos.andes.gob.ar/browse/RUP-358)
1.  Pregunta si es 'Primera Vez' cuando es un Evento.
2.  Ej. Mordedura de perro.
3.  registro.concepto.semanticTag IN(  'hallazgo' ,  'trastorno' , 'situación', 'evento')
> RUP - Preguntar si es Primera Vez cuando es un Evento

- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
1. Elimina request al historial de paciente en listado medico.
> IN - Corrige request historial

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
https://proyectos.andes.gob.ar/browse/IN-403
1. Modifica foco al agregar nuevos conceptos a una consulta. Ahora diferencia si se está agregando dentro de un seccionado (Uno o mas conceptos) y si los está agregando fuera de este.
> IN - Foco al ingresar un nuevo concepto en una valoracion inicial

- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
https://proyectos.andes.gob.ar/browse/IN-547
1. Corrige fecha 'desde' para obtención del historial de movimientos.
2. Corrige función de deshacer internación tanto desde el mapa como listado de internacion, en capas asistencial y estadistica-v2 para efectores con capas unificadas. 
3. Las salas quedan excluídas de esta funcionalidad.
4. Actualiza listado luego de deshacer.
5. Agrega controles para visualización/ocultamiento de botones de acción para casos de conexión lenta
> IN - Deshacer internación

- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/interfaces/ICreatedBy.ts
- src/app/modules/auditoria/component/auditoria-listado.html
https://proyectos.andes.gob.ar/browse/MPI-406
1.  Se agrega columna con dato "Creado por" que muestra el nombre completo, numero de DNI y efector del usuario que creó ese paciente. Cuando no existe el usuario se autocompleta con "S/D" (sin dato).
> MPI - Auditoria de pacientes- creado por

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
https://proyectos.andes.gob.ar/browse/IN-546
1. Se agrego una condición IF para que filtre por las prestaciones que no sean pertenecientes al plan de indicación (Sección de medicación, hidratación, etc)
2. Se agrego un filter al observable prestacionesList$ para que el select de prestación dentro del tab de registros no aparezca el de "plan de indicacion"
> IN - quitar indicaciones de registro

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Corrige error al visualizar registros en capa estadística y quita el filtro de prestaciones de plan de indicaciones por pedido de usuarios
1. 
2. 
3.
> fix(INT): Corrige error al visualizar registros en capa estadistica

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
1. Corrige edición de egreso para que actualice movimientos (Había un problema en asignación de valores por referencia)
2. Corrige búsqueda por documento en listados, ya que podrían haber pacientes que al egresar todavía no poseen documento.
> INT - Fix egreso y filtro por documento en listados

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
1. Corrige formato de fechas moment que deberían instaciarse como date
> IN - Fix formato de fechas

- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
> INT - Fix sincronizacion fecha egreso

- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
- src/app/services/organizacion.service.ts
https://proyectos.andes.gob.ar/browse/BI-135
1. Filtra select de zonas y organizaciones según permisos de usuario.
**OBSERVACION**: Las modificaciones se encuentran en un archivo en el link del requerimiento.
> BI - Permisos por zona

- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/modules/perinatal/components/listado-perinatal.component.ts
Cambia nombre de filtro de organización en listados de internación y perinatal
> fix(QUERIES): cambia filtro en descargas csv

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
https://proyectos.andes.gob.ar/browse/IN-532
1. Se cambia la leyenda al querer eliminar una internación de forma completa.
> IN- Control anular internación

- src/app/core/mpi/components/notas-paciente.component.ts
- src/app/core/mpi/components/notas-paciente.html
https://proyectos.andes.gob.ar/browse/MPI-397
1. Se cambió el ícono de guardar nota de Paciente.
2. Archivo: \app\src\app\core\mpi\components\notas-paciente.html
3. Se modificó la propiedad "icon" de "plus" a "check" del "plex-button"
> MPI: Cambiar icono 'plus' por 'check' en Notas Paciente

- src/app/core/mpi/components/documentos-paciente.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/paciente.html
- src/app/core/mpi/components/paciente.scss
https://proyectos.andes.gob.ar/browse/MPI-414
1.  A cargar un nuevo Paciente, si está validado, solo mostrar pacientes candidatos validados.
2. 
3.
> MPI - Paciente validado mostrar solo Pacientes candidatos validados

- src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
https://proyectos.andes.gob.ar/browse/IN-567
1. Cambiar de label "Médico" por "Profesional a cargo"
> IN - Cambiar nombre al seleccionar perfil

- src/app/components/profesional/profesional.component.ts
- src/app/components/profesional/profesional.html
- src/app/services/profesional.service.ts
https://proyectos.andes.gob.ar/browse/TM-30
1. Se agrega campo "Estado " en tm/profesionales
2. Se agrega filtro "habilitado" en forma de slider
> TM - Filtrar profesional por habilitado y estado

- src/app/components/profesional/profesional-create-update.html
- src/app/components/profesional/profesional.html
https://proyectos.andes.gob.ar/browse/TM-28
1.  Se agrega slider para habilitar/deshabilitar profesional "no matriculado" desde tm/profesional/editar
2.  Se intercambian botones editar/cerrar en sidebar tm/profesional
> TM -  Deshabilitar profesional no matriculado

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/RUP-364
1. No visualizar botón "+" desde la HUDS
2. Vale aclarar que el segundo punto solicitado, en la tarea, por ahora queda sin aplicar, ya que no se encontró la falla.
> RUP - No evolucionar trastorno resuelto

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-560
1. Permitir boton de "Exploración visual" si tiene permiso a la visualizacion de huds.
2. Ademas si se desea ingresar directamente por url, retrocederlo a mapa de camas en su respectiva capa.
3. Linteo en lineas 534, 539-544, del componente resmune-internacion.
GLPI ASOCIADO: https://glpi.andes.gob.ar/front/ticket.form.php?id=4118
> IN - Permitir botón exploracion visual

- src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/modules/perinatal/components/listado-perinatal.component.html
https://proyectos.andes.gob.ar/browse/MPI-407
1. Agregar filtraciones de identidad autopercibida (alias) o datos de identificación extranjera, para visualizarls en busquedas. 
2. Ademas se agrega el detalle del alias en las descargas de pdf (CITAS y RUP).
GLPI asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=3998
> MPI: Identidad autopercibida

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-169
1. Inhabilita seleccion de grupo profesional si no hay tipo de prestación seleccionada
2. Limpia selección de profesionales si cambia la selección de tipo de prestaciones
3. Incluye tipo de prestaciones en la busqueda de profesionales
4. Que pendiente de implementación el hint en el select de profesionales
> CIT - Control de permisos de prestaciones en profesionales

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
https://proyectos.andes.gob.ar/browse/EP-217
1. Se realizan cambios en el formulario de la ficha covid de acuerdo al archivo adjunto en la tarea de jira. Se adjunta archivo con los cambios modificados. Lo resaltado con gris es lo que está hecho.
[MSaludNQN Covid19. Ficha digital. Propuesta de cambios 7.7.2023 -hechos.pdf](https://github.com/andes/app/files/12552124/MSaludNQN.Covid19.Ficha.digital.Propuesta.de.cambios.7.7.2023.-hechos.pdf)   
3.  Tener en cuenta que hay cambios que se optó por realizarlos directamente desde la aplicación.  
4.  Cambios a realizar en la BD: agregar campo ifi en la colección forms. Se adjunta foto.
https://github.com/andes/andes-test-integracion/pull/487
> EPIDEMIOLOGIA - Actualizar ficha covid

- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
https://proyectos.andes.gob.ar/browse/IN-562
1. Se quita el request en el tab de movimientos, al momento de cerrar el sidebar.
2. Se agrega botón de cerrar el sidebar en el historial de capa médica.
> IN - Listado internacion - request inválido

- src/app/components/profesional/profesional.component.ts
- src/app/components/profesional/profesional.html
- src/app/services/profesional.service.ts
https://proyectos.andes.gob.ar/browse/TM-27
1. Se agrega nuevo switch _No Matriculado_. El cual al estar habilitado muestra solo los no matriculados. De lo contrario muestra tanto los que están como los que no están matriculados.
2. Se agrega título Listado.
3. Se incluye un mensaje cuando no hay resultados para la búsqueda.
> TABLAS MAESTRAS - Nuevo filtro tm/profesional

- src/app/apps/vacunacion/components/gestion-turnos/monitoreo-inscriptos.html
- src/app/components/prestamosHC/prestamos-hc.component.html
- src/app/components/turnos/configuracion/espacio-fisico/espacio-fisico.html
- src/app/components/turnos/dar-turnos/calendario.html
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/components/relaciones-pacientes.html
- src/app/modules/auditoria/component/auditoria.html
- src/app/modules/auditoria/component/reporte-errores.html
- src/app/modules/auditoria/component/vincular-pacientes.html
- src/app/modules/mpi/components/paciente-busqueda.html
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/components/elementos/informeActividadNoNominalizada.html
- src/app/modules/rup/components/elementos/rupers/seccionado/seccion.component.html
- src/app/modules/rup/components/internacion/puntoInicio-internacion.html
https://proyectos.andes.gob.ar/browse/PLEX-324
Actualmente se utiliza la librería de iconos de andes-font y de material design , se modificaron algun de los iconos provenientes de la dependecia de material design.
1. 
2. 
3.
> Migrar iconos a andes-font

- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
[https://proyectos.andes.gob.ar/browse/RUP-379](https://proyectos.andes.gob.ar/browse/RUP-379)
1. Quita el campo de selección de profesional destino al cargar una solicitud desde Rup 
2. Agrega label indicando que la solicitud no pasará por el modulo de solicitudes por no tener una regla asociada
> FEAT(RUP): Quita profesional destino al cargar solicitud

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/huds/vista-accesos-huds.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/PRIV-66
1. Se agrego una condición para agregar un campo mas al los parámetros que consultan a la api
> PRIV - Restricción por efector

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-163
1. Se agrega opción "volver a auditoria" en dropdown de una solicitud en estado pendiente sin turno en bandeja de entrada.
> TOP - Deshacer una solicitud auditada

- src/app/components/top/pipes/estado-prestacion.pipe.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/modules/estadisticas/components/top/filtrosSolicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-156
1.  Agregado filtro para solicitudes vencidas
2.  Agregado badge para solicitudes vencidas
> TOP - Solicitudes: nuevo estado vencido

- projects/auth/src/lib/auth.service.ts
- src/app/app.component.ts
- src/app/interfaces/IProfesional.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/services/profesional.service.ts
https://proyectos.andes.gob.ar/browse/TM-31
1. :  Se restringe el acceso a la creación de prestaciones a usuarios que  estén cargados como profesional con el atributo "habilitado" en false.
> TM - Profesionales deshabilitados

- angular.json
> MISC - Permite debuguear por consola

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Se necesitaba agregar algunos controles y eliminar subscribes para realizar el guardado de datos de manera mas secuencial y evitar modificar datos y algun guardado anterior faclló. Además informarle al ausuario de cualquier posible inconsistencia.
1. Cambio de camas: Se agregan controles, de manera que se vuelva a chequear los estados de la cama origen y destino justo antes de realizar el guardado. 
2. Ingreso de pacientes (o edición): Se agregan controles para detectar guardados interrumpidos o mal realizados de manera de cortar la ejecución e informarle a la usuario para que realice la posible anulación del ingreso.
3. Egreso de pacientes (o edición): Se secuencializa el proceso de guardado de manera de evitar inconsistencia entre internacion y movimientos. Se agregan controles y …
> INT - Refactor en controles de ingreso y egreso

- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/modules/mpi/components/paciente-buscar.component.ts
corrige error donde se mezclan pacientes luego de usar scan
https://proyectos.andes.gob.ar/browse/MPI-419
https://glpi.andes.gob.ar/front/ticket.form.php?id=4380
1. 
2. 
3.
> MPI: corrige error que cruza pacientes por scan

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-242
1. Se implementa el método "reasignarTurno" que, basado en un id de turno suspendido, realiza la reasignación del mismo en la nueva agenda.
2. La agenda suspendida actualiza el estado del turno reasignado.
3. Se utiliza el método "hayTurnoSuspendido" para chequear la existencia de un ultimo turno suspendido.
Generar una solicitud fuera de agenda desde RUP, elegir tipo de prestación (recomendado "consulta de clínica medica") e incorporar la regla de tipo "Prestación origen" -> "Organización Destino" -> "Prestación Destino". 
Luego crear una agenda para la prestación destino y agregar turnos "con llave" a partir de las 48 horas desde la creación de la solicitud. Ir a Solicitudes TOP y dar un turno para la solicitud creada desde RUP. La …
> CIT - Reasigna turnos en agenda suspendida desde TOP

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
https://proyectos.andes.gob.ar/browse/IN-581
1. En capa estadística, se visualizan únicamente los registros que son del efector logueado.
> IN - Restringir por efector los registros

- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/components/ejecucion/buscador.scss
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/RUP-359
1. Modifica estilos en botones de filtros de buscador en prestaciones abiertas de RUP
> RUP - Visualización de botones del buscador

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
- src/app/components/turnos/citas.module.ts
- src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
- src/app/components/turnos/dar-turnos/dar-sobreturno.html
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
- src/app/components/turnos/dar-turnos/seleccionar-financiador.html
- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
- src/app/components/turnos/punto-inicio/turnos-paciente.html
- src/app/interfaces/IObraSocial.ts
https://proyectos.andes.gob.ar/browse/CIT-214
1. Implementación de un componente reutilizable para las obras sociales o prepagas del paciente
2. El selector manual para "otras" ahora incluye no solo las Obras Sociales (OS) sino también todas las prepagas disponibles. Se excluyen las OS que el paciente ya posee.
3. Se agrega el componente en la pantalla -Dar Turno- en ventanilla de citas.
4. Se reemplaza el componente en la solapa -Turnos- en ventanilla de citas.
5. Se reemplaza el componente al seleccionar turno, para prestaciones iniciadas, en -Buscador de Turnos-.
> CIT - Implementa selector de financiadores

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
https://proyectos.andes.gob.ar/browse/RUP-387
1. Cambia texto de label en botón de filtro de buscador en RUP
> RUP - Modifica label en boton de filtro de buscador

- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
https://proyectos.andes.gob.ar/browse/RUP-369
1.  Se habilitó botones de descarga cuando concepto === 'elemento de registro'
> RUP - Descarga PDF de elementos de registro

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/TYP-10
1. Un usuario profesional que no tenga permisos para el módulo TYP podrá acceder al buscador a travéz de la dirección (...gob.ar/buscador). No se visualiza el icono de buscador en punto de inicio por cambio de requerimiento.
2. Se visualizan las prestaciones en las que el profesional sea parte del equipo de salud.
3. Se deshabilita el campo "Equipo de salud" .
> TYP - Corregir Acceso al buscador

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/nueva-indicacion/nueva-indicacion.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
- src/app/modules/rup/components/core/rup.component.ts
https://proyectos.andes.gob.ar/browse/IN-554
1.  Para evitar redundancias, se quita el dropdown.
2.  Se agrega cartelito inidicando la accion cuando no hay indicaciones cargadas.
3. Componentes rup y nueva-indicacion, se corrige condiciones.
> Plan indicaciones (Ref mock) - Cambios propuestos en mockups

- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
Corrige error al seleccionar financiador desde ventanilla-citas para recupero financiero.
1. 
2. 
3.
> fix(CIT): corrige bug de obra social al generar el comprobante

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
https://proyectos.andes.gob.ar/browse/CIT-250
1. Se implementa la posibilidad de no tener paciente en prestación no nominalizada.
2. Se remueve chequeo innecesario con mensaje de alerta
> CIT  - Error al crear prestación no nominalizada

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/vista-cda/vista-cda.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/vista-cda/vista-cda.component.scss
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/vista-cda/vista-cda.component.ts
https://proyectos.andes.gob.ar/browse/IN-281
1. Se incorporan los registros traídos de CDA con laboratorios a los registros actuales.
2. Se modifican las opciones de filtrado de registros para incluir laboratorios.
3. Se crea nueva vista para ver información del laboratorio y descargar.
> IN - Sumar laboratorios en vista de registros

- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.html
- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
https://proyectos.andes.gob.ar/browse/MAT-151
1. El timeout que da al intentar enviar email, (guarda el usuario), solo me dió en la subse, en mi casa anduvo OK.
2. El error de validación en un caso estudiado (Ape, nom, 32247536) se dá porque ese documento está duplicado, le cambié a 32247540 y validó OK.
3. Debajo del <form> agregué la leyenda: **Los datos deben ser ingresados tal cual figuran en el DNI.**
4. Se cambiaron plex.info('danger'...) por plex.info('warning', ...)
5. Se cambió 'plex-text' por 'plex-int pattern="patrondocumento"'
> MAT - Pantalla creacion usuario

- src/app/components/top/pipes/botones.pipe.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
Volver a ver el boton 'volver a auditoria'
> TOP (FIX) - boton 'volver a auditoria'

- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- Agrega componente de  visualización de Cdas para el historial de. la internación (capa Medica)
1. 
2. 
3.
> FIX(IN): Agrega componente de  visualizacion

- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-143
1. Se modificó para que muestre todas la Organizaciones cuando el usuario tiene permisos para todo el módulo 'visualización de información'
> BI - No carga select Organizacion

- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.html
- src/app/apps/rup/mapa-camas/sidebar/estado-servicio/estado-servicio.component.ts
https://proyectos.andes.gob.ar/browse/IN-569
1. Se agrego un botón con la función de editar la fecha del mapa de camas.
> IN - Fecha y hora del mapa de camas

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
https://proyectos.andes.gob.ar/browse/IN-557
1- Se cambio el botón de desocupar por un dropdown tanto en el main como en el sidebar.
> IN- Mejoras en egreso internacion

- src/app/components/profesional/profesional.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/directives/profesionales-select.directive.ts
- src/app/services/profesional.service.ts
https://proyectos.andes.gob.ar/browse/CIT-247
1. En profesionalService se cambió atributo '**activo**'(string) por boolean.
2. En componente 'tmProfesionales' se filtra solo habilitados.
3. En 'planificar-agenda' se agregó 'habilitado: true' en el query del request.
4. En 'profesional-component' se modificó profesionalService.activo.next(this.filtros.estado ? !this.filtros.estado : null).
> CIT - Crear agenda con profesional habilitado

- src/app/modules/perinatal/components/listado-perinatal.component.ts
Se corrigen filtros en listado perinatal al realizar la descarga csv.
1. Se corrige filtro "ausente".
2. Se corrige la fecha "hasta" incluyendo la hora fin del día.
3.
> PERINATAL: fix en filtros del listado

- src/app/core/mpi/components/paciente.component.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/mpi/components/paciente-detalle.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-estatico.component.ts
- src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-estatico.html
https://proyectos.andes.gob.ar/browse/RUP-357
1.  Se agregó un Botón 'Editar Paciente' en HUDS.
2.  <paciente-detalle> recibe @Input() puedeEditar default false.
3.  Al salir o guardar paciente vuelve a HUDS.
> RUP - Actualizar información del paciente desde RUP

- projects/shared/src/lib/server/resource-base.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/services/resumen-internacion.http.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
https://proyectos.andes.gob.ar/browse/IN-553
1. Se incorpora al listado de internación las unidades organizativas que ya provienen desde la API.
2. Se soluciona el problema de ordenan las lista de forma ascendente/descendente ya que al seleccionar una columna de dicho listado no se ordenada y saliá un error por consola.
> IN - Mejorar consulta para listado médico

- angular.json
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
Reportan que no se visualizan bien los registros de las internaciones, además funciona mal el filtro de fechas ('fecha desde' setea por defecto una fecha mayor al campo 'fecha hasta')
1. 
2. 
3.
> In (Fix) - Visualizacion de registros en sidebar

- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-unificado.component.ts
Se elimina el campo unidad organizativa del listado de internaciones histórico.
> fix(INT): Saca el  campo de UO del listado historial medico

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.scss
https://proyectos.andes.gob.ar/browse/IN-579
1. Se incorpora el botón de búsqueda para recuperar elementos del historial entre fechas de inicio y hasta
> IN - Incorporar botón de búsqueda en historial

- src/app/components/top/pipes/botones.pipe.ts
- src/app/components/top/pipes/linkTurnoRemoto.pipe.ts
- src/app/components/top/solicitudes/auditarSolicitud.component.ts
- src/app/components/top/solicitudes/auditarSolicitud.html
- src/app/components/top/solicitudes/referirSolicitud.component.ts
- src/app/components/top/solicitudes/referirSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
- src/app/core/mpi/components/notas-paciente.html
https://proyectos.andes.gob.ar/browse/TOP-153
https://proyectos.andes.gob.ar/browse/TOP-177
1. Agregar la opción de REFERIR a las solicitudes contrarreferidas en la bandeja de salida del efector origen.
2. Se crea componente referir paciente.
3. Se agregan las funcionalidades de los nuevos requerimientos de TOP-177.
NOTA: Se agrega para otra tarea un nuevo caso de test.
> TOP: Continuidad a solicitud contrarreferida

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/modules/auditoria/component/auditoria.html
https://proyectos.andes.gob.ar/browse/TYP-7
1. Se agrega una carga inicial de la colección de configuracionAutomática, para después trabajarlo.
2. La búsqueda además de realizarce por prestación, sea por tipo de facturación. (sumar/recupero).
3. NOTA: Para cuando la generación del comprobante se quiera hacer con sumar y no esté en la configuración, el mensaje debería hacer el siguiente: Esta prestación no genera comprobantes automáticos a SUMAR.  Para el caso de las obras sociales.
> TYP - Mejorar llamados a la api

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
- src/app/modules/epidemiologia/constantes.ts
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.html
- src/app/modules/forms-builder/components/forms-crud/forms-crud.component.ts
- src/app/modules/forms-builder/services/form.service.ts
https://proyectos.andes.gob.ar/browse/EP-221
https://proyectos.andes.gob.ar/browse/EP-220
1. Agrega un campo de "Descripción" a visualizar al inicio de las fichas
2. Controla el 0 inicial en el identificador PCR
3. Visualizar el identificador PCR en el buscador de fichas para las fichas tipo UMA
> fix(EPI): Corrige error con  PCR

- src/app/modules/rup/components/core/rup.component.ts
https://proyectos.andes.gob.ar/browse/RUP-390
1. Se agrega una condición mas al if para verificar si vienen los parámetros antes de asignarlos a los registros
2. 
3.
> RUP - Error en carga de componente

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
- src/app/modules/mpi/components/paciente-relaciones.component.ts
https://proyectos.andes.gob.ar/browse/EP-219
1.  Se corrigió el HTML para que funcione el scroll infinito.
2.  Se modificó listado pacientes relacionados para que devuelva paciente en lugar de paciente.relacionado
> EP - Corregir scroll al buscar pacientes y error al guardar ficha paciente relacionado

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/vistaHuds.html
https://proyectos.andes.gob.ar/browse/RUP-365
1.  Se agrego una condición para que los tabs dentro de RUP se carguen al mismo tiempo y se modificó el orden de la carga de los mismos. 
2.  Se elimino rup-seguimientoPaciente ya que se eliminaron sus componentes y su declaración en el modules.
> RUP - Cambiar foco al iniciar prestación

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso-estadistica-v2.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingreso-paciente-workflow/ingreso-paciente-workflow.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-552
1. No mostrar posibilidad de egresar el paciente (tab) cuando no tiene movimientos.
2. Eliminar internación (mostrar botón para deshacer internación) => sólo se borraría prestación/ resumen (estadística/médica).
3. Asociar la internación a una cama disponible: cargar movimiento de ingreso faltante.
> IN - Internación sin movimiento de ingreso

- src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.component.ts
- src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
> TYP (Fix) - Separa cache de busqueda en cada submodulo

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/paciente.html
https://proyectos.andes.gob.ar/browse/MPI-417
1. Se habilita el botón de "ignorar y guardar" tras encontrar coincidencias con otro paciente ya agregado.
2. Se implementa detector de cambios para los campos de formulario que deshabilitan botón de "ignorar y guardar".
- [] Si
Vinculo con pr de api a ultimo moment (laucha) por un bug que se detectó en funcionalidad similar del lado de api.
> MPI - Modifica condición para botón de "ignorar y guardar"

- src/app/components/turnos/dar-turnos/calendario-dia.class.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
https://proyectos.andes.gob.ar/browse/CIT-228
1. Se agrego un botón de dar turno en solicitudes de ventanilla-citas. 
2. Se agregaron condiciones para que aparezcan las agendas con llave, sino las de turnos programado o, en último lugar, las del día.
> CIT - Ventanilla: poder dar turno con llave

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/modules/mpi/components/paciente-listado.component.ts
- src/app/modules/mpi/components/paciente-listado.html
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-561
1.  En **plan-indicaciones-component** se establece **prestacion.inicio = 'plan-indicaciones'** antes del POST al **validar** indicacion.
2.  Se corrigió tambien **paciente-listado-component** ya que no quedaba marcado el **paciente seleccionado** en el listado.
> IN - Cargar campo para diferenciar prestación del Plan de Indicaciones

- src/app/components/turnos/dar-turnos/calendario-dia.class.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
1. A partir del pr https://github.com/andes/app/pull/2941 se introdujo un bug que oculta, por defecto, la mayoria de las agendas. Para poder verlas hay que activar el switch de "ver agendas sin turnos".
> CITAS (FIX) - Corrige visualizacion de agendas en calendario

- src/app/components/top/reglas/reglas.component.html
Cambia tipo de plex-bool por error en el check (futuro fix en plex)
1. 
2. 
3.
> fix(TOP): cambia estilo de boton por error en plex

- src/app/apps/rup/mapa-camas/mapa-camas-main.component.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-color.pipes.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-estado-nombre.pipe.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.scss
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.html
- src/app/modules/rup/components/elementos/rupers/prescripcion-medicamento-internacion/prescripcion-medicamento-internacion.component.ts
https://proyectos.andes.gob.ar/browse/IN-573
https://proyectos.andes.gob.ar/browse/IN-584
1.  Se agrega un nuevo rol dentro del modulo de internacion llamada FARMACEUTICO donde se puede ver la huds del paciente y trabajar sobre el plan de indicaciones.
2.  Dentro del plan de indicaciones, como farmacéutico puedo aceptar/rechazar una indicación que se encuentra en estado validada o bypasseada por el profesional.
3. Se agregaron nuevos badges (VALIDADA, SUSPENDIDA, ESPERANDO CONTROL DE FARMACIA) para indicar los estados de las indicaciones.
4. Se agregaron nuevos colores a las indicaciones para mostrar los estados en los que se encuentra. VERDE: indicación aceptada por farmacéutico, NARANJA: indicación bypasseada por el profesional.
5. Se modificó el label de suspender/rechazar una …
> IN - nuevo rol de internacion: farmacia

- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.html
Corrige error al visualizar solicitudes en HUDS que tengan adjuntos.
1. 
2. 
3. 
- [ X] No
> fix(HUDS): corrige error al visualizar solicitudes con adjuntos

- src/app/app.module.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/dashboard/demandaInsatisfecha.html
- src/app/components/turnos/dashboard/demandaInsatisfecha.ts
- src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
- src/app/components/turnos/dashboard/estadisticas-pacientes.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/interfaces/turnos/IListaEspera.ts
- src/app/services/turnos/listaEspera.service.ts
https://proyectos.andes.gob.ar/browse/CIT-256
1. Se modificó el componante estadisticas-paciente, se agregó **@Input() demandaInsatisfecha**.
2. Dentro del tab Turnos se agregó un form donde pide **Tipo de Prestación** (Obligatorio) solo ambito ambulatorio,
**Profesiona**l (todos) no obligatorio y Motivo (cocinado p/codigo)(hardcode).
3. Nuevo componente Angular **demandaInsatisfecha**.
4. Se modificó Esquema de colección **listaEspera**
> CIT - Demanda Insatisfecha.

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
https://glpi.andes.gob.ar/front/ticket.form.php?id=4617
1. 
2. 
3.
> TYP: Se genera siempre comprobonte para SUMAR

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-internacion-capas.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
https://proyectos.andes.gob.ar/browse/IN-596
1. Se detecta si la internación tiene un único movimiento para decidir si mostrar u ocultar el dropdown de deshacer
2. Se corrige obtención de id de resumen de internación
3. Se corrige edición de la internación en capa médica (No funcionaba)
> IN (Fix) - Deshacer internación

- src/app/components/organizacion/organizacion-create-update.component.ts
- src/app/components/organizacion/organizacion-create-update.html
https://proyectos.andes.gob.ar/browse/AM-261
1.  Como usuario gestor de Organizacion, pueda administrar por bd la distancia de que permite encontrar efectores con turnos disponible por app.
2. Se agrega campo input para el ingreso de la circunferencia en km.
3.  Se permite un rango de 1 km a 10 km por el momento.
{
"_id" : ObjectId("65c4fa41f019edab2ec92b23"),
"key" : "1",
"nombre" : "minimo-km",
"source" : "organizacion:circunferenciaKmTurno",
"type" : "number"
},
{
"_id" : ObjectId("65c4fa65f019edab2ec92b53"),
"key" : "10",
"nombre" : "maximo-km",
"source" : "organizacion:circunferenciaKmTurno",
"type" : "number"
},
{
"_id" : ObjectId("663a12e3f1b15d16a728a1f7"),
"key" : "4",
"nombre" : "default-km",
"source" : "organizacion:circunferenciaKmTurno",
"type" : "number"
}
> AM - Configuracion distancia de turnos

- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/components/turnos/gestor-agendas/revision/fuera-agenda.html
- src/app/directives/profesionales-select.directive.ts
- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
- src/app/modules/perinatal/components/listado-perinatal.component.html
https://proyectos.andes.gob.ar/browse/TM-32
1. Se modifico el plex-select para que desde diferentes módulos como gestor de agendas, TOP, buscador de turnos y prestaciones, etc se pueda visualizar no solamente el nombre y apellido del profesional sino también el documento y la matricula mas reciente. 
2. En todos los HTML solamente se eliminaron los labelField donde se utiliza la propiedad tmProfesionales ya que la misma no presentaba ninguna funcionalidad.
> TM - Nueva funcionalidad de plex-select

- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
https://proyectos.andes.gob.ar/browse/RUP-392
1. Modifica condición para el muestreo del botón de previsualización (PDF) si la prestación no esta validada.
> RUP - Omite previsualizacion en PDF sin validación de prestacion

- projects/shared/src/lib/pipes/edad.pipe.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-362
1.  Se muestra la edad del paciente en Agenda c/turnos y Fuera de Agenda.
2. Si el paciente del turno tiene fechaNacimiento, se muestra la edad con el pipe edad.
> RUP - Visualizar edad en turnos asignados en una agenda.

- src/app/components/snomed/snomed-buscar.service.ts
- src/app/components/top/reglas/visualizacionReglas.component.ts
- src/app/components/top/reglas/visualizacionReglas.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/services/top/reglas.service.ts
https://proyectos.andes.gob.ar/browse/RUP-348
1.  Agregar filtro busqueda en componente prestacionEjecucion (lineas 13-20)
2.  Filtrar dinamicamente  la prestaciones destinos que coincidan parcial o total con en el campo anterior.  
NOTA: Existe el doble scroll (el del plex-help y el plex-list). Se dejará para otra tarea.
NOTA: Por si se desea realizar consultas en la BD para chequear, se deja un ejemplito de aggregate:
db.getCollection('reglas').aggregate([
{
$match: {
$and: [
{"origen.organizacion.nombre": /SUBSECRETARIA DE SALUD/i},
{"origen.prestaciones.prestacion.term": /consulta de medicina general/i}
],
$or: [
{"destino.organizacion.nombre": /cast/i},
{"destino.prestacion.term": /cast/i}
]
}
},
{
$project: {
"prestacion": "$destino.prestacion.term",
"_id": 0
}
}
])
> CIT - Filtro para derivaciones

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/RUP-363
1.  Se modificó '**../solicitudes-component.ts**' y '**solicitudes.html**' para que envíe fechaActualizacion al get de la api.
2.  Y así obtener las solicitudes p/fecha de actualización.
3.  Mismo campo fechas desde/hasta para entradas/salidas, p/fecha de solicitud o fecha actualización.
> RUP - Filtro por actualizacion de solicitudes

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-575
1.  Al rechazar una indicación se despliega un **select** con los **Motivos de Rechazo**.
2.  Si el motivo es '**otro**', se pide descripción del **Motivo** (text). 
3.  Se agregan motivos de rechazo en la colección "**Constantes**" con el source "**plan-indicaciones:rechazo**".
4.  Se modificó esquema '**PlanIndicacionesEstadoSchema**' atributo verificacion.estado.**key**: String,
{
"_id" : ObjectId("6537aed551f2354c011e5bad"),
"key" : "errorDosificacion",
"nombre" : "Error de dosificación",
"source" : "plan-indicaciones:rechazo",
"type" : "text"
},
{
"_id" : ObjectId("6537af3851f2354c011e5bb0"),
"key" : "superaLimite",
"nombre" : "Supera duración límite (necesita validación)",
"source" : "plan-indicaciones:rechazo",
"type" : "text"
},
{
"_id" …
> IN - Plan de indicaciones: motivo de rechazo

- src/app/modules/rup/components/huds/vistaCDA.component.ts
- src/app/modules/rup/components/huds/vistaCDA.html
- src/app/modules/rup/services/CDA.service.ts
https://proyectos.andes.gob.ar/browse/HUDS-97
1.  Se agrega un boton de descargar PDF para aquellos CDAs que no tienen un archivo adjunto.
> HUDS - Exportacion de HUDS

- package.json
Nuevo comando para correr app donde se amplía el tamaño de memoria asignado a node por defecto
1. 
2. 
3.
> chore(node): amplia memoria al correr la app

- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
- src/app/apps/gestor-usuarios/interfaces/IUsuario.ts
- src/app/apps/gestor-usuarios/views/usuarios-list.view.html
User
https://proyectos.andes.gob.ar/browse/GDU-62
1. Agrega ventana de modificación de email con plex-help
2. Verifica que el usuario a modificar sea profesional temporal
3. Verifica permisos de usuario para poder editar email en profesional
4. Agrega slider con opción de reactivación de contraseña al guardar
Para testear el caso, el usuario no debe contener el campo "lastLogin" y debe existir el permiso para usuarios "usuarios:cuenta". El usuario también debe estar cargado como profesional.
> GDU - Modificar email en usuario temporal

- src/app/modules/rup/services/elementosRUP.service.ts
https://proyectos.andes.gob.ar/browse/RUP-360
1. Se cambió ruta en elementosRUP.service.ts de /modules/rup/elementosRUP a /modules/rup/elementos-rup
2. 
3.
> RUP - Unificar rutas Elementos RUP

- src/app/components/top/reglas/reglas.component.html
- src/app/components/top/reglas/reglas.component.ts
- src/app/components/top/reglas/reglas.scss
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/solicitudes/solicitudes.scss
- src/app/components/top/top.module.ts
- src/app/components/top/top.routing.ts
https://proyectos.andes.gob.ar/browse/TOP-158
1.  Aplica mockuos en pantallas de creación de reglas de entrada.
> TOP - Implementa mockups para reglas de entrada

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.scss
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.html
- src/app/interfaces/turnos/IAgenda.ts
- src/app/interfaces/turnos/ITurno.ts
https://proyectos.andes.gob.ar/browse/CIT-210
Se implementó nuevo mockup de **reasignación de turnos** para las agendas suspendidas c/turnos dados.
> CIT - Implementar mockups de reasignación de turnos

- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
Se solicita que las notas de los turnos pertenecientes en agendas suspendidas se visualicen una vez que los turnos son reasignados
1. 
2. 
3.
> fix(cit): visualizacion de nota en turno reasignado

- src/app/core/mpi/components/datos-contacto.component.ts
- src/app/core/mpi/components/datos-contacto.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/paciente.html
- src/app/core/mpi/interfaces/IDireccion.ts
https://proyectos.andes.gob.ar/browse/MPI-424
1. Se agrega un nuevo check que permite habilitar la opción de que el paciente vive en situación de calle, entonces no solo se inhabilita el poder georeferenciar una dirección sino que dicho atributo no se cargará en la base de dato. 
NOTA: en caso de probar la funcionalidad consultar de manera personal para obtener información adicional.
> MPI - Pacientes sin domicilio real

- src/app/modules/rup/services/CDA.service.ts
Corregir la ruta de acceso al pdf que se genera al visualizar un cda de histórico clínico.
> fix(HUDS): Corrige ruta al descargar pdf

- src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
https://proyectos.andes.gob.ar/browse/CIT-259
1. Guarda el elemento completo del financiador para un sobreturno
2. Los datos serán guardados en la coleccion de pacientes en la tarea https://github.com/andes/api/pull/1807
> CIT - FIX: modificar esquema de obra social al dar sobreturno

- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.scss
- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/core/mpi/components/documentos-paciente.component.ts
- src/app/core/mpi/components/documentos-paciente.html
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.html
- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
- src/app/modules/rup/components/elementos/adjuntarDocumento.html
https://proyectos.andes.gob.ar/browse/UIUX-366
1. Se modifica los iconos de las extensiones en los módulos RUP, TOP y MPI.
2. Se agrega modal solicitando confirmación al momento de eliminar.
> UIUX - Implementar extensión de archivos

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
- src/app/modules/rup/components/huds/vista-accesos-huds.html
https://proyectos.andes.gob.ar/browse/PRIV-70
1. Se agrega campo observación al modal de selección de motivo
2. Se agrega plex-help de la observación en listado de accesos HUDS
> PRIV - Agregar campo observación en motivos

- src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
https://proyectos.andes.gob.ar/browse/HUDS-77
En el modal de motivos de acceso a la HUDS se agrega
1. Imagen de la firma del profesional , si ésta existiera.
2. Nombre, apellido y número de documento del profesional.
NOTA: Para agregar una imagen de firma desde matriculaciones:
en el listado de profesionales > ver profesional > firmas > subir archivo
> HUDS - Declaración jurada de acceso a la HUDS

- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
Soluciona la descarga de los adjuntos desde el modulo rup
> fix(RUP): Visualizar botón de desacarga de adjuntos

- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.scss
Agregar un puntero a los iconos de archivos adjuntos
> fix(RUP): Agregar un cursor  tipo puntero sobre los adjuntos

- .github/workflows/has_conflicts.yml
cambia el  label para marcar conflictos
> fix(LIB): cambia el  label para marcar conflictos

- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
Se agregan controles en los motivos de acceso a la HUDS desde el modal que se usa desde internación y mpi, para contemplar los casos de detalle en el motivo.
1. 
2. 
3.
> HUDS: fix que agrega detalle y motivo en modal de acceso a la huds

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Cambiar el formato del motivo de acceso a la HUDS, de array a string. Esto cuando se continua el registro de una prestación o se accede a ver un resumen
> fix(RUP): Cambia el formato del mensaje del motivo de acceso a la HUDS

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
https://proyectos.andes.gob.ar/browse/CIT-280
1. Se agregaron condiciones para que una agenda del pasado pase a auditada en vez de publicada. También se modificaron los mensajes del modal al momento de realizar dicha acción.
> CIT - Publicar agendas en el pasado

- src/app/components/turnos/gestor-agendas/operaciones-turnos/agregar-nota-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/agregar-nota-turno.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.html
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
- src/app/components/turnos/punto-inicio/turnos-paciente.html
- src/app/modules/rup/components/huds/vistaHistorialTurnos.html
https://proyectos.andes.gob.ar/browse/CIT-254
2.  Se agrega un botón de volver al momento de querer liberar un turno ya que el mismo no existía. 
3. Se corrige algunos fix de los html como funciones y variables que no se encontraban declarados.
> CIT - Error en auditoria de agendas en turnos disponibles

- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.scss
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-154
1. Se visualiza las descripciones de las queries.
NOTA: en el HTML de bi-queires solamente se modifico la línea 23 agregando el span y la linea 9 agregando class="bi-select"
> BI - Detalle en variables query

- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-274
1.  En la creación de la agenda se verifica que el/los profesionales no estén en agendas de otros efectores en el mismo dia y hora.
2.  En la modificación de agenda, se controla que el/los profesionales, estén habilitados para la prestación seleccionada, ademas que no esten en agendas de otros efectores.
> CIT - Edición de profesional en agenda

- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
1. Modifica tutulo en sidebar de nueva prestacion fuera de agenda y agenda autocitado
2. Agrega boton 'volver' desde la pantalla de top 'mis solicitudes asignadas'
> RUP - Punto de inicio (Edit)

- src/app/components/top/solicitudes/solicitudes.component.ts
https://proyectos.andes.gob.ar/browse/TOP-183
1.  Se modifican chequeos para que al presionar "continuar registro" en una solicitud quede guardado el acceso a la huds.
> TOP - Fix en ContinuarRegistro de TOP

- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
https://proyectos.andes.gob.ar/browse/CIT-288
1.  Repara el chequeo de teléfono en paciente para agenda con turnos por reasignar
> CIT: FIX chequeo de telefono sin definir

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
> HUDS (Fix) - Suprime filtro por efector para infernaciones

- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
https://proyectos.andes.gob.ar/browse/CIT-272
1. Se agregaron a los parametros de busqueda de las prestaciones aquellas que tienen los estados "asignada" y "anulada"
2. Se cambió el color del badge de ANULADA por rojo.
NOTA: Ver si es necesario tener que cambiar el color del badge ASIGNADA ya que la misma se encuentra de color azul como los otros estados PENDIENTE y AUDITADA
> CIT - Ventanilla-Solicitudes: visualizar estado asignada

- src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
https://proyectos.andes.gob.ar/browse/CIT-273
1. Se agregó dentro del array de pacienteFields el campo edad que faltaba para poder visualizarse la edad del paciente seleccionado en MPI.
> CIT - Visualizar edad del paciente

- src/app/directives/profesionales-select.directive.ts
Reportan por glpi https://glpi.andes.gob.ar/front/ticket.form.php?id=4753 que luego de clonar una agenda previo filtrado por profesional, al volver al gestor el filtro queda guardado (esto es correcto) pero al borrarlo para volver a filtrar por otro profesional distinto no trae ningun resultado. Internamente es el plex select que devuelve error.
1. Al vaciar el filtro de profesional la directiva retorna un array vacío para evitar el error.
> CIT (Fix) - Filtro por profesional luego de clonar agenda

- src/app/modules/rup/components/core/rup.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-116
1. Se modifica la condición con timeout que pisa el estado del campo privacy en los registros de las prestaciones
> HUDS - Fix reemplazo de privacy en elemento rup

- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
- src/app/services/turnos/sms.service.ts
[https://proyectos.andes.gob.ar/browse/MISC-354](https://proyectos.andes.gob.ar/browse/MISC-354)
1. Cambia la notificación al cancelar turno
2. Cambia la notificación al cancelar la agenda completa
PR APi Y Microservicio
API: [https://github.com/andes/api/pull/1931](https://github.com/andes/api/pull/1931)
MS: [https://github.com/andes/andesMicroservices/pull/223](https://github.com/andes/andesMicroservices/pull/223)
> fix(Notificacion): Agrega envío de notificación al cancelar turno

- src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
Luego de la ultima actualización de HUDS no se visualiza el boton de descarga para las prestaciones de internación. Tampoco la unidad organizativa.
GLPI asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=4886
1. Agrega botón de descarga y UO en las prestaciónes de internación.
> HUDS (Fix) - Agrega boton de descarga y UO en prestaciones de internación

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-432
1. Se agrega control para que no pise el domicilio fisico (real) con el legal que viene de renaper.
> MPI - Domicilio legal pisa domicilio real (direccion)

- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-411
1. Se agrega los campos en la vista para que se visualice el espacion físico.
> RUP - Espacio Físico en agendas

- src/app/components/profesional/inscripcion-profesionales/inscripcion-profesionales.component.ts
https://proyectos.andes.gob.ar/browse/MISC-346
> fix(MAT): Agrega mensaje de usuario one login

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
1.  Corrige busqueda de modal iniciando fuera de agenda
> CITAS (Fix) - Corrige busqueda de modal iniciando fuera de agenda

- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
Corregir modal de motivos de accesos a la Huds, no se estaban mostrando para los usuarios que no son profesionales
> fix(HUDS): Soluciona acceso a huds para No profesionales

- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
https://proyectos.andes.gob.ar/browse/IN-608
1. Se muestra cama correcta al existir dos internaciones en un mismo día.
2. Se muestra nombre autopercibido (alias) en caso que corresponda si el paciente cambia del mismo.
> IN - Censo diario error datos de cama y paciente de internción duplicada

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
https://proyectos.andes.gob.ar/browse/RUP-407
1. Se agrega variable para que exista el foco en pestaña "Registros de la consulta" cuando se selecciona un concepto
2. En el html prestacionEjecucion se reduce condición.
> RUP - Foco en registros de consulta

- src/app/modules/rup/components/huds/detalleRegistro.html
https://proyectos.andes.gob.ar/browse/HUDS-119
1. Quita el icono de  Registros para trastornos y hallazgos
2. Cambio de título y aumento de tamaño del texto en evoluciones
> HUDS- Modifica vista en evolucion de trastornos

- src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
https://proyectos.andes.gob.ar/browse/CIT-310
1. Recupera los efectores para los cuales el usuario tiene permisos
2. Agrega filtro de efector, requerido y precargado con el efector actual
3. Envía datos del filtro para descarga de lista de espera (demandas insatisfechas)
> CIT - Implementa filtro para efector en demanda insatisfecha

- src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
- src/app/components/turnos/dar-turnos/calendario-dia.class.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/interfaces/turnos/IListaEspera.ts
https://proyectos.andes.gob.ar/browse/CIT-293
https://proyectos.andes.gob.ar/browse/CIT-276
1. Se implementa la funcionalidad de cerrar una demanda dandole un turno o seleccionando la opcion de finalizada con el motivo correspondiente.
> CIT - cerrar demanda insatisfecha

- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.html
- src/app/interfaces/turnos/ITurno.ts
https://proyectos.andes.gob.ar/browse/CIT-304
1.  Al momento de seleccionar el turno nuevo habilita [slide] Enviar Notificación (Guarda en turno campo notificar).
2.  Esquema e interfaz turno se agrega campo notificar: boolean.
3.  Nueva contante 'telefonoUnico' para local, demo y test, esto evita enviar notificación p/error.
{
"key" : "telefonoUnico",
"nombre" : "2996318193", (este es mi nro, puede ser otro)
"source" : "notificaciones:sendMessage",
"type" : "text"
}
> CIT - Reasignación turno: notificar al paciente

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
https://proyectos.andes.gob.ar/browse/MPI-436
1. Verifica si el paciente tiene vinculados antes de buscar sus internaciones
> IN (Fix) - HUDS de pacientes no incluye prestaciones de pacientes unificados

- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
- src/app/directives/profesionales-select.directive.ts
https://proyectos.andes.gob.ar/browse/CIT-309
1. Elimina el uso de la variable de clase 'agenda' que causaba un error por consola
2. Elimina funcion para filtrar profesionales habilitados (ya lo hace la directiva _tmProfesionales_)
3. Modifica la directiva _tmProfesionales_ agregando el caso (erroneo) de que quede cargado un profesional como objeto en lugar de un array
> CITAS (Fix) - Edición de profesionales de una agenda

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
> HUDS (Fix) - revierte cambios

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-332
1.  Se corrigió dar-tuenos.component, linea 1095 'this.enviarSMS(datosTurno.paciente)'
> CIT - (FIX) Error en EnviarSms al dar turno.

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
p/defecto al Crear
https://proyectos.andes.gob.ar/browse/CIT-333
1. Plex-bool Enviar Sms **activado** p/defecto.
2. Se cambia texto por **Enviar Notificación**.
> CIT - Agendas: Enviar SMS (Notificación) activado

- src/app/components/turnos/dashboard/demandaInsatisfecha.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-328
1. Se carga todo el formulario de demanda insatisfecha en un plex-help
2. Se modifica un poco el componente de demandaInsatisfecha para amoldarlo al plex-help
> CIT - Demanda Insatisfecha

- src/app/modules/perinatal/components/listado-perinatal.component.html
- src/app/modules/perinatal/services/carnet-perinatal.service.ts
https://proyectos.andes.gob.ar/browse/PER-82
1. Corrige filtros de busqueda _fechaDesde_ y _fechaHasta_
2. Agrega un _sort_ para que inicialmente ordene el listado segun la fecha del primer control
> PERINATAL (Fix) - Filtros de listado perinatal (De mariela)

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno.component.ts
https://proyectos.andes.gob.ar/browse/CIT-320
1. Se filtran las agendas con turnos suspendidos para ser mostrados como opción al momento de reasignar, omitiendo los no suspendidos.
2. Se actualiza la agenda seleccionada luego de suspender un turno para que, sin salir de esa selección, pueda figurar el nuevo turno como opción de reasignación.
> CIT - Implementa filtros de reasignación de turnos

- src/app/modules/rup/components/huds/detalleRegistro.html
- src/app/modules/rup/components/huds/detalleRegistro.ts
https://proyectos.andes.gob.ar/browse/HUDS-122
1. Se agrega el service correspondiente y se elimina el atributo prestación ya que no es necesario.
> HUDS - Error al visualizar registro con relaciones

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.scss
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
- src/app/modules/rup/services/huds.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/HUDS-113
https://proyectos.andes.gob.ar/browse/HUDS-120
1. Implementa paginación de prestaciones en internación para visualizar sin tanto tiempo de carga
2. Se modifican vistas de registros para cargar selectivamente acorde al botón de despliegue
3. Se aplican diseño de mockup para la visualización en el listado de prestaciones de la internación
4. Se repara error de visualización de datos en prestaciones fuera de una internación
> HUDS - Implementa mejoras en buscador y cambios en UI

- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
https://proyectos.andes.gob.ar/browse/EP-233
1. Agrega control de dependiencia con select estático
2. 
3.
> fix(EPI): Agrega cambios en campos con dependencias

- src/app/components/turnos/dar-turnos/calendario-dia.class.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://glpi.andes.gob.ar/front/ticket.form.php?id=5038
1. El componente de calentario-dia ahora toma como agendas exclusivas de gestion aquellas que todos sus bloques son exclusivos de gestion. De esta manera permite que los bloques que no son de gestion se muestren en el calendario.
> CITAS (Fix) - Visibilizacion de agendas con bloques de acceso directo y gestion simultánemante

- projects/shared/src/lib/pipes/capitalizeFirst.pipe.ts
- projects/shared/src/lib/shared.module.ts
- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/datos-basicos.html
- src/app/modules/mpi/components/paciente-detalle.html
- src/app/modules/mpi/components/paciente-panel.html
https://proyectos.andes.gob.ar/browse/MPI-434
1. Se agregan registros de género a colección "constantes" en demo
2. En MPI se obliga a seleccionar un genero al seleccionar sexo='otro'
> MPI -  Actualización select género

- src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.html
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternacion.scss
- src/app/modules/rup/components/huds/internacion/detalleRegistroInternación.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-126
1. Se evita al hacer click, en el elemento expandible del detalle de registros, el cierre del accordion.
> HUDS - Repara error al hacer click en detalle de registro

- src/app/components/carpeta-paciente/carpeta-paciente.component.ts
- src/app/components/carpeta-paciente/carpeta-paciente.html
- src/app/components/turnos/gestor-agendas/pipes/botonesTurnos.pipe.ts
- src/app/components/turnos/gestor-agendas/turnos.html
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
https://proyectos.andes.gob.ar/browse/CIT-339
1. Agrega botonera con opciones de editar n° de carpeta y liberar para el caso de los sobreturnos
2. Modifica algunos elementos para mejorar la apariencia de plex-help
3. Agrega patron de validez al n° de carpeta y verificación para habilitar el boton de guardado.
> CIT - Gestor de agendas - Número de carpeta

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
- src/app/modules/rup/components/ejecucion/prestacionValidacion.scss
https://proyectos.andes.gob.ar/browse/RUP-417
1. Al validar una prestación en RUP, si la misma incluye una o mas solicitudes, se debe mostrar un modal con la información del tipo de prestación y la organización de destino de la solicitud.
⚠️ Queda pendiente la revisión de los datos mostrados en pantalla: distribución, contenido y diseño.
> RUP - Implementa modal con información de envío de solicitudes

- src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
- src/app/components/turnos/dashboard/demandaInsatisfecha.ts
- src/app/interfaces/turnos/IListaEspera.ts
- src/app/services/turnos/listaEspera.service.ts
https://proyectos.andes.gob.ar/browse/CIT-323
https://proyectos.andes.gob.ar/browse/CIT-327
https://proyectos.andes.gob.ar/browse/CIT-326
1. Modifica pedido de demandas para agregar skip, limit e id de paciente en request
2. Crea scroll infinito en listado de demandas pidiendo datos sectorizados con skip y limit
3. Agrega datos de paciente y cantidad de demandas en listado principal
> CIT - Modifica recuperacion de pacientes en lista de espera

- projects/portal/src/app/services/laboratorio.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.scss
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/huds-lib.module.ts
- src/app/modules/rup/services/huds.service.ts
https://proyectos.andes.gob.ar/browse/LAB-10
1. Crea vista para laboratorios que poseen numero de protocolo, que se obtienen de SIL
2. Modifica información en sidebar para los laboratorios de SIL
3. Crea acceso para discriminar entre laboratorios de SIL y CDA's
> LAB - Implementa vista de laboratorios

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
En punto de inicio cuando hay un sobreturno liberado ocurre un error intentando relacionar los sobreturnos con las prestaciones https://glpi.andes.gob.ar/front/ticket.form.php?id=5102
1. Se filtran sobreturnos liberados al momento de cargar las prestaciones
> RUP (Fix) - Visualización de gendas mias/todas

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
Se corrige error al dar un turno en demanda insatisfecha
1. 
2. 
3.
> CITAS: Se corrige error al dar turno en demanda insatisfecha

- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
https://proyectos.andes.gob.ar/browse/GDU-67
1. Al ver un usuario en GDU, ahora se permite visualizar la opción de modificación de email a partir de la quita de la restricción para usuarios temporales.
> GDU - Quita restricción para usuario temporal en edición de email

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
https://proyectos.andes.gob.ar/browse/CIT-338
1. En agenda Dinámica, tanto en módulo Citas y RUP, despues de hace un primer click se bloquea el mismo botón, este es para evitar duplicar turnos.
2. Nota: Hacer pruebas con internet lento.
> CIT - Bloquear botón de dar turno

- src/app/components/carpeta-paciente/carpeta-paciente.component.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-343
1. Corrige uso deprecado de subscribe en patch de paciente
2. Actualiza turno del paciente agregando la nueva _carpetaEfectores_ luego de que el usuario la edite desde el sidebar
> CITAS (Fix) - Gestor de agendas: Nuevo número de carpeta

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/components/farmacia/farmacia-create-update.component.html
- src/app/components/farmacia/farmacia-create-update.component.ts
- src/app/components/farmacia/farmacia.component.html
- src/app/components/farmacia/farmacia.component.ts
- src/app/components/farmacia/farmacia.scss
- src/app/interfaces/IFarmacia.ts
- src/app/services/farmacia.service.ts
https://proyectos.andes.gob.ar/browse/TM-34
https://proyectos.andes.gob.ar/browse/TM-38  
1. Se desarrolla el nuevo modulo de farmacias que permite cargar una nueva farmacia, editar una cargada y eliminar la que se desee (esta última por el momento solo la inhabilita desde la base de datos)
[modulo_tm.txt](https://github.com/user-attachments/files/16732467/modulo_tm.txt)
Remplazar o agregar el siguiente JSON en la coleccion "módulos" para poder ver el nuevo modulo de farmacias. 
En caso contrario acceder por ruta http://localhost:4200/tm/farmacia con los permisos correspondientes.
> TM - Nuevo módulo de farmacias

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://glpi.andes.gob.ar/front/ticket.form.php?id=2745
1. Corrige seleccion de prestación al momento de validar (quedaba apuntando a la anterior)
2. Corrige error editando internación desde capa estadistica (aun no reportado, no permitía modificar fechas).
> IN (Fix) - Cambiar profesional a cargo (estadistica) y validar

- src/app/apps/rup/mapa-camas/views/resumen-internacion/resumen-internacion.component.ts
https://glpi.andes.gob.ar/front/ticket.form.php?id=4982
1. Corrige fechaFin que al estar en null moment genera un NaN (raro porque normalmente equivaliía a _now_)
> IN (Fix) - Exploración visual de internación en curso

- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
https://proyectos.andes.gob.ar/browse/GDU-74
1. En Gestión de Usuarios, se activa la organización al momento de "Agregar Organización", independientemente si después se guarda o se agregan permisos.
> GDU - Nueva organización en usuario pausada

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.scss
https://proyectos.andes.gob.ar/browse/HUDS-128
1. Organiza los laboratorios obtenidos por nombre de grupo y titulo.
> HUDS - Modificación en vista de laboratorios

- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/HUDS-104
1.  Se agrega botón de descarga con su función correspondiente para descargar los PDF de cada laboratorio seleccionado.
> HUDS - Implementar descarga en PDF de laboratorios

- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.scss
Corrige la visualización de laboratorio para incluir resultados no agrupados
> fix(HUDS): Soluciona agrupamiento de determinaciones para laboratorios

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
[EP-237](https://proyectos.andes.gob.ar/browse/EP-237)
[EP-239](https://proyectos.andes.gob.ar/browse/EP-239)
[EP-241](https://proyectos.andes.gob.ar/browse/EP-241)
1. No se muestran las fichas deshabilitadas
2. Mostrar en el modal de guardado con éxito el numero de identificación.
3. Agregar filtro de busqueda de ficha el identificador de laboratorio
4. Agregar columna para el identificador de laboratorio en el buscador de fichas 
[PR-1982](https://github.com/andes/api/pull/1982)
> EP - No mostrar fichas deshabilitadas

- angular.json
> Oculta sourceMap en producción

- src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
- src/app/components/turnos/dar-turnos/dar-sobreturno.html
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
https://proyectos.andes.gob.ar/browse/CIT-348
1. Se saca modal al momento de guardar un subre turno desde el gestor de agendas, agregando un toast con el mensaje correspondiente y cerrando el sidebar.
2. Se inhabilita el botón guardar una vez seleccionado para evitar duplicar turnos con el mismo horario.
> CIT - Guardado incorrecto de sobreturnos

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/components/datos-basicos.scss
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/modules/auditoria/component/auditoria.component.ts
- src/app/modules/auditoria/component/auditoria.html
https://proyectos.andes.gob.ar/browse/MPI-438
1.  Se cambio el label del bool de reportar errores de renaper
2.  Se quito el input de escribir un texto del reporte de error y se agregaron dos nuevos input para agregar el nombre y apellido correcto del paciente.
3. Se agrega un nuevo modal en caso de que el nombre y apellido sea igual al que se registro en MPI.
4. Se agregan nuevas leyendas sobre el reporte de error de Renaper.
> MPI - reporte de errores de renaper

- src/app/core/mpi/components/paciente.component.ts
Agrega control por el registro de bebe que no tiene reporte de error de validación con renaper
> fix(MPI): Agrega control por reporte  de error

- src/app/modules/auditoria/component/auditoria-listado.html
- src/app/modules/auditoria/component/reporte-errores.component.ts
Se controla el parametro  de errores en listado de pacientes  de auditoria
> fix(MPI): Controla reporte de error en auditoria  mpi

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/core/rup.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.component.ts
- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
- src/app/modules/rup/services/ejecucion.service.ts
- src/app/modules/rup/services/elementosRUP.service.ts
1. Implementa opción en las solicitudes para seleccionar un concepto (diagnóstico) y vincular.
2. Obtiene de la colección "constantes" la query de SNOMED para recuperar los posibles conceptos vinculados.
3. Filtra los conceptos SNOMED con los agregados a la prestación para el selector de vínculos.
4. Guarda "conceptoVinculado" a la prestación de RUP.
Agregar el siguiente objeto al a colección "constantes":
```
{
"key": "1",
"nombre": "conceptos-asociadosm",
"source": "solicitud:conceptosAsociados",
"type": "text",
"query": ""
}
```
> RUP - Vinculación de diagnósticos con solicitudes

- src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
https://proyectos.andes.gob.ar/browse/CIT-318
1. Se agrega información del paciente: edad, dirección, datos de contacto, estado (Validado o Temporal) y financiador.
2. Se modifica información en el listado de demandas: fecha, motivo y organización.
3. Se reemplaza el uso de plex-list por plex-table.
4. Se crea scroll infinito en listado de demandas.
> CIT - Modifica información de demandas insatisfechas

- src/app/components/turnos/gestor-agendas/operaciones-turnos/liberar-turno.component.ts
- src/app/components/turnos/punto-inicio/turnos-paciente.html
https://proyectos.andes.gob.ar/browse/CIT-346
1. Se agrega boton de eliminar sobreturno desde ventanilla citas
> CIT - Sobreturno se guarda sin paciente cuando se elimina

- src/app/modules/rup/components/elementos/tensionDiastolica.html
> RUP: cambia valor minimo de ta distólica

- src/app/modules/rup/components/elementos/frecuenciaCardiaca.html
- src/app/modules/rup/components/elementos/frecuenciaRespiratoria.html
- src/app/modules/rup/components/elementos/saturacionOxigeno.html
- src/app/modules/rup/components/elementos/tensionDiastolica.html
- src/app/modules/rup/components/elementos/tensionSistolica.html
Cambia máximos y requeridos en molécula de signos vitales y los componentes que utiliza
1. 
2. 
3.
> fix(RUP): cambia máximos y requeridos en CSV

- src/app/components/inicio/inicio.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/epidemiologia.routing.ts
- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.html
- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
https://proyectos.andes.gob.ar/browse/RUP-447
1. Se agrega control en el routing de ficha Epidemiologica  y en el botón ficha de RUP.
> RUP - Permisos para crear ficha epidemiologica

- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.html
Se corrige la visualización  de las fichas en la huds chequeando si se trata de covid o  no,  para levantar el  componente correcto.
> fix(HUDS): Se  corrige la visualización de fichas  desde la HUDS

- src/app/modules/rup/components/huds/detalleProcedimiento.html
- src/app/modules/rup/components/huds/detalleProcedimiento.ts
https://proyectos.andes.gob.ar/browse/HUDS-133
1. Se crea un filtro para obtener el registro coincidente entre el de la prestación y el obtenido por param, y pasarlo al elemento RUP.
> HUDS - Corrige muestra de registros RUP en procedimientos

- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.html
1.  Se agranda el tamaño del checkbox y se cambia el color del mismo al momento de querer notificar al paciente cuando se suspende el turno o los turnos correspondientes.
> CIT - cambiar tipo de visualización para notificar

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
https://proyectos.andes.gob.ar/browse/RUP-438
1. Se agregan condiciones para que los trastornos en estado inactivo o resuelto no muestren los checks de ¿ Es primera vez?
> RUP - Quitar primera vez de trastornos inactivos o resueltos

- src/app/components/top/pipes/botones.pipe.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-189
1. Se habilita el botón "anular" en la bandeja de entrada y el botón "cancelar" en la bandeja de salida.
2. Además se limpia el campo "motivo" en el anular cuando se confirma, ya que antes quedaba el texto.
> TOP - Anular solicitudes en AUDITORIA

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
https://proyectos.andes.gob.ar/browse/CIT-291
1. En una agenda B que se desee asignar un profesional que estaria en una agenda A, no deberia permitirlo.
2. Se deshabilita el botón de guardar instantáneamente cuando se detecta el anterior caso.
3. Tener presente trabajar con conexión lenta.
> CIT -  Solapamiento de profesional editando agenda

- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/components/ejecucion/vistaHuds.scss
https://proyectos.andes.gob.ar/browse/HUDS-141
1. Se fija tamaño de contenedor
> HUDS (Fix) - Scroll infinito en listado de accesos

- src/app/modules/rup/services/ejecucion.service.ts
https://proyectos.andes.gob.ar/browse/RUP-442
⚠️ La tarea pide modificar la UI en el modal, pero para lograrlo se requieren varios cambios que no justifican el resultado. En su lugar se optó por desarrollar como nueva tarea, la incorporación de estos cambios en PLEX y facilitar el proceso para todos los modal en APP. 
https://proyectos.andes.gob.ar/browse/PLEX-359
1. Para el modal de alerta de evolución se modifica el contenido, mostrando el concepto a evolucionar y se modifican los textos en botones.
> RUP - Modifica modal de evolución de trastorno

- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Información de ingreso incompleta
1. Corrige chequeo de origen externo (del ingreso)
2. Corrige manejo del valor del bool que muestra el campo para seleccionar la organización origen
3. Agrega label con detalle de organización de origen en el informe de ingreso
GLPI asociado https://glpi.andes.gob.ar/front/ticket.form.php?id=5152
> IN (Fix) - Información de ingreso incompleta

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/RUP-454
1. Se agrega condición para habilitar el tab de "Buscador" si el usuario no tiene permisos a la HUDS.
2. Se elimina tab de relaciones.
> RUP - Habilitar tab del buscador y otras cosas

- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-365
1. Se agrega badge de "reasignado" en turnos de agendas publicadas
Ejemplo de como queda badge en pantalla 720p
> CIT - Mostrar origen del turno REASIGNADO en la agenda

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-132
1. Ordenamiento por (ultima) fecha en prestaciones fuera de la internación
2. fix de undefined en validación de algunas prestaciones
GLPI asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=5163
> HUDS - Registros faltantes en HUDS en internación

- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
https://proyectos.andes.gob.ar/browse/IN-622
1. Fix cuando la internación es a las 00:00 (se restaba 1 min y bugeaba la horaMin)
> IN - Nuevo registro: Error en control de horas

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Despues de actualizar produccion alguinas prestaciones no podian ser validadas
1. 
2. 
3.
> fix(RUP): validar prestacion

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.html
https://proyectos.andes.gob.ar/browse/CIT-367
1. Refactor general del control de solapamiento de profesionales y espacio fisico en edicion de agendas
> CIT (Fix) - Error en controles de profesional y espacio fisico

- src/app/components/turnos/dar-turnos/dar-sobreturno.component.ts
- src/app/components/turnos/dar-turnos/dar-sobreturno.html
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-363
1. Se crea un modal para dar aviso al gestor del/los TURNOS Y SOBRETURNOS existentes con el mismo tipo de prestación
2. Se realiza un busqueda de "turnos futuros" al momento que se selecciona el horario de turno.
3. Luego al momento de confirma el turno, se aplica el control para disparar el modal si fuera necesario.
> CIT - Control por turnos repetidos en ventanilla

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
https://proyectos.andes.gob.ar/browse/CIT-303
1.  Se agregaron condiciones a la hora de clonar agendas para que esta misma acción no se pueda realizar en caso de que las prestaciones no presenten ámbito ambulatorio. 
NOTA: Se podría agregar un test donde se intente clonar una agenda que tenga una prestación con ambito distinto al de "ambulatorio" mostrando el mensaje correspondiente.
> CIT - clonar agendas si los conceptos turneables tienen ámbito ambulatorio

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/RUP-455
1.  Se agrega control en evento que deseleccionaba el tab activo
> RUP - error en select dinámico

- projects/portal/src/app/services/receta.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/hudsBusqueda.scss
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss
- src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.html
- src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.scss
- src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/components/ejecucion/vistaHuds.scss
- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
- src/app/modules/rup/components/huds/vistaReceta.html
- src/app/modules/rup/components/huds/vistaReceta.scss
- src/app/modules/rup/components/huds/vistaReceta.ts
- src/app/modules/rup/components/variables.scss
- src/app/modules/rup/huds-lib.module.ts
- src/app/modules/rup/services/huds.service.ts
https://proyectos.andes.gob.ar/browse/HUDS-134
https://proyectos.andes.gob.ar/browse/HUDS-142
https://proyectos.andes.gob.ar/browse/HUDS-138
1. Se implementó la funcionalidad de **visualización de prescripciones** en la HUDS de los pacientes, permitiendo acceder a información relevante sobre las recetas médicas y su vínculo con la dispensa. 
2. Se implementa la posibilidad de suspender recetas.
3. Se implementa la vista en detalle de las recetas médicas.  
4. Se implementan filtros para **buscar por término** o mostrar recetas **vigentes**
5. Se agrega detalle de dispensa, motivo de suspensión y visualización de recetas suspendidas con estilos en historial.
**Consideraciones:**  
- En una segunda etapa se evaluará la implementación de la **renovación**.
- La suspensión de un medicamento …
> HUDS - Visualización de Recetas en la HUDS

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
- src/app/modules/rup/components/elementos/recetaMedica.scss
1. Modifica la interacción del ingreso manual de cantidad de medicamento en prescripcion de medicamento
> RUP - Edit manual cantidad de medicamento

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
https://proyectos.andes.gob.ar/browse/RUP-456
1. Se realiza la búsqueda de los registros que tengan trastornos dentro de los últtmos 6 meses.
2. A su vez se precargan en el combo de diagnósticos.
3. Tener presente de chequear, trastornos activos.
> RUP - Agregar diagnósticos a la receta

- src/app/apps/rup/mapa-camas/constantes-internacion.ts
- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
https://proyectos.andes.gob.ar/browse/IN-619
1. Al momento de internar un paciente dentro de capa ESTADÍSTICA dentro sidebar en la parte de cobertura social, se agrega una nueva opción de 'Sin Datos'.
2. En caso de seleccionar la primera opción o segunda me permite elegir otra obra social. 
3. si se eligen las opciones 'Ningúna' o 'Sin Datos' dentro de la base de datos se guardan con dichos string según corresponda. En caso de no seleccionar ninguna OS ya que la misma no es obligatoria se guarda null
> IN - Modificar carga de OS en alta de internación capa estadística

- src/app/app.module.ts
- src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
- src/app/components/turnos/dar-turnos/seleccionar-financiador.html
- src/app/components/turnos/dar-turnos/seleccionar-financiador.scss
- src/app/core/mpi/components/obra-social.component.ts
- src/app/core/mpi/components/obra-social.html
- src/app/core/mpi/components/paciente.html
https://proyectos.andes.gob.ar/browse/MPI-399
1. Visualización de Obras Sociales (PUCO): se muestra el listado actual de OS provenientes de PUCO como datos de solo lectura. 
2. Tab para Gestión de Obras Sociales: se agregó un tab en el módulo MPI para la gestión de OS del paciente.
3. Se crea un input para indicar que el selector esta en modo EDITABLE.
4. Selector de Obras Sociales: se implementó un selector que obtiene OS desde la colección obraSocial, excluyendo las registradas en PUCO. 
5. Gestión Manual de OS Declaradas: se permite agregar, modificar y eliminar OS manualmente.
6. Fecha de Actualización: se muestra la fecha de actualizacion para cada OS en el listado.
> MPI - Implementa seleccion editable de obras sociales

- package-lock.json
- package.json
https://proyectos.andes.gob.ar/browse/PLEX-355
Novedades de la versión 8.0.11:
1. PLEX-TEXT - Implementa validación personalizada
4. PLEX-TEXT - Reemplaza editor html en plex-text
5. PLEX-HELP - Implementa mejoras funcionales
6. PLEX-HINT - Implementa mejoras en plex-hint
7. PLEX-HELP - Scroll y maxHeight opcionales en plex-help
8. PLEX-BOOL - Corregir overflow en checkbox
9. PLEX-TEXT - Agrega nuevos iconos en editor html de plex-text
> PLEX - Actualiza a version 8.0.11

- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
https://proyectos.andes.gob.ar/browse/TOP-192
1. Se agrega chequeo para analizar si el usuario tiene alguna solicitud con el tipo de prestación seleccionada.
2. Se quita el toast, ya que era inecesario.
3. En el componente y vista del archivo buscador, la linea 364 y 198 es modificación es por linteo.
> TOP - Corregir mensaje de solicitud en curso que no corresponde

- package-lock.json
- package.json
> PLEX - Actualiza a version 8.0.12

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.component.ts
https://proyectos.andes.gob.ar/browse/RUP-457
1.  Al agregar medicamento que ya tiene cargado el paciente y está vigente y sin dispensa o con dispensa parcial, se muestra un modal e impide carga.
> RUP - Receta: control para evitar duplicar recetas

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.ts
- src/app/modules/rup/components/huds/vistaReceta.html
https://proyectos.andes.gob.ar/browse/HUDS-151
1. Se agregan controles al suspender una receta y el envío de ids nulls
2. Se corrige error de visualización en la dosis diaria
3.
> Receta: control de request al suspender una receta

- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
Al intentar auditar una agenda, en algunas se esta rompiendo el sidebar. Esto sucede en agrndas con turnos que han pasado a disponible y por error queda la asistencia como "asistio".
1. Agrega operador de valor opcional en atributo _tipoPrestacion_ del turno
> CIT (Fix) - Evita que se rompa pantalla de auditoria

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
https://glpi.andes.gob.ar/front/ticket.form.php?id=5411
1. Verifica seteo de fechas de búsqueda de registro según ingreso y egreso del paciente
> IN (Fix) - Fecha desde-hasta en registros desde listado de internacion

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-generic/ficha-epidemiologica-generic.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/EP-246
1.  Se descarga en formato PDF la ficha epidemiológica de un paciente según los datos que se encuentren cargados.
> EP - Generar PDF de ficha epidemiológica

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
https://proyectos.andes.gob.ar/browse/HUDS-152
1. Modifica recuperación de paciente para muestra de laboratorios de SIL2
> HUDS - Modifica visualización de laboratorios del SIL2

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
https://proyectos.andes.gob.ar/browse/RUP-473
1. Se agrega control para que tampoco permita duplicar receta pendiente con las condiciones de https://github.com/andes/app/pull/3155
> RUP - Agregar control de recetas pendientes

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
https://proyectos.andes.gob.ar/browse/RUP-471
1. Modifica el chequeo de profesional valido para suspender recetas basado en codigo de profesion
> RUP - Actualiza datos de profesional en recetas

- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/services/eclqueries.service.ts
https://proyectos.andes.gob.ar/browse/RUP-466
1. Se agrega servicio para consumir la api de ECLQueries
2. Se cambias las queries harcodeadas en el componente de receta por las almacenadas en  la base de datos
> fix(RUP): Agrega consulta  por base a queries para receta

- src/app/components/top/solicitudes/historialSolicitud.html
Se agregan controles en historial por turno cancelado desde mobile, porque se rompe la visualización cuando el turno dado fue cancelado por el paciente desde la app mobile.
https://glpi.andes.gob.ar/front/ticket.form.php?id=5398
1. 
2. 
3.
> TOP: controles en historial por turno

- src/app/apps/mitos/services/snomed.service.ts
- src/app/modules/rup/components/elementos/recetaMedica.component.ts
https://proyectos.andes.gob.ar/browse/RUP-482
1. Cambia la forma de acceder al listado  de cantidades  por medicamento genérico para que funciones con la actualizacion de snomed
2. 
3.
> RUP: cambia la forma de acceder a las cantidades de presentaciones comerciales

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
- src/app/modules/rup/components/elementos/recetaMedica.scss
https://proyectos.andes.gob.ar/browse/RUP-479
1. Verifica contenido de campos de ingreso manual _dosis_ e _intervalo_ y lo conviernte uno en requerido si el otro tiene contenido y viceversa
> Receta - Visualizacion de indicaciones

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
https://proyectos.andes.gob.ar/browse/RUP-477
https://proyectos.andes.gob.ar/browse/RUP-483
1. Agrega campos para cargar serie y numero a los medicamentos
2. Los campos aparecen cuando el medicamento es con triplicado
3. Se chequea que los campos sean obligatorios si es triplicado
4. Se agrega el mensaje "Recuerde que sigue siendo obligatoria la entrega del formulario triplicado en papel" al seleccionar receta por triplicado.
> RUP - Implementa datos para tratamiento prolongado

- src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
https://proyectos.andes.gob.ar/browse/CIT-364
1. Corrección de errores en finalización de demandas, creación de llamadas y vista de listado con filtro por fecha "desde".
⚠️ Los errores de bi-queries y de pacientes con esquema incompleto mencionados no pude replicarlos, no falló en ningun caso la app. Quedo atento por si lo reportan nuevamente.
> fix(CIT) - Corrección de múltiples errores

- src/app/components/top/solicitudes/adjuntarDocumento.scss
- src/app/components/top/solicitudes/detalleSolicitud.component.ts
- src/app/components/top/solicitudes/detalleSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/core/mpi/services/paciente.service.ts
https://proyectos.andes.gob.ar/browse/TOP-195
1.  Se agrega la búsqueda de todas la internaciones del paciente, para obtener el estado.
2. Se muestra badge del estado.
3.  Se coloca modal.
4. Se deshabilita el botón de "Dar Turno" cuando el paciente tiene estado "Difuncion".
> TOP - Buscar internación

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
- src/app/components/turnos/dar-turnos/seleccionar-financiador.html
- src/app/components/turnos/dar-turnos/seleccionar-financiador.scss
https://proyectos.andes.gob.ar/browse/CIT-371
1. Si agrega un campo de texto para incluir el numero de afiliado correspondiente al financiador seleccionado.
2. Se implementa el guardado de multiples financiadores por paciente con origen ANDES
> CIT - Agrega numero de afiliado a selector de prestadores

- src/app/components/top/solicitudes/solicitudes.html
Modificación de la tarea https://github.com/andes/app/pull/3176 para que no impida dar turno para solicitud aunque el paciente figure fallecido (alta por defunción en su ultima internación)
1. Quita condificón _disable_ al botón de dar turno
> permite dar turno aunque el paciente figure fallecido

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
Evita que una prescripción figure en la lista de diagnósticos para receta
1. Filtra por conceptId de receta el listado de conceptos candidatos a diagnóstico
> RUP - Evita prescripción como diagnóstico 

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-127
1. Se agregan nuevos permisos para la HUDS en el gestor de usuarios para que solamente se puedan ver los laboratorios, las vacunas y/o las recetas. 
2. Se agrega un modal de tal forma que si se seleccionan algunas o todas las opciones de HABILITACIÓN PARCIAL DE LA HUDS junto con VER HUDS del paciente le notificara que esa acción no se podrá hacer.
> HUDS - Habilitacion parcial de la HUDS

- src/app/core/mpi/components/relaciones-pacientes.component.ts
- src/app/core/mpi/components/relaciones-pacientes.html
- src/app/core/mpi/components/relaciones-pacientes.scss
- src/app/modules/mpi/interfaces/IPacienteRelacion.inteface.ts
https://proyectos.andes.gob.ar/browse/MPI-443
1.  Se agrega un plex-bool que permite agregar si el paciente relacionado es conviviente.
> MPI - Convivientes

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.component.ts
Actualiza uso del get de receta por cambios en api, donde se asume que si no se aclara el estado de una dispensa, se envían sólo recetas sin dispensar.
1. 
2. 
3.
> Receta: actualiza get de recetas

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
https://proyectos.andes.gob.ar/browse/IN-624
1. Agrega la visualización de labos del SIL2 en el listado del sidebar.
2. Cuando se selecciona el ver, se muestra en el main principal, similar a laboratorio en huds.
3. Aclaración técnica, como no se pudo reutilizar el componente vista-laboratorio, directamente se trabajo en el ts de mapa-camas-capa.
> INT - Ver labos de SIL2 en los registros de internación

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Los protocolos del SIL2 se listan en el sidebar, pero no se visualizaba el detalle del protocolo en un tab cuando se accesedias desde RUP. 
1. Se agrega el tab de tipo laboratorio que faltaba en el componente de ejecucion
2. 
3.
> RUP: Corrige visualizacion del detalle de protocolo del SIL2

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.html
- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.scss
https://proyectos.andes.gob.ar/browse/HUDS-147
https://proyectos.andes.gob.ar/browse/HUDS-148
https://proyectos.andes.gob.ar/browse/HUDS-155
1. Se agrega en el encabezado tanto del protocolo como en el pdf el estado, tipo de muestra y prácticas solicitadas.
2. Componente hudsBusqueda es solamente cambio de linteo.
3. Se deshabilita botón de "Descargar" en caso de no tener resultados.
> HUDS - Se agrega estado, tipo de muestra y prácticas solicitadas

- src/app/core/mpi/components/paciente.component.ts
https://proyectos.andes.gob.ar/browse/MPI-448
1. Se completa el circuito de relaciones agregando el atributo esConviviente en ambos lados según corresponda
> feat(MPI-448): Convivientes - completar circuito en relacion

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/core/mpi/services/paciente.service.ts
https://glpi.andes.gob.ar/front/ticket.form.php?id=5510
1. Se cachea al paciente cuando se lo trae por id desde paciente.service y antes de pedir los labos se verifica que el paciente internado tenga dni. Si no lo tiene se usa su version cacheada (que es mas actual) y **si y solo si** esta tiene dni se ejecuta el servicio de laboratorios.
> IN (Fix) - Visualizacion de registros en pacientes sin dni

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
Corrige error que aparece al intentar seleccionar medicamentos para suspender o renovar. Concretamente es al querer suspenderlo
1. 
2. 
3.
> HUDS: habilita check al suspender medicamento 

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
Soluciona la visualización de recetas cuando se esta ejecutando una prestación en rup
1. Agrega servicio de recetas en la ejecucion de rup
2. 
3.
> fix(RUP): Agrega servicio de recetas en la ejecucion de rup 

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/components/ejecucion/buscador.scss
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/hudsBusqueda.scss
https://proyectos.andes.gob.ar/browse/HUDS-159
1. Se implementa visualizacion similar a la HUDS al clasificar un concepto snomed. 
2. Se agrega el nuevo filtro "elemento de registro" tanto en RUP como en HUDS.
> HUDS - Filtro Elemento de Registro

- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.html
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.component.ts
- projects/shared/src/lib/components/galeria-archivos/galeria-archivos.scss
- projects/shared/src/lib/pipes/fileSize.pipe.ts
- projects/shared/src/lib/shared.module.ts
- src/app/core/mpi/components/documentos-paciente.component.ts
- src/app/core/mpi/components/documentos-paciente.html
- src/app/shared/components/upload-file.component.ts
https://proyectos.andes.gob.ar/browse/MPI-442
1. Control de extensiones
2. Control de tamaño máximo 2mb
3. Control de caracteres especiales
[API PR-2072](https://github.com/andes/api/pull/2072)
GLPI: https://glpi.andes.gob.ar/front/ticket.form.php?id=5501
> MPI-442: Documentos Adjuntos: Agregar control

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
Visualizar diagnósticos registrados hace tiempo pero cuya ultima evolución este dentro de los 6 últimos meses.
1. Cambia el control de fecha de creación del trastorno por el de la última evolución
2. Cambiar el campo duplicado o triplicado por un slide
> Recetas: Mejoras en carga de diagnósticos

- src/app/apps/rup/mapa-camas/constantes-internacion.ts
- src/app/components/turnos/gestor-agendas/turnos.html
https://glpi.andes.gob.ar/front/ticket.form.php?id=5700
Corrige error de ortografía en "Cesária" por "Cesárea", "programadoss" por "programados"
1. 
2. 
3.
> Receta: corrige error ortografia

- src/app/components/turnos/dar-turnos/seleccionar-financiador.component.ts
- src/app/components/turnos/dar-turnos/seleccionar-financiador.html
1. Habilitación del campo de ingreso de numero de afiliado para todo tipo de financiador.
> MPI - Permite numero de afiliado con todos los financiadores

- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/components/datos-contacto.component.ts
- src/app/core/mpi/components/datos-contacto.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/interfaces/IPaciente.ts
- src/app/modules/mpi/components/paciente-detalle.html
[MPI-454](https://proyectos.andes.gob.ar/browse/MPI-454)
1. Generar un audit del usuario que lo cargó
2. Se agrega un label más con un hint que muestre los datos de quien lo cargo y cuando
3. Agregar botón slide que diga "Paciente fallecido".
[MPI-454](https://github.com/andes/api/pull/2084)
> MPI-454: Registrar paciente fallecido

- src/app/modules/rup/components/huds/vistaReceta.html
- src/app/modules/rup/components/huds/vistaReceta.scss
- src/app/modules/rup/components/huds/vistaReceta.ts
https://proyectos.andes.gob.ar/browse/HUDS-161
1. Se agregan todas las dispensa, junto con la organización
2. Se agrega badge de dispiensa duplicado.
> HUDS - Visualizar el listado de dispensas parciales

- projects/portal/src/app/services/receta.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.html
- src/app/modules/rup/components/ejecucion/recetas/suspenderMedicacion.ts
- src/app/modules/rup/components/huds/vistaReceta.ts
https://proyectos.andes.gob.ar/browse/REC-119
1.  Se habilita el checkbox para suspender recetas con tratamiento prolongado con alguna receta con dispensa-parcial o sin-dispensa a suspender.
2. Al Suspender tratamiento prolongado, se suspende la siguiente receta en estado pendiente y sin-dispensa, y se elimina el resto de recetas pendientes y sin-dispensa, se deja captura de como queda en DB
3. Se modifica visualización al suspender multiples medicamentos como se muestra en la imagen
> HUDS: Suspensión de receta con tratamiento prolongado

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/modules/com/components/estados-cama-provincial.html
- src/app/modules/com/components/estados-cama-provincial.scss
- src/app/modules/com/components/estados-cama-provincial.ts
- src/app/modules/com/services/estados-cama-provincial.service.ts
https://proyectos.andes.gob.ar/browse/COM-104
1. Se implementa una nueva vista para conocer el estado de las camas de cada unidad organizativa dentro de una organización en particular.
> Visualizar resumen de estados de camas provincial
