andes/app

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Aproximamos la hora de la agenda al cuarto más cercano para que no se pueda cargar hora de inicio o final como 12:37.
> Redondear al cuarto más cercano la hora de la agenda

- src/app/components/rup/formulas/indiceDeMasaCorporal.component.ts
- src/app/components/turnos/configuracion/mapa-espacio-fisico/mapa-espacio-fisico.component.ts
- src/app/components/turnos/dar-turnos/calendario.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/agregar-nota-turno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts
- src/app/pipes/pluralizar.pipe.ts
- src/app/services/paciente.service.ts
- src/app/services/turnos/turno.service.ts
Cambios para dar turnos de bloques que permite la citación por segmento.  Para los casos en que de diferentes instancias de la aplicación se intente dar el mismo turno.  Realizará un nuevo intento de dar el turno según el mensaje que reciba de la app
> Fix en turnos de bloques de Citacion por segmento

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- Corregir la actualización del paciente al dar turno. Un solo post con la actualización del contacto y de la carpeta
> Corregir la actualizacion del paciente al dar turno

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
- luego de asignar sobre turno, se refresca la agenda automáticamente para mostrar el cambio.
- soporte para sobreturnos desde revisión de agenda.
> Enhancement sobreturno

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/elementos/autocitado.html
- src/app/modules/rup/services/prestaciones.service.ts
Generar prestaciones prestaciones pendientes para planes con conceptos turneables. 
En la validación buscar agendas con turnos del profesional disponibles para mostrar el botón de dar turno. (autocitación).
> Generar prestaciones pendientes

- src/app/components/paciente/paciente-create-update.component.ts
- Verificamos en el model del paciente si tiene documento, para que no intente realizar matcheos.
- Evitamos la generación de temporales relacionados si el paciente no posee documento.
> controles cuando el paciente no posee documento

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- Luego de dar turno, el componente <dar-turno> emite la agenda modificada para que el gestor la refresque.
> Refresh luego de dar turno

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- Arreglamos errores en los botones de cambio de estado.
- La desselección de agendas tenía un error. 
- Evitar agregar códigos CIE10 duplicados en revisar agenda.
> Botones de cambio de estado

- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
- src/app/components/usuario/arbolPermisos.html
- Ahora al clonar marca correctamente los conflictos encontrados.
- Va adjunto el cambio requerido en gestión de pacientes: no permite mas "seleccionar todos" para las prestaciones.
> fix deteccion conflicto clonar agenda

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dashboard/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- dejamos de hacer un get para c/ paciente cada vez que seleccionamos una agenda, en cambio hacemos una actualización de los turnos asignados a un paciente cuando éste se modifica.
- Al dar el turno, enviamos también la fecha de nacimiento del paciente para que ésta quede guardada en el turno
> Mejora paciente turno

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/carpeta-paciente.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/carpeta-paciente.html
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- Borramos el getById de c/paciente en la agenda, que ya no es necesario en base a los cambios realizados en el PR 117 (API)
- Fix en la lectura/modificación de nroCarpeta para pacientes que tienen carpeta en más de un efector (complementa pr 120 en api )
- Fix plex toast revisión agenda
> Mejora código

- src/app/components/paciente/paciente-search.component.ts
- src/app/components/paciente/paciente-search.html
- src/app/components/turnos/dashboard/paciente-search-turnos.component.ts
- src/app/components/turnos/dashboard/paciente-search-turnos.html
- src/app/modules/rup/components/elementos/adjuntarDocumeto.ts
plex-input emite un evento **change** cuando el input pierde el foco. Por lo cual estaba lanzando una nueva búsqueda de pacientes y refrescaba la pantalla. 
Por suerte, como argumento llega un objeto Event y prevenimos _por ahora_ la búsqueda.
> Error doble click en MPI

- src/app/components/paciente/paciente-search.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dashboard/paciente-search-turnos.component.ts
- src/app/components/turnos/dashboard/puntoInicio-turnos.component.ts
- Cuando escaneamos un paciente, si éste no tenía cargado el field 'scan', lo seteamos
> Update campo SCAN

- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- Fix en botones de turnos de agendas cerradas ( se mostraban opciones para liberar turno, turno doble, etc) https://trello.com/c/H3JVfqYB/91-operaciones-de-turnos-en-agendas-con-estado-auditada
- Actualizamos los chequeos de estado de agenda, según el nuevo enum. de estados
- Queda pendiente un TODO para cambiar el estado de una agenda, a pendienteAuditoria, cuando se da asistencia a todos los turnos.
> Botones citas

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/components/elementos/temperatura.html
- src/app/modules/rup/components/elementos/tensionDiastolica.html
- src/app/modules/rup/components/elementos/tensionSistolica.html
- Al iniciar prestaciones desde le punto de inicio de RUP tomar el tipo de prestación del turno y no del bloque dado que los bloques pueden tener mas de un tipo de prestación.
- Agregar en la búsqueda de agendas aquellas que estén pendientes de Asistencia o Auditoria
> Rup pi agendas multi prestaciones

- src/app/modules/rup/components/ejecucion/puntoInicio.html
En el punto de inicio de rup cuando hay agendas, al momento de iniciar la prestación se debe tomar el tipo de prestación del turno y no del bloque.
> Corregir la generación de la prestación agendas mult-prestaciones

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/listar-turnos.html
- src/app/interfaces/turnos/ITurno.ts
Se corrige la impresión de planilla de consultorios para que muestre la fecha de nacimiento y el sexo del paciente.
> agrego sexo en el paciente que se guarda en el turno

- src/app/modules/rup/components/elementos/seguimientoDelPeso.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Nuevo método en prestaciones.service.ts que busca en las prestaciones del paciente un determinado de conjunto de conceptId. Utiliza un nuevo end point (/prestaciones/huds/idPaciente).
Extra: Se agrego máximo y mínimo en el eje X para el átomo de seguimiento de peso.
Nota: Es necesario hacer checkout en la API sobre el branch _buscar-en-huds_.
> Funcion para buscar en la HUDS en el servicio de prestaciones

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
En la validacion: cuando se rompe la validación y se vuelve a validar no se veia el boton de asignar turno.
Fitrar las prestaciones con el concepto "no concurrio ..... " para que no se envien a codificar al momento de validar
> Rup fix asignar turno

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
@andes/red-tics 
Estimados, la intención de este PR es modificar la función de aproximación de la hora cuando creamos la agenda :calendar:  . (en lugar de redondear de a 15' que lo haga de a 5')
Como esto fue hecho inicialmente en #9 , estaría bueno asegurarnos que no entre en conflicto con algún requerimiento.
besos y abrazos
> Aproximación de hora en crearAgenda

- src/app/components/paciente/paciente-search.html
@andes/red-tics 
- La idea es: Cuando el paciente search está en [modoCompleto]=false ocultar también el header. 
hay algún problema con este cambio?
> modo completo en false oculta también el header

- src/app/app.module.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/buscador-cie10.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/buscador-cie10.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/buscador-cie10.scss
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.scss
1. cambiamos el plex select para seleccionar diagnóstico por un plex-text.
2. nuevo componente de búsqueda 
3. habilitamos la posibilidad de agregar nuevos diagnósticos a turnos  codificados por profesional, además de la opción de reparar/aprobar diagnóstico
4. Cada cambio dispara automáticamente un patch a la agenda, sacamos el botón guardar. :warning:
> Revision agenda

- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
* el metodo sortCarpetas de listar-solicitudes estaba comparando por string los valores del atributo "numeros", generando una mal ordenamiento.
* En el select de profesionales ya no se visualiza mas el icono de "actualizando"
> se arregla el sortCarpetas y select de profesional en el form

- src/app/modules/rup/components/elementos/solicitudPrestacionDefault.html
Referencia: RUP - Error en visualización de planes #570
Agregar controles en el HTML de los planes cuando no se carga la organización y el profesional destino, por error en visualización.
> Resolver bug en la visualización de planes issue #570

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
* Quitamos array hardcodeado de conceptos snomed correspondientes a una "no asistencia" y lo reemplazamos por una query que devuelve todos los hijos del concepto "NO ASISTIÓ"
* Actualizamos el chequeo de asistencia que se realiza al guardar y validar prestación.
> Verificación de asistencia a través del concepto snomed

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
Se requiere visualizar relaciones anidadas en las pantallas de Validación y Resumen de RUP. Actualmente se muestra sólo 1 o más niveles padre sin hijos de nivel 2, así:
1. **(P)** padre 
===>1.1 **(H1)** hijo de **(P)** :trollface: 
===>1.1.1 (H2) hijo de hijo **(H1)**
La mejora realizada se muestra así:
1. **(P)** padre 
===>1.1 **(H1)** hijo de **(P)** :trollface: 
=======>1.1.1 (H2) hijo de hijo **(H1)**
@andrrrl
> RUP - Relaciones con niveles anidados

- src/app/modules/rup/components/elementos/seguimientoDelPeso.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Para mostrar la curva de seguimiento de peso:
- Cambiamos en el servicio que buscar conceptos en la HUDS de un paciente el parámetro "conceptos": de un array de conceptos los cambiamos por una expresión snomed.
> Refactor curva de seguimiento de peso

- src/app/components/turnos/autocitar/autocitar.html
Un profesional debe poder autocitar en una agenda que tiene bloques configurados por segmentos
1. Sacamos el filtro en la autocitación que estaba ocultando los turnos de los bloques por segmento
> RUP - Sacar filtro en autocitación cuando la agenda es por segmentos

- src/app/components/paciente/paciente-detalle.ts
* Al realizar la consulta de Renaper en algunos navegadores la fecha de nacimiento queda incorrecta.
1. Se aplica moment para estandarizar el formato de la fecha independientemente del navegador.
> Fecha de nacimiento para consultas desde Renaper

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* Resuelve Issue: fix #722
1. Al momento de dar el turno no se recuperaba la nota del mismo (si es que hubiera)
2. Se agregó este control y la nota se carga en la confirmación del turno permitiendo editarla.
> CITAS - Se agrega nota previa del turno

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
* Resuelve parte del issue #736 
1. Se corrigió un control que verificaba la cantidad de turnos de gestión configurados en lugar de restantes.
> CITAS - corrección en dar turnos con llave

- src/app/components/organizacion/organizacion-create-update.html
- src/app/modules/rup/components/internacion/mapa-de-camas/mapa-de-camas/mapa-de-camas.component.ts
Ingresar al mapa de camas cuando aún no se han configurado camas para un efector.
1. Agregamos un control cuando se cargan los filtros del mapa de camas
> RUP - Control en los filtros del mapa de camas para cuando no hay camas cargadas

- src/app/modules/rup/components/elementos/SelectPorRefset.component.ts
- src/app/modules/rup/components/elementos/SelectPorRefset.html
- src/app/modules/rup/services/prestacionGetParams.interface.ts
HUDS - Prestación Screening de otoemisión acústica neonatal
* Este PR implementa la mejora descripta en el siguiente issue: https://github.com/andes/app/issues/617
1. Si en una consulta de Screening de Otoemisión acústica se registran en antecedentes, estos se visualizan cuando se inicia una consulta nueva de Screening de Otoemisión del mismo paciente.
- Al elementoRUP cuya key "componente" es "ScreeningDeOtoemisionAcusticaNeonatalComponent"
- Dentro de su array de "requeridos"
- En el concepto cuyo term es "evaluación de antecedentes"
- Se le debe configurar el siguiente param:
`"ultimoValor": true`
Quedando:
```
"params": {
"titulo": "Seleccione algún antecedente",
"refsetId": "2121000013101",
"tipoSelect": "select",
"multiple": true,
"ultimoValor": true
}
```
> HUDS - Screening de otoemisión acústica neonatal: antecedentes

- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
* Resuelve Issue #705
1. Se agregó control de estado de agenda al verificar solapamiento cuando se edita agenda.
> CITAS - Control de estado de agenda al verificar solapamiento de profesionales

- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/app.routing.ts
* Publicar la ruta de padrones para que se pueda acceder desde diferentes efectores de la provincia
1. Se quita la autenticación a la ruta de puco. Se agrega opción "Padrones" en el menú hamburguesa.
> Publicar la ruta de padrones de obra social

- src/app/components/prestamosHC/solicitudes/listar-solicitudes.component.ts
1. En prestamos de carpeta, cuando se realiza un pedido de préstamo manual, y el paciente buscado no tiene carpeta en la institución, se da la posibilidad de crear nuevo numero de carpeta
> PRESTAMOS HC - Nueva carpeta paciente

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
* Corregir bug en el puntto de inicio de RUP cuando una agenda tiene el listado de profesionales en null
1. Agrega filtro en el punto de inicio para controlar agendas con el listado de profesionales en null
2. 
3.
> RUP: Agrega filtro en PI para agendas con profesionales "null"

- src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
- src/app/modules/rup/components/elementos/OdontogramaRefset.html
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
* Las caras de las piezas dentales se deben mostrar espejadas según en el cuadrante que estén. El problema estaba en los cuadrantes izquierdos (superior e inferior) y cuadrantes inferiores (derecho e izquierdo).
1. Las caras de las piezas de los cuadrantes de la izquierda se muestran correctamente espejados con respecto a las piezas del cuadrante derecho.
2. Ídem anterior, con el agregado que cuando la pieza dental está en un cuadrante inferior, la cara palatina (del paladar) se llama lingual (de la lengua), no estaba pedido pero es una mejora.
> HUDS/Odontología - Nombres de caras en piezas dentales

- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/resumen.html
- src/app/modules/rup/components/ejecucion/vistaCDA.html
- src/app/modules/rup/components/ejecucion/vistaHuds.html
* Diferenciar fecha de solicitud y fecha de ejecución. Se estaba mostrando la fecha de solictud y en algunos casos había más de un mes de diferencia.
1. Muestra la fecha de ejecución.
2. Si hay una solicitud, muestra la fecha de solicitud.
3. Resuelve #1044
> rup: fecha de solicitud y ejecución.

- src/app/components/turnos/dar-turnos/dar-turnos.html
* Se requiere al momento de dar el turno, si es una agenda dinámica que aparezca el horario de la agenda en sidebar.
> agrega horario en el caso de selección de agenda dinámica

- src/app/components/turnos/gestor-agendas/operaciones-agenda/clonar-agenda.ts
* Verificar en la clonación de agendas los chequeos de conflictos. Había casos en los que permitía clonar una agenda en una fecha donde existía un conflicto (coincidencia en el horario y el profesional)
1. Se modifico el método que verifica los conflictos
> CITAS - Corrige condición al verificar conflictos en la clonación

- src/app/app.component.ts
Agregar acceso al mapa de camas desde el menú hamburguesa
1. Agrega acceso al mapa de camas desde el menú hamburguesa para usuarios con permisos
2. 
3.
> Internación - Mapa camas acceso

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
* Corrige Bug que ocurría al planificar o editar una agenda en planificación. Se mostraba conflicto de profesional o espacio físico cuando una agenda finalizaba exactamente al mismo horario que comenzaba otra.
1. Se elimina parámetro extra en llamada al servicio de agendas.
> Fix solapamiento

- src/app/components/turnos/dashboard/estadisticas-agendas.component.ts
- src/app/components/turnos/dashboard/estadisticas-agendas.html
- src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
- src/app/components/turnos/dashboard/estadisticas-pacientes.html
Se quita la sección de cálculos estadísticos totales de turnos asignados (entre otras queries) y se reemplaza por información útil al usuario. Evitando la ejecución del cálculo estadístico de agendas por cada dación de turno.
> CITAS: Se reemplaza la información estadística de agendas por información útil al usuario.

- src/app/modules/rup/components/elementos/adjuntarDocumento.component.ts
Al momento de querer adjuntar un archivo con la app mobile para la prestación "actividades con la comunidad" daba un error ya que no se estaba controlando que venga el paciente. Estas prestaciones no tienen un paciente.
> RUP: Se resuelve problema de actividades comunidad al subir archivo.

- src/app/modules/rup/services/prestaciones.service.ts
* Epicrisis y colonoscopía al tener seccionados, quedaron afuera los hallazgos y trastornos registrados. Se requiere poder visualizarlos en el listado de la HUDS.
1. Se realizo un patch momentaneo, especifico para esta dos prestaciones. 
Queda pendiente detectar automáticamente las secciones para cualquier prestaciones.
> HUDS: visualizar registros de epicrisis y colonoscopia

- src/app/app.component.ts
- src/app/components/paciente/paciente-search.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
En un PR se modificó mal el permiso para ingresar al componente `paciente-search`. Entonces cada vez que se trataba de entrar a un lugar donde se utiliza este componente sin permiso de visualización de huds, rebotaba.
Descubrí también que podía ver en el menú hamburguesa CITAS: Punto de Inicio y no poder ingresar por no poseer MPI. Le agregué este permiso, además de citas, para mostrar el acceso solamente cuando pueda entrar realmente (ahorro el rebote a inicio).
1. 
2. 
3.
> Permiso - MPI y visualización de huds

- src/app/components/profesional/profesional-create-update.component.ts
- src/app/components/profesional/profesional.component.ts
- src/app/services/profesional.service.ts
Optimización de ancho de banda para los get de profesionales.
1. Agrega get para profesionales para que no traiga todos los campos (solamente id, documento, nombre y apellido)
> refactor(profesional): agrega select en get

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
Fix de issues #1288 y #1289
1. Se agregó un event emitter para en el  componente de turnos para refrescar la agenda seleccionada en el gestor de agenda, produciendo la actualización de la botonera.
2. En el componente de botonera de agenda, se agregó una nueva condición (existencia de turno con asistencia registrada) para ocultar botón de suspensión de agenda, en los casos de agendas dinámicas.
> AGENDAS: Refresca botonera de agenda al dar asistencia a un turno

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
Al editar una agenda en planificación y que tuviera asignado profesional/es, al borrar los mismos el atributoo quedaba en null en lugar de array vacio. Esto producia un error.
issue #1382 
1. En la edición de una agenda, al momento de borrar sus profesionales este array queda en 'null' cuando debería ser un array vacío. Cuando esto sucede se le asigna '[]'.
> CITAS: Turnos en agendas sin profesional

- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
https://pm.andes.gob.ar/projects/citas/work_packages/803/activity
1. Al planificar una agenda se setea a cada turno el valor "auditable" correspondiente al atributo con mismo nombre del tipoPrestación asignado al bloque.
Agregar a los conceptos turneables con conceptId 34043003 y 861000013109 el atributo `auditable` en `false`
`db.getCollection('conceptoTurneable').updateMany({$or: [{conceptId: '34043003'}, {conceptId: '861000013109'}]}, { $set: {auditable: false}})`
https://github.com/andes/api/pull/794
> Audita automáticamente agendas de prestaciones no auditables 

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
#1453 
1. Luego de crear una agenda, se resetean los parámetros skip y limit quedando con estos valores:
```
skip: 0,
limit: 15
```
> fix(citas): se resetean parámetros skip y limit en query de agendas

- src/app/core/mpi/components/paciente-cru.html
Se rompieron 5 test de cypress porque se introdujo un espacio en un atributo html.
https://github.com/andes/app/pull/1419/files#diff-5bb58586b9985f865cd6750980ffb3e9R215
1. Se remueve el espacio.
> fix(citas): remove space in html attribute

- src/app/services/websocket.service.ts
Se quita evento reconnect_attempt en servicio de websocket
1. Elimina evento reconnect_attempt
> fix(turnero): se quita evento reconnect_attempt

- src/app/apps/gestor-usuarios/components/perfiles-detail.component.ts
No se puede guardar perfiles por un cambio en angular 8. 
1. ViewChild: static: false 
2. 
3.
> fix(gestor-usuarios): fix abm perfiles ANGULAR 8

- src/app/modules/rup/components/ejecucion/resumen-paciente/resumenPaciente-dinamico.component.ts
La expresión estaba al revés, buscaba los padres y no los descendientes. Se ve que con mongo no pasaba nada, pero con Snowstorm la query empezó a funcionar como corresponde y provocaba que la HUDS no  ciertos pacientes no se vean. Con los que tienen colonoscopía.
> fix(huds): wrong snomed expresssion Riesgo Cardiovascular

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/especialidad/especialidad-create-update.component.ts
- src/app/components/tipoPrestacion/tipoPrestacion-create-update.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts
- src/app/modules/estadisticas/components/tabla-2d/tabla-2d.component.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.scss
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
- src/app/modules/rup/components/elementos/OdontogramaRefset.html
- src/app/modules/rup/components/elementos/OdontogramaRefset.scss
- src/app/modules/rup/components/huds/vistaDetalleRegistro.html
- src/app/modules/rup/components/huds/vistaDetalleRegistro.scss
- src/app/modules/rup/components/huds/vistaDetalleRegistro.ts
- src/app/modules/rup/components/huds/vistaSolicitudTop.ts
- src/app/modules/rup/components/variables.scss
- src/app/modules/rup/interfaces/prestacion.registro.interface.ts
- src/app/modules/rup/services/elementosRUP.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/services/turnos/configPrestacion.service.ts
- src/environments/environment.dev.ts
- tslint.json
https://pm.andes.gob.ar/projects/rup/work_packages/741/activity
1. Se agregó un componente que muestra detalles de una pieza dental y visualiza los registros históricos de la misma, de manera interactiva
2. Se cambió la manera en que se muestran los odontogramas validados, se muestra el número de registros con dígitos en lugar de elementos SVG.
> RUP: Odontograma histórico con detalles de piezas

- src/app/components/inicio/inicio.component.ts
- src/app/components/inicio/inicio.html
- src/app/components/inicio/inicio.scss
Agrega cuadrado para Analtytics bajo permisos. La URL viene hardcodeada por el momento, la idea es reestructurar esa pantalla para que sea dinámica, configurable desde alguna colección. 
1. Se agrega un cuadrado al home.
> feat(home): agrega menu analytics

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
https://proyectos.andes.gob.ar/browse/RUP-6
1. Al registrar prestación fuera de turno, se bloquea el botón iniciar prestación al cliquearlo, para evitar duplicados de la prestación
> RUP: Deshabilita botón iniciar prestación (fuera de turno)

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
1. Se agrego el campo [min] al plex-int para restringir que no se ingresen números de pacientes negativos al citar por segmento (Linea 297)
2. Se agrego el campo [min] al plex-int para restringir que no se ingresen números de pacientes negativos al citar pacientes simultáneos (Linea 287)
Observación: Agrego las lineas porque los demás cambios son de linteo.
> fix(CITAS): no deja ingresar numero de pacientes negativos al citar por segmento

- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.html
#1449
1. Además de lo solicitado en la #1449, también se aplicó el cambio para las prestaciones destino de salida y para los combos de solicitudes de entrada
2. Dado el comportamiento de plex select que deja la opción previamente seleccionada dentro de las opciones del select una vez que se limpió el data de dicho select, fue preciso implementar un workaround en los plexselects para que toda vez que la selección sea nula, vuelva a auto asignarse el null y vaciar el array de opciones, para limpiar el remanente de las opciones del componente
> TOP: limpia opciones de Selects

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
Poder setear distintos niveles de visibilidad en el gestor de usuarios:
- _public_: cualquier puede asignar ese permiso.
- _restricted_: Solo si tenes ese permiso podes asignarlo a otros usuarios.
- _hidden_: Invisible para todos, se gestiona desde base de datos.
Con esta funcionalidad, solo los que tienen permiso de matriculaciones pueden dar permisos para matriculaciones. Si no tenes permisos y estás editando un usuarios, no se lo pisas como pasaba antes.
Del lado de la APP, se ocultan los accordion correspondiente al nivel de visibilidad, permitiendo al gestor de usuarios poder mantener el permiso si estaba habilitado.
PR API: https://github.com/andes/api/pull/865/files
> feat(gestor-usuario): add visibility attribute

- src/app/app.routing.ts
- src/app/apps/turnero/services/pantalla.service.ts
- src/app/apps/turnero/turnero.routing.ts
- src/app/apps/turnero/views/pantalla-detalle.component.ts
- src/app/apps/turnero/views/pantalla-detalle.html
- src/app/apps/turnero/views/pantallas.component.ts
- src/app/apps/turnero/views/pantallas.html
- src/app/apps/turnero/views/pantallas.scss
Permitir configurar los totems de la misma forma que las pantallas del turnero. Se deberá especificar al cargar una nueva de qué tipo es (totem/turnero).
1. Se cambiaron textos en la pantalla de configuración
2. Se agregó un select al cargar pantallas para seleccionar el tipo
3. Se muestran/ocultan campos dependiendo el tipo
> TURNERO: sumado tipo a la configuración de pantallas

- src/app/components/turnos/dashboard/estadisticas-pacientes.html
1. Al dar un turno a un paciente que se encuentra dentro del programa SUMAR, en el sidebar mostraba el financiador vacio. Ahora muestra el nombre correctamente 
Antes:
Despues:
> MPI: Muestra financiador SUMAR al dar un turno

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Se agrega control de paciente en el punto de inicio de RUP, para evitar la generacion del token de acceso a la HUDS para prestaciones no nominalizadas
1. Verificación en preAccesoHuds
2. 
3.
> fix(rup): Agrega control para prestaciones no nominalizadas

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
No se visualizaba SUMAR en el listado de prestaciones y turnos en el caso de los pacientes que tienen dicha cobertura
1. Cambia la propiedad a mostrar de nombre a financiador 
2. 
3.
> fix(buscador de prestaciones y turnos): Cambia la propiedad a mostrar

- src/app/modules/rup/components/ejecucion/buscador.component.ts
Cuando el profesional no tenía frecuentes, devolvía este error en la consola:
```
core.js:6014 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
at BuscadorComponent.<anonymous> (buscador.component.ts:198)
at Generator.next (<anonymous>)
at fulfilled (rup.component.ts:36)
at ZoneDelegate.invoke (zone-evergreen.js:359)
at Object.onInvoke (core.js:39699)
at ZoneDelegate.invoke (zone-evergreen.js:358)
at Zone.run (zone-evergreen.js:124)
at zone-evergreen.js:855
at ZoneDelegate.invokeTask (zone-evergreen.js:391)
at Object.onInvokeTask (core.js:39680)
at resolvePromise (zone-evergreen.js:797)
at zone-evergreen.js:707
at fulfilled (rup.component.ts:36)
at ZoneDelegate.invoke (zone-evergreen.js:359)
at …
```
> fix(rup): corrige error profesional sin frecuentes

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
1. Al momento de hacer click en el boton ' NO SE ASIGNA TURNO ' se guarda la organizacion en una variable para insertarla en la lista de espera
> CITAS: Se agrega la organizacion al no asignar turno

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
Se disparaba el uso de cpu en el servidor a partir del PR que recargaba el punto de inicio del profesional cada 30 segundos
1.  Se quitan llamados a prestaciones en la recarga del punto de inicio. 
2. Se deja solo la recarga de la agenda actual cada 30 segundos.
3. Se eleva el intervalo de refresco de 30 segundos a 5 minutos
> RUP: se modifican llamados a la api en la recarga del punto de inicio

- src/app/components/top/solicitudes/auditarSolicitud.component.ts
- src/app/components/top/solicitudes/auditarSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/tsconfig.json
Permitir que el profesional pueda dar respuesta a la solicitud sin necesidad de pasar por un turno
https://proyectos.andes.gob.ar/browse/TOP-15
1.  Se sumó un botón cuando se audita una solicitud para 'Asignar'
2.  Permite la selección de un profesional e indicar el motivo al seleccionar 'Asignar'
3.  Se suman al listado las solicitudes auditadas
> TOP: Asignación de una solicitud a un profesional al auditar

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
Se quita tooltip que indicaba la cantidad de solicitudes asignadas para mejora de performance
1. Se quita llamada a solicitudes en carga de punto de inicio de rup
2. Se quita tooltip del botón
> Punto de inicio RUP: Quita tooltip de cantidad de solicitudes asignadas

- src/app/apps/turnero/views/pantalla-detalle.component.ts
- src/app/apps/turnero/views/pantallas.component.ts
Arreglar error en '/pantallas' al leer el id de la organización de auth 
1. Se cambia this.auth.organizacion.id por this.auth.organizacion en los componentes pantallas y pantalla-detalle
> MISC: arreglo de error al cargar vista de pantallas

- src/app/app.routing.ts
- src/app/components/top/solicitudes/nuevaSolicitud.component.ts
- src/app/components/top/solicitudes/nuevaSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
Permitir scrollear en el formulario de carga de una nueva solicitud en pantallas de menor resolución. 
1. Se crea la ruta /solicitudes/[tipoSolicitud] para evitar herencia de estilos indeseados al crear una nueva solicitud (los que hacen desaparecer el scroll)
2. Se refactoriza la navegación desde y hacia la bandeja de entrada de solicitudes (src\app\components\top\solicitudes\solicitudes.html)
> fix(solicitudes): Evitar herencia de estilos en nueva solicitud

- .github/pull_request_template.md
- src/app/app.routing.ts
Agregar un recordatorio para que no se olviden de correr los tests localmente antes de crear un PR
1. Ninguna, se editó el template de este texto
> Se actualiza template de PRs, se agrega recordatorio para correr tests

- src/app/apps/auth/components/login/login.html
1. Una funcionalida de plex-icon evitaba que se vea el icono de la contraseña.
> fix(auth): agrega icon de contraseña en login

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
Incorporar funcionalidad que permite dar una autocitación que se perdió en rebase, otra vez :joy_cat: 
1. Se agregó funcionalidad de dar turno autocitado desde punto inicio de RUP
**Habría que agregar test más completos para Autocitación, que contemplen el ciclo completo desde el punto de inicio de RUP, y navegación**
> fix(rup-autocitación NUEVO): se agregan cambios para determinar autocitación

- src/app/modules/rup/components/ejecucion/buscador.scss
**Requerimiento**
https://proyectos.andes.gob.ar/browse/UIUX-95
**Funcionalidad desarrollada** 
Se agrega la propiedad <overflow-x: hidden> al tag <cdk-virtual-scroll-viewport>
**Cuál era el problema?**
Angular material incorpora la siguiente directiva: cdk-virtual-scroll-viewport *que a su vez, incluye la propiedad overflow con valor 'auto' haciendo override sobre la clase .plex-box-content*  del plex-box que está seteada inicialmente en hidden sobre el eje x (overflow-x: hidden); generando un scroll innecesario en el panel lateral.
> RUP - Se elimina scroll horizontal en resultados

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
El loader de plex quedaba corriendo todo el tiempo al dar una autocitación.
1. Se elimina un POST sin subscribe que no es estaba ejecutando y no dabía estar ahí.
> fix(rup): remueve llamado incesario a crear prestacion

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
#1541 
1. Al marcar una agenda cómo dinámica, se resetean los bloques de agenda, dejando un único bloque con datos cargados por defecto.
> CITAS: Resetea los bloques de agenda dinámica

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.html
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
Sumar en RUP en las prestaciones de la historia de salud un filtro usando plex-options para elegir entre origen ambulatorio/internacion
1. Se suma un filtro fijo en la pestaña historia de salud (prestaciones) implementado con plex-options
2. Fix de error de null al borrar los filtros
> RUP: filtro por ámbito de origen en prestaciones de la historia de salud

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.html
Arregla bug: En planificación de agenda, si se destilda el checkbox de ventanilla virtual y el bloque previamente tenía una cantidad de turnos virtuales mayor que 0, dicha cantidad permanece, a pesar que no debiera poseer ninguún turno virtual.
1. Cada vez que se destilda el checkbox de ventanilla virtual, se setea la cantidad de turnos virtuales a 0.
> CITAS: Resetea turnos virtuales a 0

- src/app/core/mpi/components/paciente-cru.component.ts
- src/app/core/mpi/components/paciente-cru.html
Deshabilita el botón "Ignorar y Guardar" para evitar doble click al guardar un paciente, después de mostrarse el listado de pacientes similares
1. Agrega propiedad disabled al botón "Ignorar y Guardar" en paciente-cru
2. 
3.
> fix(mpi): Evita doble click en  "Ignorar y Guardar"

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.html
Problema con el tooltip de copiar/pegar permisos
1. Se agrega _titlePosition="left"_ a _plex-button_ para solucionar problema con el _tooltip_ en botones de copiar y pegar permisos
> USUARIOS: Fix copiar/pegar permisos

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/historial-detalle/historial-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/ingreso/informe-ingreso.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/lista-espera/lista-espera.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaPrestacion.ts
Pre-visualización de prestaciones de internación desde el mapa de cama. 
1.  Agrega botón "ojo" en cada registros de internación.
2. Se pre-visualizan en el layout pricipal.
3. Se elimina modulo internación hasta que exista el modulo de RUP.
> mapa-camas: pre visualización de los registros médicos

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/plugins/servlet/mobile#issue/CIT-19
1. Al inicializar el componente turnos-prestaciones, se verifica si el usuario logueado es profesional, en caso de serlo se muestran solo los turnos asignados al mismo y se bloquea el filtro de profesionales( _[readonly]="selectProfesional"_ ).
2. Al seleccionar un turno se verifica si el usuario logueado es profesional, en caso de serlo se oculta el botón "Comprobante"
> CITAS: Visualizar detalle de agendas y prestaciones realizadas por el profesional

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/ingreso/ingresar-paciente.component.ts
Mostrar nombre del sector para identificar la cama ya que hay muchas camas con el mismo nombre: "CAMA 01", "CAMA 02".
1.  Agrega nombre del sector para identificar rapidamente la cama.
> feat(mapa-camas): agrega sectores en seleccionar cama

- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
[https://proyectos.andes.gob.ar/browse/CIT-28](url)
1. Al suspender una agenda se refresca la vista del gestor de agendas y se llama a la función _verAgenda_ para que se muestre el estado actualizado
GLPI asociado: [https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=4571](url)
> CITAS: Al suspender una agenda en el gestor no se actualiza el estado

- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
- src/app/directives/prestaciones-select.directive.ts
- src/app/services/conceptos-turneables.service.ts
Cache de prestaciones según permisos y replicada en la directiva de prestaciones.
Ajusta la busqueda de instituciones y limit=50 en el gestor de usuarios para mantener compatibilidad.
https://github.com/andes/api/pull/970
> tipo-prestaciones: cache de prestaciones según permisos

- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/panel-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
[https://proyectos.andes.gob.ar/browse/CIT-26](url)
1.  Se agrega verificación al cambiar el estado de una agenda, en el caso en que la seleccionada haya cambiado de estado mostrara un "warning" y se actualizará el gestor de agendas.
> CITAS: Pasar control de estados de agendas para operaciones que estan en app a la api

- src/app/shared/components/upload-file.component.ts
El evento change del input de <upload-file> se propagaba hasta plex-tab que emitia un (chage), provocando que se actualicen toda la vista y queden las componentes desacopladas.
1. Agrego stopPropagation
2. 
3.
> fix(prestamo-carpeta): stopPropagation change event

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
Existen usuarios con solo permisos a internación y no pueden validar actualemente. 
1. Control de permisos para internacion
> fix(rup): permisos solo internacion

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-83
1. Remueve control que filtra los conceptos turneables de la lista de procedimientos.
> RUP: habilita registrar turneables como procedimientos

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Al editar una cama y volver al mapa de camas la cama queda seleccionada pero en el sidebar se ve el estado de servicio. Debería mostrarse la cama seleccionada.
1.  Si hay una cama seleccionada al entrar al mapa de camas, muestra el detalle de la misma.
2. 
3.
> INTERNACION - Arregla mapa de cama al volver de la edición con cama seleccionada

- src/app/modules/rup/components/elementos/observaciones.component.ts
- src/app/modules/rup/components/elementos/observaciones.html
ObservacionesComponent es más bien un átomo para escribir: _observaciones_, _motivos_, etc
1. Parametriza el label del plex-text
> feat(elementos-rup): titulo parametrizable en ObservacionesComponent

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
https://proyectos.andes.gob.ar/browse/GDU-7
1. Se agrega _(_change_)_ al árbol de permisos para emitir un evento al cambiar el _plex-bool_ que selecciona todas las prestaciones.
2. Se elimina comentario confuso en linea 35.
> Gestor de Usarios: Fix Toggle "seleccionar todos" de Solicitudes

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
Al querer volver al mapa de camas, el botón 'volver' direcciona al usuario hacia el punto de inicio de RUP. En camino feliz sería que regrese al mapa de camas.
1.  El mapa de camas declara la ruta a volver para que en huds de paciente pueda volver al mapa de camas. 
2. 
3.
> INTERNACION - Arregla navegacion defectuosa entre mapa-camas y huds de paciente

- src/app/apps/gestor-usuarios/views/usuarios-list.view.html
- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
https://proyectos.andes.gob.ar/browse/GDU-14
1. Se visualizan en el gestor de usuarios todas las organizaciones en las que el usuario seleccionado tiene permisos.
2. Se verifican los permisos para las organizaciones del usuario logueado para mostrar o no los botones de editar y activar o desactivar las distintas organizaciones.
> Gestor de usuarios: Visualizar todas organizaciones en las que el usuario tiene permiso

- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
https://proyectos.andes.gob.ar/browse/TOP-48
1. Se elimina el botón de sacar turno del listado de solicitudes en punto de inicio de CITAS
2. Muestra solo solicitudes pendientes o en auditoría en el listado
> CITAS: quitar botón de dar turno desde solicitudes en punto de inicio

- package-lock.json
- package.json
- src/app/apps/auth/components/select-organizacion/select-organizacion.component.ts
- src/app/apps/auth/components/select-organizacion/select-organizacion.html
- src/app/apps/auth/components/select-organizacion/select-organizacion.scss
https://proyectos.andes.gob.ar/browse/GDU-9
1. Se agrega un mensaje para mostrar en el momento que un usuario loguea y no tiene permisos para ninguna organización.
2. Se actualiza versión de plex para utilizar plex-label con sus nuevos atributos por recomendación del equipo UI/UX.
Se cambia el mensaje a mostrar por pedido de la Mesa de ayuda.
> Usuarios: Mensaje al seleccionar organización despues de login

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/components/reportesDiarios/reportes-diarios.module.ts
- src/app/components/reportesDiarios/reportes-diarios.routing.ts
Genera un modulo que se carga perezosamente para evitar cargar la librería de excel que es muy pesada en el archivo raíz de la aplicación. 
Antes:
chunk {1} main.cd02d39e63755c8321b1.js (main) 7.94 MB [initial] [rendered] 
Después:
chunk {1} main-es2015.e351e019ff503b36bc74.js (main) 6.57 MB [initial] [rendered]
> refactor(reportes-diarios): crea modulo lazy load

- src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
- src/app/apps/gestor-usuarios/views/usuarios-list.view.html
- src/app/apps/gestor-usuarios/views/usuarios-list.view.ts
https://proyectos.andes.gob.ar/browse/GDU-1
1. Se muestra el botón de 'Perfiles' solo si tiene el permiso usuarios:perfiles:write
2. El componente PerfilListComponent redirecciona a inicio si no tiene el permiso usuarios:perfiles:write
> GDU: control de acceso a Perfiles

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-22
1. Al hacer click en  cancelar cuando te pide seleccionar el motivo de acceso, continúa a la HUDS sin guardar el registro
> RUP: arreglo de acceso a HUDS sin elegir motivo

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.html
- src/app/modules/rup/interfaces/elementoRUP.interface.ts
https://proyectos.andes.gob.ar/browse/RUP-99
1. Al cargar el elemento RUP, si este no indica si requiere diagnostico principal, le setea el atributo `requiereDiagnosticoPrincipal` en `true`
2. En caso de no requerir diagnostico principal, se ocultan los radios de diagnostico principal y la pantalla no requiere principal para validar la prestación.
3. Se remueve el atributo `motivoConsultaOpcional` en desuso de la prestacion
- [] No
> RUP: Evalúa condición requiereDiagnosticoPrincipal

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=4621
1. Se modifica el campo _financiador_ por _nombre_ para que al seleccionar una prepaga se muestre de forma correcta.
> Turnos: Mostrar correctamente prepagas en el buscador de turnos y prestaciones

- src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
Cuando se abre un plex-modal, es posible cerrarlo presionando la tecla ESC, actualmente se puede cerrar, pero si cierra de esta manera luego el modal no vuelve a abrirse. Nótese que si se usa el botón "Cerrar" nativo de plex-modal el problema no sucede.
1. Se usó una manera diferente de registrar que el modal se cerró, antes hacía `this.modal.close()` ahora hace `this.modal.closed = true`, ya que la detección de eventos de teclado ya realiza un llamado al método `close()` y si se usa el mismo método desde el componente motivo-de-acceso genera un loop de llamados a `close()`, o algo.
2. Tener en cuenta que hay un problema con plex-modal en PLEX que no permite ingresar nada en el campo de búsqueda, ese bug se arregla en https://github.com/andes/plex/pull/128, mientras tanto se puede probar …
> HUDS: fix(modal motivo acceso): se corrige problema al cerrar con tecla ESC

- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
https://proyectos.andes.gob.ar/browse/RUP-136
1. Se deja de auditar la agenda al validad prestaciones no nominalizadas desde la app
> RUP: se deja de auditar la agenda al validar la prestación para no nominalizadas

- src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
La prestación de atención domiciliaria COVID, solo debe aparecer en la unidad organizativa de COVID. 
1. Se crea un filtro de registro por unidad organizativa.
2. Se puede configurar inclusivo o exclusivo (usando el caracter !).
```
{
"tipo" : "nuevo-registro",
"label" : "Epicrisis",
"parametros" : {
"unidadOrganizativa" : [ 
"!309901009"
],
"concepto" : {
"conceptId" : "2341000013106",
"term" : "epicrisis médica",
"fsn" : "epicrisis médica (elemento de registro)",
"semanticTag" : "elemento de registro"
}
}
}
```
> feat(mapa-camas): registros filtros por unidad organizativa

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/movimientos-internacion/movimientos-internacion.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.html
https://proyectos.andes.gob.ar/browse/IN-177
Quitar filtro por ambito internación, pero agregar fecha mínima. Si se hacen estudios fuera del ambito internación (desde fuera de agenda o programado) se deben ver los registros. 
1. Quita filtro por ambito
2. Busca el historial de la internación y usa esas fechas para calcular.
> feat(mapa-camas): quita filtro por ambito en registros medicos

- src/app/components/top/reglas/visualizacionReglas.html
Corrige BUG que ocurría en el listado de reglas que ahora muestra la localidad del efector y hay organizaciones en la BD que no tienen nombre en la localidad.
> fix(TOP): control en visualización de reglas

- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/services/query.service.ts
Corregir bug que ocurre al iniciar el módulo de reportes y el microservicio de bi-queries está inactivo
Nota: queda pendiente una mejora para agregar una ruta en la API que devuelva si está vivo.
> fix(reportes): Agrega control para microservicio inactivo

- src/app/modules/rup/components/elementos/SelectPorRefset.html
- src/app/modules/rup/components/elementos/valorFecha.html
Poder visualizar el term, sobre el valor en SoloValores, para saber al referencia a ese valor dentro de una molécula.
1. Solo se agrega que en los componente de SelectPorRefset y valorFecha se visualice el term en el huds.
2. 
3.
> RUP - Visualiza "term" o "title" en SoloValores

- src/app/components/top/reglas/visualizacionReglas.component.ts
- src/app/components/top/reglas/visualizacionReglas.html
En la visualización de reglas globales, el llamado a la api para traer las organizaciones colapsaba en producción, por lo que se decide eliminar el dato de localidad.
1. En el listado de reglas globales se quita la localidad de las organizaciones
> TOP: arreglo en visualización de reglas globales

- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/RUP-135
https://proyectos.andes.gob.ar/browse/RUP-137
1. Se elimina de la app la lógica de marcar la asistencia a un turno cuando se crea la prestación
2. Se elimina el uso de localStorage para guardar el idAgenda en RUP
Se debe mergear https://github.com/andes/app/pull/1783 antes porque se trabajó sobre la rama de ese PR
> RUP: Marcar asistencia del turno en background

- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.html
- src/app/apps/gestor-usuarios/components/arbol-permisos/arbol-permisos-item.component.ts
https://proyectos.andes.gob.ar/browse/GDU-5
1. Se suma plex-copy a los select de prestaciones para poder copiar entra items
- [] Si
> GDU: permitir copy/paste entre prestaciones

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
https://proyectos.andes.gob.ar/browse/RUP-93
Adicionales
https://proyectos.andes.gob.ar/browse/RUP-119
https://proyectos.andes.gob.ar/browse/RUP-121
1. Se removió la carga de prestaciones pendientes del método `actualizar`.
2. En el método `iniciarPrestación`:
-  Se cambió la entrada de parámetros por el turno
-  Se luego de obtener el token de acceso a HUDS y antes de crear la prestación nuevo, consulta a la API si existe una solicitud pendiente para ese turno; si la encuentra, ejecuta esa prestación.
- Se arregló el id de turno que se envía por parámetro a `generateHudsToken`
- Al crearPrestacion, se cambió la fecha que se envía, el `new Date()` x `turno.horaInicio`, para que la ejecución quede registrada con la fecha del turno que la inició.
3. Se remueve código en desuso relacionado a …
> RUP: pto inicio lazy load pendientes

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
…acceso a huds
https://proyectos.andes.gob.ar/browse/RUP-189
1. En el preAccesoHuds, si el motivo por el que se controla es continuar o ver el resumen de la prestación, no controla si tiene permisos para visualizar HUDS
> RUP: permitir ver y continuar prestación si el usuario no tiene acceso a HUDS

- src/app/apps/auth/components/accept-disclaimer/modal-disclaimer.component.ts
- src/app/modules/rup/components/elementos/OdontogramaRefset.component.ts
Bug de odontograma cuando se usaba como segundo registro. El valor no estaba definido.
> fix(rup): odontrograma no se podia usar como segungo registro

- src/app/components/top/solicitudes/detalleSolicitud.html
En el detalle de una solicitud con indicaciones, a partir del cambio en el sidebar que pasa a ser invert no se visualizan las indicaciones cargadas desde RUP en el plex-help. 
1. Se modifica el class del parrafo donde se visualizan las indicaciones para resolver el bug provisoriamente hasta que suban cambios a plex.
> fix(TOP): no se visualizaban  indicaciones de RUP

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Corregir error al cargar las solicitudes desde RUP, se están cargando como procedimientos y no como solicitudes.
1. Control si el filtro actual en el buscador es por solicitudes 
2. 
3.
> fix(RUP): control del filtro actual para solicitudes

- src/app/modules/rup/interfaces/elementoRUP.interface.ts
- src/app/modules/rup/services/ejecucion.service.ts
https://proyectos.andes.gob.ar/browse/RUP-179
1. En la ejecución de una prestación, si el concepto a registrar está repetido se chequea si el elementoRUP asociado permite repetidos.
> RUP: posibilidad de registrar conceptos repetidos en una prestación

- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
Mueve la logica de crear solicitudes a la API.
> refactor(rup): crear solicitudes en background

- src/app/modules/rup/components/elementos/evolucionProblemaDefault.html
- src/app/modules/rup/components/huds/vistaProcedimiento.html
- src/app/modules/rup/components/huds/vistaRegistro.html
- src/app/modules/rup/services/prestaciones.service.ts
La variable cache del servicio prestaciones ahora es un observable. Esta mal acceder directamente a ella. 
1. 
2. 
3.
> fix(huds): cache es un observable ahora

- src/app/modules/rup/services/prestaciones.service.ts
Quita sort innecesario de Prestaciones. Se pretende disminuir el trabajo de Mongo evitando el sort en memoría.
> perf(huds): quita sort innecesario

- src/app/components/top/pipes/estado-solicitud.pipe.ts
- src/app/components/top/solicitudes/detalleSolicitud.html
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
- src/app/components/top/top.routing.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
Utiliza pipe para calcular el estado de la solicitud por unica vez. Evitar multiples llamados. Dejo console.log para que verifiquen el comportamiento. 
De todas forma, quedan algunas mejoras más, es un ejemplo. La función **mostrar** llama a **verificarEstado**, habŕia que refactorizar bien todo. 
También hay algunos badge que no dependian de la función verificarEstado, eso complica mucho seguir el código. Esta partido en dos. 
Antes de completar este PR, habría que **UNIFICAR** criterios.
> perf(top): evita calcular estado todo el tiempo

- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
Cuando se elige mal al paciente a internar, por error y se inicia la internación, no hay manera de corregir esta situación al menos que se lo egrese, pero el registro en el historial sigue quedando.
1. Agrega un botón para poder deshacer una internación.
2. 
3. 
- [] No
> INTERNACION - Deshacer internacion si tiene ingreso solamente

- src/app/apps/gestor-usuarios/services/perfiles.http.ts
- src/app/apps/gestor-usuarios/views/perfiles-list.component.ts
https://proyectos.andes.gob.ar/browse/GDU-26
1. fix ExpressionChangedAfterItHasBeenCheckedError perfiles
2. 
3.
> GDU: fix ExpressionChangedAfterItHasBeenCheckedError perfiles

- src/app/apps/rup/mapa-camas/interfaces/IInconsistencia.ts
- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
- src/app/apps/rup/mapa-camas/views/integridad/detalle/detalle-integridad.component.html
- src/app/apps/rup/mapa-camas/views/integridad/detalle/detalle-integridad.component.ts
- src/app/apps/rup/mapa-camas/views/integridad/filtros-inconsistencia/filtros-inconsistencias.component.html
- src/app/apps/rup/mapa-camas/views/integridad/filtros-inconsistencia/filtros-inconsistencias.component.ts
- src/app/apps/rup/mapa-camas/views/integridad/integridad-camas.component.html
- src/app/apps/rup/mapa-camas/views/integridad/integridad-camas.component.ts
- src/app/apps/rup/mapa-camas/views/integridad/integridad.service.ts
- src/app/apps/rup/mapa-camas/views/integridad/item-inconsistencia/item-inconsistencia.component.html
- src/app/apps/rup/mapa-camas/views/integridad/item-inconsistencia/item-inconsistencia.component.ts
Se necesita una vista con una tabla que muestre las inconsistencias de las camas de internacion
1. Agrega componente de integridad de camas
2.
3.
> INTERNACION - Agrega componente de integridad de camas

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/interfaces/prestacionGetParams.interface.ts
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-124
1. Nueva funcion ' anular inicio de prestacion' que, dada una prestación en ejecución, desasocia el turno/sobreturno de la agenda correspondiente (En caso de no ser prestación fuera de agenda) y pone en estado anulada dicha prestación. De esta manera la prestación puede volver a iniciarse.
> RUP - Invalidar inicio de prestación

- src/app/core/mpi/components/paciente.component.ts
Incidente 
Cuando se validaba una persona fallecida, se deshacia la validación y posteriormente se cargaba el documento de otro paciente, la fecha de fallecimiento quedaba seteada con el dato de la primera validación, causando que a la última persona validada se le asigne una fecha de fallecimiento.
1. Inicializa y limpia variables en backup de validación
2. 
3.
> fix(mpi): setea fecha de fallecimiento

- src/app/modules/estadisticas/components/citas/filtros.component.ts
No se estaban mostrando correctamente los dashboards de Agendas y turnos.
El error se daba porque estaban desactualizados los permisos para profesionales y prestación entonces solo filtraba por aquellos turnos o agendas del profesional logueado.
1. Se actualizan los permisos.
> Dashboard: fix permisos actualizados

- src/app/modules/auditoria/component/auditoria.component.ts
- src/app/modules/auditoria/component/auditoria.html
https://proyectos.andes.gob.ar/browse/MPI-268
1. Corrección de parámetros de búsqueda en componente auditoría
> MPI - Fix error en búsqueda de pacientes auditoria

- src/app/components/top/pipes/botones.pipe.ts
- src/app/modules/rup/interfaces/prestacion.interface.ts
https://proyectos.andes.gob.ar/browse/TOP-86
1. Se agregan controles en pipe de botones para que permita la anulación de solicitudes en estado auditora
NOTA: reemplaza PR https://github.com/andes/app/pull/1956
> feat(TOP): permite anular solicitudes en estado auditoria

- src/app/components/top/pipes/botones.pipe.ts
Quitar control que se realizaba para mostrar botón anular en solicitudes pendientes. Se estaba chequeando que no existieran movimientos en esa solicitud pero nos reportan que hay casos en los que aún habiendo movimientos las solicitudes penidentes deben ser canceladas. 
1. Se actualizó el pipe que realiza los chequeos para mostrar los botones
> fix(TOP): realiza cambio en condiciones para anular solicitudes

- projects/shared/src/lib/server/error-handler.service.ts
Parche para solucionar este error en cada publicación:
```
Uncaught (in promise): ChunkLoadError: Loading chunk 19 failed.
(missing: https://app.andes.gob.ar/19-es2015.15f3a210e4e46d27270b.js)
ChunkLoadError: Loading chunk 19 failed.
(missing: https://app.andes.gob.ar/19-es2015.15f3a210e4e46d27270b.js)
at Function.c.e (https://app.andes.gob.ar/runtime-es2015.9442cb678bb1d755afbe.js:1:1382)
at JI (https://app.andes.gob.ar/main-es2015.796a2f1cff678fec075f.js:1:4381570)
at $n.loadModuleFactory (https://app.andes.gob.ar/main-es2015.796a2f1cff678fec075f.js:1:1658725)
at $n.load (https://app.andes.gob.ar/main-es2015.796a2f1cff678fec075f.js:1:1658468)
at c.project (https://app.andes.gob.ar/main-es2015.796a2f1cff678fec075f.js:1:1647951)
at c._tryNext …
```
> fix(chore): chunk error

- src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/BI-59
1. Agrego _plex-dropdown_ en la vista del buscador de turnos y prestaciones para que el usuario pueda seleccionar que columnas desea ver y cuales no. Por defecto se mostraran fecha, paciente, tipoPrestacion y estado.
2. Se agrega el ámbito a las columnas dinámicas.
> Turnos y prestaciones: columnas dinámicas 

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/interfaces/frecuentesProfesional.interface.ts
- src/app/modules/rup/services/frecuentesProfesional.service.ts
En algunos casos el calculo de frecuentes se hace muy demandante, todo el tiempo y ya son larga listas de conceptos.
Como primer medida vamos a aplicar Cache mediante de REDIS cuando la lista es más 20 conceptos, así mantenemos la actualización real time cuando arranca una prestación o profesional a registrar.
La idea es empezar a experimentar con algo no tan crítico como los frecuentes, antes de llegar a otras secciones.
https://github.com/andes/api/pull/1176
1. Se acomodan interfaces y servicio.
> feat(rup): agrega cache redis para frecuentes

- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-35
1. Permite asignar notas tanto desde el COM como del efector origen y desde el efector destino solo a partir desde que esta aceptada.
> COM: permitir sumar nota a origen/destino

- projects/shared/src/lib/operators/index.ts
- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.html
- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
- src/app/modules/visualizacion-informacion/services/export-huds.service.ts
- src/app/modules/visualizacion-informacion/visualizacion-informacion.module.ts
- src/app/modules/visualizacion-informacion/visualizacion-informacion.routing.ts
https://proyectos.andes.gob.ar/browse/PRIV-52
1. Se agrega componente y vista para Exportar HUDS.
2. Se agrega al documentos.service las peticiones necesarias para pedidos de HUDS.
En la coleccion `modulos` dentro del documento con nombre `Visualización`  en los permisos globales agregar:
`"huds:?"`
y crear un nuevo submodulo inserntando el siguiente json en el array `submodulos`:
```
{
"permisos" : [ 
"huds:exportarHuds:?"
],
"_id" : ObjectId("5fb55fa1081c031348aca9c8"),
"nombre" : "Exportar HUDS",
"linkAcceso" : "/visualizacion-informacion/exportar-huds",
"color" : "#ad6787",
"icono" : "exportar-corazon",
"orden" : 3
}
```
> VISUALIZACION DE INFORMACION: Exportar HUDS

- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-34
1. Evitar llamado a reglas de derivación al abrir el detalle de una derivación
> COM: hacer un único llamado a reglas de derivación

- src/app/modules/com/components/punto-inicio.html
https://proyectos.andes.gob.ar/browse/COM-41
1. Mostrar filtro de gravedad e iconos solo a usuarios del COM
> COM: mostrar gravedad solo a usuarios del COM

- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-69
1. Se modifica el componente y la vista para chequear el nuevo permiso `totalOrganizaciones` , en el caso que el usuario lo tenga, si la query viene con el campo organizaciones requerido en true, elimina esa restricción, caso contrario la deja como esta.
> BI-QUERIES: Campo obligatorio/no obligatorio "organización" en bi queries

- src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
- src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.html
- src/app/modules/visualizacion-informacion/components/exportar-huds/descargas-pendientes.component.ts
- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.html
- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
- src/app/modules/visualizacion-informacion/services/export-huds.service.ts
- src/app/modules/visualizacion-informacion/visualizacion-informacion.module.ts
Descarga de prestaciones desde el buscador de turnos y prestaciones.
Refactor filtros del buscador de turnos y prestaciones.
1. Se separa en un nuevo componente descargas-pendientes el listado de las peticiones de huds para ser usado tanto en exportar-huds como en el buscador de turnos y prestaciones.
2. Se agrega en el componente como en el html de turnos-prestaciones, la posibilidad de seleccionar/deseleccionar una o mas o todas las prestaciones que se encontraron al realizar la búsqueda.
3. Se agregan al `exportHudsService` un `Observable` y un `subject` para mantener actualizada la lista de descargas disponibles/pendientes.
1. Se agrupan todos los filtros dentro de un `plex-wrapper` para que se distribuyan de una mejor manera.
2. Al cerrar una prestación que se esta mostrando en el …
> TURNOS-PRESTACIONES: Descarga de prestaciones desde el buscador de turnos y prestaciones

- src/app/app.module.ts
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/nueva-derivacion/nueva-derivacion.component.ts
- src/app/services/drive.service.ts
https://proyectos.andes.gob.ar/browse/COM-48
1. Al eliminar un archivo de la galería se llama a la ruta DELETE /drive/:id
> COM: borrar archivos del drive al eliminar de la galería

- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
El error se da al seleccionar una cama, tocar en "nuevo registros" y hacer click de nuevo en la cama para deseleccionarla. Se emite null como cama seleccionada, entonces la unidad organizativa es null por lo tanto no tiene conceptId.
1. Agrega control en caso de que la unidad organizativa sea null.
2. 
3.
> INTERNACION - Agrega control en los registros si la unidad organizativa es null

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.scss
https://proyectos.andes.gob.ar/browse/MISC-115
1. Se agrega virtual scroll a la pantalla del buscador de turnos y prestaciones.
2. Se agrega el filtro ambito dentro del conjunto de filtros"
> TURNOS-PRESTACIONES: Agregar virtual scroll y filtro ambito

- src/app/modules/rup/components/ejecucion/acciones-envio-informe/acciones-envio-informe.component.ts
- src/app/modules/rup/components/ejecucion/modal-seleccion-email.component.ts
- src/app/modules/rup/components/ejecucion/modal-seleccion-email.html
https://proyectos.andes.gob.ar/browse/RUP-152
1. Se permite seleccionar los adjuntos que serán enviados por mail con el pdf
2. Si se manda un registro aislado, solo se adjuntan si hay relación con el componente adjuntarDocumentoComponent
> RUP: Enviar archivos ajuntos por mail

- projects/auth/src/lib/auth.service.ts
- src/app/app.component.ts
- src/app/apps/auth/auth.module.ts
- src/app/apps/auth/auth.routing.ts
- src/app/apps/auth/components/forgot/forgot.component.ts
- src/app/apps/auth/components/forgot/forgot.html
- src/app/apps/auth/components/forgot/forgot.scss
- src/app/apps/auth/components/login/login.component.ts
- src/app/apps/auth/components/login/login.html
- src/app/apps/auth/components/recovery/recovery.component.ts
- src/app/apps/auth/components/recovery/recovery.html
- src/app/apps/auth/components/recovery/recovery.scss
- src/environments/apiKeyMaps.ts.example
- src/environments/environment.demo.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
- Posibilidad de configurar si la funcionalidad de "olvide mi contraseña" la quiero habilitada o no.
- Envío de correo con un link para el reseto de la misma si es un usuario temporal c/ mail (campos obligatorios) para poder utilizar esta funcionalidad. En caso que el usuario no sea externo, se redirecciona al sitio de onelogin para la procecusión del trámite.
Proceso que permite el login y reset de contraseña para usuarios externos para el proceso de vacunación
PR https://github.com/andes/api/pull/1233
PD: Queda pendiente el test en andes-test-integración
> feat(login): Se agrega la posibilidad resetear la contraseña para los usuarios externos (no OneLogin)

- src/app/modules/mpi/components/paciente-detalle-foto.directive.ts
Error de sincronización de fotos del paciente. 
1. Desconecta el viejo IntersectiónObserver antes de armar uno nuevo.
> fix(mpi): foto paciente directiva

- src/app/modules/rup/components/elementos/vacunas.component.ts
1- Se modifica la condición de la diferencia de días para el chequeo de interdosis, ya que la resta actual daba en números negativos.
2- Para los casos que sea el mismo día (exactamente 21 días) se modifica a menor estricto.
1. 
2. 
3.
> fix(vacunas): fix en la condicion de timepo interdosis

- src/app/modules/rup/components/elementos/vacunas.component.ts
- src/app/modules/rup/components/elementos/vacunas.html
- src/app/services/vacunas.service.ts
- Permite seleccionar los lotes de vacunas respetando el formato origina, pero utilizando un plex-select.
- Permite mantener los lotes asociados a cada vacuna.
https://proyectos.andes.gob.ar/browse/MISC-118
https://github.com/andes/api/pull/1265
> feat(vacunas): Se agrega la posiblidad de seleccionar el lote correspondiente

- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/components/top/solicitudes/formNuevaSolicitud.html
https://proyectos.andes.gob.ar/browse/TOP-106
1. Permitir cargar solicitudes sin profesional origen
2. Mostrar mensaje de confirmación si no se seleccionó un profesional origen
> TOP: poder guardar solicitudes sin profesional de origen

- src/app/apps/rup/mapa-camas/interfaces/IMaquinaEstados.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-destino-generico/cama-destino-generico.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.html
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
Configurar en la maquina de estado  una sala (id) especifica para que automaticamente se eliga como destino del pase de unidad organizativa. Opcionalmente, el usuario puede elegir la cama de destino si la conoce (tambien configurable).
1. Agrega control para poder elegir o no una cama al realizar pase, según la configuracion de la maquina de estados. 
2. 
3.
> INTERNACION - Nuevo pase de UO configurable por maquina de estados

- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/agregar-paciente.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/revision-agenda.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/sobreturno.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/core/mpi/components/busqueda-mpi.component.ts
- src/app/core/mpi/components/busqueda-mpi.html
- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/services/paciente-buscar.service.ts
- src/app/core/mpi/services/pacienteCache.service.ts
Dado un paciente existente que no haya sido validado por scanner, realizando una búsqueda por scan el paciente se obtiene y visualiza correctamente pero no se le asigna el código de scan para que persista en DB
1. Modifica servicio de pacienteCaché para que en lugar de almacenar si el paciente fue escaneado o no, almacene codigo de scan o null respectivamente.
2.
> MPI - Salva valor de scan en paciente existente

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
1. Se agregó un máximo permitido de 500 prestaciones al momento de exportar las mismas desde el buscador de turnos y prestaciones
2. Si ocurre que un usuario selecciono mas de 500 prestaciones, el botón exportar quedara deshabilitado mostrando un hint que indica el numero máximo permitido de prestaciones.
> TURNOS-PRESTACIONES: Agregar máximo permitido al exportarHuds

- src/app/apps/vacunacion/components/inscripcion.component.ts
Agrega control de edad mayor a 18 en fecha de nacimiento para los grupos policia y personal de salud que no tenían el control.
1. Se agrega control en grupos
> feat(inscripcion): agrega control de edad mayor a 18 en grupos faltantes

- package-lock.json
- package.json
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.html
- src/app/components/turnos/gestor-agendas/turnos.html
[https://proyectos.andes.gob.ar/browse/CIT-109](https://proyectos.andes.gob.ar/browse/CIT-109)
Imposibilidad de percibir con lector de pantalla, determinados elementos de la interfaz del gestor de agendas, especialmente en botones sin texto (acciones iconográficas al seleccionar una agenda).
1. Descargar el [lector de pantalla NVDA](https://nvda.es/descargas/descarga-de-nvda/) (sólo windows, sino alguno para Linux: se sugiere [ORCA](https://wiki.gnome.org/Projects/Orca))
2. Instalar [plex v7.15.0](https://github.com/andes/plex/releases/tag/v7.15.0) (npm i @andes/plex@latest)
1. Se agrega atributo ariaLabel a todos los `<plex-button>` con atributo 'icon' de modo que al pasar el screen-reader describa la acción que representa el icono en cuestión.
> fix(gestor-agendas): agrega aria-label en botoneras

- src/app/apps/gestor-usuarios/views/usuarios-edit.view.ts
Fix gestor usuarios
al agregar permisos a mano  y después un perfil se perdian los cambios.
> fix(gestor-usuarios): ajustes de perfiles

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-21
https://proyectos.andes.gob.ar/browse/EP-35
- Agregar la posibilidad de enviar conceptos snomed a la ficha epidemiológica.
1. Dado un código snomed ingresado en la creación de un nuevo formulario se obtiene el concepto y se muestra en el dropdown de selección de fichas.
2. Dado un campo de tipo snomed donde se ingrese una query snomed se obtiene el resultado de dicha query y se agregan los resultados en un plex-select.
3. Se actualiza en MPI el dato del campo telefónico ingresado en la ficha.
4. Se realiza la carga inicial de los datos del domicilio del paciente, obtenidos de MPI, si se realizan modificaciones de estos campos en la ficha, se actualizan estos datos en el documento de la base de datos del paciente.
5. Se agrega en el titulo de la …
> FICHA-EPIDEMIOLÓGICA: Enviar datos de la ficha epidemiológica a MPI

- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/modules/rup/components/ejecucion/buscador.component.ts
https://proyectos.andes.gob.ar/browse/TOP-111
1. Al cargar una nueva solicitud en TOP, si el paciente tiene una en curso para la misma prestación muestra un mensaje de error.
2. Al cargar una solicitud desde RUP, si el paciente tiene una en curso para la misma prestación muestra mensaje de error.
> TOP: Alertar al cargar solicitud repetida

- src/app/apps/vacunacion/components/listado-inscriptos.component.ts
- src/app/apps/vacunacion/components/listado-inscriptos.html
https://proyectos.andes.gob.ar/browse/VAC-68
1. En la columna certificado si es de factores-riesgo y tiene entre 57 y 59 años mostrar 'No corresponde'
> VAC: en la columna certificado deberá decir "No corresponde" si es factores-riesgo y tiene entre 57 y 59 años

- src/app/apps/vacunacion/components/editar-inscripcion.component.ts
Al editar una inscripción, si el mail o el telefono no cumplían la expresión regular no habilitaba el botón Guardar pero tampoco le daba un feedback al usuario. 
1. Se agrega control que muestra al usuario los errores.
> fix(Inscripciones): Mostrar errores al editar inscripcion

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
Agregar la opción de agregar argumentos de tipo "select-static" en las bi-queries para que al momento de necesitar algún select con opciones "estáticas" se puedan agregar desde la base de datos y no modificar el componente.
1. Se agrega al html de bi-queries el caso "select-static" para que cuando venga un argumento de este tipo, lo muestre como un select con las opciones ingresadas en el array "items" del argumento.
2. Se agregan el argumento en las queries que usaban select de tipo estáticos.
3. Se eliminan del componente los arrays que se usaban en los select.
4. Elimino array en desuso de la ficha epidemiológica.
[agendas.txt](https://github.com/andes/app/files/6467884/agendas.txt)
[turnos.txt](https://github.com/andes/app/files/6467885/turnos.txt)
> BI-QUERIES: Agrega select-static

- projects/shared/src/lib/operators/index.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/integridad/filtros-inconsistencia/filtros-inconsistencias.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/filtros-internacion/filtros-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.service.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
https://proyectos.andes.gob.ar/browse/IN-259
1. Agrega columna y filtros de obra social.
> INT - Agrega columna 'obra social' en listado

- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/interfaces/prestacion.interface.ts
https://proyectos.andes.gob.ar/browse/RUP-252
1. se agrega unidad organizativa a vista prestacion
2. 
3.
> feat(RUP):agregar unidad organizativa a la prestación

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
Eliminar doble request al hacer una nueva búsqueda.
1. Se agrega la función cache() al observable ficha$ para evitar un doble request.
2. Se eliminan funciones cache() que están de mas.
> BUSCADOR EPIDEMIO: Fix doble request

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Filtrar búsqueda por campo activo en la colección localidad, esto es para filtrar los barrios que aparecen en el select.
1. Se agrega el params activo:true para traer solo localidades.
2. Se modifica datos de array de residencia por nuevo requerimiento.
> FICHA EPIDEMIOLÓGICA: field activo localidades

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-82
https://proyectos.andes.gob.ar/browse/EP-83
1. Se agrega un nuevo campo para seleccionar en el caso que la residencia donde el paciente reside no se encuentra en el combo.
2. Se modifica el modo de obtener las organizaciones en la seccion usuario para que al visualizar una ficha se muestre correctamente la misma.
[fichacovid.txt](https://github.com/andes/app/files/6633159/fichacovid.txt)
> FICHA EPIDEMIOLÓGICA: Nuevo campo residencias

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
Cuando se superan las 500 prestaciones seleccionadas, el boton exportar aparece como deshabilitado pero al hacer click llama a la funcion exportarHuds. Fix it!
1. Se pone en modo disabled el botón exportar cuando las prestaciones seleccionadas superan las 500.
> Turnos prestaciones: Disabled boton exportar

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Al crear una ficha, si el resultado del antigeno es no reactivo y no se marca ni pcr ni lamp, muestra mensaje pidiendo que se marque alguno, cuando se marca se duplican las secciones al guardar.
1. Se cambia el campo del findIndex por el correcto
> FICHA EPIDEMIOLOGICA: Fix secciones

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
Agregar una opción de carga parcial que oculte la sección clasificación final y modificar el aviso al momento de crear una nueva ficha si el paciente tiene otra creada en los últimos 14 días.
1. Se agrega plex-bool que al tildarlo oculte la sección "Clasificacion final" para poder cargar parcialmente la ficha.
2. Se modifica el cartel de aviso de ficha dentro de los 14 dias por un "confirm" para que permita de todas formas crear una nueva ficha.
[fichacovid.txt](https://github.com/andes/app/files/6709452/fichacovid.txt)
> Ficha Epidemiologica: Ficha parcial

- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/app.module.ts
- projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.html
- projects/portal/src/app/components/dar-turno-detalle/dar-turno-detalle.component.ts
- projects/portal/src/app/components/dar-turno/dar-turno.component.html
- projects/portal/src/app/components/dar-turno/dar-turno.component.ts
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.html
- projects/portal/src/app/pages/mis-turnos/mis-turnos.component.ts
- projects/portal/src/app/services/turno.service.ts
- src/app/services/turnos/agenda.service.ts
https://proyectos.andes.gob.ar/browse/PDP-58
1. Se agregan componentes y vistas para mostrar turnos disponibles (mobile) para que el paciente tenga la posibilidad de solicitar alguno de los disponibles.
2. Se utiliza  `navigator.geolocation.getCurrentPosition` (ubicación que solicita el navegador usado) para obtener coordenadas del dispositivo en el que paciente este en ese momento para obtener las prestaciones disponibles de la misma manera que en la app mobile.
3. Se elimina el cache en el getTurnos() para poder actualizar estos luego de que el paciente saque uno. 
4. Se agregan en la sección "Mis Turno" del portal, botones para navegar entre el historial de turnos y la solicitud de estos según marca le mockup.
Hay algunas diferencias en cuanto al mockup que se acordaron con …
> PORTAL DE PACIENTE : Solicitar turno

- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
- src/environments/environment.dev.ts
Condición para ordenar por fecha de creacion en caso de ficha de epidemilogia
1. 
2. 
3.
> HUDS: fix ordenar prestaciones

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Unificar como se va a guardar el identificador del pcr (Solo números)
1. Se agrego un patrón en el plex-text del identificador pcr para que solo acepte 'letras+numero' o solo números.
2. En el componente se chequea que si lo que se ingreso en el campo idPcr son solo números, o si viene con alguna palabra delante, en el caso que sea así, se elimina la palabra y se guarda solo el número.
> Ficha Epidemiologica: regex pcr

- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionValidacion.component.ts
- src/app/modules/rup/services/prestaciones.service.ts
https://proyectos.andes.gob.ar/browse/RUP-257
1. Elimina método clonar y modifica romper validación, en servicio de prestaciones
> RUP - Guarda prestaciones modificadas y anuladas en nueva colección

- src/app/modules/epidemiologia/components/seguimiento/seguimientoEpidemiologia.html
- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/components/huds/vistaPrestacion.ts
Eliminar los input que se agregaron en el componente vista-prestacion.
1. Se agrega el plex-button dentro del componente de seguimiento.
2. Se elimina plex-button, input y eventos agregados en el componente vista-prestacion.
> Epidemiología: Elimina input vista-prestacion

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
Como se cargan idPcr con 0 adelante y sin 0 delante. Controlar y eliminar el 0 en caso de existir (se acordó con el laboratorio hacer lo mismo de ambos lados.)
1. Se modifica el control al guardar el idPcr ( En el caso que exista ). Si ademas de alguna palabra tiene un 0 por delante, se elimina.
> Epidemiología: Nuevo regex idPcr

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-114
1. Se agrega la columna PCR al buscador, si la ficha tiene el campo se muestra el mismo, caso contrario se muestra 'Sin PCR'.
2. Se agrega un nuevo filtro de clasificación final al buscador.
> Buscador Epidemiología: Agregar filtro de clasificación final y columna idPcr

- src/app/modules/com/com.module.ts
- src/app/modules/com/components/actualizar-estado.component.ts
- src/app/modules/com/components/actualizar-estado.html
- src/app/modules/com/components/detalle-derivacion.component.ts
- src/app/modules/com/components/detalle-derivacion.html
- src/app/modules/com/components/punto-inicio.component.ts
- src/app/modules/com/components/punto-inicio.scss
- src/app/modules/semaforo-priorizacion/components/scss/semaforo.scss
- src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.component.ts
- src/app/modules/semaforo-priorizacion/components/semaforo-priorizacion.html
- src/app/modules/semaforo-priorizacion/interfaces/ISemaforo.ts
- src/app/modules/semaforo-priorizacion/service/semaforo.service.ts
https://proyectos.andes.gob.ar/browse/MISC-171
1. https://proyectos.andes.gob.ar/browse/MISC-171
2. 
3. 
[semaforo com.txt](https://github.com/andes/app/files/6717889/semaforo.com.txt)
> MISC: componente semaforo priorizacion

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-122
1. Agrego al object paciente el campo autopercibido y el genero.
> Ficha Epidemiologica - Identidad autopercibida en ficha covid19

- src/app/apps/gestor-usuarios/services/permisos.service.ts
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/epidemiologia.module.ts
- src/app/modules/epidemiologia/pipes/checkEdit.pipe.ts
https://proyectos.andes.gob.ar/browse/EP-116
1. Se obtienen las organizaciones en las que el usuario tiene permisos. Con estos permisos se verifica si las ficha obtenidas en el buscador fueron creadas en alguna organización en la que el usuario logueado tenga permisos, de ser así y si el usuario puede editar fichas se le mostrara el botón "editar" caso contrario, queda oculto.
2. Se agrega cacheStorage al get de organizaciones del PermisosService.
Este PR debe subir luego de https://github.com/andes/app/pull/2379
> Epidmiología - Permitir editar fichas solo a usuarios con permisos en la organizacion en la que fue creada

- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
https://proyectos.andes.gob.ar/browse/EP-115
1. Se agrega la función getField() al service para tener una función que al mandarle por parámetro una ficha, una sección y un campo(opcional), busque en la ficha y retorne el resultado. Esto se hizo para no seguir pegando esa búsqueda en todos lados ( queda pendiente un refactor en la ficha cada vez que se hace una búsqueda de estas).
2. Se modifica la rup card de la ficha epidemiologica para que en la parte de profesional se muestre:
- Si la ficha esta confirmada, el profesional que hizo esta acción.
- Si la ficha no esta confirmada y se pidió un hisopado que fue al laboratorio, el profesional que hizo esta acción.
- Cualquier otro caso, quien creo la ficha.
[fichacovid.txt](https://github.com/andes/app/files/6977429/fichacovid.txt)
> Epidemiología - Agregar el profesional que confirmo y el que hisopo en la ficha covid 19

- src/app/components/turnos/punto-inicio/turnos-paciente.component.ts
https://proyectos.andes.gob.ar/browse/CIT-122
1. Si solo se habilita la opción de liberar turnos para un usuario, la funcion getPermissions devuelve un array vació, por esto se cambia la función por check para que la variable puedaLiberarTurno quede en true en el caso de tener solo ese permiso.
2. Se hace lo mismo para puedeRegistrarAsistencia
- [] No
> CITAS - No se habilita el boton liberar turnos desde el punto de inicio

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
https://proyectos.andes.gob.ar/browse/MISC-184
1. Se agrega un label para mostrar que no hay resultados en el buscador de turnos y prestaciones.
2. Se agrega cache() a la subscripcion de la búsqueda.
> Turnos Prestaciones - Turnos prestaciones: agregar label "No se encontraron resultados"

- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
Actualizar limite de export huds en el buscador de turnos y prestaciónes
1. Se vuelve a poner 500 como máximo en el export de turnos y prestaciones. Se había actualizado por error.
> Turnos prestaciones: Actualizar limite de export huds en el buscador de turnos y prestacion

- src/app/app.module.ts
- src/app/services/token-expired.interceptor.ts
https://proyectos.andes.gob.ar/browse/PRIV-34
Queda pendiente cerrar sesión por inactividad.
1. HttpInterceptor para cuando la sessión se termina.
> feat(auth): catch fin de session

- src/app/modules/estadisticas/components/citas/filtros.component.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
https://proyectos.andes.gob.ar/browse/BI-108
1. Filtro de zonas sanitarias en bi-queries según permisos
En la query agendas-consolidado, reemplazar el argumento zona por:
{
"key" : "zona",
"label" : "Zona Sanitaria",
"tipo" : "zonaSanitaria",
"required" : false,
"subquery" : {
"organizacion.zonaSanitaria._id" : "#zona"
}
}
> BI: filtros por zonas en bi-queries

- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
- src/app/interfaces/IProfesional.ts
https://proyectos.andes.gob.ar/browse/GDU-39
1. Se suman datos de matrícula externa cuando el usuario es un profesional no matriculado
> GDU: suma datos de matricula externa a detalle de usuario

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.html
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
https://proyectos.andes.gob.ar/browse/EP-165
1. Se seteal el collapse del wrapper al buscar fichas para que al volver del editar/ver una ficha quede en el estado anterior.
> Epidemiologia - Se cierra collapse al editar/ver una ficha

- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
- src/app/modules/perinatal/components/listado-perinatal.component.ts
Se agrega filtro por paciente en descarga CSV
https://proyectos.andes.gob.ar/browse/PER-60
https://proyectos.andes.gob.ar/browse/GDU-40
1. Se agrega filtro por paciente en descarga de CSV
2. En query perinatal se modifica filtro de fecha, considerando que al menos uno de los controles esté entre el rango de fechas.
3. Se modifica label "observaciones" por "Profesión".
Modificar query con "nombre" : "listado-perinatal". 
```
{
"nombre" : "listado-perinatal",
"descripcion" : "Listado de controles perinatales",
"coleccion" : "carnet-perinatal",
"query" : [ 
{
"!match" : {
"controles.fechaControl" : {
"!gte" : "#fechaDesde",
"!lte" : "#fechaHasta"
}
}
}, 
{
"!unwind" : "$controles"
}, 
{
"!match" : {
"controles.fechaControl" : {
"!gte" : "#fechaDesde",
"!lte" : "#fechaHasta"
},
"#profesional" …
```
> PER: Agrega filtro por paciente en descarga CSV

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
[ ](https://proyectos.andes.gob.ar/browse/EP-172)
1. Se elimina restricción de guardar fichas con antígeno no reactivo en casos asintomáticos.
2. Se elimina el borrado de la clasificación final cuando el caso es asintomático.
> Epidemiología -  No borrar clasificacion final caso asintomatico

- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
https://proyectos.andes.gob.ar/browse/CIT-138
1. Se modifico la función puedoDisponer() agregando una condición para verificar que cuando se arma la agenda y se le asignan turnos con llave o del profesional, se modifica el valor de reservadoGestion o reservadoProfesional que aparecen en los bloques de una agenda. Y esto nos permitirá saber si tiene que figurar el botón disponible o no
> CIT - Ocultar botón disponible en agendas con turnos del dia/programados

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
Los enfermeros no estan viendo la exploración visual  de la internación.
> fix(mapa-camas): enfermeros no ven exploracion visual

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
https://proyectos.andes.gob.ar/browse/EP-178
1. Se setea como readonly el select PCR
> Epidemiología - Dejar readonly select muestra de pcr

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
https://proyectos.andes.gob.ar/browse/EP-179
1. Se elimina la restricción de guardar al registrar un antígeno no reactivo, antes era obligatorio pedir pcr o lamp, ahora se modifico.
> Epidemiología - Modificar restriccion antigeno no reactivo

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/services/pacientes-vacunas.service.ts
https://proyectos.andes.gob.ar/browse/EP-180
1. Se setea al inicio el estado de vacunación contra el covid 19 de un paciente, si el paciente posee alguna dosis se completan los campos correspondientes, permitiendo de todas formas modificar estos.
2. 
3.
> Epidemiología - Mostrar en la ficha el estado de vacunacion del paciente

- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
- src/app/modules/rup/services/elementosRUP.service.ts
https://proyectos.andes.gob.ar/browse/EP-187
1. Se agrega el concepto "Certificado de aislamiento" a la prestacion que se abre automativamente para los casos que se confirman desde la ficha covid 19.
> Epidemiología - Agregar concepto Certificado de aislamiento por covid a ficha confirmada

- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.html
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
https://proyectos.andes.gob.ar/browse/EP-192
1. Se agregan nuevos tipos de confirmación en la sección clasificación final.
2. Se agrega el concepto Enfermedad covid 19, cuando la ficha es confirmada por los nuevos tipos.
> Epidemiologia - Agregar autotest al select Tipo de confirmacion de la seccion "Tipo de confirmacion y calasificacion final"

- src/app/app.module.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.component.ts
- src/app/components/turnos/gestor-agendas/gestor-agendas.html
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/botones-agenda.html
- src/app/interfaces/ITipoPrestacion.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queries.component.ts
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queriesPage.component.html
- src/app/modules/visualizacion-informacion/components/bi-queries/bi-queriesPage.component.ts
- src/app/modules/visualizacion-informacion/visualizacion-informacion.module.ts
- src/app/modules/visualizacion-informacion/visualizacion-informacion.routing.ts
https://proyectos.andes.gob.ar/browse/CIT-134
https://proyectos.andes.gob.ar/browse/CIT-153
1. Permite carga masiva de pacientes por consulta
2. 
3.
> CIT: carga masiva de pacientes

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-392
Si el paciente esta resperidaro, muestra la R de respirador en verde.
> feat(mapa-camas): mostrar uso del respirador

- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/punto-inicio/turnos-paciente.html
https://proyectos.andes.gob.ar/browse/CIT-172
1. Se agregan controles para agendas sin profesionales
2. 
3.
> fix(citas): se agregan controles en agendas con profesionales null

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
- src/app/components/turnos/dar-turnos/dar-turnos.scss
https://proyectos.andes.gob.ar/browse/CIT-119
Por cuestiones de espacio en el sidebar y según lo charlado en la reunión
1. Se saco el icono de calendario grande 
2. Si se filtra únicamente por tipo de Prestación en el detalle de la agenda se visualiza solamente el equipo de salud
3. Si se filtra únicamente por Equipo de salud en el detalle de la agenda se visualiza solamente la tipo de prestación
4. Si se filtra por tipo de prestación y equipo de salud, se muestran ambos datos en el detalle de la agenda.
5. El botón de información se cambio de lugar hacia arriba y en todo momento tiene la información general de la agenda, aparecen el Equipo de salud y tipo de prestación completo y espacio físico. 
6. EL boton de volver anterior funcionaba como demanda rechazada por lo que ahora a ese …
> CITAS - Cambio de diseño y demanda rechazada

- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicaciones-botonera/indicaciones-botonera.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/motivo-suspension/motivo-suspension.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.module.ts
Registrar motivo de suspensión de indicaciones
1. 
2. 
3.
> IN: motivo suspensión indicación

- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica-crud/ficha-epidemiologica-crud.component.ts
- src/app/modules/epidemiologia/services/ficha-epidemiologia.service.ts
https://proyectos.andes.gob.ar/browse/EP-211
1. Se elimina la opción Nexo del select Tipo de confirmación.
2. Se elimina la opción Nexo del buscador de fichas.
> Epidemiología - Eliminar confirmacion por nexo de la ficha covid 19

- src/app/components/reportes/encabezadoReportes.component.ts
- src/app/components/reportes/encabezadoReportes.html
https://proyectos.andes.gob.ar/browse/MISC-225
1. Se agrego un nuevo filtro de cie10.
> MISC - Agregar filtro por conceptos en el reporte c2

- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.html
- src/app/apps/rup/mapa-camas/views/censos/censo-mensual/censo-mensual.component.ts
https://proyectos.andes.gob.ar/browse/IN-442
1. Se agregaron dos labels diferentes para indicarle al usuario como debe comenzar y que no hay resultados de la busqueda que realizó.
> IN - Labels de resultados en pantalla de censos

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-item/registros-huds-item.component.ts
https://proyectos.andes.gob.ar/browse/IN-430
1. Se agrego un boton "anular" de color rojo el cual anula la prestación.
> IN - Permitir anular prestaciones de internación

- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-186
> CITAS - Visualizacion de turnos agenda dinamica

- src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-eventos/indicacion-eventos.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-471
1. Se agrega funcionalidad para que cada organizacion pueda configurar ( por base de datos ) el horario de inicio de la grilla del plan de indicaciones.
2. Según el horario de inicio, se crearan los eventos, desde que comienza el turno hasta el final.
3. Se restringe para que solo se puedan registrar eventos perteneciente al día actual, sin importar la configuración de los turnos.
> Plan indicaciones - Modificar grilla horaria del plan

- src/app/modules/perinatal/components/detalle-perinatal.component.html
- src/app/modules/perinatal/components/listado-perinatal.component.html
https://proyectos.andes.gob.ar/browse/PER-77
1. Se visualiza la cantidad de embarazos en caso de que se seleccione el term "mas de 10 embarazos"
Es necesario que primero se haga el merge de la tarea PER-72 para poder ver los cambios y las nuevas funcionalidades de esta tarea.
> PER - Cantidad de embarazos

- src/app/core/mpi/components/busqueda-mpi.component.ts
- src/app/modules/mpi/components/paciente-buscar.component.ts
https://proyectos.andes.gob.ar/browse/MPI-392
1. Al ingresar un paciente en la búsqueda de MPI, si el mismo es extranjero pero posee DNI argentino (validado o sin validar), se visualiza el formulario correspondiente para pacientes argentinos.
2. Se mantiene la visualización del formulario exclusivo para pacientes extranjeros solo si tienen numero de identificación pero no tienen DNI.
3. Se mantiene la visualización del formulario correspondiente para el resto de los casos.
> MPI - Visualización de formulario para pacientes con DNI argentino

- src/app/apps/rup/mapa-camas/services/permisos-mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
https://proyectos.andes.gob.ar/browse/IN-330
1. Permisos para plan de indicaciones
2. 
3.
> IN: permisos para plan de indicaciones

- src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
https://proyectos.andes.gob.ar/browse/RUP-344
1. Se verifica si el usuario tiene permiso para acceder al link de plantillas: https://demo.andes.gob.ar/rup/plantillas.
> RUP - Agrear permiso para abm de plantillas

- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/cambiar-cama.component.ts
- src/app/apps/rup/mapa-camas/sidebar/desocupar-cama/desocupar-cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-489
1. Se agrego un setFecha para que en primera instancia actualice el mapa de camas antes de realizar un movimiento y con este mismo va a saber si la cama se encuentra o no disponible para realizar un cambio. También se agregaron múltiples controles al momento de guardar un cambio o pase de UO para evitar duplicados o movimientos que no corresponden.
Nota: anteriormente requería los cambios en la api, pero como no son necesarios se procede a cerrar el PR.
> IN - controles para pacientes duplicados en camas distintas

- src/app/components/turnos/punto-inicio/puntoInicio-turnos.component.ts
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
https://proyectos.andes.gob.ar/browse/CIT-211
GLPI: https://glpi.andes.gob.ar/front/ticket.form.php?id=3708
1. Se incorpora un nuevo permiso _Visualizar solicitudes_ que permita visualizar el listado de solicitudes pero que no se vea el botón _Cargar Solicitud Nueva_.
2. Cuando el permiso _Visualizar solictudes_ y   _Registrar solicitud_ están desactivados, no se muestra el botón _Solicitudes_.
3. Cuando el permiso _Visualizar solictudes_ está activado no se muestra el botón _Cargar Solicitud Nueva._
En resumen:
En ventanilla (CITAS) actualmente existe un permiso para poder visualizar el listado de solicitudes  y agregar una nueva (turnos:puntoInicio:solicitud) que está en el archivo puntoInicio-turnos.component.ts.
En esta funcionalidad se incorpora un nuevo permiso que permite solo …
> CITAS - Separar permiso de creación de solicitudes

- src/app/components/top/solicitudes/historialSolicitud.html
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-154
1. Se agrega el nombre del efector en el historial de la solicitud tanto para las solicitudes de entrada como de salida.
2. Se cambia el tamaño del sidebar para mejor visualización del mismo.
> TOP - información sidebar - historial

- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.html
- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
https://proyectos.andes.gob.ar/browse/HUDS-83
1.  Agrega doble filtro tipo checkbox para CDAs vacunas y laboratorios
2. Envía los datos a excluir en la prop  -excluye-
3. Deshabilita filtros en caso de marcar la opción de exportar HUDS completa
> HUDS - Agrega filtro de CDAs al exportar HUDS

- src/app/app.module.ts
- src/app/core/mpi/components/busqueda-mpi.component.ts
- src/app/core/mpi/components/datos-basicos.component.ts
- src/app/core/mpi/components/datos-basicos.html
- src/app/core/mpi/components/paciente.component.ts
- src/app/core/mpi/components/paciente.html
- src/app/core/mpi/services/pacienteVinculadoCache.service.ts
https://proyectos.andes.gob.ar/browse/MPI-393
1. Se crea un nuevo formulario (paralelo) para registrar a un paciente extranjero con DNI argentino
2. Se crea una opción (boton slide) para habilitar el con DNI a un paciente extranjero
3. Se validan los campos actuales del formulario para el paciente extranjero al momento de habilitar la opción para registrar con DNI argentino
4. Se validan los campos del paciente con DNI argentino
5. Al momento de validar con RENAPER, se reemplazan los datos obtenidos en el formulario de paciente con DNI argentino
6. Al momento de guardar los datos del paciente, se chequean las suregencias con pacientes similares
7. Al seleccionar un paciente sugerido, el formulario se redirige al formulario tradicional de registro de paciente argentino
8. Al momento de …
> MPI: Implementa registro para extranjeros con DNI argentino

- package-lock.json
- package.json
- src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.component.ts
- src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.html
- src/app/components/buscadorTurnosPrestaciones/no-nominalizadas/no-nominalizadas.scss
- src/app/components/buscadorTurnosPrestaciones/services/turnos-prestaciones.service.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.html
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.module.ts
- src/app/directives/prestaciones-select.directive.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/huds/vistaPrestacion.ts
https://proyectos.andes.gob.ar/browse/TYP-5
https://proyectos.andes.gob.ar/browse/TYP-11
1. Crea nuevo componente para la visualización de prestaciones "no nominalizadas".
2. Modifica el componente de búsqueda actual para excluir las prestaciones "no nominalizadas" del campo "Prestaciones".
3. Segun lo especificado en la tarea [TYP-11](https://proyectos.andes.gob.ar/browse/TYP-11), se modifica la directiva "prestaciones-select" para poder filtrar por tipo de prestacion en los listados de selección.
Requiere ultima versión de Plex Icons: 
https://www.npmjs.com/package/@andes/icons
https://github.com/andes/andes-font-icon/pull/13
Se deben actualizar el módulo de "Turnos y Prestaciones" en la colección "modulos" con los siguientes datos:
```
{
"nombre" : "FACTURACIÓN",
"descripcion" : …
```
> TYP - Listado de prestaciones no nominalizadas

- src/app/components/top/pipes/botones.pipe.ts
- src/app/components/top/pipes/estado-prestacion.pipe.ts
- src/app/components/top/pipes/estado-solicitud.pipe.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/solicitudes/solicitudes.html
https://proyectos.andes.gob.ar/browse/TOP-142
1.  Corregidos badges de solicitudes de "Turno dado" a "Ejecución"
2.  Corregidos filtros de "Turno dado" que también mostraba solicitudes en "Ejecución"
3.  Botón "Continuar registro" restringido a solicitudes donde el usuario tiene permisos para rup e inició el registro de atención medica o tiene permisos especiales, siempre con con la prestación  en ejecución.
> TOP - Revisar y analizar comportamiento del botón continuar

- src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/indicacion-detalle/indicacion-detalle.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.html
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/modules/rup/components/core/rup.component.ts
https://proyectos.andes.gob.ar/browse/IN-583
1.  Se agrega un boton para eliminar las indicaciones que se encuentran en estado "borrador"
2. NOTA: en el html de plan-indicaciones.component.html solamente se modifica las lineas 125 a 128 donde se agrega dicho botón.
> IN - Eliminar indicación en estado borrador

- src/app/components/turnos/dar-turnos/calendario.component.ts
- src/app/components/turnos/dar-turnos/calendario.html
- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dar-turnos/dar-turnos.html
https://proyectos.andes.gob.ar/browse/CIT-249
1. Se modificó <**dar-turnos**> para que inabilite botón [**DAR TURNO**] si la agenda Dinámica no es del día de la fecha.
2. Se corrigió <**calendario**> para que muestre correctamente **label e iconos** de cant.agendas y turnos disp.
> CIT - Ventanilla: No dar turno en agenda dinamica

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/dashboard/demandaInsatisfecha.html
- src/app/components/turnos/dashboard/demandaInsatisfecha.ts
- src/app/services/turnos/listaEspera.service.ts
https://proyectos.andes.gob.ar/browse/CIT-268
1. El método post de ../routes/listaEspera.ts decide si agregar un nuevo doc a la colección o una nueva demanda a un doc existente.
2. Desde app se invoca desde ../turnos/listaEspera.Service.ts método save(...)
3.
> (FEAT) Demanda Insatisfecha: pasar funcionalidad a API

- src/app/components/turnos/autocitar/autocitar.component.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.html
- src/app/modules/rup/components/ejecucion/prestacionCrear.scss
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
- src/app/modules/rup/components/ejecucion/puntoInicio.scss
- src/app/modules/rup/components/variables.scss
https://proyectos.andes.gob.ar/browse/RUP-370
1. Implementa rediseño basado en mockup para punto de inicio
2. Implementa rediseño basado en mockup para selección de pacientes en agenda dinámica
> RUP - Implementa mockups en punto de inicio

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.component.ts
- src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.html
- src/app/apps/rup/mapa-camas/sidebar/periodos-censables/periodos-censables.scss
- src/app/apps/rup/mapa-camas/views/censos/censo-diario/censo-diario.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
https://proyectos.andes.gob.ar/browse/IN-594
1. En el detalle de la internación (Ingreso) puedo verse una opción para agregar periodos censables, solo en capa estadística.
2. El selector de periodos permite agregar uno o mas periodos a partir del ingreso por fechas.
3. Los periodos se agregan al campo periodosCensables de la internación.
4. Si se borra el listado de periodos el estado esCensable en la internación pasa a "false".
5. Si la internación tiene estado esCensable "false" y  se agregan periodos, pasa a ser "true".
> IN - Implementa periodos censables en internacion

- src/app/modules/rup/components/ejecucion/dacion-turno/asignar-turno.html
Se corrige error al intentar dar un sobreturno para agendas que tienen más de una prestación.
NOTA: Considerar que las prestaciones no tienen que tener configuración de dinámica en true
1. Se corrige error al intentar dar un sobreturno para agendas múltiple prestacion
2. cambia fondo al buscar paciente y no encontrarlo
3.
> RUP: corrige bug en sobreturnos

- src/app/apps/rup/mapa-camas/mapa-camas.module.ts
- src/app/apps/rup/mapa-camas/mapa-camas.routing.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.http.ts
- src/app/apps/rup/mapa-camas/services/plan-indicaciones.service.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-medicamentos-capas.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion-capas/listado-medicamentos-capas.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/services/documentos.service.ts
https://proyectos.andes.gob.ar/browse/IN-574
1.  Reporte de los pedidos de medicamentos de un sector para realizar el control de entrega de medicación 
2.  Extraccion de una planilla con la siguiente información: DNI paciente / sector / unidad org./ cama actual/ los datos del medicamento, filtros por sector, unidad organizativa y por nombre de medicamento para un efector.
3. Descarga en csv
> IN - Reporte pedido de medicamentos

- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
https://proyectos.andes.gob.ar/browse/IN-599
1. Se agrega la función .sort para poder ordenar todas las prestaciones ya filtradas de forma descendente.
NOTA: Para poder reproducir el error buscar por demo algún paciente que presente en diferentes fechas tanto CDAs como prestaciones creadas.
> IN - Cambiar orden en Registros médicos

- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/filtros-cama/filtros-camas.scss
https://proyectos.andes.gob.ar/browse/IN-595
1. Modifica la condición de "collapse" para poder modificarlo programáticamente.
2. Crea método checkSeleccion() que permite saber si hay filtros seleccionados dentro del collapse
> IN - Implementa filtros de busqueda autoexpandibles

- src/app/apps/rup/mapa-camas/sidebar/nuevo-registro-salud/nuevo-registro-salud.component.ts
- src/app/apps/rup/mapa-camas/views/plan-indicaciones/plan-indicaciones.component.ts
- src/app/components/buscadorTurnosPrestaciones/turnos-prestaciones.component.ts
- src/app/components/top/solicitudes/solicitudes.component.ts
- src/app/components/top/top.module.ts
- src/app/interfaces/IMotivosHuds.ts
- src/app/modules/rup/components/ejecucion/hudsBusquedaPaciente.component.ts
- src/app/modules/rup/components/ejecucion/prestacionCrear.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.html
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
- src/app/modules/rup/components/internacion/puntoInicio-internacion.component.ts
- src/app/modules/rup/huds-lib.module.ts
- src/app/modules/rup/interfaces/IMotivoAcceso.ts
- src/app/modules/rup/rup.module.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/services/motivosHuds.service.ts
https://proyectos.andes.gob.ar/browse/PRIV-65
Se reemplazan los motivos de acceso a la HUDS estáticos por accesos a BD.
1. Acceso explícito a la HUDS (modal).
2. Buscador de Turnos y prestaciones.
3. Al iniciar una prestación.
4. Desde la internación (modal) de acceso a los registros y plan de indicaciones.
5. Solicitudes: bandeja de entrada/salida al iniciar una prestación.
NOTA: considerar que resuelva el error reportado en https://proyectos.andes.gob.ar/browse/HUDS-112
> PRIV - Visualizar motivos de acceso a la HUDS

- src/app/app.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
https://proyectos.andes.gob.ar/browse/GDU-64
1. Se verifica si el usuario es un profesional habilitado o no. Si se encuentra duplicado mostrará los datos del habilitado y en caso de que se encuentre deshabilitado mostrará un badge rojo DESHABILITADO.
> GDU - Controlar datos del profesional asociado al usuario

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.component.ts
- src/app/components/demandaInsatisfecha/demanda-insatisfecha.html
- src/app/components/turnos/citas.module.ts
- src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
- src/app/interfaces/turnos/IListaEspera.ts
https://proyectos.andes.gob.ar/browse/CIT-277
https://proyectos.andes.gob.ar/browse/CIT-278
1.  Implementa mockups para nuevo módulo de demanda insatisfecha
2. Se recupera lista de espera de pacientes sin turnos, con opciones de filtros
3. Se visualiza detalle de paciente en sidebar
4. Se visualizan llamados con formulario de carga
5. Se visualiza historial de turnos del paciente
> CIT - Implementa mockups de demanda insatisfecha

- projects/auth/src/lib/auth.service.ts
- src/app/app.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.component.ts
- src/app/apps/gestor-usuarios/components/usuario-detalle/usuario-detalle.html
- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
https://proyectos.andes.gob.ar/browse/RUP-416
1. Al loguearse vincula usuario sólo con profesional habilitado (pasa controles a api).
2. En gestor de usuarios: corrige badge de usuario no vinculado a un profesional, ya que se veía como "Deshabilitado".
3.
> fix(Login): filtro profesional habilitado en login

- src/app/apps/rup/mapa-camas/interfaces/ISnapshot.ts
- src/app/apps/rup/mapa-camas/services/mapa-camas.service.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/internacion-detalle/internacion-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.html
- src/app/apps/rup/mapa-camas/sidebar/egreso/egresar-paciente.component.ts
- src/app/apps/rup/mapa-camas/sidebar/egreso/informe-egreso.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.html
- src/app/apps/rup/mapa-camas/views/cama/cama.component.ts
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.html
- src/app/apps/rup/mapa-camas/views/listado-internacion/listado-internacion.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/item-cama/item-cama.component.ts
https://proyectos.andes.gob.ar/browse/IN-593
1. Evita duplicación de egresos al editar desde el listado
2. Oculta opciones para "desocupar cama" en el dropdown del mapa (al igual que en el sidebar) si el paciente está egresado en el futuro
3. Al editar una cama, restringe edición de UO si la cama se encuentra ocupada en ALGUNA capa
4. Oculta tab "egreso" en todas las capas desde el mapa. Las habilita solo desde el listado y el historial
> IN (Fix) - Duplicación de egresos y otros

- src/app/components/turnos/gestor-agendas/operaciones-agenda/planificar-agenda.component.ts
https://proyectos.andes.gob.ar/browse/CIT-286
1. Se agregan modals en las siguientes situaciones
- Cuando empiezo a cargar prestaciones nominalizadas y cargo una no-nominalizada, eliminandose del listado esta última
- Cuando cargo una prestación no-nominalizada y cargo una nominalizada, eliminandose del listado esta última
> CIT - Corregir la creación de agendas no nominalizadas

- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/ejecucion/vistaHuds.component.ts
- src/app/modules/rup/components/ejecucion/vistaHuds.html
- src/app/modules/rup/components/huds/detalleProcedimiento.html
- src/app/modules/rup/components/huds/detalleProcedimiento.scss
- src/app/modules/rup/components/huds/detalleProcedimiento.ts
- src/app/modules/rup/components/huds/vistaPrestacion.html
- src/app/modules/rup/huds-lib.module.ts
https://proyectos.andes.gob.ar/browse/HUDS-118
1. Se implementa la vista para las prestaciones de tipo "procedimiento"
2. Se incorpora la nueva vista en punto de inicio de HUDS y en la ejecución de RUP
> HUDS - Implementa vista exclusiva para procedimientos

- src/app/components/top/solicitudes/formNuevaSolicitud.component.ts
- src/app/components/top/solicitudes/formNuevaSolicitud.html
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/lista-solicitud-turno-ventanilla.html
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.component.ts
- src/app/components/turnos/punto-inicio/solicitud-turno-ventanilla/solicitud-turno-ventanilla.html
https://proyectos.andes.gob.ar/browse/CIT-359
1. Se agrega la posibilidad de cargar solicitudes de salida desde ventanilla citas
2. Se agrega combo de conceptos asociados a  las solicitudes  cargadas desde  ventanilla citas
> feat(CITAS): Agrega Conceptos asociados a solicitudes desde ventanilla

- src/app/components/turnos/dashboard/demandaInsatisfecha.html
- src/app/components/turnos/dashboard/demandaInsatisfecha.scss
- src/app/components/turnos/dashboard/demandaInsatisfecha.ts
- src/app/services/turnos/listaEspera.service.ts
https://proyectos.andes.gob.ar/browse/CIT-344
1. Pide datos de solicitudes pendientes asociadas al paciente y la prestación
2. Si existen solicitudes se muestra modal informando de las mismas
3. Finaliza cierre de demanda al cerrar modal
https://proyectos.andes.gob.ar/browse/CIT-345
1. Pide datos de turnos futuros asociados al paciente y la prestación
2. Si existe turno se evita el guardado de la demanda y se muestra modal notificando los datos del turno
> CIT - Verifica turnos y solicitudes al asignar demanda

- src/app/modules/rup/components/elementos/talla.html
- src/app/modules/rup/components/elementos/tensionDiastolica.html
- src/app/modules/rup/components/elementos/tensionSistolica.html
https://proyectos.andes.gob.ar/browse/RUP-428
1. Modifica controles para molécula "Medir la altura del paciente"
2. Modifica controles para molécula "Presión sistólica"
3. Modifica controles para molécula "Presión diastólicae"
> RUP - Modifica controles en moléculas

- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
- src/app/modules/rup/components/elementos/recetaMedica.scss
https://proyectos.andes.gob.ar/browse/RUP-395
https://proyectos.andes.gob.ar/browse/RUP-400
https://proyectos.andes.gob.ar/browse/RUP-427
https://proyectos.andes.gob.ar/browse/MISC-380
https://proyectos.andes.gob.ar/browse/RUP-395
1.  Se modifica la carga de medicamentos
2.  Se quita restricción de 2 medicamentos por receta
3.  Se quitan opciones de triplicado/duplicado/simple
https://proyectos.andes.gob.ar/browse/RUP-400
1- Se agregar la cantidad de unidades (campo numérico).
2- Se campo dosis diaria
https://proyectos.andes.gob.ar/browse/RUP-427
1- Cambio titulo de Indicaciones por "Indicaciones diarias".
2- En los campos frecuencia se agrega un combo de 1 a 24 por horas, y en duración que por día.
3- Se modifican nombres de los atributos para que coincidan con los que se guarda el …
> RUP - Receta : modificar molécula

- src/app/modules/rup/components/ejecucion/laboratorios/vista-laboratorio.component.ts
El detalle de un protocolo ya viene formateado desde la api y eliminamos el formateo  del lado de la  app
> refactor(HUDS): optimiza código al recibir detalle de un  protocolo

- src/app/modules/rup/components/ejecucion/puntoInicio.component.ts
- src/app/modules/rup/components/ejecucion/puntoInicio.html
…responde
https://proyectos.andes.gob.ar/browse/HUDS-140
1. Se elimina el acceso a huds cuando en RUP no se tienen permisos de HUDS al presionar "Ver resumen" y "Continuar registro"
> HUDS -  Eliminar el registro de acceso a la HUDS cuando no corresponde

- src/app/components/turnos/dar-turnos/dar-turnos.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-agenda/suspender-agenda.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-agendas.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/reasignar/reasignar-turno-automatico.component.ts
- src/app/components/turnos/gestor-agendas/operaciones-turnos/suspender-turno.component.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
- src/app/services/turnos/sms.service.ts
https://proyectos.andes.gob.ar/browse/CIT-355
1. Se elimina código obsoleto 'enviarSms' y sus llamadas. 
2. Se quita if (environment.production === true)
3. Se modifica también suspender-turno.component para marcar el turno.avisoSuspension = 'enviado' o 'fallido' idem 
suspender-agenda.
> CIT - Notificaciones: limpiar código innecesario

- projects/portal/src/app/services/laboratorio.service.ts
- src/app/modules/rup/components/ejecucion/hudsBusqueda.component.ts
https://proyectos.andes.gob.ar/browse/LAB-13
1.  Si el paciente es temporal (sin DNI) envía documento del parentezco (progenitor/a).
2.  SI no hay documento no hace el GET.
> LAB - Paciente temporal enviar DNI parentezco

- src/app/modules/rup/components/ejecucion/buscador.component.ts
- src/app/modules/rup/components/ejecucion/buscador.html
https://proyectos.andes.gob.ar/browse/RUP-415
1. Se restringe la agregación del concepto Receta en RUP a profesionales :
- Médico/ Obstetra/ Odontólogo
- Matricula Vigente (no vencida/ no suspendida/ matriculado)
> RUP -  Concepto Receta Autorización

- src/app/apps/rup/mapa-camas/sidebar/cama-detalle/cama-detalle.component.ts
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.html
- src/app/apps/rup/mapa-camas/sidebar/registros-huds-detalle/registros-huds-detalle.component.ts
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.html
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.scss
- src/app/apps/rup/mapa-camas/views/mapa-camas-capa/mapa-camas-capa.component.ts
- src/app/modules/epidemiologia/components/buscador-ficha-epidemiologica/buscador-ficha-epidemiologica.component.ts
- src/app/modules/epidemiologia/components/ficha-epidemiologica/ficha-epidemiologica.component.ts
- src/app/modules/mpi/components/paciente-detalle.component.ts
- src/app/modules/rup/components/huds/modal-motivo-acceso-huds.service.ts
- src/app/modules/rup/services/huds.service.ts
- src/app/modules/rup/services/prestaciones.service.ts
- src/app/modules/visualizacion-informacion/components/exportar-huds/exportar-huds.component.ts
https://proyectos.andes.gob.ar/browse/IN-612
1. Se reduce el rango inicial de registros de internación a 3 dias desde el día de la fecha
2. Se modifica vigencia de tokenHuds de 4horas a 1hora
3. Se modifica el pedido de motivo de acceso a la HUDS a sólo una vez hasta vencimiento de token
4. Se agrega estructura de tokenHuds en memoria de sesion para que no se sobreescriba el token al querer revisar varios pacientes y se mantega el mismo token vigente
> IN -  Cambiar periodos de registros de internación

- src/app/apps/rup/plantillas-rup/plantillas-rup.component.ts
- src/app/modules/rup/components/core/rup.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.component.ts
- src/app/modules/rup/components/ejecucion/prestacionEjecucion.html
- src/app/modules/rup/components/elementos/recetaMedica.component.ts
- src/app/modules/rup/components/elementos/recetaMedica.html
- src/app/modules/rup/components/elementos/recetaMedica.scss
- src/app/modules/rup/services/ejecucion.service.ts
https://proyectos.andes.gob.ar/browse/RUP-424
1. Se bloquea la edición de la receta chequeando si la validación se rompió en la prestacion.
2. Se crean funciones para validar los conceptos al momento de agregarlos a la prestacion verificando si estan bloqueados para editar/agregar.
3. Se agrega posibilidad de mostrar un mensaje de alerta en componente RUP
> RUP - Bloquea edicion de recetas

- src/app/app.module.ts
- src/app/components/turnos/dashboard/estadisticas-paciente.scss
- src/app/components/turnos/dashboard/estadisticas-pacientes.component.ts
- src/app/components/turnos/dashboard/estadisticas-pacientes.html
- src/app/components/turnos/punto-inicio/puntoInicio-turnos.html
- src/app/components/turnos/punto-inicio/turnos-paciente.html
- src/app/components/turnos/punto-inicio/turnos-paciente.scss
- src/app/services/turnos/historial-turnos.service.ts
https://proyectos.andes.gob.ar/browse/CIT-341
1. Se hace un refactor en el tab de historial con lo siguiente:
- Se agegan los filtros: Por estado, rango de fechas y prestación. 
- Se agrega un scroll infinito
- Se visualizan turnos suspendidos que pertenezcan a agendas ya suspendidas o no.
- Los turnos suspendidos que ya fueron reasignados se muestran con un hint "reasignado"
- Se plexea todo el listado
- Dentro del tab turnos se cambia el formato del label de "Sin turnos asignados" si el paciente no tiene turnos a futuro
> CIT - Visualización de historial de turnos

- src/app/components/turnos/gestor-agendas/pipes/botonesAgenda.pipe.ts
- src/app/components/turnos/gestor-agendas/pipes/botonesTurnos.pipe.ts
- src/app/components/turnos/gestor-agendas/turnos.component.ts
- src/app/components/turnos/gestor-agendas/turnos.html
https://proyectos.andes.gob.ar/browse/CIT-369
1. Se soluciona el problema de que no se actualiza el contador de turnos cuando se suspenden los turnos y se vuelven a pasar a disponible
2. Se agregan otras soluciones como: 
- No se muestra el botón de reasignar dentro de la agenda una vez que se hayan reasignado todos los turnos. 
- Una vez que el turno se suspende (con o sin paciente) no se puede volver a suspender el mismo. 
- No se pueden liberar turnos suspendidos que presenten un paciente.
> CIT - Error al volver a disponible turno suspendido
